### ISSUE TITLE
Cannot load large dataset

### ISSUE THREAD

**Issue by marcadella** [OpenRefine/OpenRefine#4117] opened 2021-08-23 10:37 UTC
Issue with loading large dataset.

### To Reproduce

I uploaded a relatively large dataset (637.4Mb, 920233 lines). But I'm getting issues when opening the project.
- Once opened only 360326 records are listed in the top left corner. All the data is uploaded though since I get the expected number of lines when I download the data as TSV.
- Using a text facet with a constant attribute shows the expected number though.
- Trying to select these do not work, openrefine will try to load forever.

OpenRefine is running with 32Gb memory (`-m 32G`) and our server has plenty of free RAM (>200Gb).
No error in the log (except the first line but I think it doesn't matter given what I can see in the lines that follow):
```
/app/refine: line 810: [: 32G: integer expression expected
You have 257692M of free memory.
Your current configuration is set to use 32G of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
/usr/lib/jvm/java-1.8-openjdk/jre/bin/java -cp server/classes:server/target/lib/* -Xms1400M -Xmx32G -Drefine.memory=32G -Drefine.max_form_content_size=1048576 -Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython -Dpython.cachedir=/root/.local/share/google/refine/cachedir -Drefine.data_dir=/data -Drefine.webapp=main/webapp -Drefine.port=3333 -Drefine.host=0.0.0.0 com.google.refine.Refine
```

### Versions
 - Operating System: CentOS 7
 - Browser Version: Chrome
 - JRE or JDK Version: OpenJDK 1.8
 - OpenRefine: 3.4.1 (from https://hub.docker.com/r/felixlohmeier/openrefine/)

**Comment by thadguidry** [comment] 2021-08-23 12:01
Remember that OpenRefine can work with Records or Rows. https://docs.openrefine.org/manual/exploring#rows-vs-records
There might be something going on with the data itself that might be causing issues.
Can you try using the line-based importer just to see if it is truly 920233 rows(lines)?
Then one-by-one try to systematically create New Columns based on using split() or partition() ex. `value.split(",")[0]` using the delimiter such as comma U+002C that the dataset seems to use.  And monitor the memory usage to see how large the heap grows each time.  Hopefully you can split out into all the columns that you need with much overhead.  If you are successful, then it might be something with the format of the data and the options and importer that you chose initially.

**Comment by marcadella** [comment] 2021-08-23 12:51
Thanks for the help, we found out that the issue happened when importing a TSV file where each line starts with a tab (i.e. the first column contains empty values). Could that be a bug?

**Comment by thadguidry** [comment] 2021-08-23 13:12
Not a bug.  If each line starts with a tab, then this would likely force record mode to occur, and then depending on the amount of columns that are subsequently created (and the length of strings within each cell) will exponentially increase the amount of Java objects created that the heap would need to maintain past the Eden Space and Tenured Space (old gen).

We do plan to do better during preview and give users potentially better warnings about possible trouble ahead.
This is covered in a few existing issues.

I'll close this since you probably have already used `sed` or another tool to quickly cleanup your file for our cleanup tool OpenRefine :-)

**Closed by thadguidry** 2021-08-23 13:12 UTC
Labels: bug, to be reviewed

**Comment by marcadella** [comment] 2021-08-24 06:53
> this would likely force record mode to occur

The documentation says nothing about "forcing" record mode. Instead, it states that raw mode is used by default and record mode needs to be switched manually.
I think "automatic" record mode is not a desired behavior.

**Comment by orothad** [comment] 2021-08-24 12:34
Thanks for the notice about the documentation.  I will update it and make it accurate.
Row mode is not default initially when you create a new project and it detects that Column 1 has some blank cells.  The Engine will instead be put into Record mode automatically.  You can check our source code and better yet our tests to see this.
Here is an example text that you can paste into our Clipboard importer and Create a Project from it and notice that Record mode will be the initial mode.  This is because of the blank cells detected in the first key column which are defining the additional rows for each of the 3 "records" and their sets of attribute pairs.

```
key,Attribute1,Attribute2
1,name,marcadella
,interest,OpenRefine
2,name,John
3,name,Thad
,interest,chess
```
