### ISSUE TITLE
"Match other cells with same content" keeps appearing as the default choice

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#2316] opened 2020-02-19 08:42 UTC
**Describe the bug**

When doing reconciliation, I sometimes manually match entries to Wikidata items using "Search for match". I choose the correct match but the match is applied to _all entries with the same name_ because the radio button "Match other cells with same content" is always ticked by default. Even if I change it, next time this button will again be ticked. 

**Expected behavior**
It would be very cool if I could either choose the default button in settings, or OpenRefine could remember my last choice.

**Screenshots**
<img width="303" alt="Bez názvu" src="https://user-images.githubusercontent.com/21329813/74816668-ddd1bb00-52fb-11ea-9f0b-7e2c15717660.png">

**Desktop**
 - OS: [Windows 10]
 - Browser Version: Chrome version 80.0.3987.106
 - OpenRefine 3.3 Beta

**Comment by adrijshikhar** [comment] 2020-02-20 21:17
@wetneb i would like to work on this. can you please assign it to me?
PS: i have already setup the repo

**Comment by adrijshikhar** [comment] 2020-02-22 18:09
@VojtechDostal Can you please add the steps to reproduce the issue. Thanks

**Comment by wetneb** [comment] 2020-02-23 11:20
@adrijshikhar you might want to learn about reconciliation in OpenRefine - this issue should be understandable if you are familiar with reconciliation workflows in OpenRefine. For instance:
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation

**Comment by VojtechDostal** [comment] 2020-02-23 11:51
@adrijshikhar Thanks for taking up my issue. It would be very helpful if it could be solved. If you want I am happy to assist so that you can easily reproduce the issue. But it should be pretty clear once you try it out for yourself.

**Comment by VladimirAlexiev** [comment] 2020-02-27 10:04
@adrijshikhar #2332 shows that "Match other cells with same content" is actually harmful. 
So please make "Match this cell only" the first and default choice.

**Comment by thadguidry** [comment] 2020-02-27 13:04
@VladimirAlexiev Agree to change the default choice, but curious... we do have Undo/Redo to help here a little or is there some extra problems with Undo in this case ?

**Comment by wetneb** [comment] 2020-02-27 13:35
Not sure about the change of default and changing the order of options - this step should not be done lightly as many users might be used to the current UI layout.

**Comment by thadguidry** [comment] 2020-02-27 14:30
Then... Let's make it a preference that can be set!

Our core philosophy:
We trust users to know what is best for them.
We give power to our users.
We don't choose what is best for them.

I think we need to stick to our core philosophy more in many feature areas of OpenRefine and allow preferences for default handling more than we do now.

More preferences have been asked for many times by GLAM and News orgs that have dedicated workflows that operate in a certain fashion.  Let's help them by opening up more config preferences eventually in areas.

**Proposal:**
Defaults can be stored in the same preferences store we have now, and we just expose those variable defaults to be overridden.  Doesn't have to be fancy, just a set it/forget it which is the handling we have now in places.  We can use convention so that it's easy to search in code...just prefix the keys with something like `$Default`

`$DefaultSearchForMatch : matchOther`

**Comment by VladimirAlexiev** [comment] 2020-02-28 06:27
>problems with Undo in this case

No, just didn't think of it :)

**Comment by wetneb** [comment] 2020-03-06 16:12
Hi @adrijshikhar, just checking if you are still working on this? Let us know if you struggle with anything.

**Comment by khyati-agarwalss** [comment] 2020-03-16 18:31
Hi @adrijshikhar , are you still working on this? If not, can I take this up?

**Comment by khyati-agarwalss** [comment] 2020-03-17 17:39
Hi @wetneb , I think we can solve this by:
1. Replacing "Match other cells with same content" with "Match other rows with same content".
2. Converting the two radio buttons into two clickable buttons and removing the "Match" button.
This will solve both the problems: #2316 and #2332 . 
Any feedback on this?

**Comment by wetneb** [comment] 2020-03-17 18:08
Hmmm, #2332 is not just about the text displayed in the UI: the behaviour of the operation itself must be changed. So I would not try to tackle this issue in the same go.

Converting the radio buttons into clickable buttons would not work for the "New item" option, I think (since the behaviour of that button is also controlled by the existing radio buttons I think).

Why not simply remember which radio button was last picked and restore this choice next time the dialog is opened?

**Comment by Garima829** [comment] 2020-03-17 18:34
> Why not simply remember which radio button was last picked and restore this choice next time the dialog is opened?

I think this would be a better way out as it saves the hassle of selecting "Match this cell only" every time the user wants to choose a new match

**Comment by khyati-agarwalss** [comment] 2020-03-17 18:58
@wetneb and @Garima829 , I get your point. So a checkbox saying "Remember my choice" can be added, which when checked, the current choice out of the two options will get saved.

**Comment by wetneb** [comment] 2020-03-17 19:03
I am not even sure we need a "Remember my choice" checkbox for this. In any case we always want to show the radio buttons - it is just their default value we want to change.
I think it would be pretty consensual to just fill this default value with the previously selected one, with no additional action required from the user (so, consider your "remember my choice" checkbox always ticked). That seems to be what @VojtechDostal implied, no?

**Comment by khyati-agarwalss** [comment] 2020-03-17 19:31
> I think it would be pretty consensual to just fill this default value with the previously selected one, with no additional action required from the user (so, consider your "remember my choice" checkbox always ticked). That seems to be what @VojtechDostal implied, no?

Ohh yes, that completely makes sense.

**Comment by leoshrey** [comment] 2020-03-31 07:28
Hi @wetneb , is this still being worked upon? If not, I want to take this up, can you please suggest?

**Comment by wetneb** [comment] 2020-03-31 07:47
Hi @khyati-agarwalss, are you still working on this?

**Comment by khyati-agarwalss** [comment] 2020-03-31 08:10
No @wetneb , I couldn't solve it. @leoshrey you may proceed with it.

**Comment by BreeAnn7** [comment] 2020-07-17 21:47
Did this issue get fixed? In my version it still defaults to "Match Other Cells with Same Content" and then if I happen to forget to change it to " Match this cell only" it bumps me all the way to the beginning of my project.  So after working 700 rows where I've reconciled wikidata matches if I don't always remember to change it to Match this cell only--I get moved back to row 1..which is frustrating.  I can't figure out how to change the default based on this thread.

Am I missing an update?

**Comment by wetneb** [comment] 2020-07-18 09:27
Hi @BreeAnn7, this has not been solved yet (the issue is still open).

**Comment by WaltonG** [comment] 2022-03-31 14:43
@wetneb  Can I work on this ?

**Closed** 2022-04-05 08:25 UTC
Labels: enhancement, UI, good first issue, reconciliation
