### ISSUE TITLE
CSV Import - Store Blank Columns Checkbox

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#1965] opened 2019-02-20 11:15 UTC
The *CSV/TSV separator-based-files* import settings display has a checkbox option for `Store blank rows`:
- when checked (default), empty rows are stored;
- when unchecked, empty rows are discarded.

It would be useful to also support a `Store blank columns` option, such that:
- when checked (default), empty columns are stored;
- when unchecked, empty columns are discarded.

**Comment by ostephens** [comment] 2019-02-20 12:56
Closing as Duplicate of #1750

**Closed by ostephens** 2019-02-20 12:56 UTC
Labels: duplicate
