### ISSUE TITLE
Key/Value Columnize merges rows

### ISSUE THREAD

**Issue by zingbat** [OpenRefine/OpenRefine#712] opened 2013-04-30 00:22 UTC
Experiencing issues with an exported WordPress XML file being properly read in without a bunch of blank lines, and then using key/value columnize to operate on post metadata. Comment from Tom Morris on the [OpenRefine Google Group where I asked for help (and posted the XML file I'm working with)](https://groups.google.com/forum/?fromgroups=#!topic/openrefine/t88PE-q1kVM) was: 

"There's are secondary issues with a large number of blank rows getting created by the XML importer and with the ordering of columns not being the very good, but even after I deleted all the blank rows and moved the postID column to the beginning (so that it could be used to group records together), the key/value transpose still didn't work the way it should.  I fixed some some another problem in this area, but it looks like there's more work to be done."
##

**Comment by wetneb** [comment] 2017-08-02 08:19
Closing as a duplicate of #1214.

**Closed** 2017-08-02 08:33 UTC
Labels: To Be Reviewed
