### ISSUE TITLE
Transforming a number column to text adds a trailing .0

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1228] opened 2017-08-04 05:23 UTC
#Hi all,  

tabular files often contain a numeric ID column. In Excel, this ID is sometimes stored erroneously as a number, not text. When importing this type of file into Open Refine and transform the ID into text, it often happens that Open Refine adds a .0 at the end. It can be deleted (`value.replace(/.0$/, '').trim() `), but I think this can be a problem for many users, since this ID column is often used for Vlookup / cell.cross().

![screencast](https://user-images.githubusercontent.com/6286410/28955252-972940da-78e5-11e7-9e9a-e6577e25cadc.gif)

**Comment by narendravardi** [comment] 2017-10-10 18:34
@thadguidry can i work on this?

**Comment by thadguidry** [comment] 2017-10-10 22:56
@narendravardi Go for it.  Submit pull request when done.

**Comment by narendravardi** [comment] 2017-10-16 14:20
@thadguidry any suggestions on where to make the changes?

I have gone through the classes `EngineDependentMassCellOperation` and `TextTransformOperation` based on the message printed on the gif file. But I couldn't find out. Please help me out! :)

**Comment by thadguidry** [comment] 2017-10-17 02:38
@narendravardi it all starts here https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js#L206

BUT you cannot just change that existing "to Text" operation because many folks already depend on its current functionality as its expected when you convert Java Numbers to Strings (and we don't want to throw away the original value that Apache POI found in the Excel cell either) https://docs.oracle.com/javase/tutorial/java/data/converting.html

Also, when we display a Number in the Cells in our datagrid, we are not displaying the .0 for whole numbers.  That's a design choice we made long ago.  And want to keep that. (and keep them green colored :)  )

So...

I think we might want to have a new operation for this use case ?

@ettorerizza what do you think ?  how about a "chomp Decimal Text" or "strip Fraction Text" or ?

**Comment by thadguidry** [comment] 2017-10-18 22:57
Hmm... I'm wondering if this is issue is also showing itself in subtle ways even for `cross()` problems as in this guy's problem #1158

**Comment by thadguidry** [comment] 2017-11-10 03:35
@narendravardi How's your progress coming on this issue ?

**Comment by thadguidry** [comment] 2017-11-10 03:37
@narendravardi How's your progress on this ?

**Comment by jackyq2015** [comment] 2017-11-10 16:53
I would say it is an expected behaviour.  The original number has the 1 decimal. so the 14.0 will show as 14 when it's a number. But when you convert to text, it shows 14.0 to preserve the decimal. There is no need and also should not cut the trailing 0

**Comment by thadguidry** [comment] 2017-11-10 18:10
@jackyq2015 this needs to be a display option then, I would say.  So let's make an enhancement around the need to SHOW FULL PRECISION or somesuch....it has been asked for before on the mailing list in the past.  Do you agree with adding a new display option, Jacky ?

**Comment by jackyq2015** [comment] 2017-11-10 18:31
Agree. I found that issue number #1271 for full precision. will treat this one a duplicate of it.

**Closed by jackyq2015** 2017-11-10 18:31 UTC
Labels: easy, enhancement, import/xls, priority-Medium

**Comment by thadguidry** [comment] 2017-11-10 18:43
@jackyq2015 cool. glad we agree
