### ISSUE TITLE
OpenRefine 3.4.1: Reconciliation Service does not use proxy defined in openrefine.l4j.ini

### ISSUE THREAD

**Issue by ToVie** [OpenRefine/OpenRefine#3919] opened 2021-05-19 15:32 UTC
OpenRefine 3.4.1 on Windows (with or without integrated JRE) does not use the proxy set in openrefine.l4j.ini to connect to reconciliation service (https://lobid.org/gnd/reconcile)

### To Reproduce
1. First, set proxy in openrefine.l4j.ini using the following parameters:
  `-Dhttps.proxyHost=proxy-name.domain.ch`
  `-Dhttps.proxyPort=8080`
  `-Dhttp.proxyHost=proxy-name.domain.ch`
  `-Dhttp.proxyPort=8080`
  `-Dhttp.nonProxyHosts=localhost`
2. Then, start OpenRefine using openrefine.exe, open project, select column "CDU - GND" for reconciliation
3. Then start reconciling using https://lobid.org/gnd/reconcile
4. Finally, OpenRefine throws the following error 
`16:50:55.909 [                  command] Failed to guess cell types for load
{"q0":{"query":"Landquart (Fluss)","limit":3}} (0ms)
org.apache.http.conn.HttpHostConnectException: Connect to lobid.org:443 [lobid.org/193.30.112.187] failed: Connection timed out:...`

### Current Results
The following messages are shown in OpenRefine (with verbosity "all"): 
![image](https://user-images.githubusercontent.com/3183064/118835282-21322500-b8c3-11eb-964e-10960864dff3.png)
Additionally we did monitor the network traffic using wireshark and did find no connection from our localhost to our proxy but instead a connection request from our localhost to "emphytos.hbz-nrw.de"  which bears the alias "lobid.org" with the  IP 193.30.112.187.
This leads us to the conclusion that OpenRefine does not use the proxy settings specified in openrefine.l4j.ini.

### Expected Behavior
OpenRefine connects to the Reconciliation service using the proxy specified in openrefine.l4j.ini using the parameters  
  `-Dhttps.proxyHost=proxy-name.domain.ch`
  `-Dhttps.proxyPort=8080`
  `-Dhttp.proxyHost=proxy-name.domain.ch`
  `-Dhttp.proxyPort=8080`
  `-Dhttp.nonProxyHosts=localhost`

### Versions
 - Operating System: Windows 10
 - Browser Version: Edge or Firefox
 - JRE or JDK Version: java version "1.8.0_281" Java(TM) SE Runtime Environment (build 1.8.0_281-b25) Java HotSpot(TM) 64-Bit Server VM (build 25.281-b25, mixed mode)
 - OpenRefine: Version 3.4.1 [437dc4d]

### Datasets
[Dummy.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/6509899/Dummy.openrefine.tar.gz)

### Additional context
OpenRefine runs behind a proxy that does not allow direct connections to the internet. 
We tried both packages that are available for windows (windows with java and widows kit without java)
We also tested with the setting "-Djava.net.useSystemProxies=true", set the proxy-server in the java control panel and got the same results.
We also tried to run openrefine directly from the commandline and added the proxy parameters (we could not test refine.bat because the use of batch files is blocked by group policy).

**Comment by thadguidry** [comment] 2021-05-19 16:20
@ToVie Hmm, curious, instead of through the object method (which there might indeed be a bug that we need to look into further where Apache HTTP client isn't picking them up for some reason)...
Can you try setting with a Windows environment variable at the system level (not user)?
`http_proxy` and `https_proxy`  (lowercase should be fine for Apache HTTP Client library we use and should recognize them)
You can then verify that the proxy settings are passing through into OpenRefine's system Java environment by actually just doing a Custom text tranform on some column and just preview using GREL Clojure expression to pick them up:
```clojure
(System/getenv "https_proxy")
```
where this Clojure expression lists all environment variables exposed to Java system:
```clojure
(System/getenv)
```

**Comment by ToVie** [comment] 2021-05-20 11:57
@thadguidry Thank you for your quick reply. Unfortunately I am not allowed to add or change environment variables on my office machine.
However I did as you suggested on a free test machine:

1. I added `http_proxy` and `https_proxy` as system variables
2. I tested `(System/getenv "http_proxy")` on a column => it works, I see the value of the variable

But I don't  know how to set these as proxies to be used by OpenRefine.

**Comment by wetneb** [comment] 2021-05-20 12:16
This is likely to have changed in the development version as we have switched to a different underlying HTTP library. Is it an option for you to try with a development snapshot? https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases
Otherwise we will soon release 3.5-beta1.

**Comment by ToVie** [comment] 2021-05-20 12:17
@thadguidry Your comment got me thinking and I did some further tests on OpenRefine reconciliation.

**1. Windows proxy and  `-Djava.net.useSystemProxies=true` with valid proxy** 
I tested with a working openly available test proxy (`85.214.250.48:3128`) set in windows system settings (manual/custom proxy configuration) and `openrefine.l4j.ini` with `-Djava.net.useSystemProxies=` set to `true`.
=> Reconciliation service works as expected

**2. Windows proxy and  `-Djava.net.useSystemProxies=true` with invalid proxy** 
I tested with a invalid proxy (`127.0.0.1:1234`) set in windows system settings (manual/custom proxy configuration) and `openrefine.l4j.ini` with `-Djava.net.useSystemProxies=` set to `true`.
=> Reconciliation service does not work as expected

**3. Commented out `-Djava.net.useSystemProxies=true` and instead define invalid proxy in `-Dhttp.proxyHost` / `-Dhttp.proxyPort` and `-Dhttps.proxyHost` / `-Dhttps.proxyPort`
I added `127.0.0.1` and `1234` to the proxy settings, restarted `openrefine.exe` and ran reconciliation.
=> Expected behaviour: Reconciliation fails
=> Actual behaviour: Reconciliation succeeds

**Comment by ToVie** [comment] 2021-05-20 12:18
@wetneb I try the development snapshot.

**Comment by ToVie** [comment] 2021-05-20 13:02
@wetneb I tested the latest development snapshot as described above. The result is the same:
1. `-Djava.net.useSystemProxies=true` and define invalid proxy => reconciliation does not work - as it is expected
2. Commented out `-Djava.net.useSystemProxies=true` and instead define invalid proxy in` -Dhttp.proxyHost` / `-Dhttp.proxyPort` and `-Dhttps.proxyHost` / `-Dhttps.proxyPort` => reconciliation works although it should not

Unrelated to this issue there seems to be a problem with log4j in the development snapshot.

**Comment by thadguidry** [comment] 2021-05-20 14:27
@wetneb Looks like we might need to add the `getProxy()` to our `RequestConfig.custom` on
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/util/HttpClient.java#L69 ?

What's interesting also is the note on the [`DefaultRoutePlanner`](http://hc.apache.org/httpcomponents-client-5.1.x/current/httpclient5/apidocs/org/apache/hc/client5/http/impl/routing/DefaultRoutePlanner.html), which I didn't check on if it is indeed utilized through the call stack (you might check), which says:

> Default implementation of an HttpRoutePlanner. It will not make use of any Java system properties, nor of system or browser proxy settings.

Then there's also the [`SystemDefaultRoutePlanner`](http://hc.apache.org/httpcomponents-client-5.1.x/current/httpclient5/apidocs/org/apache/hc/client5/http/impl/routing/SystemDefaultRoutePlanner.html) which says:

> HttpRoutePlanner implementation based on ProxySelector. By default, this class will pick up the proxy settings of the JVM, either from system properties or from the browser running the application.

**Comment by ToVie** [comment] 2021-05-21 07:04
@thadguidry I see your point. In our case, that is working in a restricted environment, it would be helpful to define a proxy that differs from the general setting on OS level. The general setting enforces a proxy with kerberos authentication based on user and token, which breaks a lot of java applications. Therefore an alternate proxy was defined that allows or disallows access based on  the machine sending the request.

**Comment by wetneb** [comment] 2021-05-27 09:39
Thanks for the thorough analysis!

Then this issue is pretty clear to me: one needs to make sure that our HttpClient class respects the custom proxy settings that we advertise (such as `http.proxyPort` and `http.proxyHost`).

I am marking this as a good first issue because @ToVie's diagnosis in https://github.com/OpenRefine/OpenRefine/issues/3919#issuecomment-845049535 should be easy to follow, to test a fix.

**Comment by hpiedcoq** [comment] 2021-11-04 09:48
Hi!
We are currently facing this issue regarding Refine behind a proxy on the dedicated instance that we host on our organization infra.
"add column by fetching URL..." doesn't work.

We use a workaround by _curling_ the url usint jython, but it's not really user-friendly.

Is there any progress on this topic?

**Comment by isabelgalanb** [comment] 2022-01-31 11:26
Hi, I've just download release 3.5.2 and looks like the problem persists.
Anybody knows in which release it will be solved?

Thanks.

**Comment by wetneb** [comment] 2022-01-31 18:54
Hi!

Unfortunately we do not know: it will not be solved until someone contributes a fix for this issue. I understand this is an important issue for many people, so I am adding this high priority tag hoping that it will attract contributors, but that does not guarantee anything of course.

**Comment by isabelgalanb** [comment] 2022-02-25 12:23
Finally I got it worked. 

In my organization, besides HTTP Proxy, we have got SOCKs Proxy. Then, configuring it in file openrefine.l4j.ini it worked.

-DsocksProxyHost=proxy-name.domain.ch
-DsocksProxyPort=1080 

Thanks. I hope this helps you too.

**Comment by WaltonG** [comment] 2022-03-29 10:11
@wetneb I would like to work on this issue. Based on the discussions I think ill get to  the solution

**Comment by wetneb** [comment] 2022-03-31 09:58
@WaltonG I would expect `openrefine.l4j.ini` to be only read when OpenRefine is launched via `openrefine.exe` (which you can generate with `mvn package`). Is this how you are testing it?

**Comment by WaltonG** [comment] 2022-03-31 11:11
@wetneb I launched it using the refine command, I guess thats why openrefine.l4j.ini was not read. I will re-test with openrefine.exe

**Comment by thadguidry** [comment] 2022-03-31 14:58
@WaltonG It's interesting that they give the `<jre><opt>` context in their documentation: http://launch4j.sourceforge.net/docs.html#Configuration_file

```
<opt>-Dlaunch4j.exedir="%EXEDIR%"</opt>
<opt>-Dlaunch4j.exefile="%EXEFILE%"</opt>
<opt>-Denv.path="%Path%"</opt>
<opt>-Dsettings="%HomeDrive%%HomePath%\\settings.ini"</opt>
```
and also http://launch4j.sourceforge.net/docs.html#Additional_jvm_options
And very interesting choice of phrase here in that section:
> Now you can specify the options in the configuration file, ini file or in both, **but you cannot override them**.

We know that `java.net.useSystemProxies` is a system environment property.  And environment property for the JRE system.
And within code we know we can do something like `System.setProperty("java.net.useSystemProxies", "true");`

So perhaps we can just do:
`-Denv.java.net.useSystemProxies=true` ???

**Comment by WaltonG** [comment] 2022-03-31 15:57
@thadguidry I think with -Denv.java.net.useSystemProxies=true  one will not be required to add proxy details to the configuration file. Let look into it to get more insight.

**Comment by wetneb** [comment] 2022-03-31 16:10
@WaltonG your testing code is incorrect. When you write
`System.getenv("http.proxyHost" + "getenv with -D")`, that is the same thing as `System.getenv("http.proxyHostgetenv with -D")` and that is clearly not going to retrieve the configuration variable you expect.

Of course make sure you repackage (`mvn package`) every time you make code changes too.

**Comment by WaltonG** [comment] 2022-03-31 16:56
@wetneb Yes am now on the right track. Initially I was adding the test data to refine.ini  and not openrefine.l4j.ini. 
Thank you for the oversight of System.getenv("http.proxyHost" + "getenv with -D").  The  + "getenv with -D" was supposed to be a tag but the syntax was incorrect thats why I got nulls from the below latest output

[-Xms512m, -Xmx1024m, -Djava.library.path=server/target/lib/native/windows, -Xms256M, -Xmx1024M, -Djava.net.useSystemProxies=true, -Dhttp.proxyHost=proxy.com, -Dhttp.port=80]
null
null
null
null

**Comment by WaltonG** [comment] 2022-03-31 17:25
@wetneb I have confirmed from the test that proxy port and host in the openrefine.l4j.ini file can be retrived by getProperty method

[-Xms512m, -Xmx1024m, -Djava.library.path=server/target/lib/native/windows, -Xms256M, -Xmx1024M, -Djava.net.useSystemProxies=true, -Dhttp.proxyHost=proxy.com, -Dhttp.port=80]
null Retrieved by getenv
null Retrieved by getenv
proxy.com Retrieved by getProperty
80 Retrieved by getProperty

**Closed** 2022-04-19 14:30 UTC
Labels: bug, priority: High, good first issue, reconciliation, fetch urls
