### ISSUE TITLE
«Split multi-valued cells in column address» does not fill the remaining cells

### ISSUE THREAD

**Issue by n-timofeev** [OpenRefine/OpenRefine#5487] opened 2022-12-02 20:34 UTC
Not sure if this is a bug or a feature, but in many cases it is impossible to use «Fill down» function and you have to write complex expressions for each column. Very tiring...

### Input
```
+------+---------+------------+
| name | address | email      |
+------+---------+------------+
| A    | X       | a@mail.com |
+------+---------+------------+
| B    | Y1;Y2   | b@mail.com |
+------+---------+------------+
| C    | Z       |            |
+------+---------+------------+
```

### Current Results
```
+------+---------+------------+
| name | address | email      |
+------+---------+------------+
| A    | X       | a@mail.com |
+------+---------+------------+
| B    | Y1      | b@mail.com |
+------+---------+------------+
|      | Y2      |            |
+------+---------+------------+
| C    | Z       |            |
+------+---------+------------+
```

### Expected Behavior
```
+------+---------+------------+
| name | address | email      |
+------+---------+------------+
| A    | X       | a@mail.com |
+------+---------+------------+
| B    | Y1      | b@mail.com |
+------+---------+------------+
| B    | Y2      | b@mail.com |
+------+---------+------------+
| C    | Z       |            |
+------+---------+------------+
```

### Versions
 - Operating System: Windows Server 2022
 - Browser Version: Edge 107
 - JRE or JDK Version: Java 18
 - OpenRefine:  3.6.2

**Comment by wetneb** [comment] 2022-12-02 21:13
Hi @n-timofeev, this is the intended behaviour of this function indeed. To obtain the state you want, you should use the Fill down operation on other columns, _in records mode_, starting with the columns which are not the first one.

**Comment by wetneb** [comment] 2022-12-02 21:15
Closing since this is a not a bug.

**Closed by wetneb** 2022-12-02 21:15 UTC
Labels: question, records
