### ISSUE TITLE
Facet's "Invert" button should always be visible

### ISSUE THREAD

**Issue by esiegerman** [OpenRefine/OpenRefine#1010] opened 2015-06-26 16:45 UTC
A facet's _invert_ button is only visible if items from that facet are selected (i.e. if the facet is currently active).  _invert_ should be visible, and clickable, at all times, so that one can:
- see more easily whether the facet is in "include" or "exclude" mode, i.e. what clicking on one of its items will do (one can infer this from the signs of the item counts, but showing the state explicitly would improve usability)
- toggle that state without having to select an item first

**Comment by magdmartin** [comment] 2015-06-29 04:17
In Refine2.6-beta when in exclude mode the color of the select value change from orange to black, the value is strike-through and a minus sign is added. So I personally don't think we need to do any additional changes on that point. 

However, I agree with @esiegerman the inverse function should be available right away to the user. The initial facet can look like this: 
![new facet example](https://cloud.githubusercontent.com/assets/2589584/8400868/aec00c14-1df3-11e5-9da1-11d769eeb4cb.jpg)

**Comment by jackyq2015** [comment] 2015-06-30 12:26
My understanding is that "invert" will do a "include others item except this one". so there's nothing to invert if no item is selected. The function is like in file browser you can do a "Invert Selection"operation. But it only allow you start with one item. correct me if I am wrong.

**Comment by esiegerman** [comment] 2015-06-30 16:49
@jackyq2015 The thing is that _invert_ is a toggle -- and it remembers its state even if nothing is selected.  Try this:

1. create a new facet
2. select one or more choices; they highlight in red
3. click _invert_; they turn into struck-through black
4. click _reset_
5. click a choice; it comes up **already inverted**

It's that memory that makes _invert_ different from _reset_:  clicking _reset_ with nothing selected[1] would be a no-op; clicking _invert_ with nothing selected would still be a meaningful operation, as it would affect what _will_ happen the next time you select something.

@magdmartin Agreed that the inversion state doesn't need any more graphic treatment; keeping the button visible (and clickable) would be enough.

[1] assuming the _reset_ button itself stayed visible -- which I'm _not_ asking for btw

**Comment by jackyq2015** [comment] 2015-07-01 01:36
@esiegerman I tried the given steps. But after I did the step 5, it marks the selected in red and shows the "change", "invert" and "reset" link without "already inverted" showed. For me, it's normal. can you paste a screenshot for it? Maybe you come across different issue.

**Comment by esiegerman** [comment] 2015-07-01 02:20
@jackyq2015 Woops, my description was incorrect.  Step (4) should read:

4. Deselect all of the selected choices

_reset_ flips the facet back to _include_ mode, but if you deselect all the choices yourself, it stays in _exclude_ mode.

**Comment by jackyq2015** [comment] 2015-07-01 16:43
@esiegerman Still, I can't reproduce it even I did the step 4 as you corrected.

The deselect(by click it) will also set the mode to include. Actually, it only allow you "include" either all items or only 1 items, there is no multi selection.

**Comment by tfmorris** [comment] 2015-10-16 20:40
The current behavior sounds inconsistent, so marking this as a bug.

**Comment by thadguidry** [comment] 2017-08-29 19:32
Verified as working as expected in 2.7  I am the one who originally tested this, way back when.  INVERT is a special mode and stays in that mode until you unselect it.  While in inverted mode, a click on a value itself will cause it to strikethrough and this is expected.  If you click on include next to it, it will be deselected.  You stay in inverted mode until you have clicked on INVERT again to change back to normal mode in the facet.

**Closed by thadguidry** 2017-08-29 19:32 UTC
Labels: bug
