### ISSUE TITLE
Export fails when outputting Excel 2017+

### ISSUE THREAD

**Issue by scottythered** [OpenRefine/OpenRefine#2111] opened 2019-08-07 16:56 UTC
**Describe the bug**
OR fails when exporting a project as an Excel 2017+ file.

**To Reproduce**
Try exporting a project as an Excel 2017+ file.

**Current Results**
```
HTTP ERROR 500
Problem accessing /command/core/export-rows/infineon_adds_2019-06-26-csv.xlsx. Reason: DEFAULT

Caused by: java.lang.NoSuchFieldError: DEFAULT
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:125)
	at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:75)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:115)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Desktop:**
 - OS: Windows 10
 - Browser Version: Chrome 75.0.3770.142 (64-bit), Firefox 68.0.1 (64-bit)
 - JRE or JDK Version: Java( SE Runtime Environment build 1.8.0_221-b11

**OpenRefine:**
 - OpenRefine Version 3.2 [55c921b]

**Comment by wetneb** [comment] 2019-12-22 09:24
I cannot reproduce this, neither on master nor from 3.2. It might be specific to the project. @scottythered, do you think you could share a sample project where this happens?

**Comment by tfmorris** [comment] 2020-06-29 00:37
Closing. Feel free to reopen if you have an example that reproduces this.

**Closed by tfmorris** 2020-06-29 00:37 UTC
Labels: XLS(X), bug, export, not reproducible
