### ISSUE TITLE
Custom text facet boolean facets not displaying

### ISSUE THREAD

**Issue by richyvk** [OpenRefine/OpenRefine#1983] opened 2019-03-14 02:54 UTC
Having an issue when doing a custom text facet on a column.

Seems to happen with both GREL and Python.

An example would be doing a custom text facet on a column using the expression `startsWith(value, 'A')`

In the facet choices after faceting I would expect to see both `true` and `false` as a choice, but I only see `(boolean)`.

In the facet dialogue box the preview is showing true/false as expected so faceting is working.

Using Version 3.1 [b90e413] on MacOS Mojave. Installed using Mac kit.

Tested on same machine with version 2.8 and it works fine. Haven't tried with version 3.0.

**Comment by thadguidry** [comment] 2019-03-14 03:07
Yes sorry about that.  We fixed this.  Try 3.2 Beta https://github.com/OpenRefine/OpenRefine/releases

**Comment by richyvk** [comment] 2019-03-14 03:29
@thadguidry Tested 3.2 beta and working - thanks very much for clarifying :)

**Comment by wetneb** [comment] 2019-03-14 08:58
Closing then as a duplicate of #1957.

**Closed by wetneb** 2019-03-14 08:58 UTC
