### ISSUE TITLE
Cluster merge selection gets confused by multiple clicks

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#1056] opened 2015-09-01 16:44 UTC
In the clustering dialog, if you click the "Merge?" checkbox and then click one of the names in the cluster (so that it's value gets used as the target merge value), the internal state of the cluster `edit` toggle becomes `false`

**Comment by magdmartin** [comment] 2015-09-06 17:29
Duplicate of #1060 which provie more details. Closing this issue.

**Closed by magdmartin** 2015-09-06 17:29 UTC
Labels: bug, component-UI
