### ISSUE TITLE
Wikimedia Commons Wikibase not detecting Odia-script characters

### ISSUE THREAD

**Issue by psubhashish** [OpenRefine/OpenRefine#5657] opened 2023-02-28 23:39 UTC
I've been trying to upload a batch of files that have names containing both Latin and [Odia](https://en.wikipedia.org/wiki/Odia_script) characters. Commons allows filenames with Odia characters, for instance, [this file](https://commons.wikimedia.org/wiki/Category:Audio_files_created_using_Kathabhidhana). See the screenshot of the error I see below. cc @wetneb

<img width="752" alt="OpenRefine-issue-with-Odia" src="https://user-images.githubusercontent.com/1258090/222007841-b59c7218-db7a-44aa-b5cf-45b88375e354.png">

**Comment by wetneb** [comment] 2023-03-01 06:43
Duplicate of #5656

**Closed by wetneb** 2023-03-01 06:43 UTC
Labels: duplicate
