### ISSUE TITLE
Wikitext input field in schema editor removes line breaks

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5341] opened 2022-10-14 14:56 UTC
I tried adding the following Wikitext in the Wikitext input field in the schema editor (Wikimedia Commons manifest) (notice the line breaks):

```
=={{int:filedesc}}==
{{Information
|author=[[User:Spinster|Sandra Fauconnier]]
}}

=={{int:license-header}}==
{{cc-by-4.0}}
```

The input field removes the line breaks: 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/9881645/195875678-997c1971-6d5d-4315-98f3-f13edf60670d.png">

Also in the uploaded file ([example](https://commons.wikimedia.org/w/index.php?title=File:Koninklijk_Theater_Tuscinski_%E2%80%93_cinema_organ_01.jpg&action=edit&oldid=696344130)), which is not really 'best practice' on Wikimedia Commons (and I've witnessed one test upload where the Wikitext didn't render properly because of this).
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9881645/195875826-487b24d6-049d-4ea2-8a20-a8f900731fa0.png">

### Expected Behavior
Line breaks stay.

### Versions
 - OpenRefine: Version 3.7-SNAPSHOT [cca62b5]

### Datasets
[uploading-3-files-to-Commons-and-everything-will-go-wrong.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/9787467/uploading-3-files-to-Commons-and-everything-will-go-wrong.openrefine.tar.gz)

### Additional context
In @lozanaross' [wireframes](https://xd.adobe.com/view/3ae13acb-7afb-4ea5-8252-351a1622abba-6fb2/screen/e6078d8a-bffc-4284-a73e-341303012812) there's the suggestion to add a 'drag to make field bigger' thingy in the bottom right corner and that corresponds with the expectation that line breaks are kept.

Our more advanced plans about a simple Wikitext builder should also take this into account.

**Comment by wetneb** [comment] 2022-10-14 17:07
I would say duplicate of #5287 then?

**Closed** 2022-10-14 20:31 UTC
Labels: bug, duplicate, wikicommons, UX
