### ISSUE TITLE
Handle errors on project load better

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#697] opened 2013-03-14 19:35 UTC
I ran out of memory when loading a project and the Refine UI just stayed stuck with the spinner up.  We need to handle this better.  The error did make it back the Javascript console:

Failed to load resource: the server responded with a status of 500 (GC overhead limit exceeded) http://127.0.0.1:3333/command/core/get-project-metadata?project=1964915921526

and this was the stack trace on the server

14:52:05.576 [                   refine] GET /command/core/get-project-metadata (19ms)
14:53:57.640 [          org.mortbay.log] Error for /command/core/get-project-metadata (112064ms)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:2694)
        at java.lang.String.<init>(String.java:234)
        at org.codehaus.jackson.util.TextBuffer.contentsAsString(TextBuffer.java:324)
        at org.codehaus.jackson.impl.ReaderBasedParser.getText(ReaderBasedParser.java:87)
        at com.google.refine.model.Cell.loadStreaming(Cell.java:165)
        at com.google.refine.model.Row.loadStreaming(Row.java:228)
        at com.google.refine.model.Row.load(Row.java:198)
        at com.google.refine.model.Project.loadFromReader(Project.java:218)
        at com.google.refine.model.Project.loadFromInputStream(Project.java:182)
        at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:152)
        at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:113)
        at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:224)
        at com.google.refine.ProjectManager.getProject(ProjectManager.java:377)
        at com.google.refine.commands.Command.getProject(Command.java:181)
        at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:53)
        at com.google.refine.RefineServlet.service(RefineServlet.java:170)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)

**Comment by thadguidry** [comment] 2019-03-01 18:46
Steps to reproduce:
1. Increase Refine memory in order to large a large CSV file.
2. Use a large CSV or JSON file and load into Refine.
3. Save project.
4. Decrease Refine memory to default 1400mb or less to cause error to occur on project loading.
5. Restart Refine.
6. Click to open the large project and notice large spinner and then error in console.
 
Even now with version 3.2 , we still don't show to the user in the UI that a Memory Error has occurred on Project loading, and we could and should within the context of `/command/core/get-project-metadata`

Perhaps add more robust error handling within [Refine.reinitializeProjectData](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/project.js#L179) or [onLoad()](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/project.js#L498) ?

```
12:03:45.988 [                   refine] GET /command/core/get-project-metadata (11ms)
12:04:11.538 [          org.mortbay.log] Error for /command/core/get-project-metadata (25550ms)
java.lang.OutOfMemoryError: Java heap space
        at com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer.makeChild(CharsToNameCanonicalizer.java:315)
        at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1345)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:899)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at com.google.refine.model.Row.loadStreaming(Row.java:225)
        at com.google.refine.model.Row.load(Row.java:204)
        at com.google.refine.model.Project.loadFromReader(Project.java:218)
        at com.google.refine.model.Project.loadFromInputStream(Project.java:177)
        at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:157)
        at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:118)
        at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:249)
        at com.google.refine.ProjectManager.getProject(ProjectManager.java:505)
        at com.google.refine.commands.Command.getProject(Command.java:175)
        at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:53)
        at com.google.refine.RefineServlet.service(RefineServlet.java:182)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
```

**Comment by thadguidry** [comment] 2019-04-24 01:15
Closing since #704 captures the general feature request better.

**Closed by thadguidry** 2019-04-24 01:15 UTC
Labels: bug, error handling, priority-High, usability
