### ISSUE TITLE
Reconciling without names

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#2433] opened 2020-03-18 09:00 UTC
Sometimes, you want to reconcile with objects no matter what their name (label) in Wikidata is. I have therefore created an empty column and tried to reconcile to it:

<img width="603" alt="Bez názvu" src="https://user-images.githubusercontent.com/21329813/76943122-21b9df00-68ff-11ea-8cc6-d4dea83059b3.png">

However, the reconciliation process fails because it is probably dependent on a non-empty string in the main field. Is it possible to somehow only reconcile based on coordinates?

**Comment by wetneb** [comment] 2020-03-18 09:19
Currently the reconciliation API does not make it easy to reconcile without names, this is something we would like to improve:
https://github.com/reconciliation-api/specs/issues/27

The Wikidata reconciliation service will only ignore labels when given a unique identifier property as extra column, implementing coordinate-based retrieval would be quite some work in the current state of things (but I totally agree it would be a useful thing to do and hopefully it could happen once/if we migrate to a new architecture, see [T244847](https://phabricator.wikimedia.org/T244847)).

**Comment by VojtechDostal** [comment] 2020-03-18 09:35
Thank you for the great work you're doing ;)

**Comment by VojtechDostal** [comment] 2021-09-10 09:14
This is nicely solved by https://github.com/gitonthescene/csv-reconcile so I'm in favor of closing this issue.

**Comment by wetneb** [comment] 2021-09-10 11:43
For me it feels like this is still a very legitimate feature request for OpenRefine actually, so let's reopen it :)

**Comment by mshd** [comment] 2021-11-17 16:33
Any update?

**Comment by wetneb** [comment] 2023-09-01 15:45
I simplified the title of this issue to make it more generic. The problem isn't specific to Wikidata, or to geographic coordinates: this is about reconciling based on some property which is not the name, in the absence of a column with names.

**Comment by wetneb** [comment] 2023-09-10 14:15
This is a duplicate of #6044 - since that one has more discussion already, let's close this one and continue the discussion there.

**Closed by wetneb** 2023-09-10 14:15 UTC
Labels: reconciliation, reconciliation API design
