### ISSUE TITLE
cluster with one row count

### ISSUE THREAD

**Issue by martinrefinepro** [OpenRefine/OpenRefine#2162] opened 2019-09-19 04:33 UTC
**Describe the bug**
OpenRefine 3.2 return cluster with one-row count for key collision methods are impacted. 
The issue was introduced in the 3.2 release. 

**To Reproduce**
Create a project from clipboard
insert three line 
```
a
b
c
```
invoke clustering > key collision > fingerprint

**Current Results**
we see cluster with one-row count. It seems only the key collision methods are impacted. 

![clipboard - OpenRefine](https://user-images.githubusercontent.com/29434859/65213628-eab06100-da74-11e9-8f45-5457cce8f284.png)

**Expected behavior**
OpenRefine should show the message `No clusters were found with the selected method`

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chromium Version 76.0.3809.100
 - JRE or JDK Version:java version "1.8.0_201"

**OpenRefine (please complete the following information):**
 - Version 3.2 

I tested with OpenRefine 3.1 and it behaves as expected (ie no cluster found)

**Comment by wetneb** [comment] 2019-09-19 07:09
Seems to be a duplicate of #2147 which was solved in the upcoming 3.3 release.

**Comment by wetneb** [comment] 2019-09-22 16:36
Closing as duplicate of #2147

**Closed by wetneb** 2019-09-22 16:36 UTC
Labels: bug, clustering, duplicate
