### ISSUE TITLE
Index page: `next` button does not appear as expected for Deutsch

### ISSUE THREAD

**Issue by joanneong** [OpenRefine/OpenRefine#1455] opened 2018-02-06 13:00 UTC
I was trying out different languages offered by OpenRefine when I noticed something weird about the index page after I switched the language to Deutsch:

![index_page_error](https://user-images.githubusercontent.com/24493463/35860823-6a1d21dc-0b80-11e8-9462-09e0bc2c5f81.png)

It is supposed to be a "Next" button, but it is not showing up for Deutsch. 

P/S I am using MacOS, and running OpenRefine on Google Chrome Version 64.0.3282.140 (Official Build) (64-bit).

**Comment by wetneb** [comment] 2018-02-06 18:33
@joanneong good catch! That's because the German translation is still very far from complete, so many strings don't even show up. I thought that we had a proper language fallback in place (so that the English strings are used instead) but if we have one it clearly does not work. #1285 could address that so if you want to work on this it might be useful to coordinate there.

**Comment by ostephens** [comment] 2018-02-07 09:32
The current i8n solution in use doesn't support a fallback option in the way we need (I did look at this previously but can't remember the details) - so agreed that #1285 is the way forward

**Comment by magdmartin** [comment] 2018-02-08 02:05
Should #946 have taken care of this?

**Comment by wetneb** [comment] 2018-02-08 08:05
@magdmartin no this was already merged and the problem is still here

**Comment by wetneb** [comment] 2019-12-20 19:06
Language fallback was implemented so we can close this now.

**Closed by wetneb** 2019-12-20 19:06 UTC
Labels: UI, grid pagination / scrolling, i18n
