### ISSUE TITLE
Total fail when delete files with codification issues

### ISSUE THREAD

**Issue by RicardoOrtizG** [OpenRefine/OpenRefine#3514] opened 2021-01-22 16:42 UTC
Trying to delete files with codification issue in Open Refine 3.4.1. # 3511, the Open Refine collapse and is showing no more files.

### To Play
1. Delete files using the GUI of OpenRefine
2. OpenRefine still showing the files, like the files weren't deleted
3. I reload the openRefine and it showed collapsed.

![image](https://user-images.githubusercontent.com/15789737/105518850-c129ca00-5ca6-11eb-8b38-46477a57abbd.png)

**Comment by wetneb** [comment] 2021-02-02 16:51
Hi @RicardoOrtizG, thanks for this report! It is not clear to me what files you deleted, can you be more precise?

**Comment by RicardoOrtizG** [comment] 2021-02-22 21:01
Sorry, I put a wrong URL. I was trying to delete the files I mentioned in the issue [#3511 ](https://github.com/OpenRefine/OpenRefine/issues/3511)

**Comment by wetneb** [comment] 2021-02-24 14:30
Let's close this and handle this in #3511 since it should be the same root cause.

**Closed by wetneb** 2021-02-24 14:30 UTC
Labels: bug, not reproducible
