### ISSUE TITLE
Convert to date : bug

### ISSUE THREAD

**Issue by bouzinac** [OpenRefine/OpenRefine#3123] opened 2020-08-24 21:18 UTC
Hello...
There is a horrible bug with the "convert to date" button : Dates are interpreted as MonthDayYear whilst they were DayMonthYear before the conversion.
is there a button to help define the conversion, to tell if the date to be converted shall be understood as MDY or DMY ?

**Comment by thadguidry** [comment] 2020-08-24 21:23
A button for convert to date?  We don't have that exactly.
Perhaps you mean some menu item on Edit column... Transform?

You can find the documentation for GREL for the `toDate()` function here:
https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions

We also have some community recipes for Dates found here:
https://github.com/OpenRefine/OpenRefine/wiki/Recipes#3-dates

**Comment by bouzinac** [comment] 2020-08-25 05:11
Yes, to reproduce the pb, use this path:
"dataset"     :   "_dates
06/09/1962
16/09/1962_"
copy the dataset to openrefine
on the column menu, hit : edit cells // common transforms // To dates

the result will be "1962-06-09T00:00:00Z" while I was having **6 september 1962**
But!! and that's why I have been put in error : the second convert is correct "1962-09-16T00:00:00Z" because 16 cannot be a month :)

**Comment by thadguidry** [comment] 2020-08-25 13:35
@bouzinac our toDate() function (which the Edit cells -> Common transforms -> To dates will use in the background) is assuming month first as the default.  Which is why I gave you the documentation links to learn more options and ways to control things, even to give a particular format that you think the dates column is formatted in.

You can experiment with **Add column based on this column...**

![image](https://user-images.githubusercontent.com/986438/91180383-49cb1c80-e6ad-11ea-8714-3254343b9537.png)

Here I am giving the default boolean argument value of Month First with `true`:

![image](https://user-images.githubusercontent.com/986438/91179167-c4933800-e6ab-11ea-95e9-7c7d7917d7c6.png)

but you can change that my giving `false` instead. And notice the month and day are now switched:

![image](https://user-images.githubusercontent.com/986438/91179232-dbd22580-e6ab-11ea-9331-89fb7664809f.png)

and here I am being even more exact with GREL `toDate()` function and tell GREL exactly the format of my dates in the column and then asking GREL to convert to a String (keeping it as Text) but only the year part:

![image](https://user-images.githubusercontent.com/986438/91179911-beea2200-e6ac-11ea-9261-dd82ceb68a36.png)

Here I am doing the same thing, but instead of `toString()`, I am using the `datePart()` to ask for only the year part of my date:

![image](https://user-images.githubusercontent.com/986438/91180195-16888d80-e6ad-11ea-9118-0b82554d2598.png)

Please join our mailing list so that you can ask questions from our community at any time; details on our website: https://openrefine.org/community.html

I will close this issue since it is not a bug.  But now you have learned a little more of OpenRefine GREL functions!

**Closed by thadguidry** 2020-08-25 13:35 UTC
Labels: wontfix

**Comment by bouzinac** [comment] 2020-08-25 17:04
Ok
Then the  edit cells // common transforms // To dates
'To dates' button should be better labelled like 'From MDY to dates'...

Thanks for the interesting screenshots !

Alexis

Le mar. 25 août 2020 à 15:35, Thad Guidry <notifications@github.com> a
écrit :

**Comment by thadguidry** [comment] 2020-08-25 17:52
@bouzinac Is your native language French?  Do you have suggestions for better French labels on some of the menu items?  Which ones and what do you suggest would be a good French phase?

**Comment by tfmorris** [comment] 2020-08-25 18:51
This is similar to #3020 and we've discussed changing the behavior, but it wouldn't preserve backward compatibility, which is a problem.

**Comment by bouzinac** [comment] 2020-08-25 19:37
I wasn't aware of the 3020 ticket.
If the dev is painful, my goal is not to cancel the button but make the
label more concise and less confusing.
The english label of that button could be "Text MDY to date" or
"MonthDayYear to date"
And the French label "Convertir MoisJourAnnée vers date" : there would be
no questions about the behaviour of the shortcut button.
What about two different buttons, one with "MDY conversion" and the other
"DMY conversion" ?

Le mar. 25 août 2020 à 20:51, Tom Morris <notifications@github.com> a
écrit :
