### ISSUE TITLE
Every other reconciliation batch fails in 3.5

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3664] opened 2021-02-23 02:52 UTC
With the current development version, every other reconciliation call fails with a `NoHttpResponseException`, apparently because it's attempting to reuse a closed connection.

### To Reproduce

Reconcile a project with more than 20-30 rows and observe that the console logs failures on every other call.

### Current Results
Every other batch fails with an HTTP error.

### Expected Behavior
All batches get reconciled

### Versions
 - OpenRefine: current development version

**Comment by gitonthescene** [comment] 2021-03-10 09:01
I think there is a related bug with using Data Extension.  It might be exactly the same bug, but I thought it worth pointing out.  Getting `127.0.0.1:5000 failed to respond` messages for every other batch.

**Comment by gitonthescene** [comment] 2021-03-10 11:08
Oho!!  This looks like it might be a issue with the server.  I found [this post](https://stackoverflow.com/questions/10523879/how-to-make-flask-keep-ajax-http-connection-alive) which enables [Keep-Alive](https://www.imperva.com/learn/performance/http-keep-alive/) on my flask server and I'm not seeing issues with every other batch failing.

This raises the question about whether to consider this a server problem or a client problem.  Should OpenRefine be able to handle servers which close connections after each request?  Or maybe we should require that `Keep-Alive` be enabled for reconciliation servers.

In any event, I believe this to be the source of the problem.  OpenRefine is [pooling connections](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/util/HttpClient.java#L57) but they're being closed on the server side when `Keep-Alive` is not enabled.

**Comment by gitonthescene** [comment] 2021-03-10 11:10
On the positive side, this was probably exposed because reconciliation is so fast on OpenRefine 3.5!!  :D

**Comment by tfmorris** [comment] 2021-03-10 17:35
> Should OpenRefine be able to handle servers which close connections after each request? 
> Or maybe we should require that Keep-Alive be enabled for reconciliation servers.

Yes, we need to handle this. Persistent connections are a performance optimization, but the system should still be functional without it.

Our HTTP implementation has changed completely since last release, so some of the behavior changes may be associated with the switch to Apache HTTP Client 5.

I should have noted what reconciliation service I was using on the original ticket, but I suspect it was your CSV reconciliation service, so the comment about this being specific to servers that don't support Keep-Alive makes sense.

**Comment by gitonthescene** [comment] 2021-03-10 21:22
I think some defensiveness is a good idea, but it's worth noting that [HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616.html) has been available for 20 years.  TBH, I'm surprised that flask doesn't have some protocol check.  In any event, I think it's probably fair to classify this as a non-critical bug.

**Comment by wetneb** [comment] 2021-05-02 08:03
I will try to reproduce this. Do I understand correctly that this happens with [csv-reconcile](https://github.com/gitonthescene/csv-reconcile)?

**Comment by gitonthescene** [comment] 2021-05-02 08:57
It does if you remove [this line](https://github.com/gitonthescene/csv-reconcile/blob/master/csv_reconcile/__init__.py#L214).  Honestly I don’t believe any real production services still close connections after each request any more.  The server that comes with Flask is not meant to be production ready.  Instead it should be wrapped with gunicorn or uwsgi.  The line pointed to above is a cheap hack meant to make the project as easy as possible to get up and running.

For clarity, this is all stuff I’ve learned along the way.

OTOH, as mentioned above while this sort of pathological closing of connections with each request is unlikely, the odd broken connection is not.  I’m guessing you’d like to test against broken connections.  If so, removing that line is one way to guarantee connections will be broken.

I hope this helps.  Let me know if you have any questions.

**Closed** 2021-05-15 06:52 UTC
Labels: bug, priority: High, reconciliation

**Comment by gitonthescene** [comment] 2021-05-15 07:46
Great!  I take it you were able to make use of the service as described above?
