### ISSUE TITLE
Reconciling one project against another??

### ISSUE THREAD

**Issue by gitonthescene** [OpenRefine/OpenRefine#3700] opened 2021-03-05 07:57 UTC
This actually less of a real feature request than it is a brainstorming exercise.  Feel free to close if there’s likely to be no time for it.

The [reconcile-csv](http://okfnlabs.org/reconcile-csv/) reconciliation service could be used to reconcile one project against another by simply exporting the latter as a csv and then supplying the desired id and name columns to pick what to resolve to and what to resolve against.

This makes me wonder if this step is really necessary.

### Proposed solution

You could have reconciling one project against another as a feature of OpenRefine.  You would supply a column of unique ids and a column of what to reconcile against and simply run the reconciliation.  There are design choices about how to ensure unique ids but I think this is doable.

Moreover, clustering is just a special case of this where a project is reconciled against itself with the clustering column representing both the ids and the value to reconcile against.  So there is a potential to consolidate the underlying code.

You could even serve up the reconciliation service as `http://127.0.0.1/reconcile/<project name or id>/<id col>/<reconcile column>` with the benefit being to keep the API consistent.

Given that clustering is available I’d think most of the pieces would be readily at hand.

Like I said, this is more imagineering than an actual feature request, but I thought I would toss it out there.  I’m sorry if it comes across as noise.

Regards,

### Alternatives considered

Simply continue using tools like reconcile-csv.

**Comment by wetneb** [comment] 2021-03-05 08:54
Very legitimate request! In fact it is a duplicate of #2003 #941 #176, so closing this.

**Closed by wetneb** 2021-03-05 08:54 UTC
Labels: duplicate, enhancement, reconciliation

**Comment by gitonthescene** [comment] 2021-03-05 09:20
It might be worth suggesting using reconcile-csv in the short term or my python version [csv-reconcile](https://github.com/gitonthescene/csv-reconcile) which is more configurable.  I plan on adding more documentation shortly.

**Comment by wetneb** [comment] 2021-03-05 12:48
PRs to update our docs / website in this regard would be most welcome :)

**Comment by gitonthescene** [comment] 2021-03-05 23:28
I’m happy to.  Can you suggest where?  Is there a Tips and Tricks section?

**Comment by wetneb** [comment] 2021-03-06 07:39
Perhaps it could be mentioned somewhere in https://docs.openrefine.org/manual/reconciling?
