### ISSUE TITLE
Fusion Tables uploads not correctly escaped

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#677] opened 2013-02-10 19:56 UTC
A cell value containing the string "P\Invoke" causes an error, apparently because the \ not getting correctly escaped.

**Comment by jackyq2015** [comment] 2015-07-25 01:37
can't reproduced under current dev master. The "P\Invoke" was properly exported to Fusion table.  I suspect it's already fixed by Google. 

We can close it.

**Closed** 2015-08-13 02:19 UTC
