### ISSUE TITLE
Crash investigation - autosave

### ISSUE THREAD

**Issue by Downchuck** [OpenRefine/OpenRefine#813] opened 2013-09-16 01:47 UTC
This may just be something for me to investigate. This is on an old version of openrefine 2.6. Approx @5525d89ed20b6d50e6a3312f9ed9438324c031bb.

Exception in thread "autosave" java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:810)
        at java.util.HashMap$EntryIterator.next(HashMap.java:851)
        at java.util.HashMap$EntryIterator.next(HashMap.java:849)
        at com.google.refine.InterProjectModel.flushJoinsInvolvingProject(InterProjectModel.java:112)
        at com.google.refine.model.Project.dispose(Project.java:109)
        at com.google.refine.ProjectManager.saveProjects(ProjectManager.java:265)
        at com.google.refine.ProjectManager.save(ProjectManager.java:206)
        at com.google.refine.RefineServlet$AutoSaveTimerTask.run(RefineServlet.java:93)
        at java.util.TimerThread.mainLoop(Timer.java:534)
        at java.util.TimerThread.run(Timer.java:484)

**Comment by tfmorris** [comment] 2015-04-30 04:20
I'm going to close this as a duplicate of #652 which has been fixed.  Please reopen if it's seen again with more recent code.

**Closed by tfmorris** 2015-04-30 04:20 UTC
Labels: bug, duplicate
