### ISSUE TITLE
Building an extension for reconcile-csv

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#941] opened 2015-02-02 03:02 UTC
Building on @psychemedia on issue 933 (https://github.com/OpenRefine/OpenRefine/issues/933#issuecomment-72378546) to build container for running CSV backed reconciliation services using the [Open Knowledge Lab Reconcile-CSV server](http://okfnlabs.org/reconcile-csv/) : [Reconcile-CSV container](https://registry.hub.docker.com/u/psychemedia/docker-reconciliation/).

My thoughts were on building a plugin that will provide:
- the reconcile-csv jar file
- a Javascript library to upload the csv and pass the parameter to the jar file
- a way to start the service and add the reconciliation service to OpenRefine.

**Comment by psychemedia** [comment] 2015-02-02 13:56
I've just posted some more thoughts about running reconciliation servers in docker containers that could then be linked to an OpenRefine container: [OpenRefine Style Reconciliation Containers](http://blog.ouseful.info/2015/02/02/openrefine-style-reconciliation-containers/).

**Comment by wetneb** [comment] 2017-08-02 08:11
I think it would be great to have it as an extension, that would not use CSV files but any OpenRefine project. You could just reconcile a column to any other project in OpenRefine.

**Comment by wetneb** [comment] 2019-04-01 13:02
Closing as duplicate of #2003.

**Closed by wetneb** 2019-04-01 13:02 UTC
Labels: enhancement, reconciliation
