### ISSUE TITLE
OpenRefine not opening any more

### ISSUE THREAD

**Issue by galleron** [OpenRefine/OpenRefine#4967] opened 2022-06-17 07:00 UTC
I have installed the latest stable version of Open Refine on  my Mac (OS BigSur), and it is not working any more. I receive the error message I copy underneath. I have checked my Java, it is OK (8).
Same error with 3.4 and previous versions.
I have been using Open Refine since 2018, and on this same machine, I don't understand the problem.
Anybody can help?
Best regards,
Ioana Galleron
_________________________________________
HTTP ERROR 500 Butterfly Error Butterfly incurred in the following errors while initializing: java.lang.Exception: Failed to initialize module (missing Java class definition): rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl] at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:480) at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451) at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308) at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1281) at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594) at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:478) at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:720) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at com.google.refine.ValidateHostHandler.handle(ValidateHostHandler.java:96) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:500) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoClassDefFoundError: org/json/JSONException at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) at java.lang.Class.privateGetPublicMethods(Class.java:2902) at java.lang.Class.getMethods(Class.java:1615) at org.mozilla.javascript.JavaMembers.discoverPublicMethods(JavaMembers.java:373) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:348) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:301) at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:418) at org.mozilla.javascript.JavaMembers.&lt;init&gt;(JavaMembers.java:56) at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:826) at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:785) at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:50) at org.mozilla.javascript.NativeJavaObject.&lt;init&gt;(NativeJavaObject.java:52) at org.mozilla.javascript.NativeJavaClass.&lt;init&gt;(NativeJavaClass.java:44) at org.mozilla.javascript.NativeJavaClass.&lt;init&gt;(NativeJavaClass.java:40) at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136) at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:134) at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84) at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1999) at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672) at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10._c_script_0(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js:4) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.exec(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at edu.mit.simile.butterfly.ButterflyModuleImpl.initScope(ButterflyModuleImpl.java:619) at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:629) at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94) at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476) ... 34 more Caused by: java.lang.ClassNotFoundException: org.json.JSONException at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 65 more</h2>

URI: | /
-- | --
500
Butterfly Error Butterfly incurred in the following errors while initializing: java.lang.Exception: Failed to initialize module (missing Java class definition): rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl] at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:480) at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451) at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308) at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1281) at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594) at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:478) at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:720) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at com.google.refine.ValidateHostHandler.handle(ValidateHostHandler.java:96) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:500) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoClassDefFoundError: org/json/JSONException at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) at java.lang.Class.privateGetPublicMethods(Class.java:2902) at java.lang.Class.getMethods(Class.java:1615) at org.mozilla.javascript.JavaMembers.discoverPublicMethods(JavaMembers.java:373) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:348) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:301) at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:418) at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:56) at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:826) at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:785) at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:50) at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:52) at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:44) at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:40) at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136) at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:134) at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84) at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1999) at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672) at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10._c_script_0(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js:4) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at org.mozilla.javascript.gen.file__Users_utilisateur_Library_Application_20Support_OpenRefine_extensions_module_MOD_INF_controller_js_10.exec(file:/Users/utilisateur/Library/Application%20Support/OpenRefine/extensions/module/MOD-INF/controller.js) at edu.mit.simile.butterfly.ButterflyModuleImpl.initScope(ButterflyModuleImpl.java:619) at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:629) at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94) at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476) ... 34 more Caused by: java.lang.ClassNotFoundException: org.json.JSONException at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 65 more
refine

**Comment by wetneb** [comment] 2022-06-17 07:40
It looks like you might have installed extensions which are not compatible with this version of OpenRefine.
Looking at the logs, one of the extensions uses the "org.json" library which has been removed since OpenRefine 3.2.
I would try removing those extensions and starting OpenRefine again.

**Comment by nixsiow** [comment] 2022-09-24 12:06
How can one removes the said extension if OpenRefine won't open properly? Can you please help? Thanks.

**Comment by wetneb** [comment] 2022-09-25 07:06
You can find the locations where your extensions are installed here:
https://docs.openrefine.org/manual/installing#installing-extensions
You can simply delete those folders directly and that will uninstall those extensions.
Since this is a support request and not a bug for us to solve, I am closing this (but we have other issues to improve the user experience around extensions, such as #3223 and #3326. If you have follow-up questions, feel free to ask them on the mailing list or other help forums (such as StackOverflow).

**Closed** 2022-09-25 07:07 UTC
