### ISSUE TITLE
Undo/Redo page reset problem

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#572] opened 2012-10-15 03:41 UTC
_Original author: ericjarv...@gmail.com (May 05, 2012 19:02:28)_

This is related to some of the other recent posts I've made.  Again, this is related to how the page reloads when edits have been committed.  In this particular case, when using the 'Undo' tool to undo some recent changes, upon selecting the respective undo, the page is refreshed back to #  1.  This would not be a big deal if the user had only a few pages to deal with, but when the user is editing page 14,389 of 25,000... its a bummer, because the 'only' way to get back to page 14,389 is to manually click 'next... next... next..', which of course is counter productive.

So, I would suggest that Refine returns the user to the last view, or the exact view of that given undo, after performing any 'undo', this way the user is returned ot the exact spot s/he was at when s/he made that particular edit in the first place, but now is there because s/he undid it, or redid it if the case may be.  Always returning the user to page 1/record 1 isa real pain.

Thanks,

Eric Jarvies

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=572_

**Comment by wetneb** [comment] 2019-12-20 14:53
Similar to #33 but for undo/redo

**Comment by wetneb** [comment] 2023-01-02 17:32
My change in #5411 has not fixed that yet, because an undo/redo action can not always preserve pagination: it depends on the nature of the operations involved. If all of the operations between the previous point and the new one preserved the row/record structure, then we should indeed preserve the pagination, otherwise we need to go back to the first page.

To solve this we need more operation metadata, which is something I will be introducing in the project to improve OpenRefine's reproducibility.

**Closed** 2023-02-09 12:09 UTC
Labels: bug, imported from old code repo, priority: Medium, undo/redo/history, grid pagination / scrolling
