### ISSUE TITLE
JSONArray[0] not a string error when editing number via the facet

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#1639] opened 2018-06-05 18:19 UTC
#### Set up

OpenRefine 3.0-beta
ubuntu 16.04 
Chromium Version 66.0.3359.181 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

#### Steps followed to create the issue:

[Download the dataset Donavan-A75335 ](https://drive.google.com/drive/folders/0B43bFBSY0ET3VkttWnlzQ05IaDQ )
Apply the operation Text transform in column `AMOUNT_70: value.toNumber()`
Create a text facet and try to edit one number (see screenshot)

![jsonarray 0 not a string](https://user-images.githubusercontent.com/2589584/40994813-4ac0311e-68cb-11e8-978a-2135e7097919.png)

OpenRefine return the following error message: `JSONArray[0] not a string.`

Tested the same process with 2.8 without issue. 

Trace:
```
14:11:37.227 [                   refine] POST /command/core/mass-edit (6814ms)
14:11:37.228 [                  command] Exception caught (1ms)
org.json.JSONException: JSONArray[0] not a string.
	at org.json.JSONArray.getString(JSONArray.java:405)
	at com.google.refine.operations.cell.MassEditOperation.reconstructEdits(MassEditOperation.java:124)
	at com.google.refine.commands.cell.MassEditCommand.createOperation(MassEditCommand.java:59)
	at com.google.refine.commands.EngineDependentCommand.doPost(EngineDependentCommand.java:78)
	at com.google.refine.RefineServlet.service(RefineServlet.java:178)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by magdmartin** [comment] 2018-06-05 18:20
duplicate of #1631 ?

**Comment by ostephens** [comment] 2018-06-06 09:45
Yes this is a duplicate of #1631 - closing as duplicate and will cross reference from there that it also effects editing from a text facet

**Closed by ostephens** 2018-06-06 09:45 UTC
Labels: bug
