### ISSUE TITLE
Fetch urls sometimes fails with OR 3 RC1

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1691] opened 2018-08-01 13:48 UTC
I'm trying to figure out why I can extract the source code of this page using "fetch url" with OR 2.8, but not with OR 3 RC1 : http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01071.html

**Current Results**
An empty new column

**expected result**

![screenshot-127 0 0 1-3333-2018 08 01-15-46-11](https://user-images.githubusercontent.com/6286410/43525422-097f7a62-95a2-11e8-8048-c8e6a69f3709.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome last version

**OpenRefine (please complete the following information):**
 - Open Refine 3 RC1

**Datasets**
Other similar URLs : 

http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01071.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01072.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01073.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01074.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01075.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01076.html	
http://elections2006.brussels/results/fr/local_brussels/preferencevotes/nav01077.html

**Comment by thadguidry** [comment] 2018-08-01 23:49
It works fine for me.  You might have add an error happening server side ?  do the fetch again and choose the radio button for **"on error"** to "store error" instead of the default of "set to blank".

**Comment by ettorerizza** [comment] 2018-08-02 08:29
@thadguidry : error 403 (with Firefox too)

```
HTTP error 403 : Forbidden | <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied</Message>
</Error>
```
Could it be related to some recent changes in the user agents used by OR ?

**Comment by jackyq2015** [comment] 2018-08-03 11:56
Looks like related. @ostephens or @wetneb can take a look

**Comment by wetneb** [comment] 2018-08-04 12:04
@ettorerizza I can't reproduce this on master. Is it possible that you made too many requests and that you got blocked? Can you try fetching few URLs from a different IP address, with a large delay between consecutive requests?
![image](https://user-images.githubusercontent.com/309908/43676323-e014cc76-97e6-11e8-92b7-cf3766cb75df.png)

**Comment by wetneb** [comment] 2018-09-05 17:03
Closing as not reproducible, feel free to reopen if more information is provided.

**Closed by wetneb** 2018-09-05 17:03 UTC
Labels: bug, fetch-urls, not-reproducible
