### ISSUE TITLE
A "NullPointerException" could be thrown

### ISSUE THREAD

**Issue by WaltonG** [OpenRefine/OpenRefine#4692] opened 2022-04-04 08:19 UTC
In the file ProjectManager.java located at /main/src/com/google/refine/ProjectManager.java "placeHolderJsonObj" is nullable hence a "NullPointerException" could be thrown in the following scenario

 private boolean isValidUserMetadataDefinition(ObjectNode placeHolderJsonObj) {
        return (placeHolderJsonObj != null &&              **2**
                placeHolderJsonObj.has("name") &&
            placeHolderJsonObj.has("display"));
    }

if (!isValidUserMetadataDefinition(placeHolderJsonObj)) {  **1 | 3**
                logger.warn("Skipped invalid user metadata definition" + placeHolderJsonObj.toString());   **4**
                continue;
            }

1. A nullable placeHolderJsonObj is passed to isValidUserMetadataDefinition()
2. Implies placeHolderJsonObj can be null
3. Implies placeHolderJsonObj is null
4.  placeHolderJsonObj is dereferenced hence a NullPointerException

**Comment by WaltonG** [comment] 2022-04-04 08:23
@antoine2711 I think this can be a good first issue

**Comment by antoine2711** [comment] 2022-04-04 09:53
@WaltonG 👍  
@wetneb is the one who can check this.

**Comment by WaltonG** [comment] 2022-04-04 10:27
@antoine2711 Let me see if I can get some

**Comment by wetneb** [comment] 2022-04-10 10:39
@WaltonG thank you for looking for more good first issues! I think it would be even easier if you could describe a use case where the NPE is triggered (for instance, provide a `workspace.json` file to start with, launch OpenRefine on it and describe what to do in OpenRefine to see the NPE)

**Comment by WaltonG** [comment] 2022-04-10 11:13
@wetneb Thanks for the review. Will action on the recommendations

**Comment by sherrif10** [comment] 2022-04-14 08:28
Hello @wetneb can you assigne me this issue i work on it.

**Comment by antoine2711** [comment] 2022-04-14 08:33
> Hello @wetneb can you assigne me this issue i work on it.

@sherrif10: please note that the issue is still labeled « to be reviewed ». With those, you must make sure you can reproduce the bug before going forward. Once you confirm the bug, you can put the step to reproduce it in the description of the issue.

Regards, Antoine

**Comment by sherrif10** [comment] 2022-04-14 08:35
Thanks for quick response. @antoine2711

**Comment by sherrif10** [comment] 2022-04-14 12:58
Hello @WaltonG  Would you really confirm the effect of this issue.

**Comment by wetneb** [comment] 2022-04-14 18:23
Ok so I would propose to close this issue. @WaltonG in the future it would be great if you could open issues about bugs that you are able to reproduce fully, as a user.

**Closed by wetneb** 2022-04-14 18:23 UTC
Labels: bug, to be reviewed
