### ISSUE TITLE
Unicode (UTF-8) chars problem.

### ISSUE THREAD

**Issue by blacksmoke26** [OpenRefine/OpenRefine#1066] opened 2015-09-15 16:17 UTC
i have problem with UTF-8 encoded files, Right after upload my file (text of URDU Language) converted to following text:

16    Ø§Ø·Ø§Ù„ÙˆÛŒ
7      Ø§Ù†Ú¯Ø±ÛŒØ²ÛŒ
19    Ø§ÙˆØ³ØªØ§Ø¦ÛŒ

**Comment by magdmartin** [comment] 2015-09-15 17:59
Junaid,

Thank you for reporting it. Can you tell us with Operating System and 
version of Refine are you using? That will help us to trouble shoot it.

Thank you
Martin

**Comment by tfmorris** [comment] 2015-10-16 16:30
@blacksmoke26 Many of the file formats (those which don't declare character encoding explicitly) allow the user to select the character encoding to use.

What was the original file format?  Did you select the character encoding or just accept the default?  If you provide us with additional information and, preferably, access to the original file, we can look into this further.

**Comment by wetneb** [comment] 2017-08-26 09:30
Closing as non-reproducible since the user did not provide any sample file.

**Closed by wetneb** 2017-08-26 09:30 UTC
Labels: encoding, not-reproducible
