### ISSUE TITLE
Duplicate entries in fingerprint() result for diacritic folded variants

### ISSUE THREAD

**Issue by Yomguithereal** [OpenRefine/OpenRefine#1161] opened 2016-11-15 10:38 UTC
Hello @OpenRefine. Thanks for your great work and tool! While perusing the code of the `fingerprint` method, I noticed that removing the accents of the string is done at the end of the processus rather than before the tokenization. What's the rationale for this? Wouldn't it be better to drop the accents before the tokenization for fuzzier matches?

**Comment by wetneb** [comment] 2019-12-20 18:14
Intuitively removing accents and tokenizing should commute, at least in the languages I am aware of. So the choice of order should not matter as far as I am aware. Feel free to reopen this if you have a concrete example of a language (ideally also an example of a string in that language) where the order is important.

**Comment by Yomguithereal** [comment] 2019-12-20 23:05
What I meant, but this has been a long time since I've opened this issue, is that dropping accents after tokenization & deduplication in the algorithm can lead to this result:

`électricité electricite` will yield `electricite electricite` rather than only `electricite`.

This because of the way the fingerprinting is implemented in Java. So I was wondering whether it was a bug or what was actually expected and why? But once again it has been a long time and maybe the Java code changed since then.

**Comment by wetneb** [comment] 2019-12-20 23:07
Ah, if deduplication is done before dropping accents then yes this is weird.

**Comment by tfmorris** [comment] 2020-07-06 23:57
#1256 is a duplicate of this and was fixed by @wetneb in 2017 with #1257, but the NGramFingerprintKeyer still suffers from this bug:
https://github.com/OpenRefine/OpenRefine/blob/9f7d5b878628c40d68a445b751fd50140d922e7d/main/src/com/google/refine/clustering/binning/NGramFingerprintKeyer.java#L52-L58

The use of the homegrown `asciify()` method is pretty ugly too. We should use standard diacritic and case folding.

**Closed** 2020-07-07 07:02 UTC
Labels: bug, clustering, duplicate, localization
