### ISSUE TITLE
Add Beider-Morse phonetic encoder

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#633] opened 2012-11-11 15:47 UTC
This encoder was developed to match Jewish family names across European language variants, but is useful in other circumstances as well.

http://commons.apache.org/codec/apidocs/org/apache/commons/codec/language/bm/BeiderMorseEncoder.html

**Comment by wetneb** [comment] 2018-12-30 20:57
Duplicate of #926.

**Closed by wetneb** 2018-12-30 20:57 UTC
Labels: clustering, duplicate, enhancement
