### ISSUE TITLE
Enhancement request: 'Open Project' list

### ISSUE THREAD

**Issue by hvmarck** [OpenRefine/OpenRefine#657] opened 2013-01-17 08:56 UTC
The 'Open Project' list could do with more metadata (e.g. 'Date Created', number of lines/records, number of columns, ...), and if possible sortable.

As a workaround I created a 'Google Refine Projects' that pieces this together from /command/core/get-all-project-metadata, /command/core/get-models and /command/core/get-columns-info.
##

**Comment by tfmorris** [comment] 2015-10-16 20:29
This should potentially include any additional metadata from #1045 as well, especially *description*

**Comment by wetneb** [comment] 2017-08-02 08:21
Closing as a duplicate of #1221.

**Closed by wetneb** 2017-08-02 08:21 UTC
Labels: enhancement

**Comment by tfmorris** [comment] 2020-06-13 23:34
Usually we try to keep the oldest of a pair of duplicates, so we probably should have closed #1221 instead of this, but for the record, this was included with OpenRefine 2.8 in November 2017.
