### ISSUE TITLE
Reconciliation service stuck in Open Refine 3.1 for service http://refine.codefork.com

### ISSUE THREAD

**Issue by SIB83** [OpenRefine/OpenRefine#2016] opened 2019-04-11 14:36 UTC
I have some test data, that I would like to expand with some additional data.

Start reconciling

![1](https://user-images.githubusercontent.com/43852028/55965949-d8d1c300-5c77-11e9-8829-d16e7eacdf85.JPG)

I try to use this reconciliation service: http://refine.codefork.com/reconcile/viafproxy/DNB. However, now it is stuck at the "working"-screen. Last time it worked on my laptop during a training session. But not now on my work computer. Does anyone know anything about this problem?

refine.codefork.com Service

![2](https://user-images.githubusercontent.com/43852028/55965973-e1c29480-5c77-11e9-97c5-ca5510480dc1.JPG)

stuck at "Working"-Screen

![3](https://user-images.githubusercontent.com/43852028/55965981-e6874880-5c77-11e9-8ee3-1565d5d233fc.JPG)

Thank you for every help and advice

**Comment by ostephens** [comment] 2019-04-12 08:28
Hi @SIB83. I've just tried the reconciliation service with OpenRefine 3.1 locally and had no problem.

Is there any information in the OpenRefine console that might help diagnose the problem? (if you are on a Mac you won't see this usually but there is a way of starting OpenRefine so you see the console - let me know and I can share instructions)

The only thing that stands out in your screenshots is the mis-coded ü in the column name appearing as a <?>. Have you tried fixing that before trying the reconcile?

**Comment by SIB83** [comment] 2019-04-12 08:41
Hello @ostephens

I have already corrected the "ü" and similar, but the error still occurs. 

I was on a training course for Openrefine and used the program on a laptop. There the reconciliation service worked without problems. Now I wanted to use the program on my work computer and the problem occurred. Can this have anything to do with the employer's server or firewall settings? How can I send you information for that?

**Comment by ostephens** [comment] 2019-04-12 08:42
@SIB83 firewall or proxy settings could cause some problems I think.

Are you on Windows, Linux or Mac?

**Comment by SIB83** [comment] 2019-04-12 08:52
@ostephens Windows 7 Service Pack 1

Runs in Firefox Version 60.6.1esr (32-Bit)

**Comment by ostephens** [comment] 2019-04-12 08:55
OK - can you have a look at the console (black/white text window) which opens when you run OpenRefine and see whether there are any messages in there when you try the reconciliation and share the results here?

**Comment by SIB83** [comment] 2019-04-12 09:18
Here is the result

![4](https://user-images.githubusercontent.com/43852028/56026527-9b6f4300-5d14-11e9-9ca8-511246fdb5b8.JPG)

![5](https://user-images.githubusercontent.com/43852028/56026532-9f9b6080-5d14-11e9-95e0-014fbea186ca.JPG)

**Comment by ostephens** [comment] 2019-04-12 09:56
Thanks. That does look like the problem is getting a connection to the remote service - which in turn suggests a firewall or proxy issue.

Unfortunately this is the kind of problem that is really difficult to diagnose and fix from a distance - as the solution may depend on exactly on firewall/proxy configuration on both on your computer and in your network.

First things first:

- Can you successfully visit http://refine.codefork.com/reconcile/viafproxy/DNB in your browser?
- Do you know what the proxy configuration you need to use is?
- Do you know if your proxy requires authentication and if so, what type of authentication is in use
- Do you know if it is allowed to bypass your proxy? (i.e. are you forced to use the proxy or is there an option to not use it when it causes problems)

**Comment by SIB83** [comment] 2019-04-12 10:03
Can you successfully visit http://refine.codefork.com/reconcile/viafproxy/DNB in your browser?

Yes i can

    Do you know what the proxy configuration you need to use is?

no

    In your browser/system is the proxy configured automatically or is it done manually with a set proxy host/port?

The configuration is: "Use proxy settings of the system"
And in the field "no proxy for": localhost, 127.0.0.1

    Do you know if your proxy requires authentication and if so, what type of authentication is in use

no

    Do you know if it is allowed to bypass your proxy? (i.e. are you forced to use the proxy or is there an option to not use it when it causes problems)

i dont think i have the rights to do that

**Comment by ostephens** [comment] 2019-04-12 10:07
I'm afraid I suspect this is a conversation you will need to have with local IT support in the first case. However, you could try the following to see if it works:

- Find the file `openrefine.l4j.ini` in the OpenRefine folder
- Open the file in a text editor
- Find the line that reads `-Djava.net.useSystemProxies=true`
- Change this to read `-Djava.net.useSystemProxies=false`
- Save the file
- Run OpenRefine by double clicking OpenRefine.exe
- Try using the reconciliation service

**Comment by SIB83** [comment] 2019-04-12 10:19
Unfortunately, it doesn't work. I think then it is really a problem with the server settings of the employer

**Comment by ostephens** [comment] 2019-04-12 10:21
OK. If you can find out more about the proxy setup of the network you are one, then I may be able to help further. I'll close this for now, but please feel free to re-open if you get more information

**Closed by ostephens** 2019-04-12 10:21 UTC
