### ISSUE TITLE
Refine tests fails for ProjectMetadataTests.serializeProjectMetadata

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1881] opened 2018-12-02 04:20 UTC
**Describe the bug**
Refine tests fails for ProjectMetadataTests.serializeProjectMetadata

**To Reproduce**
1. 'refine clean'
2. 'refine test'

**Current Results**
```
[ERROR] Failures:
[ERROR]   ToFromConversionTests.testToDate:164 expected [2012-03-01T00:00Z] but found [2012-03-01T06:00Z]
[ERROR]   ProjectMetadataTests.serializeProjectMetadata:22 expected:<{"name":"numeric facet test","tags":[],"created":"2018-09-04T16:07:31Z","modified":"2018-09-04T17:02:31Z","creator":"","contributors":"","subject":"","description":"","rowCount":4,"title":"","homepage":"","image":"","license":"","version":"","customMetadata":{},"importOptionMetadata":[{"guessCellValueTypes":false,"projectTags":[""],"ignoreLines":-1,"processQuotes":true,"fileSource":"(clipboard)","encoding":"","separator":"\\t","storeBlankCellsAsNulls":true,"storeBlankRows":true,"skipDataLines":0,"includeFileSources":false,"headerLines":1,"limit":-1,"quoteCharacter":"\"","projectName":"numeric facet test"}]}> but was:<{"created":"2018-09-04T22:07:31Z","modified":"2018-09-04T23:02:31Z","name":"numeric facet test","tags":[],"creator":"","contributors":"","subject":"","description":"","rowCount":4,"title":"","version":"","license":"","homepage":"","image":"","importOptionMetadata":[{"guessCellValueTypes":false,"projectTags":[""],"ignoreLines":-1,"processQuotes":true,"fileSource":"(clipboard)","encoding":"","separator":"\\t","storeBlankCellsAsNulls":true,"storeBlankRows":true,"skipDataLines":0,"includeFileSources":false,"headerLines":1,"limit":-1,"quoteCharacter":"\"","projectName":"numeric facet test"}],"customMetadata":{}}>
[INFO]
[ERROR] Tests run: 555, Failures: 2, Errors: 0, Skipped: 0
```

**Expected behavior**
Tests Pass

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - JRE or JDK Version: JDK 1.8.0_181 64bit

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.1 [Trunk]

**Comment by wetneb** [comment] 2018-12-02 06:08
Duplicate of #1874.

**Closed by wetneb** 2018-12-02 06:08 UTC
Labels: bug, duplicate, tests

**Comment by thadguidry** [comment] 2018-12-02 06:14
ah the Metadata is also a date related issue.  OK.  I'll let you fix this bugs and test again once you've squashed them.
