### ISSUE TITLE
core/key-value-columnize operation. Is this a bug?

### ISSUE THREAD

**Issue by fabiolinus** [OpenRefine/OpenRefine#5046] opened 2022-07-08 17:54 UTC
Hi. I added a screenshot. It is an example of key-value-columnize operation. First row of the result show some empty cells. Is this a small bug? Thanks a lot for your effort in OpenRefine!

![gif1](https://user-images.githubusercontent.com/33990409/178044487-ed77a1b1-d14d-41a4-ab3f-e4c0a8921da2.gif)
[Data2.csv](https://github.com/OpenRefine/OpenRefine/files/9074164/Data2.csv)
.

**Comment by wetneb** [comment] 2022-07-08 18:59
This looks normal to me. Have you had a look at the documentation for this operation? In particular here is a section which explains the behaviour you are observing: https://docs.openrefine.org/manual/transposing#row-order

**Comment by antoine2711** [comment] 2022-07-08 21:14
@fabiolinus: general information about OpenRefine: the first column is also the « record » column. For OpenRefine to understand that many rows are in the same record, those rows must have the cell of the first column empty. That tells OR that it's with the previous row in the same record.

It not directly relevent to your current case here, but keep in mind that if you change it to record-mode, there will be a strange grouping.

Regards, Antoine

**Comment by fabiolinus** [comment] 2022-07-09 04:55
Hi. This is an example in the documentation online:

Name     | Galanthus nivalis
Color      | White
IUCN ID  | 162168
Name     | Narcissus cyclamineus
Color      | Yellow
IUCN ID  | 161899

First columns contains the same sequence (Name,Color,IUCN ID). This sequence will be transformed into a row by openrefine. How can I obtain the same starting point with my 'Data2.csv'? In other words data in the first columns (Col1) are ordered and doesn't follow the example before. I need something like D1,D2,D3,D4,D5,D1,D2,D3,D4,......

Col1 | Col2
D1    | a
D1    | b
D2    | A
D2    | B
D2    | C
D2    | D
D3    | f
D3    | g
D3    | h
D4    | a1
D4    | a2
D4    | a3
D4    | a4
D4    | a5
D4    | a6
D4    | a7
D4    | a8
D4    | a9
D4    | a10
D5    | b1
D5    | b2
D5    | b3
D5    | b4

**Comment by wetneb** [comment] 2022-07-09 04:59
This is now really a question and not a bug report, so I would propose to close this issue and have this conversation on the mailing list instead.

**Closed by wetneb** 2022-07-09 04:59 UTC
Labels: bug, question, to be reviewed, transpose/pivot

**Comment by fabiolinus** [comment] 2022-07-09 05:19
You are right. Sorry again and thanks for your help.

**Comment by fabiolinus** [comment] 2022-07-16 16:12
Hi. I have a simple dataset:
A B1 a2 b3 c
I'd like to obtain a csv file with tow columns: A (numeric) and B (string):
A, "B"1, "a"2, "b"3, "c"
I use Custom Tabular Exporter but it puts quote evertwhere or ad a lot of quotes to the elements of column B:
""a""
or
"""a"""
How can I obtain a simple schema like before? Thanks a lot,
Fabio


    Il sabato 9 luglio 2022 06:59:14 CEST, Antonin Delpeuch ***@***.***> ha scritto:  
 
 


This is now really a question and not a bug report, so I would propose to close this issue and have this conversation on the mailing list instead.

**Comment by fabiolinus** [comment] 2022-07-16 16:13
Hi. I have a simple dataset:
A B1 a2 b3 c
I'd like to obtain a csv file with tow columns: A (numeric) and B (string):
A, "B"1, "a"2, "b"3, "c"
I use Custom Tabular Exporter but it puts quote evertwhere or ad a lot of quotes to the elements of column B:
""a""
or
"""a"""
How can I obtain a simple schema like before? Thanks a lot,
Fabio


    Il venerdì 8 luglio 2022 23:14:33 CEST, Antoine Beaubien ***@***.***> ha scritto:  
 
 


@fabiolinus: general information about OpenRefine: the first column is also the « record » column. For OpenRefine to understand that many rows are in the same record, those rows must have the cell of the first column empty. That tells OR that it's with the previous row in the same record.

It not directly relevent to your current case here, but keep in mind that if you change it to record-mode, there will be a strange grouping.

Regards, Antoine

**Comment by wetneb** [comment] 2022-07-16 16:24
Hi! Please ask the question on the mailing list, StackOverflow, or other help forums.
