### ISSUE TITLE
Using "search for match" sends back to the first row

### ISSUE THREAD

**Issue by Ash-Crow** [OpenRefine/OpenRefine#2002] opened 2019-03-30 11:50 UTC
**Describe the bug**
When reconciling, after matching an entry using the "Search for match" button, the display moves to the first rows of the first page of the project instead of staying at the point we were at.

**To Reproduce**
0. Open a project that is several pages long and reconcile a column.
1. Go to the second page of results
2. Click on the "Search for match button" on an entry that has not been automatically reconciled, which opens a modal window
3. Click on the match button
4. The rows displayed are now the first ones of the first page.

**Current Results**
A page that has likely already completely reconciled is displayed and we must navigate again to the page we are working on (which can become really frustrating if we have a project with a lot of pages and many entries to reconcile manually.)

**Expected behavior**
When the modal is closed, the same rows that were displayed before we used it are still displayed.

**Screenshots**
![step1](https://user-images.githubusercontent.com/765956/55275717-66adc580-52ea-11e9-80ae-516883c08e68.png)
![step2](https://user-images.githubusercontent.com/765956/55275715-66adc580-52ea-11e9-9250-652f17b5cd8c.png)
![step3](https://user-images.githubusercontent.com/765956/55275716-66adc580-52ea-11e9-9a42-fe72d3a01ec3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 & 18.10
 - Browser Version: Firefox 66
 - JRE or JDK Version: openjdk version "1.8.0_191"

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.1 Beta

**Datasets**
Any dataset

**Comment by wetneb** [comment] 2019-03-30 12:14
Hi @Ash-Crow! This is a duplicate of #33, where the following solution is proposed:

> For now, what you can do is as follows:
> -  select None in the Judgment facet to see only those rows that haven't been matched. Or if the facet isn't there, it's available in the column's menu Reconcile -> Facets ->By Judgment.
> - just keep on the first page and process the first row. Once you manually match it, it goes away (since its judgment is no longer None).
>

**Closed** 2019-03-30 12:14 UTC
Labels: duplicate, reconciliation

**Comment by thadguidry** [comment] 2019-03-30 12:34
@wetneb Eventually, I think we should make this process easier for users.  Staying in some "Reconcile Mode" with its fancy panels is in our long-range plans, and once you are out of Reconcile Mode, then things behave normally with Facets.  I wonder if it is easy enough to introduce a Reconcile Mode now?

**Comment by wetneb** [comment] 2019-03-30 13:03
Yes, that discussion is still current. It's indeed a frequently requested feature.
