### ISSUE TITLE
add flushing for overlaymodels

### ISSUE THREAD

**Issue by Vern1erCa11per** [OpenRefine/OpenRefine#1577] opened 2018-04-23 09:28 UTC
I'm currently implementing the inverted index based on the columns of a project in my extension.
(If you're interested in it, see [this under-development extension](https://github.com/Vern1erCa11per/refine-fuzzymatch-extension))
The inverted index is in the OverlayModel and is dependent on the cell values and the column model of a project.
Therefore, it requires flushing on the project or column changing, but OverlayModels doesn't support flushing at the same time of the changes.

I think it is not difficult and destructive to because the similar flushing were implemented for InterProjectJoin.

I infer some OvelayModels which developers want to implement have often  the dependency on the cell values and the column model, so there is a demand for flushing of OverlayModel.

I implemented the conceptual implementation in [my fork brunch](https://github.com/Vern1erCa11per/OpenRefine/tree/add/flush/overlaymodel).

**Comment by wetneb** [comment] 2018-04-23 11:56
hi @Vern1erCa11per, thanks for starting this interesting discussion.
I think you are using the OverlayModel in a way that is quite different from the use case it was designed for (storing the Freebase Protograph or the RDF skeleton). As far as I can tell, the idea behind it being an *overlay* means that it is a data structure that it independent of the table data itself (it just stores metadata).

But why not! We can definitely explore exposing callbacks that are similar to those you mention. We should do that in a way that is backwards compatible (for instance by providing default blank implementations for the new methods that we add, so that existing extensions that use the overlay model do not break). We need to explore the various use cases and come up with a signature that works for everyone. For instance, it would be useful for the schema overlays (RDF, Wikidata) to be notified when a column is renamed or deleted (because these schemas store references to these columns), but that does not seem to be possible with your current approach.

In https://github.com/Vern1erCa11per/OpenRefine/commit/35b7e2e13a29d5366b94718e606f19947663eeef you add the hooks in various `Change` classes, I would prefer to have it only in one place (where changes are applied). In general, any update to the table data is always performed by applying / unapplying changes, so I guess there could be just one or two method in the `OverlayModel` like:

```
public void onApplyChange(Change change);
public void onUnapplyChange(Change change);
```

If necessary we could extend the `Change` interface to make it easier to know what sort of change it made (for instance, which column(s) it modified).

**Comment by Vern1erCa11per** [comment] 2018-04-23 23:45
Thank you, @wetneb,  That's what I want !!!  I also require what sort of change it made.

**Comment by wetneb** [comment] 2023-04-18 11:37
Five years later, I am not so sure about this.

The main problem I now see is that an `OverlayModel` is a part of the project data that is versioned by the changes themselves. So, a given instance of an overlay model should be immutable (it should not be possible to modify it without creating a copy of it and updating it in the project by applying a `Change`).

In this context, it is hard for me to see how we could have methods such as the `public void onApplyChange(Change change)` I suggested above. It raises many questions which seem to indicate that this is not the right approach:
* would the `onApplyChange` method be called on the overlay model that is stored in the project before the change or after the change?
* the `onApplyChange` method would not be allowed to change anything in the overlay model itself (since it is meant to be immutable). So what else should it do, with this `void` return type? It must be having a side effect somewhere else - but then maybe the overlay model is not the right place to register such a callback to make changes to that other place
* or perhaps if the overlay model does want to modify itself, then it should be able to trigger another `Change`  on top of the change that triggered the callback. But then would the callback be called again on that new change? That seems to be a recipe for an infinite recursion.

Overall, I think maintaining an inverted index isn't really what overlay models are designed for. I would rather follow the design of the index underpinning the `cross` function: a standalone class which stores the relevant indices outside of the project data itself.

For those reasons I am closing this, but feel free to chime in anyway if you think this decision could be revisited.

**Closed by wetneb** 2023-04-18 11:37 UTC
Labels: enhancement, overlay model, extension
