### ISSUE TITLE
Missing internationalization (i18n) on About page

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3089] opened 2020-08-17 00:20 UTC
None of the text on the About page is internationalized so that it can be translated into languages other than English.

The individual HTML elements should be given unique ids which can be used with the `$.i18n()` calls to set the text for the element based on the user's current language. The license text and copyright statement should **not* be translated.

These elements should be translated and their text moved into the English translations file, referenced by the element IDs (the first two can be combined for consistency and to minimized translation):
https://github.com/OpenRefine/OpenRefine/blob/fc21d58ed11af8e512be5fd5852a281c88791fb7/main/webapp/modules/core/about.html#L38
https://github.com/OpenRefine/OpenRefine/blob/fc21d58ed11af8e512be5fd5852a281c88791fb7/main/webapp/modules/core/about.html#L67
https://github.com/OpenRefine/OpenRefine/blob/fc21d58ed11af8e512be5fd5852a281c88791fb7/main/webapp/modules/core/about.html#L88
https://github.com/OpenRefine/OpenRefine/blob/fc21d58ed11af8e512be5fd5852a281c88791fb7/main/webapp/modules/core/about.html#L110

The two main paragraphs of text can translated independently to minimize the HTML markup that they include and the links and anchor text for Metaweb and Google (e.g. `<a href="http://www.metaweb.com/">Metaweb Technologies, Inc.</a>`) can be substituted in as parameters (ie `$1`, `$2`) to the `$.i18n()` call since they don't need to be translated.

**Comment by HeroicHitesh** [comment] 2020-09-14 14:22
@tfmorris Does this issue need further fixes or is it resolved? I see there's a merged PR, so if the issue is resolved by your PR kindly close this issue to avoid confusion.

**Comment by wetneb** [comment] 2020-09-14 14:25
As far as I can tell, #3090 has not solved this, only prepared for it.

**Comment by HeroicHitesh** [comment] 2020-09-14 14:30
Ahh ok @wetneb I saw the changes made in #3090 now. So, I think this issue is up-for-grab, if yes I would like to work on it.

**Comment by wetneb** [comment] 2020-09-14 14:34
Wonderful, thank you!

**Comment by singhakshita** [comment] 2021-02-06 10:55
can i work on this issue ?

**Comment by wetneb** [comment] 2021-02-06 17:47
Yes, thank you!

**Closed** 2021-02-08 19:37 UTC
Labels: UI, bug, good first issue, localization
