### ISSUE TITLE
Not able to see open/create project , even I am using openrefine-win-with-java-3.4.1

### ISSUE THREAD

**Issue by adityakumar1990** [OpenRefine/OpenRefine#3869] opened 2021-05-02 09:36 UTC
### To Reproduce
1. First, download openrefine-win-with-java-3.4.1
2. Then, extract and run refine.cmd 
3. Finally, On Browser only able to see the logo
4. 
![image](https://user-images.githubusercontent.com/72451094/116808679-ce810b00-ab57-11eb-8d8d-e7de0670ec29.png)

![image](https://user-images.githubusercontent.com/72451094/116808696-e8225280-ab57-11eb-9587-b5261bec18bf.png)

### Versions
 - Operating System:  Windows 10
 - Browser Version: Chrome
 - JRE or JDK Version: jdk-16
 - OpenRefine:  3.4

**Comment by adityakumar1990** [comment] 2021-05-02 09:37
Finding the same issue with 3.3 version too

**Comment by thadguidry** [comment] 2021-05-02 17:02
1.  This might be due to a path naming issue.  See #3277 

2. Did you have any extensions installed previously for OpenRefine? See #3326 
If so, this might be because an OpenRefine extension that you have installed in the AppData folder for OpenRefine, which is also where the workspace is defaulted under and holds your projects folders and files.
So... we don't want to risk losing your projects when deleting the OpenRefine extension to fix things...so let's do these steps in order:

- Backup the OpenRefine folder under your AppData folder.  (use Zip or whatever archive tool like 7z that you have on Windows and then move this .zip file to a safe location or additionally uploaded to the cloud somewhere)
- Delete the OpenRefine folder under your AppData folder.
- Start OpenRefine, which will recreate the folder and workspace folder within it.
- Report back any good news, then we can take next steps (which will be to selectively move your project folders back into place from your saved .zip backup file)

Let us know in a reply here if any of the above issues or steps helps to solve this problem.

**Comment by wetneb** [comment] 2021-05-03 05:43
You could also right-click somewhere in the OpenRefine page, open your inspector and check if there are any error messages in the console, that could help us debug this issue.

**Comment by adityakumar1990** [comment] 2021-05-03 05:53
C:\Users\kumarad>echo %USERPROFILE%
C:\Users\kumarad

C:\Users\kumarad>
There is no special char . 
![image](https://user-images.githubusercontent.com/72451094/116844882-00e74280-ac02-11eb-82d7-4452f49cac56.png)

For me it is only showing the logo

**Comment by wetneb** [comment] 2021-05-03 06:00
Thanks for the screenshot - it looks like you have opened the inspector, but not clicked on the "Console" tab where I expect there could be some errors.

**Comment by adityakumar1990** [comment] 2021-05-03 06:04
![image](https://user-images.githubusercontent.com/72451094/116845429-730c5700-ac03-11eb-8996-b8f2dce68e3d.png)
Is this you looking for ?

**Comment by wetneb** [comment] 2021-05-03 06:09
Yes thank you!

**Comment by adityakumar1990** [comment] 2021-05-03 06:31
An

> Yes thank you!

Any resolution ?

**Comment by Garry711** [comment] 2021-05-11 08:04
@adityakumar1990 I got exactly the same problem. 
Couldn´t find an answer yet. But I keep searching. Please tell me if you got an solution.

**Comment by Garry711** [comment] 2021-05-19 09:16
Got it! 
Installed jdk 15.0.1 instead of 16.0.1 and reinstalled OpenRefine 3.4.1. 

Now its running!

**Comment by wetneb** [comment] 2021-05-19 12:30
Thanks a lot @Garry711 for reporting this, then that seems to indicate that we do not support Java 16 yet. We should investigate this.

**Comment by thadguidry** [comment] 2021-05-19 13:29
@wetneb this doesn't make sense, if they are using our `win-with-java` release that has embedded Java (which uses Java 8) why would the release or something within it even care or try to use a locally installed Java version 16?

**Comment by wetneb** [comment] 2021-05-19 13:34
@thadguidry it's a good point and I don't know what the answer is! I suspect the local java runtime environment might have priority over the embedded one in some cases?

@Garry711 did you download the version with embedded Java or without?

**Comment by thadguidry** [comment] 2021-05-19 13:46
I took the liberty to test just now by changing my `JAVA_HOME` and my Path pointing to OpenJDK 16 and started OpenRefine win-with-java 3.4.1 and it's working fine.
![image](https://user-images.githubusercontent.com/986438/118823129-5b2d0800-b87e-11eb-86d9-fbb60b9ceae2.png)

When `JAVA_HOME` is set or not, my understanding was that `win-with-java` would always use embedded Java from package.
If folks wanted to control the Java environment to use, then they should use our other release without embedded Java.

**Comment by thadguidry** [comment] 2021-05-19 15:41
Yes.  With `JAVA_HOME` set back to point to my OpenJDK 16.0.1 and confirming `java -version` on command line showed OpenJDK 16.0.1 and then downloading the OpenRefine 3.4.1 Windows kit (without Java) then I was still able to get OpenRefine to run as normal.

**Comment by thadguidry** [comment] 2022-10-06 06:59
This might be an issue with previous OpenRefine extensions installed.
We have a troubleshooting FAQ that can help: https://github.com/OpenRefine/OpenRefine/wiki/FAQ#only-shows-logo-when-starting-or-open-project-doesnt-work-or-shows-mixed-up-html-content-in-my-browser

Closing as not reproducible.

**Closed** 2022-10-06 06:59 UTC
Labels: bug, to be reviewed

**Comment by wetneb** [comment] 2022-10-06 07:10
Thanks for this bug triaging @thadguidry, very helpful! :)
