### ISSUE TITLE
go browse to openrefine 3.0 show nothing except title.

### ISSUE THREAD

**Issue by Sanyorke-Han** [OpenRefine/OpenRefine#1765] opened 2018-10-17 02:09 UTC
**Describe the bug**
environment: windows 10 or windows 7, Java SDK 8u51.
download openrefine 3.0, unpakage, click refine.bat, the start up success and it auto launch chrome browser Version 69.0.3497.100 (Official Build) (64-bit). 
but finally, I only got blank page:
![openrefine30_blank_page](https://user-images.githubusercontent.com/2055205/47057579-ef7ced00-d1f3-11e8-9c99-0906283be396.JPG)

in chrome, I push key F12, it shows error in js, as below:
![openrefine30_develop_page](https://user-images.githubusercontent.com/2055205/47057612-10454280-d1f4-11e8-8dad-4b4c182e7e5d.JPG)

when I use openrefine.exe to start, I got same result, the start page report error:
```
 Failed to use jdatapath to detect user data path: resorting to environment variables (331ms

 Failed to use jdatapath to detect user data path: resorting to environment variables (0ms)
```
here is the screenshot:
![openrefine30_start_up_page](https://user-images.githubusercontent.com/2055205/47057760-aed1a380-d1f4-11e8-9e65-c9b23964cf32.JPG)

the old version openrefine 2.8 works well on my environment.

thanks.

**Comment by wetneb** [comment] 2018-10-17 07:46
I think this is a duplicate of #1717.

**Closed** 2018-12-31 15:09 UTC
Labels: duplicate
