### ISSUE TITLE
Date retrieved from Wikidata registering as wrong type

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1588] opened 2018-04-28 12:13 UTC
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Comparing master+wikidata extesion with OR 2.8

#### Steps followed to create the issue:
Another date issue I'm afraid.  Not sure if this is related to general date handling or something about the wikidata extension - not had a chance to look yet.

Using the code from master branch + wikidata extension
Adding a column using "Add columns from reconciled values" with a date type (e.g. 'date of birth'). 

#### Current Results:

The retrieved date is not identified as a 'date' type in OR but rather as a 'Java.time.OffsetDateTime'

<img width="786" alt="screen shot 2018-04-28 at 12 56 38" src="https://user-images.githubusercontent.com/576174/39396385-2be77ecc-4ae5-11e8-8dbd-dc5954218fc3.png">

however, then opening the same project (no changes) in OR2.8 the same cell shows correctly as 'date' type

<img width="940" alt="screen shot 2018-04-28 at 13 05 12" src="https://user-images.githubusercontent.com/576174/39396419-ac951e12-4ae5-11e8-966f-89e9d5aa716c.png">

In addition this seems to stop date based functions working on the value in master branch:

<img width="996" alt="screen shot 2018-04-28 at 13 04 31" src="https://user-images.githubusercontent.com/576174/39396427-d00e956c-4ae5-11e8-8cb6-d5512959a3c0.png">

But the same function works fine in 2.8

<img width="817" alt="screen shot 2018-04-28 at 13 05 24" src="https://user-images.githubusercontent.com/576174/39396431-dbadac28-4ae5-11e8-87a7-7af06f527480.png">

#### Expected Results:

Expect the data to register as a 'date' type, and for date functions to work as in 2.8

**Comment by wetneb** [comment] 2018-04-30 17:03
So, here is how I understand the situation:
when @jackyq2015 worked on last modified dates he undertook to migrate from old-style `Date` and `Calendar` classes to the modern implementations, which was not necessary in the migration from JDK7 to JDK8 but is generally a sensible thing to do. However, this work has not been finished so there are discrepancies in the code (some parts still work with the old-style classes, some use the new ones), which causes the bug observed by @ostephens (which btw is not specific to `wikidata-extension`, it can be observed in `master` too).
There are two ways out of this situation:
- migrate everything to the new classes (which can potentially cause some unexpected side effects)
- revert the changes and go back to the original classes (which is a step backwards)

@jackyq2015 any info would be welcome…

**Comment by thadguidry** [comment] 2018-05-01 01:49
I say we go forward.
And its not hard to go forward... it just means everyone putting better Tests in place where we are lacking them.
Like here especially lacking:
https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/server/src/com/google/refine/tests/expr/functions/ExpressionUtilsTests.java

But basically adding good tests for these 44 source files that involve Date:
https://github.com/search?utf8=%E2%9C%93&q=Date+repo%3Aopenrefine%2Fopenrefine+path%3A%2Fmain%2Fsrc+language%3AJava+language%3AJava&type=Code&ref=advsearch&l=Java&l=Java

**Comment by wetneb** [comment] 2018-05-01 07:01
@thadguidry a full migration would be very costly (as you said there are many different classes which still use that). There might be ways to isolate that usage (for instance, it is probably hard to migrate the internals of CalendarParser to use the new classes, but it should be doable to just change its interface).
Personally I will not have time to do a full migration before at least 6 weeks…

**Comment by jackyq2015** [comment] 2018-05-01 17:02
i will take a look. but date is an internal type of openrefine. we are
moving to java 7 date to java 8 time api. there is nothing wrong with the
type. the broken part is the function.

**Comment by wetneb** [comment] 2018-05-02 21:07
`toDate('2017-01-01T00:00:00Z').type()` gives `java.time.OffsetDateTime` whereas `toDate('2017-01-01').type()` gives `date` because since your partial migration the `toDate` function can return various types depending on the input… I can provide a quick fix for that but it does not fix the root cause.

This situation where both old and new date classes are allowed as cell values is dangerous - now I realize that this change was quite ill judged. It was a mistake to do it lightly: in most applications, you could have relied on the type checker to do the migration, but because OpenRefine uses `Object` for cell values, we cannot rely on that.

**Comment by jackyq2015** [comment] 2018-05-03 02:57
I think the java 8 time API is the right way to go even it will take effort. It is safe to just keep the java 7 Date and Calendar API but it is not the long term solution. The original code has a pattern to deal with the date like this:
```
if (instance of date)
  do something;
else if (instance of calendar)
 do something else;
```
I doubt if it's necessary. Even it is, I think some of them is for backward compatibility.  We can consider to use the OffsetDateTime to unify those kind of block if possible. At least I know for the cell date type, we can store the "date" string to indicate its type, not the java class. So potentially it's possible to only change the code but keep the file format untouched.

**Comment by wetneb** [comment] 2018-05-03 06:19
I don't think dates should be stored as strings - this would go against the current design of storing strings, numbers, patterns and dates as different Java objects. For now, we need to make sure all dates stored in cells use the Java 7 classes, not the Java 8 ones, so that we don't break compatibility with GREL and extensions which rely on that. This is especially important because this introduces bugs that cannot be detected at compile time.

**Closed** 2018-05-19 18:03 UTC
Labels: bug

**Comment by tfmorris** [comment] 2020-07-06 00:30
We are still fixing bugs related to the change of the internal Date type including #1908 and #2241.

**Comment by tfmorris** [comment] 2020-08-08 20:42
Another impact of this change was redefining the historical OpenRefine handling dates without timezones as being datetimes in the local timezone to instead cast everything as UTC datetimes.

There is absolutely no reason that dates in in metadata need to be treated uniformly with the user data type. They are completely different, disjoint contexts. Things like modifiedAt metadata should be stored as an ISO 8601 UTC datetime and converted to the user's locale by the browser. This has nothing to do with how dates in user data are parsed, computed on, etc.
