### ISSUE TITLE
OpenRefine minimal formating for really big datasets 

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#967] opened 2015-04-08 20:22 UTC
Hello, OpenRefine is a great and unique tool in playing with large datasets. 

I am playing with datasets so big, that the biggest bottleneck is the browser, that crashes.

Could it be possible, to have the option to switch to a more rudimentary setting, or limit the amount of facets that the bworser will load.

For Example, i have a text facet with over 400.000 options, that is crashing the browser. I want to cluster all of this facet, but i don`t really want to see of of them, because is kind of impossible, without the browser crushing. 

The compute facets takes only 300 miliseconds, but the showing in the browser is killing my 8 gb, I7 intel processor on google chrome.

**Comment by rodalpho** [comment] 2015-04-16 17:13
I actually came here to post about this exact same issue. The Openrefine backend performs great with a ton of options inside a facet, but my browser doesn't-- it locks up for 4-5 minutes every time I refresh the data. This is using 64bit Chrome; firefox is even worse.

As I see it, the problem is most likely that Openrefine is trying to display all 90,000 options inside that little table on the left side of the page, and browsers aren't equipped to handle that. One fix would be to only show the first "X" options by default, where X should probably be around 25. Another would be to implement paging, similarly to the data paging in the right-side panel.

**Comment by jackyq2015** [comment] 2015-04-16 18:37
Just curiosity how come you have so many options(90000)? what kind of data set are you dealing with?

**Comment by baditaflorin** [comment] 2015-04-16 18:40
I don`t know for rodalpho, but for me, i have the court files from the romanian justice system, from 2000 to 2014, and the data is really bad. 

You can have the same entity written in 1000 ways.

Like 
Calea Ferata Romana
Caile ferate Romane
Calea Ferată Romana
Calea Ferată Româna
Calea Ferată Română
Cala Ferata Romana
etc

**Comment by tfmorris** [comment] 2015-04-16 22:52
Two things:

1. The default limit for the number of choices in a text facet is much, MUCH, lower, so you must have increased it.  You can reset it lower by going to http://127.0.0.1:3333/preferences and changing ui.browsing.listFacet.limit to a lower value.

2. You can access clustering without using a Text Facet by using Edit Cells -> Cluster and Edit.  This will take you directly to the clustering dialog.  If you have too many choices there, you could pre-filter using something like a text facet on the first character of the value.

We already have an issue regarding performance of facets, so I'm going to close this.

**Closed by tfmorris** 2015-04-16 22:52 UTC
