### ISSUE TITLE
Cluster & Edit box overflow makes it unusable on some screens

### ISSUE THREAD

**Issue by evanwill** [OpenRefine/OpenRefine#1141] opened 2016-07-13 19:23 UTC
When clustering, the "Cluster & Edit" dialog box has styling issues: large text string values overflow the box, making the cluster visualizations and the ui buttons appear off screen. The overflowing box can not be dragged or scrolled into a usable position. The only solution is to zoom the browser window out to 50%. See attached images using Windows 10, Refine 2.6rc2. The overflow issue is worse on Chrome, but the box size with inaccessible ui buttons is on both Chrome and Firefox. 

on Chrome:
![refine_cluster_issue_chrome](https://cloud.githubusercontent.com/assets/13864643/16816610/838ab22a-48f3-11e6-802f-29bb312ed078.PNG)

on Firefox:
![refine_cluster_issue_firefox](https://cloud.githubusercontent.com/assets/13864643/16816616/898c5930-48f3-11e6-8329-6b98cf8625cc.PNG)

I work with text tables, so I have this issue regularly. I did not notice it when working on my desktop with large monitor, but with a new 14" laptop (FHD 1920 x 1080) and 13" laptop (3200x1800) it happens constantly making it impossible to cluster at times. 

The issue seems to be mentioned in #938, but it is assigned as a minor, low priority issue. However, since this issue prevents features of the software from being usable, it seems like it should be a higher priority bug.

**Comment by thadguidry** [comment] 2016-07-13 21:26
This is a general UI issue that affects many programs, not just OpenRefine.

The issue is really "How do we handle displaying long strings of information to a user?",  "Do we autowrap?", "Do not autowrap and instead create a horizontal scrollbar for the user to pan left or right to review long strings?"  "How far should the pan left or right be allowed, should their ever be a max limit?"

Some of these challenges are answered with a few Jquery plugins.
Here is one that comes to mind that could help with a horizontal scroll that auto updates and recalculates scrollbar sizes on javascript/ajax changes such as what happens during Clustering.

[https://gromo.github.io/jquery.scrollbar](https://gromo.github.io/jquery.scrollbar/)

**Comment by evanwill** [comment] 2016-07-13 23:16
There is something clearly broken in the styling on Chrome however that could be an easy fix by looking at why it works in Firefox. Some odd browser prefix thing?

The usability issue for both browsers is that the pop up `dialog-frame` is set to width 1000px, the height is set by the content, but if it is taller than the browser window size, it is not possible to scroll down to use the full pop up since its container `dialog-container` is set to `position: fixed`. A quick fix to allow scrolling is to set `dialog-container` to `position: relative`, but that breaks the "draggable" functionality.

It might be an issue with deeper roots, since it looks like when rendering it must query the browser for window size to set the parameters of the page. However, on Win 10 it seems to get the size of the full screen rather than window, since a small portion of the UI is actually below the browser window, where the task bar is, and is inaccessible unless I go to full screen mode with the browser. This maybe an issue specific to HD screens that use scaling to have everything appear normal size on the screen.

**Comment by tfmorris** [comment] 2020-07-27 19:36
As mentioned above, this is a duplicate of #938.

**Closed** 2022-09-01 04:56 UTC
Labels: bug, duplicate, UI, clustering
