### ISSUE TITLE
Importing problem when we choose two or more files.

### ISSUE THREAD

**Issue by chetan-v** [OpenRefine/OpenRefine#2987] opened 2020-07-25 13:48 UTC
When you choose two files (.xml and .csv)extensions then it will not work properly in importing.
If we checked only one file at a time then it work fine but we click back and checked another extension file then it will not guessed the right file.

### To Reproduce
1. First, go to "This computer" 
2. Then, choose two files at a time [TestFiles](https://drive.google.com/drive/folders/1skaTnzTcTuLJM1HLYC7t6iAh4NN7AB0E?usp=sharing)
3. And press "Configure Parsing Options"
4. and see what happens
### Current Results

(This issue is more understand by these two videos )

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/63091769/88458183-debdd880-cea9-11ea-94a1-43f37ae8e39c.gif)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/63091769/88458383-47f21b80-ceab-11ea-9482-d77d5ca1be44.gif)

### Expected Behavior

give an error when we parse two file at a time.

### Versions
 - Operating System:  Ubuntu 18.04 
 - Browser Version: Chrome

**Comment by chetan-v** [comment] 2020-07-28 17:59
@thadguidry please look in this matter.

**Comment by thadguidry** [comment] 2020-07-28 18:42
@chetan-v Sorry, I don't understand.  Do you want me to try to reproduce this on Windows with Chrome?  What explicitly do you mean by "look into this matter"?

**Comment by chetan-v** [comment] 2020-07-28 18:44
> @chetan-v Sorry, I don't understand. Do you want me to try to reproduce this on Windows with Chrome? What explicitly do you mean by "look into this matter"?

Yes I want this
And want you to suggest some solution

**Comment by wetneb** [comment] 2020-07-28 19:06
Just a side note about language, it is more polite if you avoid things like "I want you to". Instead, you can use "would like", "could you"… Your requests for help should not read like orders :)

**Comment by thadguidry** [comment] 2020-07-28 20:17
@wetneb it's fine, I didn't take it as an order.  I automatically imply "Please, " before every user request within OpenRefine community context :-)

**Comment by chetan-v** [comment] 2020-07-29 03:09
I am sorry for this. I apologise mr thad.
Actually I am not a native speaker(I always  Grammer mistakes).
But I am fully agree with @wetneb.
When I translated the phrase then I realize its not a right way to talk with seniors.
Next time I am very take care of it.
regards,
chetan

**Comment by wetneb** [comment] 2020-07-29 06:49
It's not a problem at all, I just thought I would let you know because it can be useful in other contexts.

**Comment by thadguidry** [comment] 2020-07-29 15:29
@chetan-v The expected outcome should actually be an error message like:
ERROR: the number of columns is not the same between all your selected files to import.

Additional improvement message ...
"OpenRefine can only import multiple files into a single project if all selected files have the same number of columns."
to add before this text:

![image](https://user-images.githubusercontent.com/986438/88819075-1ddb7a80-d185-11ea-8aa1-c498007a13e3.png)

**Comment by chetan-v** [comment] 2020-07-29 16:26
> @chetan-v The expected outcome should actually be an error message like:
> ERROR: the number of columns is not the same between all your selected files to import.
> 
> Additional improvement message ...
> "OpenRefine can only import multiple files into a single project if all selected files have the same number of columns."
> to add before this text:
> 
> ![image](https://user-images.githubusercontent.com/986438/88819075-1ddb7a80-d185-11ea-8aa1-c498007a13e3.png)

Oh, I thought it is a guessing problem.
can I add this line
 > "OpenRefine can only import multiple files into a single project if all selected files have the same number of columns."

**Comment by chetan-v** [comment] 2020-07-30 05:02
Just for discuss something else from this issue(related UI)-

first I thought may be I did something wrong in my branch but when I checkout master branch nothing was change. 
@thadguidry Please check this.(May be its an issue)

![Screenshot from 2020-07-30 10-20-17](https://user-images.githubusercontent.com/63091769/88882189-0072e300-d24f-11ea-8977-4f4a76ec42e6.png)

**Comment by thadguidry** [comment] 2020-07-30 17:56
@chetan-v your branch https://github.com/chetan-v/OpenRefine/tree/Extra has not been merged yet into our OpenRefine master branch as seen in your PR (merge is blocking from 1 reviewer) https://github.com/OpenRefine/OpenRefine/pull/3011
Once it is reviewed and approved for merge into our master branch, then you will see the updated messaging that you changed.
Patience. 
But for now, it should show changed on your branch, correct?

**Comment by thadguidry** [comment] 2020-07-30 18:05
@chetan-v Indeed it is changed on your branch and seems to look fine when I check it out.

![image](https://user-images.githubusercontent.com/986438/88957949-59e60c80-d265-11ea-8623-2d3518181de2.png)

**Comment by chetan-v** [comment] 2020-07-30 18:19
> @chetan-v your branch https://github.com/chetan-v/OpenRefine/tree/Extra has not been merged yet into our OpenRefine master branch as seen in your PR (merge is blocking from 1 reviewer) #3011
> Once it is reviewed and approved for merge into our master branch, then you will see the updated messaging that you changed.
> Patience.
> But for now, it should show changed on your branch, correct?

Thanks but,
I said something else

Please look at this Screenshot

> ![Screenshot from 2020-07-30 10-20-17](https://user-images.githubusercontent.com/63091769/88882189-0072e300-d24f-11ea-8977-4f4a76ec42e6.png)

I said that when I click 'web address url' content get hidden from the left side.
(And it didn't happen before)
My resolution of screen is 1024 x768 (4:3)

**Comment by thadguidry** [comment] 2020-07-30 19:35
@chetan-v That's a small Chrome issue (I think) because of the way some properties are set in the `.less` files.  So I'd open a new issue to make this more cross-browser compatible.

It does not happen in Firefox for me as shown:

![image](https://user-images.githubusercontent.com/986438/88966406-e0a0e680-d271-11ea-8dfd-e45a04476779.png)

**Closed** 2020-08-03 12:15 UTC
Labels: bug, to be reviewed
