### ISSUE TITLE
Text filter should wait until user finishes before updating.

### ISSUE THREAD

**Issue by 0robus** [OpenRefine/OpenRefine#2112] opened 2019-08-07 18:33 UTC
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
When entering a string or regex expression in the text filter, I'm often prevented from finishing the expression before OpenRefine attempts to update the results. This is frustrating, especially when trying to formulate complex regex.

**Describe the solution you'd like**
My preferred solution would be a `Submit` button (ideally with a keyboard shortcut) so that OpenRefine doesn't keep trying to update while I'm typing.

**Describe alternatives you've considered**
The only alternative I've found is to write regex expressions in a text file and copy/paste into the text filter.

**Comment by coderrsid** [comment] 2020-01-18 18:09
Hey @0robus .. 
Can you explain the problem with some pictures? I'm looking forward to solve this.

**Comment by wetneb** [comment] 2020-01-18 18:59
This is due to the fact that the facet updates too quickly - it should wait for a longer period of inactivity in the text field before updating the facet and reporting any error. I am not exactly sure what timeout is currently used but solving this issue might just be down to increasing that timeout.

**Comment by coderrsid** [comment] 2020-01-23 13:43
@wetneb  So is that a practice we should seek? Like should we try increasing that timeout or more..?

**Comment by wetneb** [comment] 2020-01-23 13:49
@coderrsid have you managed to reproduce the issue on your side? This is the first step if you want to solve this. Let me know if you need help for that. Once you have witnessed the issue yourself, you should be in a better position to find out how to solve it. You can just ask yourself: as a user, how would I want this text field to behave?

So, once that is out of the way, I can return the question to you: what would *you* propose?

**Comment by thadguidry** [comment] 2020-01-23 14:09
[It fires on every keyup currently](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/facets/text-search-facet.js#L144)
Try it by racking your fingers randomly over the keyboard and noticing in the console terminal that the /command/core/compute-facets will be invoked continuously, and not wait for your fingers to stop typing.

My opinion would be that it needs to fire AFTER a 1.5 - 2 sec delay of the last keyup. The reset of the [keypress event handler via Jquery probably needs investigating](https://api.jquery.com/keypress/)
or you can just [implement your own](https://medium.com/javascript-in-plain-english/how-to-detect-a-sequence-of-keystrokes-in-javascript-83ec6ffd8e93)

**Comment by wetneb** [comment] 2020-01-23 14:15
Well, if there is no timeout right now, it should not be hard to do better…

**Comment by kushthedude** [comment] 2020-02-22 17:26
@wetneb I would like to work on the following. I have already set up the Open Refine on my local, also I would like to complete the project `Replace row pagination by infinite scrolling` this summers.

**Comment by wetneb** [comment] 2020-02-22 17:32
Great! This issue is indeed a good start if you want to apply for the infinite scrolling project.

**Comment by ostephens** [comment] 2020-02-25 15:53
I'm not convinced that increasing the timeout here is the best  solution. Increasing timeout to 2000ms as per #2324 makes the UI feel less responsive when the user is typing a plain text string.

I think we should:

1. Have separate timeouts depending on whether the user is typing a regex or just a text filter
2. Consider separating the Regex validity checking from the facet update and only update the facet if there is a valid regex (and put the regex validity feedback next to the filter textbox rather the current situation where it is separated in the display)

These two changes can be tackled separately as the first is straightforward whereas the second will take more work. I hope that @kushthedude can make some changes to #2324 for (1) if we agree this is a sensible thing to do @wetneb @thadguidry

**Closed** 2020-03-07 21:10 UTC
Labels: UI, good first issue
