### ISSUE TITLE
Preferences for projects are not saved

### ISSUE THREAD

**Issue by hvmarck** [OpenRefine/OpenRefine#887] opened 2014-06-25 13:29 UTC
When using '/command/core/set-preference' with parameters 'project', 'name' and 'value' everything looks fine (value can be retrieved per project using '/command/core/get-preference'), but shutting down OpenRefine and restarting it shows that the preferences where not saved. It looks like the project is not marked as 'dirty'. The evidence for this is that If you do some other editing in the project, the preferences are saved.

My workaround at this time is to use '/command/core/rename-project' to rename the project to the name it already has, causing the project to be marked 'dirty'.

**Comment by jackyq2015** [comment] 2015-08-20 01:41
@hvmarck The get operation is not allowed. so http://127.0.0.1:3333/command/core/set-preference?project=1801073216107&name=xxxxx&value=vvvvvv will generate exception:
java.lang.UnsupportedOperationException
	at com.google.refine.commands.Command.doGet(Command.java:86)
	at com.google.refine.RefineServlet.service(RefineServlet.java:170)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Or you mean you do it in POST? Please clarify.

**Comment by jackyq2015** [comment] 2015-08-25 00:06
Close it since it can't be reproduced. Please reopen it if have any further concern.

**Closed by jackyq2015** 2015-08-25 00:06 UTC
Labels: bug
