### ISSUE TITLE
parseHtml() behaves unpredictably

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3306] opened 2020-11-02 22:22 UTC
Given some HTML (in this case, from a Project Gutenberg ebook), parseHtml() does some strange editing. 

1) It removes the `<!DOCTYPE...>` tag from the beginning.
2) It prematurely closes the `<head>` tag regardless of the original position of `</head>`, and opens up `<body>` immediately after. It thus pushes all sorts of CSS and meta tags directly into the `<body>`. 

![diff1](https://user-images.githubusercontent.com/28012148/97924093-1bad2d00-1d2d-11eb-9321-dbb50765ce7c.PNG)

The original position of `</head><body>` should have been fine. 

![diff2](https://user-images.githubusercontent.com/28012148/97924101-1cde5a00-1d2d-11eb-9f38-d2f8cd14fc53.PNG)

On other HTML, it converts `<!DOCTYPE html>` to lowercase but doesn't remove it. (I presume this is the intended behaviour.)

I'm sure there are more issues but these seem to be a good starting place. I realize the parseHtml() function relies entirely on external code from Jsoup, but it's worth looking at.

### To Reproduce
1. First, create a project with clipboard and pasting in a URL. (You can replicate mine with https://www.gutenberg.org/files/1342/1342-h/1342-h.htm but feel free to test others.)
2. Fetch HTML using "Add column by fetching URLs" 
3. Then, take the fetch results and run them through value.parseHtml().toString()
4. Finally, compare the two. 

### Expected Behavior
I'm happy to have weird behaviour and the introduction of errors as long as I can document them. If this behaviour is predictable (i.e. does the exact same thing on every HTML page), we're good to go! 

My current draft of the help text for the function reference is:
> parseHtml(s)
> Given a cell full of HTML-formatted text, simplifies HTML tags (such as by removing “ /” at the end of self-closing tags), closes any unclosed tags, and inserts linebreaks and indents for cleaner code. You cannot pass parseHtml() a URL, but you can pre-fetch HTML with the “Add column by fetching URLs” menu option. A cell cannot store the output of parseHtml() unless you convert it with toString(). 
> When parseHtml() simplifies HTML, it can sometimes introduce errors. When closing tags, it makes its best guesses based on line breaks, indentation, and the presence of other tags. You may need to manually check the results. 
> You can then extract or .select() which portions of the HTML document you need for further splitting, partitioning, etc. An example of extracting all table rows from a div using parseHtml().select() together is described more in depth at StrippingHTML.

**Comment by thadguidry** [comment] 2020-11-02 23:23
That's XHTML - which stands for EXtensible HyperText Markup Language. XHTML is a stricter, more XML-based version of HTML.
Yes it's confusing as well with the `DOCTYPE html` but the full line means and should be read as sayiing... "HTML document with XHTML 1.0 strict extensions included as defined by this dtd....blah blah blah"

So you are using a flat-tipped screwdriver on some cross-point screws.  Kinda, sorta. :-)

Luckily, Jsoup has an XML parser as well, which should help you more... and we provide the wrapper function for this:
`value.parseXml()`

And Jsoup follows the WHATWG HTML specification for parsing HTML and XML syntax: 
 https://html.spec.whatwg.org/multipage/xhtml.html#xhtml
https://html.spec.whatwg.org/multipage/#toc-the-xhtml-syntax

**Comment by thadguidry** [comment] 2020-11-02 23:28
If it helps...here's the actual Jsoup method docs for each one
https://jsoup.org/apidocs/org/jsoup/parser/Parser.html#xmlParser()

> htmlParser
> public static Parser htmlParser()
> Create a new HTML parser. This parser treats input as HTML5, and enforces the creation of a normalised document, based on a knowledge of the semantics of the incoming tags.
> 
> Returns:
>     a new HTML parser. 


> xmlParser
> public static Parser xmlParser()
> Create a new XML parser. This parser assumes no knowledge of the incoming tags and does not treat it as HTML, rather creates a simple tree directly from the input.
> 
> Returns:
>     a new simple XML parser.

**Comment by tfmorris** [comment] 2020-11-03 18:41
@thadguidry when you triage bug reports, can you please try to remember to add the appropriate labels (and remove the `to be reviewed` label if no one else needs to review it)?

Are you saying that this is not a bug? (ie should be closed)

**Comment by thadguidry** [comment] 2020-11-03 19:30
@tfmorris (I'll try to remember)  Yes, it is not a bug, it's predictable handling from Jsoup's classes with the WHATWG specs.

(And where the parse settings can be tweaked by users, but we don't expose those [options](https://jsoup.org/apidocs/org/jsoup/parser/ParseSettings.html) currently for allow/disallow tag and attribute names to be lower-cased during parsing. That would be an enhancement request separately someone could make if really needed.)

**Comment by tfmorris** [comment] 2022-10-19 00:23
Closing as not a bug based on @thadguidry 's comment above.

**Comment by thadguidry** [comment] 2022-10-19 00:45
Closing as won't fix.

**Closed by thadguidry** 2022-10-19 00:45 UTC
Labels: bug
