### ISSUE TITLE
Translation string keys incorrect (facet-flag/facet-error/facet-star)

### ISSUE THREAD

**Issue by strarsis** [OpenRefine/OpenRefine#3695] opened 2021-03-04 13:45 UTC
### To Reproduce
1. Switch the language to another language than the default language of OpenRefine (English), e.g. German.
2. Note that the captions for facet selection (most-left column drop-down menu) are swapped/incorrect: 
Translation string key [core-views/facet-error](https://github.com/OpenRefine/OpenRefine/blob/3.4.1/main/webapp/modules/core/langs/translation-de.json#L642) is swapped with [core-views/facet-flag](https://github.com/OpenRefine/OpenRefine/blob/3.4.1/main/webapp/modules/core/langs/translation-de.json#L547).
Additionally [core-views/facet-flag](https://github.com/OpenRefine/OpenRefine/blob/3.4.1/main/webapp/modules/core/langs/translation-de.json#L547) is used instead of [core-views/facet-star](https://github.com/OpenRefine/OpenRefine/blob/3.4.1/main/webapp/modules/core/langs/translation-de.json#L673), though that flag is symbolized as a star.

### Current Results
Incorrect/swapped translation strings as wrong keys are used.

### Expected Behavior
Correct translation strings, correct usage of translation keys.

### Versions
 - Operating System: Windows 10 x64
 - Browser Version: Latest Chrome
 - JRE or JDK Version: Windows Runtime Bundle
 - OpenRefine: `Version 3.4.1 [437dc4d]`

### Datasets
(applicable to any dataset)

**Comment by Warpeas** [comment] 2021-03-12 14:58
@wetneb Our study group would like to solve this issue and would like to get some advice. Thank you!

SE_SUSTech

**Comment by wetneb** [comment] 2021-03-12 15:12
Hi @Warpeas, welcome on board!

We have a broad overview of the contribution process here: https://github.com/OpenRefine/OpenRefine/wiki/Your-first-pull-request

If you have any specific questions please do ask!

**Comment by Warpeas** [comment] 2021-04-24 08:40
Hi, I think this problem is caused by some mistakes in translation. And it's fixed by commit [3465](https://github.com/OpenRefine/OpenRefine/commit/823097fb2e2aff5bb68cba00b225026e6f8b041a). I tried to switch to another language that I can understand (Chinese) and there's no such problem. I think the language load process is correct now in the new version and this issue could be closed. If there are other problems please let us know.

**Comment by wetneb** [comment] 2021-04-24 12:09
I agree, this was specific to German and seems to have been fixed by updates to the translations. Thanks for your investigation!

**Closed by wetneb** 2021-04-24 12:09 UTC
Labels: UI, bug, good first issue, localization
