### ISSUE TITLE
Refine messes up quotations marks on import and export.

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#402] opened 2012-10-15 03:35 UTC
_Original author: bad...@gmail.com (June 10, 2011 21:34:32)_

I noticed some problems with google-refine dealing with quotes.

== SETUP ==

$ cat /etc/redhat-release 
CentOS release 5.6 (Final)

$ java -version
java version &quot;1.6.0_17&quot;
OpenJDK Runtime Environment (IcedTea6 1.7.10) (rhel-1.21.b17.el5-x86_64)
OpenJDK 64-Bit Server VM (build 14.0-b16, mixed mode)

I tried both Google Refine Version 2.0 [r1836] and Version 2.1 [TRUNK].

== TEST FILE ==

The test I did uses the attached file which contains:

First column|Second column
&quot;Quotes&quot; with words after|02134
&quot;Quotes on each side&quot;|6789

I experienced problems both at import and export of the file.

== DESCRIPTION OF THE PROBLEM ==

=== Importing the file ===

I leave all the default options except for the pipe as the column separator. I tried both with or without &quot;Ignore quotation marks&quot; checked and it made no difference. Here is the result I get:

+-----+--------------------------+---------------+
| All | First column             | Second column |
+-----+--------------------------+---------------+
| 1.  | Quotes&quot; with words after | 2134          |
| 2.  | Quotes on each side      | 6789          |
+-----+--------------------------+---------------+

As you see, the first quote disappeared on the first line and both quotes disappeared on the second.

=== Exporting the file ===

Without any modification, I select Export and Tab-separated value. Here is the output I get (replacing tab by pipe):

First column|Second column
&quot;Quotes&quot;&quot; with words after&quot;|2134
Quotes on each side|6789

As you can see now I get more quotes on the first line and no quotes on the second.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=402_
##

**Comment by thadguidry** [comment] 2016-07-14 20:06
@tfmorris Well coming back to this after a few years. :)  We definitely need 1 enhancement here on the Export -> Custom Tabular Exporter

**1. The issue is that we did not give the user an additional checkmark option to output With Quotes or Not.**
We need to give the user this option.
I ran across it today with a pure line input format... SQL  and just 1 column to hold all the lines of SQL text.
I did a few transformations on a few faceted lines for each TABLESPACE and then went to use Custom Tabular Exporter to export just pure lines from Column 1.... but...sigh....

Grid View:
CREATE TABLE "VT1"."ACCOUNT_PROCESS_MONITOR" 
   (	"OPERATION" VARCHAR2(10 BYTE), 
	"BATCH_NO"" NUMBER(7,0), 
	"PROCESS_COUNT" NUMBER(4,0), 
	"CREATED"" DATE
   ) SEGMENT CREATION IMMEDIATE

Custom Tabular Exporter output:

CREATE TABLE "VT1"."ACCOUNT_PROCESS_MONITOR" 
"   (	""OPERATION"" VARCHAR2(10 BYTE), "
"	""BATCH_NO"" NUMBER(7,0), "
"	""PROCESS_COUNT"" NUMBER(4,0), "
"	""CREATED"" DATE"
   ) SEGMENT CREATION IMMEDIATE

tons of extra quotes that are not needed an no way to get rid of them with any of the options in Custom Tabular Exporter.

So then tried to use Templating Export.... but get an extra null for blank rows.
**2. So even Templating Export needs a checkmark option for omitting blank or null rows as well.**

**Comment by thadguidry** [comment] 2018-02-15 18:52
Closing this issue as it is pretty much resolved now after move to OpenCSV 4.0 and the new Importer UI options now in place ... and so will open new issue for the Templating Export enhancement I mentioned to support conditional Quotes or not and excluding blank or null rows.

**Closed by thadguidry** 2018-02-15 18:52 UTC
Labels: bug, import, imported from old code repo, priority-Medium
