### ISSUE TITLE
error uploading data from csv, perhaps due to colon included in temp filename

### ISSUE THREAD

**Issue by jpasini** [OpenRefine/OpenRefine#1142] opened 2016-07-15 14:33 UTC
I have Windows 7, OpenRefine 2.6rc2 and Oracle jdk 1.8u92 and I haven't been able to upload data from a local csv file. The message is

`Error uploading data: C:\Users\myuser\AppData\Local\Temp\Jetty_127_0_0_1_3333_webapp____4ulpc9\import\1\raw-data\C:\Users\myuser\Documents\datasets\Hartford\Incidents.csv (The filename, directory name, or volume label syntax is incorrect)
`

I already saw another thread mention that something similar could happen if you don't have write permission to the temp folder, but in this case I'm running it from my account and the Local folder seems to be under my account. The problem here is more likely the colon in the filename (the "\C:\" in the middle of the pathname). Has anyone else seen this?

The csv file is the exported csv from this public data set:
https://data.hartford.gov/Public-Safety/Police-Incidents-01012005-to-Current/889t-nwfu

Thanks in advance,
Jose Miguel

**Comment by thadguidry** [comment] 2017-03-30 14:13
This isn't a OpenRefine issue, but a local environment issue.  The proof is in our code here:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importing/ImportingJob.java#L70

But to help you out, Check your TEMP and TMP environment variables for possible corruption, or just simply change them to another folder path like ```E:\TEMP``` or whatever you want.

On my Windows 7 spare laptop, I have my User Environment Variables for TEMP and TMP pointing to
```%USERPROFILE%\AppData\Local\Temp```

![tempdiroveride](https://cloud.githubusercontent.com/assets/986438/24508349/bdf4e910-1528-11e7-9282-51b7cea8b9eb.PNG)

**Comment by cameronstewart** [comment] 2017-03-30 22:02
Thanks Thad, I changed the System Variables but it didn't seem to make a
difference.  I'll try another box.

**Comment by jackyq2015** [comment] 2017-03-31 03:30
How do you create the project? Did you use the "Choose file" button to select the csv file or you use the URL?

**Comment by cameronstewart** [comment] 2017-03-31 03:32
File option

**Comment by jls4dtna** [comment] 2017-04-21 20:20
I have this same issue, and it has nothing to do with the value of TMP or TEMP. Using the Browse button, I selected the file Librarygood.xml, which was in my Windows 7 home directory C:\Users\STAMPEL.  When I tried to load it, I got this error, much like the others received:

![image](https://cloud.githubusercontent.com/assets/27868729/25293817/456ad426-2691-11e7-8f60-8bff136d2a79.png)

It seems clear that OpenRefine was trying to copy the xml file in its own private temp directory  'C:\Users\STAMPEL\AppData\Local\Temp\Jetty_127_0_0_1_3333_webapp____4ulpc9\import\2\raw-data', replicating the original file's path - i.e., C:\Users\STAMPEL.

The problem is that the colon character is not allowed in Windows file names. The colon needs to be removed or replaced with a legal character. That should fix the issue.

**Comment by cameronstewart** [comment] 2017-04-23 06:04
So how would you fix this considering everything will be somewhere on a
drive so a drive: will be replicated Irrespective of where it is?

**Comment by jls4dtna** [comment] 2017-04-24 15:16
You can simply retain the drive letter but remove the colon.

e.g. C:\foo\bat\bar\data.xml is mapped to ...\raw-data\C\foo\bat\bar\data.xml

**Comment by jackyq2015** [comment] 2017-04-24 16:23
I cannot reproduce the issue. The file path you selected should not has
been taken the full path. Should be file name only. Did you copy paste the
full path

**Comment by jls4dtna** [comment] 2017-04-24 16:39
I did not copy the full path. I did not copy anything at all. As I stated in my original posting,

I used the Browse button to select the file…

[cid:image002.jpg@01D2BCDE.9FFA5370]

Then I selected the file…

[cid:image003.jpg@01D2BCDE.9FFA5370]

Then I clicked the Next button…

[cid:image010.jpg@01D2BCDE.9FFA5370]

And then I got the error message:

[cid:image011.jpg@01D2BCDE.9FFA5370]

**Comment by bright-sea** [comment] 2017-04-24 17:55
There is no problem in my old 32bit windows7 machines, everything works fine. Today I changed to a new 64bit windows7 machine and  seeing exactly the same issue. Nothing to do with users operation, I just choose a file from dialog. Running as administrator doesn't help.

**Comment by jls4dtna** [comment] 2017-04-24 18:00
Right. The problem is in Windows 7. I read in another forum that someone had been using Refine on earlier version(s) of Windows for years with no problem, but when they moved to Windows 7 this problem happened immediately.

**Comment by bright-sea** [comment] 2017-04-24 18:03
One more test found out the problem: It is happens when you use IE browser. If you change to use chrome, it will be OK. This might be caused IE11 which was installed on my new Windows7.

So we can further investigate this at IE11 on other environment.

**Comment by jls4dtna** [comment] 2017-04-24 18:15
Setting Chrome as the default browser fixed the problem for me.

**Comment by cameronstewart** [comment] 2017-04-25 03:33
Makes sense but how do you modify it?  The error just pops up in a dialogue
box.

**Comment by jls4dtna** [comment] 2017-04-25 15:16
@cameronstewart, read the most recent posts. The root cause of the problem is different than I supposed. It turned out that the full path should never have been replicated in the first place, therefore my proposed solution is not helpful. The workaround is to make Chrome your default browser.

**Comment by jackyq2015** [comment] 2017-04-26 02:56
Seems there are some inconsistency between chrome and IE for the file selector component. I can put a patch on either front end or back end to extract the file name only. But MS is moving to Edge from IE, not sure it is still worth fixing it.

**Comment by cameronstewart** [comment] 2017-04-26 03:00
Great - didn't even think of that...just post http://127.0.0.1:3333/ into
Chrome address bar!
[image: Inline image 1]


Works as expected.  thankyou for the idea!

Cameron

**Closed** 2017-05-08 00:14 UTC
