### ISSUE TITLE
Timeline Facet too imprecise to capture exact date range

### ISSUE THREAD

**Issue by srappel** [OpenRefine/OpenRefine#5001] opened 2022-06-29 20:23 UTC
### To Reproduce
1. First, create a timeline facet based on a date-formatted field
2. Then, slide the lower or upper bounds to the desired date/time to set the facet

### Current Results
It is unclear how the stop points of the sliders for the timeline facet are generated. Here's a sample of the dates and times I'm attempting to facet

> 2021-06-18T00:00:00Z
> 2021-06-18T00:00:00Z
> 2021-06-21T00:00:00Z
> 2021-06-21T00:00:00Z
> 2021-06-24T00:00:00Z
> 2021-06-25T00:00:00Z
> 2021-07-09T00:00:00Z
> 2021-07-21T00:00:00Z

I would like to facet my results to a lower bound of 2021-07-01. But when I move the slider, it jumps from 2021-06-19 18:16:48  to 2021-07-20 04:45:54. None of the data includes times, yet the slider seems to jump to specific times (see screenshot examples). 

### Expected Behavior
The user should be able to enter exact parameters for this functionality. I would expect to be able to define an exact date/time to facet and not be at the whim of the seemingly random time stops.

### Screenshots
![image](https://user-images.githubusercontent.com/12561339/176504279-0375bdc5-b769-4996-93ea-31c206db7bbe.png)
![image](https://user-images.githubusercontent.com/12561339/176504394-624f37eb-ce29-4d4e-aa6b-795180a53e18.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox 91.10.0esr (64-bit)
 - OpenRefine: Version 3.5.1

**Comment by thadguidry** [comment] 2022-06-29 22:24
I cannot reproduce this.  Are you sure that you used the menu over your date column and chose "Edit cells" -> "Common transforms" -> "to date" before attempting the timeline facet?

My timeline facet (Facet -> timeline facet) seems to work just fine and also appears differently than your screenshots.

![image](https://user-images.githubusercontent.com/986438/176555923-3335c363-589d-4b43-9194-49b56ff2fc4b.png)

**Comment by srappel** [comment] 2022-06-30 19:11
### Sample Data:
[sample_data.csv](https://github.com/OpenRefine/OpenRefine/files/9022661/sample_data.csv)

Here's a copy of all 3000+ records of dates. Notice that all of them have only dates and the time is T00:00:00Z.

![image](https://user-images.githubusercontent.com/12561339/176758636-7fa59acf-d8a4-424f-a417-295adf50edd1.png)

I'm still getting seemingly random upper and lower bounds on the timeline sliders.

This is not in 3.5.2, so we are using the same version. @thadguidry , Could you try to reproduce with the sample data above?

**Comment by thadguidry** [comment] 2022-06-30 19:58
Ah, now I understand!  You want control over the binning size, and probably other controls also.
Yeah, there is only a default binning size (a cluster bar) which changes based on the data in the column and you cannot control that yet.
Sorry about that, but yes, this is a known issue already in https://github.com/OpenRefine/OpenRefine/issues/3248

In the meantime, you can create a custom Text facet based on your criteria for lower or upper bounds to get exact precision and control that you might need.
For example:
GREL
```
if (
  and(value.datePart("year") >= 2017, value.datePart("month") >= 7, value.datePart("day") >=01),
  true,
  false
) 
```
Notice in the screenshot that those date greater or equal to 2017-7-01 are marked `true` in the expression preview.
You can of course modify the GREL to what you need and even use multiple `if()` or `and()` or whatever logic you need.
Then choose the `true` rows in the custom text facet.  (PAINFUL, I know, and not a slider at all, but the only way other than hand clicking manually on each 1138 choices !!! to include or not in the facet, that are the range of dates in a text facet if applied on ConsDate.)

Hopefully we get issue #3248 taken care of sooner rather than later, even if just allowing a lower and upper bound "data entry" window...which would be a quick good start
![image](https://user-images.githubusercontent.com/986438/176765020-c7321339-19d9-413b-8618-89acdfeeee0f.png)

**Comment by thadguidry** [comment] 2022-06-30 20:05
Another alternative... use `value.datePart()`  3 times with Add column based on... so you have a separate year, month, and day column to make custom text facets with boolean values and apply a single `if()` condition for only the part of each column as you need. (saving you from a large single custom grel over your 1 date column, you can have 3 smaller grel expressions.  up to you)

**Comment by thadguidry** [comment] 2022-06-30 20:07
duplicate of #3248

**Comment by thadguidry** [comment] 2022-06-30 20:08
duplicate of #3248

**Closed by thadguidry** 2022-06-30 20:08 UTC

**Comment by srappel** [comment] 2022-06-30 20:47
> Sorry about that, but yes, this is a known issue already in https://github.com/OpenRefine/OpenRefine/issues/3248

I apologize. I searched around in the issues but didn't find this one.

Your example of a GREL facet to do what I need to do will be very helpful. Thank you! I tinkered around with it but struggled to get the syntax right for what I wanted to do. Your code will do exactly what I need.
