### ISSUE TITLE
Search option has disappeared from reconciliation results (3.8.0)

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#6610] opened 2024-05-17 06:26 UTC
When reconciling against Wikidata, I don't get the option anymore to search when there has been no match on a cell. I tested with a few other reconciliation services and the search has disappeared there too.

<img width="528" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/9881645/a3a7ebfe-c885-4770-b07c-06bbdcefd637">

In the screenshot above, under the Create new item option I would expect a search option to appear.

OpenRefine 3.8.0 on MacOS, Chrome 124.0.6367.201

**Comment by wetneb** [comment] 2024-05-17 06:48
Thanks for reporting! It's a duplicate of #6599, whose fix is to be released in 3.8.1

**Closed by wetneb** 2024-05-17 06:48 UTC
Labels: Type: Bug, Status: Pending Review
