### ISSUE TITLE
Add a "Pause" button for long-running processes

### ISSUE THREAD

**Issue by raymondde** [OpenRefine/OpenRefine#5183] opened 2022-08-12 12:18 UTC
Add a "Pause" button while uploading files is in progress. With the next finished file the upload process should stop and a "Continue" button should re-start the uploa with the next file.

Reason: When uploading a really large batch of file (> 500) it could be usefiil to pause the upload for some time.

**Comment by trnstlntk** [comment] 2022-08-15 14:47
I have transferred this issue from the CommonsExtension repository to the general OpenRefine one, as I think this fits better there (pausing other kinds of data uploads may also be a request).

**Comment by wetneb** [comment] 2023-02-07 09:50
I have changed the title of this issue to make it more general: this is now about making it possible to pause any long-running process, such as:
* reconciliation
* add column by fetching urls
* data extension
* wikibase edit upload

This is something I intend to work on as part of the reproducibility project, as it touches on the structure of the process queue.

**Comment by thadguidry** [comment] 2023-02-07 11:12
Hmm, any possibility for Clustering pausing across large bin sets? Maybe/maybe not? or only some algorithms? or is Clustering not a true long-running process, I forget.

**Comment by wetneb** [comment] 2023-02-07 12:22
Clustering is indeed not the same sort of process (because it is not tied to an operation), so I would keep this outside the scope of this issue. We have a separate issue about this process: https://github.com/OpenRefine/OpenRefine/issues/241

**Comment by wetneb** [comment] 2023-04-10 12:40
Closed by https://github.com/OpenRefine/OpenRefine/commit/06595aeca093c26db8d233b04ceeeb907f834753

**Closed by wetneb** 2023-04-10 12:40 UTC
Labels: enhancement, large project support, wikibase, file upload
