### ISSUE TITLE
Feature request: Allow column exclude during project creation

### ISSUE THREAD

**Issue by simon1tan** [OpenRefine/OpenRefine#957] opened 2015-03-09 20:01 UTC
There seems to be many ways to exclude rows but a quick way to include/exclude columns would be nice. Maybe a checkbox at the column header? The Custom Tabular Exporter looks nice :). Perhaps something like that for imports. Thanks.

**Comment by wetneb** [comment] 2017-08-02 08:47
Closing as duplicate of #612.

**Closed by wetneb** 2017-08-02 08:47 UTC
Labels: duplicate, enhancement, import
