### ISSUE TITLE
Error Message - Timeout

### ISSUE THREAD

**Issue by alexabdelwahab** [OpenRefine/OpenRefine#955] opened 2015-03-05 22:20 UTC
I'm new to OpenRefine and am trying to get it to work on a Mac with OS X Yosemite (10.10.2)
I'm trying to work with data but I keep getting the following message:
'Error contacting recon service: timeout : timeout - http://standard-reconcile.freebaseapps.com/reconcile'
I'm not sure what is wrong or how I get it to stop.

**Comment by jackyq2015** [comment] 2015-03-08 13:54
I never used Mac.  But you can try to use chrome. Most likely your problem will be gone.

**Comment by tfmorris** [comment] 2015-03-08 22:39
The standard reconciliation service is gone, thus the message.  It can be safely ignored, but it is annoying.  The current development version has this service removed, but I think it gets recreated automatically if you try to remove it in the released version.

I think this error was originally mentioned in #805, but it has morphed beyond recognition and no longer makes any mention of it.

The issue isn't platform-specific and affects all three platforms equally.

**Comment by magdmartin** [comment] 2015-07-05 15:48
Fixed in OpenRefine2.6 RC1

**Closed by magdmartin** 2015-07-05 15:48 UTC
Labels: bug

**Comment by kabhinav** [comment] 2015-11-07 14:52
I am still getting this message in the code checkout from master branch.
