### ISSUE TITLE
Unicode characters inserted incorrectly

### ISSUE THREAD

**Issue by strarsis** [OpenRefine/OpenRefine#3691] opened 2021-03-03 12:48 UTC
### To Reproduce
1. Edit a text field or use the cell replace transformation, insert an Unicode character, like this smiley `😀`.
Notice that this Unicode character is displayed as an invalid/placeholder character instead (``). As the manually inserted Unicode character still looked fine (when replacing or before saving), the font, browser or OS is not the reason for the Unicode characters becoming invalid ones.

### Current Results
Invalid/placeholder character (``) when inserting an Unicode character.

### Expected Behavior
Proper editing and retrieving of Unicode characters.

### Versions
 - Operating System: Windows 10 x64
 - Browser Version: Chrome
 - JRE or JDK Version: Windows distribution
 - OpenRefine: `Version 3.4.1 [437dc4d]`

**Comment by Warpeas** [comment] 2021-04-25 14:01
@wetneb Hi, I tried to reproduce this issue in OpenRefine 3.5-beta [4aef758] and it seems correct. Maybe someone has fixed it.

SE_SUSTech

**Comment by wetneb** [comment] 2021-04-25 14:27
Hi @Warpeas, thanks very much for investigating this! Did you try with Chrome on Windows specifically?

**Comment by Warpeas** [comment] 2021-04-25 15:09
Hi, @wetneb Yes, I'm using Chrome version 90.0.4430.85 and Windows 10.

**Comment by wetneb** [comment] 2021-04-25 15:14
Thanks, let's close this as not reproducible then.

**Closed by wetneb** 2021-04-25 15:14 UTC
Labels: bug, encoding, to be reviewed

**Comment by strarsis** [comment] 2021-04-25 15:39
Well, I will download the latest release and retry again then...

**Comment by wetneb** [comment] 2021-04-25 15:45
@strarsis happy to reopen if you find out that this persists of course!

**Comment by Warpeas** [comment] 2021-04-25 17:07
Hi, @wetneb This issue can be reproduced in the latest release v3.4.1. And seems to be fixed before the 3.5-beta [4aef758]. So @strarsis maybe you can try to use the beta version or wait until the v3.5 release?
