### ISSUE TITLE
CSV parsing on import less precise with 2.6

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#1034] opened 2015-07-17 20:51 UTC
Take this file form the city of Toronto open data set http://opendata.toronto.ca/building/cleared.permits/clearedpermits2013_csv.zip

When loading in GoogleRefine 2.5 
- extract the file from archive
- create two extra columns Column 31    Column 32 due to some EST_CONST_COST having comma to separate hundreds and thousand. 

When loading in OpenRefine2.6Beta
- extract the file from archive
- create two extra columns Column 31    Column 32 due to some EST_CONST_COST having comma to separate hundreds and thousand. 
- some rows aren't parsed as new rows and stored into a single line, generating extra column

When loading with OpenRefine2.6 RC1, 
- the parser don't recognize the file in the zip archive. 
- When I unzip the archive  and load the csv it create up to Column 39 due to comma in the DESCRIPTION field that wasn't generating error in 2.6Beta.

**Comment by jackyq2015** [comment] 2015-07-18 15:21
I just imported this file on master build. it parsed the zip and created up to Column 139. which revision is the 2.6 RC1 built from?

**Comment by jackyq2015** [comment] 2015-07-19 01:27
Indeed the RC1 behave differently with the current master and 2.6 Beta when importing the given file. The source and binary of RC1 can be found at:
https://github.com/OpenRefine/OpenRefine/releases/tag/v2.6-rc1

**Comment by tfmorris** [comment] 2015-07-22 16:07
The good news is that there have only been 20 commits (and fewer changes than that due to PR merges) since RC1.  The bad news is that I don't, at a glance, see anything which is a likely culprit.

What operating system are you testing on?  Does it occur on more than one?  One possibility is that it's a build issue for one platform, but I'll need to dig in more to figure out what's going on.

**Comment by magdmartin** [comment] 2015-07-22 17:12
I am running Refine on linux.

**Comment by tfmorris** [comment] 2015-07-22 18:25
I've tested both the Mac and Windows RC1 kits and can't reproduce the problem, so my assumption is that this is something that is Linux (or JVM) specific, not a difference in behavior between RC1 and the current development version.

**Comment by tfmorris** [comment] 2015-07-22 18:29
p.s. just to be explicit, on both platforms the last column for the imported project is named DEMOLITION, the same that I see in Excel and there are no additional columns after EST_CONST_COST (ie the next column is named ASSEMBLY).

**Comment by jackyq2015** [comment] 2015-07-23 01:44
There is some inconsistency. i am using current dev master on windows 7. what I saw is the last column is "Column 139". From "Column 31" until Column 139" are all empty and somehow the parser get it wrongly. Is there someone else can test the same file on other platform such as Mac?

**Comment by magdmartin** [comment] 2015-09-07 17:23
I am experiencing this issue again with the RC1 on a ubuntu machine. I also realized that the data set use quotation mark and un/checking "Quotation marks are used to enclose cells containing column separators" have no effect on the preview.

**Comment by tfmorris** [comment] 2015-10-16 20:24
So, is this a real issue or not?  If it's real, it should be fixed for 2.6.  If it's not, we should close it.

**Comment by tfmorris** [comment] 2020-06-16 16:53
No response in 5 years. Closing.

**Closed by tfmorris** 2020-06-16 16:53 UTC
Labels: CSV/TSV, bug, import, not reproducible, priority: Medium
