### ISSUE TITLE
Actions with column should affect on filters for this column

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1026] opened 2015-07-10 23:18 UTC
1. On column rename, filters/facets that was enabled for this column, respectively should be set to new column name.
2. On column delete these filters/facets should be removed too.

**Comment by magdmartin** [comment] 2015-07-13 13:53
+1

**Comment by tfmorris** [comment] 2015-07-22 15:18
This is a duplicate of #133

**Closed by tfmorris** 2015-07-22 15:18 UTC
Labels: duplicate
