### ISSUE TITLE
Edit > Apply to All Identical Cells resets display to first page

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#536] opened 2012-10-15 03:40 UTC
_Original author: ericjarv...@gmail.com (February 26, 2012 13:54:39)_

When editing cells, and when the user is on page 2 or greater, and clicks the 'Apply to All Identical Cells' button, the view is refreshed and returned to the first page, instead of refreshing and remaining on the current page.  

The user must page forward to return to the previous page/row, and because there are only;
&lt;&lt; first &lt; previous   next &gt; last &gt;&gt; 
options, and no page numbers, it can be particularly frustrating.

Thus, this issue touches on two items;
1. When 'Apply to All Identical Cells'  is clicked, do not return to first page/row.
2. Add 'clickable' page numbers to the previous/next section so the user can jump forward e.g.-
&lt;&lt; first &lt; previous    1|2|3|4|5|6|7|8|9|10   next &gt; last &gt;&gt; 
or
enter page number[       ]  [Go]
# 

Thanks,

Eric Jarvies

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=536_

**Comment by wetneb** [comment] 2019-12-20 14:40
Marking as duplicate of #33, even if it isn't exactly the same operation: the work needed to fix this is the same.

**Closed** 2019-12-20 14:41 UTC
Labels: UI, bug, duplicate, imported from old code repo, priority: Medium
