### ISSUE TITLE
Add import options to operational history 

### ISSUE THREAD

**Issue by nikolatulechki** [OpenRefine/OpenRefine#5164] opened 2022-08-09 12:30 UTC
We are currently working on [ontorefine-cli](https://github.com/Ontotext-AD/ontorefine-cli), a command-line interface to [ontotext-refine](https://platform.ontotext.com/ontorefine/index.html), itself a fork of OpenRefine with added functionalities to produce RDF.  

The main use-case of the CLI is to be able to repeat and automate a end-to-end workflow. The story we want to tell is that of a  user  iteratively coming up with a conversion "recipe" using the UI and then applying this on more data with the same characteristics.  

While we can easily extract the list of operations from the UNDO/REDO tab in OpenRefine, access to the import options is a little bit more tricky. They are available in the "Project metadata" dialog, which is available when selecting "about" from the list of projects. For our use case, these options are required because without them, we can not assure that the raw input data is processed by the CLI in exactly the same way as the project in the UI. This is even more important for XML or JSON inputs, for which the import options contain flattening instructions.    

### Proposed solution

Our proposition is that the import options become available in the operations history json array, generated from the undo/redo tab with proper values for "op:", such as  "import/csv" or "import/xml".
These entries should be ignored when working on a project in the UI, but will be applied by the CLI when transforming new data with the same structure.  

### Alternatives considered

Passing the import options as a separate file to the CLI, which requires some tedious explanations for the users on how to find them, copy and paste them into a file.

**Comment by wetneb** [comment] 2022-08-09 13:00
Definitely keen to work on this (although I want to take the time to think more about the pros and cons of various designs - it's worth getting this right).

This is a duplicate of #460, where there is quite some discussion already.

**Comment by wetneb** [comment] 2022-10-05 20:52
Let's close this to keep the issue contained in #460, since @VladimirAlexiev already added more thoughts there.

**Closed by wetneb** 2022-10-05 20:52 UTC
Labels: duplicate, enhancement, import, undo/redo/history
