### ISSUE TITLE
SQL exporter doesn't create compliant column names

### ISSUE THREAD

**Issue by stevevance** [OpenRefine/OpenRefine#1940] opened 2019-01-30 21:52 UTC
**Describe the bug**
The SQL exporter will not create SQL-compliant column names. If a column has spaces, they are replaced with "-" by default, and replaced with nothing if the "Trim Column Names" checkbox is unchecked. Hyphens are not an acceptable character in a SQL column name. 

**To Reproduce**
1. Open a dataset that has column names with spaces in them. 
2. Click Export>SQL Exporter. 
3. Click "Download" tab. 
4. Click Preview
5. Attempt to create a table in an SQL database with the SQL exported by OpenRefine. It will not create, and SQL will print an error like:
````
ERROR:  syntax error at or near "-"
LINE 11: Line1-Street TEXT NULL,
              ^
````

**Current Results**
What results occured or were shown.

**Expected behavior**
The SQL Exporter should, by default, convert column names to an SQL-compliant name, replacing spaces and other illegal characters with "_" (underscore). Column names can also not begin with numbers. They cannot have single quotes or punctuation. 

**Screenshots**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/1330459/52015084-c5032700-24a6-11e9-80c2-cecf14078dfe.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1330459/52015094-caf90800-24a6-11e9-9e56-53dd83e88954.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1330459/52015101-cfbdbc00-24a6-11e9-9303-fe6f7eff2b0b.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.14.2
 - Browser Version: Safari 12.0.2
 - JRE or JDK Version: 1.8.0_121

**OpenRefine (please complete the following information):**
 - Version 3.1 [b90e413]

**Comment by thadguidry** [comment] 2019-01-31 00:32
Incidentally, we had decided during design time of the SQL Exporter that it was up to users to get their data in the right order prior to export (which includes names/data)

**Comment by wetneb** [comment] 2019-02-01 20:03
I don't think we should just throw a warning, the expected behavior described above looks reasonable to me.

**Comment by thadguidry** [comment] 2019-02-01 23:07
@wetneb Well, then the only way would be going "semi-safe"... where someone can write the Identifers conversion routines by following PostgreSQL Lexical Structure documentation as a general guide. Since ISO locks up the standard behind a paywall. https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

Following that should make it compatible for all databases.

**Comment by yuepeng-unc** [comment] 2020-03-19 16:11
I am beginning to work on this. I am planning to convert the column names to valid SQL column names. 
Please assign the issue to me. Thanks.

**Comment by thadguidry** [comment] 2020-03-19 16:12
@yuepeng-unc Thanks for taking up this issue.  Happy to work with you on this.

**Comment by NikitaEmberi** [comment] 2021-02-17 17:24
I started working on this issue by adding back quotes to each column name before exporting to sql to allow name flexibility. Please can you assign this issue to me. Thanks.

**Comment by NikitaEmberi** [comment] 2021-02-18 21:17
will the back quotes added to column names like this would do?
![image](https://user-images.githubusercontent.com/59737567/108422538-b1c57e80-725c-11eb-9f90-334df38874f3.png)

**Comment by stevevance** [comment] 2021-02-22 03:23
@NikitaEmberi PostgreSQL also allows double quotes `"` to escape field/column names that have spaces.

**Comment by NikitaEmberi** [comment] 2021-02-22 11:19
Yes sir double quotes works fine with PostgreSQL but when I tried to import it on MySQL or MariaDB it still gave me same errors as mentioned above and then I found that databases like MySQL require back quotes. I was thinking of writing SQL export query based on the database type chosen by user. 
I am following the link provided by @tfmorris sir on issue #2716:
https://stackoverflow.com/questions/2901453/sql-standard-to-escape-column-names

**Comment by NikitaEmberi** [comment] 2021-02-22 18:49
If the user connects to PostgreSQL then queries will be exported as:
![image](https://user-images.githubusercontent.com/59737567/108754984-ac25ac80-756c-11eb-8f36-1fed00e1f459.png)

If the user connects to MySQL, MariaDB or SQLite then queries will be exported as:
![image](https://user-images.githubusercontent.com/59737567/108754939-9d3efa00-756c-11eb-9e10-b839538eb470.png)

Would this do?

**Comment by wetneb** [comment] 2021-02-24 10:40
It looks sensible to me!

**Comment by shelomi99** [comment] 2022-04-01 05:43
Hi @wetneb I tried to reproduce this issue locally.

If a column name has a space, and the "Trim Column Names" checkbox is checked, the name is trimmed to remove any whitespaces.  According to the Expected behavior should the column name replace the space with an '_' character instead?
![image](https://user-images.githubusercontent.com/50749107/161201881-b2900464-3cae-430c-83be-5d407916e6f2.png)
![image](https://user-images.githubusercontent.com/50749107/161201895-82be9272-b67a-4f3e-af82-ea9f953d72df.png)

<hr>

Also, what is the expected behavior when "Trim Column Names" checkbox is unchecked? 
currently, it is replaced with nothing and it will prompt and error when creating a table in an SQL database with that script
![image](https://user-images.githubusercontent.com/50749107/161201913-12f9d15a-0a88-4186-a63b-97050c86f2b0.png)
![image](https://user-images.githubusercontent.com/50749107/161201944-7d3fd535-2f09-4159-85fa-c7c6795a1565.png)

**Comment by antoine2711** [comment] 2022-04-01 06:07
> If a column name has a space, and the "Trim Column Names" checkbox is checked, the name is trimmed to remove any whitespaces. According to the Expected behavior should the column name replace the space with an '_' character instead?

The discussion in this issue seams to point much more in the direction of escaping. It’s kinder to the user to respect is choice. Removing was most probably an easy fix to a problem. The quoting on the other hand, is more complicated but much more useful to the user.

Unless you see a problem with implementing quotes based on the type of database, quoting is the way! ;-)

Regards,
   Antoine

**Comment by shelomi99** [comment] 2022-04-01 07:08
Hi @antoine2711, appreciate your quick response. So is it right to assume that when it comes to an SQL only scenario, it should export all column names within backticks. Exporting with backticks should not be limited to column names with special characters yeah?

**Comment by antoine2711** [comment] 2022-04-01 10:01
> (…) it should export all column names within backticks. 
Yes. But, for some databases, backticks seams to (might) not work… (not sure, and the exception if so)

> Exporting with backticks should not be limited to column names with special characters yeah?
Yes.

I'm assign this issue to you. Feel free to ask any questions.

Regards, 
   Antoine

**Comment by shelomi99** [comment] 2022-04-02 03:29
Hey, @antoine2711 I have a question regarding the SQL exporter. Is there an option for the user to select the database type before exporting the SQL script as it is not mentioned in the description of the bug?
If there is no option to select the database, in order to make the SQL script compatible with all the databases, escaping is not really an option. 

> Expected behavior
The SQL Exporter should, by default, convert column names to an SQL-compliant name, replacing spaces and other illegal characters with "_" (underscore). Column names can also not begin with numbers. They cannot have single quotes or punctuation.

If this is the case after doing some searching I have found that this expected behavior is the only way to go. Correct me if I'm wrong.

**Comment by thadguidry** [comment] 2022-04-02 04:03
@shelomi99 There is no option to select a SQL database type to export for.  SQL is a standard and the export is that of a **SQL script** that adhere's nearly verbatium to the SQL standard and it's lexical syntax and formatting.  Have a look at all my various comments above in prior years. (This issue has been around since 2019) In particular, about PostgreSQL syntax of identifiers in the **4.1.1 Identifiers and Key Words section** in https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS  It will give you all the rules necessary for producing a compliant SQL script export that many OpenRefine users need, who must now manually make small corrections to the current exported SQL script to be compliant to be able to import into their own database systems.

**Comment by antoine2711** [comment] 2022-04-02 04:31
> Is there an option for the user to select the database type before exporting the SQL script as it is not mentioned in the description of the bug?

@shelomi99 : you are right, there are none. That could be added to the Download tab, but it would be far from the original post, and more complex.

The scope of this issue is to substitute invalid characters from the title with the underscore charater, when the « Trim Column Names » option is checked.

If you want to push the issue a bit further, you _could_ also add a text field to specify the escaping character. That way, the user has the control (and the escaping can be done without triming). But this feature could/should be another issue in itself.

Regards,
   Antoine

**Comment by shelomi99** [comment] 2022-04-02 08:10
@thadguidry The approach that you have suggested would very well work for PostgreSQL but I doubt we can make
it work for all databases. Unicode escapes work for PostgreSQL but the same does not work for MYSQL and it will be
a tedious task for the user to change the column names manually.

@antoine2711 I have opened the below pull request [1] to simply substitute invalid characters from the column names with 
an underscore character using a regex. Please do review the PR and give your thoughts on the fix.

[1] https://github.com/OpenRefine/OpenRefine/pull/4685

Regards,
Shelomi

**Comment by thadguidry** [comment] 2022-04-02 13:28
@shelomi99 I did not say to use escaping but to refer to that reference that suggests to use underscores in column names which is what we do as a standard practice in the DB world.

**Comment by shelomi99** [comment] 2022-04-02 13:41
Sorry for the misunderstanding @thadguidry. It is in fact the approach that I have followed when adding the fix for this issue. Refer [1] for the fix. Thanks for your input and help :)

1. https://github.com/OpenRefine/OpenRefine/pull/4685

**Closed** 2022-04-03 05:05 UTC
Labels: bug, good first issue, SQL/database

**Comment by antoine2711** [comment] 2022-04-03 07:34
@shelomi99 : good work. You can start to look at the « [Good Second Issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+Second+Issue%22) ».

Or you could start a new issue to for an escape character!

Regards,
   Antoine

**Comment by shelomi99** [comment] 2022-04-06 17:55
Hi @antoine2711, as the improvement you suggested requires a bit more effort I started looking into a good second issue instead at [1].  Appreciate it if you could give me insights on it :)

1. https://github.com/OpenRefine/OpenRefine/issues/195

**Comment by antoine2711** [comment] 2022-04-07 02:37
@shelomi99 : the improvement I suggested are for ANOTHER NEW issue! You have done enough on this one, it's done! ;-)

For the other issue, you can ask me general questions thru email: antoine@beaubien.qc.ca, or specific questions about the issue on the issue itself.

Regards, Antoine
