### ISSUE TITLE
Unexpected behavior when using "Apply to all identical cells" on blank cells

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1061] opened 2015-09-04 20:42 UTC
When I edit a blank/null cell via "Edit this cell" and select "Apply to all identical cells", neither the original cell nor the other blank/null cells are updated. The yellow-highlighted status message at the top-center of the window says merely, "Mass edit 0 cells in column title". 

(At first I didn't notice that data wasn't updating, and as a result I lost work.) 

In other words, "Apply to all identical cells" only seems to work on cells that are not blank/null.

(I'm using 2.6RC1 with current versions of Mac OS X and Google Chrome.)

**Comment by magdmartin** [comment] 2015-09-05 18:57
duplicate of #332

**Closed by magdmartin** 2015-09-05 18:57 UTC
Labels: bug
