### ISSUE TITLE
refine script ignores compilation errors and attempts to run the app anyway

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5698] opened 2023-03-16 14:56 UTC
The `refine` script on Linux does not do a good job at stopping if it needs to compile OpenRefine and compilation errors occur.

### To Reproduce
Steps to reproduce the behavior (from a git clone of the repository):
1. First, clean with `./refine clean`
2. Then, introduce some compilation error somewhere, such as by doing `rm ./extensions/wikibase/src/org/openrefine/wikibase/qa/QAWarning.java`
3. Finally, run `./refine`

### Current Results

The compilation fails in the Wikibase extension but the `refine` script still attempts to start OpenRefine:

```
...
[ERROR] extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizer.java:[104,17] cannot find symbol
[ERROR]   symbol:   class QAWarning
[ERROR]   location: class org.openrefine.wikibase.qa.scrutinizers.NewEntityScrutinizer
[ERROR] extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizer.java:[104,39] cannot find symbol
[ERROR]   symbol:   class QAWarning
[ERROR]   location: class org.openrefine.wikibase.qa.scrutinizers.NewEntityScrutinizer
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :wikibase


15:54:05.840 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
15:54:05.975 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 bytes (135ms)
15:54:06.359 [            refine_server] Initializing context: '/' from '/home/user/OpenRefine/main/webapp' (384ms)
15:54:06.948 [            refine_server] Starting autoreloading scanner...  (589ms)
15:54:13.478 [                   refine] Starting OpenRefine 3.8-SNAPSHOT [acca2dd]... (6530ms)
15:54:13.495 [                   refine] initializing FileProjectManager with dir (17ms)
...
```

### Expected Behavior

The `refine` script should stop at the end of the failing Maven build.

### Versions
 - Operating System: Linux
 - JRE or JDK Version: 17
 - OpenRefine: master branch

## Additional context

This could be solved with some bash flags, see https://github.com/OpenRefine/OpenRefine/issues/5241

**Comment by S1Y333** [comment] 2023-03-19 03:42
@wetneb Can you please assign this issue to me? I want to try, thanks so much

**Comment by S1Y333** [comment] 2023-03-19 16:51
@wetneb I ran these three steps and Openrefine didn't start because of the error. Please find the screenshot and the log file for your reference.

<img width="1331" alt="Screen Shot 2023-03-19 at 12 49 39 PM" src="https://user-images.githubusercontent.com/105386341/226191727-c6ba9bfc-6f9a-405b-ae4b-541cd9424772.png">

[Refine script output log](https://github.com/OpenRefine/OpenRefine/files/11011696/Refine.script.output.log)

**Comment by wetneb** [comment] 2023-03-19 18:51
That's great, so you have reproduced the bug.
Looking forward to your pull request to fix it!

**Comment by S1Y333** [comment] 2023-03-20 03:26
> That's great, so you have reproduced the bug.
> Looking forward to your pull request to fix it!

@wetneb Hi Antonin, I mean when I reproduced the bug, the refine script stopped at the end of the failing Maven build and OpenRefine didn't start, which is the expected result of fixing this bug. So can you please clarify what I need to fix based on my log?  Thank you

**Comment by wetneb** [comment] 2023-03-20 07:13
In your log file, the lines 1370 to 1381 do show that OpenRefine started, even if it resulted in an error in your browser.

Those lines 1370 to 1381 should not be there.

**Comment by S1Y333** [comment] 2023-03-20 15:40
> In your log file, the lines 1370 to 1381 do show that OpenRefine started, even if it resulted in an error in your browser.
> 
> Those lines 1370 to 1381 should not be there.

Okay, thanks for your explanation. I got my task, but I want to know if I am using mac OS to test, is it ok? Any prerequisite knowledge to complete this task? I am not quite familiar with Linux, so any information would be helpful for me to get started. Much appreciated.

**Comment by wetneb** [comment] 2023-03-20 15:43
You can totally work on this on Mac OS. Because `refine` is a bash script, familiarity with bash will likely be very useful.

**Comment by S1Y333** [comment] 2023-03-22 14:37
@wetneb Hi Antonin, I learned the Bash script a few days and know the following code automatically start the Refine.java file, so my goal is to record the compile failure and stop this script from running, am I right? 

` RUN_CMD=("$JAVA" -cp "$CLASSPATH" "${OPTS[@]}" "com.google.refine.Refine")

    echo ""
    
    

    if [ -z "$FORK" ] ; then
        exec "${RUN_CMD[@]}"
    else
        "${RUN_CMD[@]}" &
        REFINE_PID="$!"
    fi`

tried the following steps:
- if I add set -e or set -o pipefail to the script, it will come out the "unbounded variable error"
- I also tried to add a flag to the test(), servertest(), extensiontext() to record the error code then use the flag to stop running but it's not working.
- I also tried to remove the <skip> tag in the pom.xml

I feel like I didn't find when and where the extension starts compiling in the refine script. Also, which part of the code is testing all the extensions' compilation when run() executes?

**Comment by wetneb** [comment] 2023-03-22 14:44
Extensions are compiled alongside the rest of the modules by calling Maven (`mvn compile test-compile`). That's why you do not see any section that is specific to extensions in the refine script: they are all handled inside Maven.

**Comment by wetneb** [comment] 2023-03-22 15:41
It looks promising, looking forward to your PR!

**Comment by S1Y333** [comment] 2023-03-22 17:47
@wetneb I submitted the pull request here -> https://github.com/OpenRefine/OpenRefine/pull/5720 

Looking forward to the result!

**Closed** 2023-03-22 20:39 UTC
Labels: bug, good first issue, error handling
