### ISSUE TITLE
UnsupportedOperationException when using "Add entity identifiers column"

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3164] opened 2020-09-05 13:03 UTC
Testing the new Reconcile -> Add entity identifiers column is causing a JS console error and internal server error 500

### To Reproduce
1. Import existing OpenRefine project attached (SCOR-Data)
2. On Species column, choose Reconcile -> Add entity identifiers column and type in a new column name and click OK.
3. Notice that yellow banner shows and mentions `cell.recon.match.id` as the expression used and that a column is indeed created, but what seems to be with the original value name instead of a Q id.
4. Behind the scenes a JS console error appears.

### Current Results
JS Console error:
```
XML Parsing Error: not well-formed
Location: http://127.0.0.1:3333/command/core/add-column?baseColumnName=Species&newColumnName=new2&columnInsertIndex=1&onError=set-to-blank&project=2587479226146
Line Number 1, Column 1:
add-column:1:1
```

add-column source debugger:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 INTERNAL_SERVER_ERROR</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /command/core/add-column. Reason:
<pre>    INTERNAL_SERVER_ERROR</pre></p><h3>Caused by:</h3><pre>java.lang.UnsupportedOperationException
	at com.google.refine.commands.Command.doGet(Command.java:89)
	at com.google.refine.RefineServlet.service(RefineServlet.java:180)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>    
```

### Expected Behavior
1. New feature "Add entity identifiers column" should add the Wikidata Q id's into the new column instead of original values from Species column and hiding an severe internal error!
2. No new column should be created on this operation or any others if there is an internal error.  This was the part that really confused me and did not make sense that an operation still completed, and the wrong one, and despite having an internal error. Something also seems buggy deeper with default error handling somewhere.

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: openrefine-win-3.4-beta-534-g4fbd84a

### Datasets
[SCOR-Data.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/5178086/SCOR-Data.openrefine.tar.gz)

### Additional context
New Feature was merged in here, but maybe not tested? or tested well? https://github.com/OpenRefine/OpenRefine/pull/2378
Wow, even more puzzling is that @wetneb asked that the onError handling be changed to "set-to-blank", but what feels like is happening is actually "keep-original" ->  https://github.com/OpenRefine/OpenRefine/pull/2378/commits/6484f085b4e60b384f4ddcd825565e40ffb88f60

**Comment by TheTrailblazer09** [comment] 2022-04-05 01:29
Please assign me to this

**Comment by antoine2711** [comment] 2022-04-05 01:38
@TheTrailblazer09: it's yours.

Please note that it is still `To Be Reviewed`, and as such, it is not totally confirmed.

Regards, Antoine

**Comment by wetneb** [comment] 2022-04-26 12:04
This was probably caused by a missing `./refine build` before `./refine`, so I would suggest to just close it.

**Closed by wetneb** 2022-04-26 12:04 UTC
Labels: bug, error handling
