### ISSUE TITLE
value.toTitlecase() does not properly title case after special character

### ISSUE THREAD

**Issue by alanyee** [OpenRefine/OpenRefine#5894] opened 2023-06-04 02:48 UTC
### To Reproduce
1. First, have data that contains words with special characters that are not properly title cased like `O'hare`
2. Then, run the common transform on that data e.g. `To titlecase` or run this GREL transform `value.toTitlecase()`

### Current Results
The alphabetic character after the special character stays uncapitalized.
![image](https://github.com/OpenRefine/OpenRefine/assets/1873994/30f78baa-0477-4d7c-8712-ba0d4f34d6ac)

### Expected Behavior
The alphabetic character after the special character should be capitalized.

### Screenshots
The Python's built-in [title](https://docs.python.org/3/library/stdtypes.html#str.title) works as intended:
![image](https://github.com/OpenRefine/OpenRefine/assets/1873994/01d9f81d-adcf-4433-9ac7-9c4f54f6c1de)

Also these websites demonstrate a properly working title case:
https://capitalizemytitle.com/
![image](https://github.com/OpenRefine/OpenRefine/assets/1873994/ab010d3c-95d0-4f5d-972e-2d23c28f2be4)

https://titlecaseconverter.com/
![image](https://github.com/OpenRefine/OpenRefine/assets/1873994/6404c5aa-60a6-4de2-9e07-ab6d95eed3d0)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox 113.0.2
 - JRE or JDK Version: 11.0.18
 - OpenRefine: OpenRefine 3.7.2 (including Java)

**Comment by thadguidry** [comment] 2023-06-04 05:20
Hi @alanyee First of all, thanks for this issue and discussion!

There are many options to casing and capitalization across numerous human languages, as well as domains in [Science](https://en.wikipedia.org/wiki/Letter_case#Unit_symbols_and_prefixes_in_the_metric_system), Engineering, Math, Business.  Our current `toTitlecase()` specifically does not handle a few rules but also has others that you might see in other programming languages, like Python's `title()` as a quick example that uses different word boundary rules.  Anyways, this was intended since OpenRefine was designed to handle a wide range of cases but leaving those best to be handled with additional controls and functions available to users through GREL rather than making assumptions for the user on a form of title casing.  We've kept the implementation lean and lazy intentionally and not too eager.  I think keeping `toTitlecase()` as it is with its current implementation has brought a nice balance for users.  This is because oftentimes we had seen in the past when non-alphabetic characters show up in cells or substructures of cells, that this often is the result of the original source data having data partitions, or record formats, or other special structures.  And users would best know how to handle this rather than an algorithm (like the current `toTitlecase()` guessing across a rule set that might not actually apply well to the use case.  OpenRefine, as a power tool for working with messy data, as well as structured data that might be within a single cell, then gives you other GREL functions (and Jython!) to easily handle casing rules or capitalization as you would like.

Having said all that, we have in the past talked about adding a few additional options to control `toTitlecase()` more and these would be passed into it as additional parameters.  We would have to be careful with `toTitlecase()` for fear of breaking others repeated workflows.  But I am not against adding a few more parameters to `toTitlecase()` such as `WordCaps (boolean - true/false) - will attempt to always capitalize using unicode word boundaries`

@tfmorris do you also have anything to add?  I know you also have some gut feelings about this from the past on the previous mailing list and issues.

**Comment by ostephens** [comment] 2023-06-05 09:14
It doesn't seem to be documented but you can give toTitlecase() a list of text values to be used as separators. E.g.:

`value.toTitlecase(" '")`

should capitalise letters appearing after spaces and after an apostrophe.

But of course - it's so much more complicated than that to do actual title casing (because you don't want `o'hare's example` to become `O'Hare'S Example`. Because of these complications I'm not sure it is fair to say you can "easily handle casing rules or capitalization as you would like." using GREL or Python. Rules for title casing or sentence casing are complex and vary depending on language and style (as @thadguidry says).

However- it looks like both of the services mentioned above support API calls (although there are charges associated once you go over 100 requests) and it's possible the desired outcome could be achieved by doing an API look up (e.g. using Add column by fetching URLs) 

I think a more sophisticated toTitlecase either built in, or via an extension, would probably be welcomed by users, but I think it would have to do quite a bit more than just extend the current implementation which is just https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/WordUtils.html#capitalizeFully(java.lang.String) surfaced in GREL

**Comment by tfmorris** [comment] 2023-11-07 22:19
I think this is mostly a duplicate of #2483

**Comment by thadguidry** [comment] 2024-06-23 01:18
Fixed docs for missing `toTitlecase()` delimiter argument in https://github.com/OpenRefine/openrefine.org/pull/352

**Closed** 2024-06-23 01:20 UTC
Labels: Type: Bug, grel

**Comment by tfmorris** [comment] 2024-06-23 01:54
Thanks for the doc fix.

For the record, the ability to customize delimiters was added to close #447 and released in Google Refine 2.5.
