### ISSUE TITLE
OR on Mac cannot save data as XLSX or ODS

### ISSUE THREAD

**Issue by wrogner** [OpenRefine/OpenRefine#2439] opened 2020-03-19 14:51 UTC
**Describe the bug**
OpenRefine can load data by creating a new project. However, this data cannot be saved (exported) as XLSX or ODS (both apps installed - just in case it might be a library cause).

**To Reproduce**
macOS 10.15.3
Install OR (either from download or from brew)
Create a project, load data
Export data (creates a tar file)
Export as XLSX (does not finish - no file dialog)
Export as ODS (does not finish - no file dialog)

**Current Results**
Can't save projects in application format

**Expected behavior**
Save and load projects in application formats

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Version: Firefox 74.0
 - JRE or JDK Version:
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.3 (1) (homebrew), OpenRefine 3.3 (download)

**Datasets**
any

**Additional context**

**Comment by wetneb** [comment] 2020-03-19 15:07
> However, this data cannot be saved (exported) as XLSX or ODS (both apps installed - just in case it might be a library cause)

Can you give us a precise description of what happens concretely when you try to export a project to XLSX or ODS?

**Comment by thadguidry** [comment] 2020-03-19 17:57
They said they don't get a file dialog popping up.  On Firefox, there should be a file download dialog that shows.  If this is not happening, then I think perhaps there might be a POI exception happening that's not getting caught?

@wrogner can you look into the console and see if any Java stack traces appear in the log with an error when you attempt to export as an XLSX file?  For me, on Windows, when I export as XLSX, Firefox will open a new browser tab and then popup a Opening xxxx.xlsx ... dialog which allows me to toggle between "Open with" or "Save File" as shown:
![image](https://user-images.githubusercontent.com/986438/77098905-1a6b0200-69e1-11ea-8d6a-d4b944f69414.png)

**Comment by wrogner** [comment] 2020-03-20 07:36
a) the Browser console stays empty (no errors reported)
b) Project creation does not work (I would have to export the project in order to create a project - if saving fails, I have to restart)

c) I have removed OpenRefine as it does not work and lacks functionality of joining data or manipulating it effectively

**Comment by wetneb** [comment] 2020-03-20 08:27
> c) I have removed OpenRefine as it does not work and lacks functionality of joining data or manipulating it effectively

Thank you for your report :) I am going to close this as non reproducible, feel free to reopen if you can give us more information.

**Comment by wrogner** [comment] 2020-03-20 09:48
It's up to you to close this but it is reproducable on several Macs with different macOS.

It just does not produce any usable outcome on the console.

**Comment by wetneb** [comment] 2020-03-20 10:05
Sure, I don't expect useful information to be in the browser console.
What would be massively useful if you could share the server logs:
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac
But I assumed that was not possible since you had already uninstalled OpenRefine, hence the closure.

**Comment by antoine2711** [comment] 2020-03-21 22:10
> It's up to you to close this but it is reproducable on several Macs with different macOS.
> 
> It just does not produce any usable outcome on the console.

Hi. I'm a Mac user (since ever), and I tried on my Mac (X.14.6, MacMini 2018), and I was able to Export: ODS, XSL, XSLX. I'm using Chrome.

Are you having this problem on all of your Macs? Have you tried Safari and/or Chrome?

Regards, Antoine

**Comment by wrogner** [comment] 2020-03-21 22:53
Should the browser make a difference?
I have this issue on any Mac with 10.15.3 and Firefox and Safari.
I admin, I haven't tried Chrome.

**Comment by antoine2711** [comment] 2020-03-22 01:21
Actually, the browser is the #1 variable with the most impacts on the problems or OpenRefine.

On my side, and I understand it won't help you much, but Safari, Firefox v74 and Chrome are able to export in .ODS, .XLS, .XLSX.

Your issue doesn't seam to be an easy one…

**Comment by thadguidry** [comment] 2020-06-26 12:28
Closing since @antoine2711 and other users I've talked to, do not have this issue on their Mac.  We can reopen once we have more information.

**Closed by thadguidry** 2020-06-26 12:28 UTC
Labels: ODS, XLS(X), bug, export, not reproducible
