### ISSUE TITLE
Support drag and drop when creating a project from local files

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6250] opened 2023-12-18 11:30 UTC
In the project creation screen, the user needs to click the "Browse" button to select files from their computer. Dragging and dropping a file there does not work.

### Proposed solution

Add support for dragging and dropping a file, as an alternative to clicking the "Browse" button. The drag and drop could be enabled for a reasonably wide rectangular area around the button (likely an existing `<div>` element). For instance, the area circled in red in this screenshot could be a candidate:

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/92a3eb25-5760-428f-8c1a-70c8e4dd0860)

On top of this, the "Next" button is perhaps redundant: one could go to the next stage as soon as a file has been selected / dropped.

### Alternatives considered

We could also make it visually explicit that drag and drop is supported. Perhaps @cooperzoe has suggestions?

### Additional context

Brought up during @cooperzoe's onboarding with the tool.

**Comment by tfmorris** [comment] 2023-12-18 19:15
I like the idea of drag and drop. I would suggest:
* definitely using some type of affordance to make the availability of the feature obvious to the user (example below)
* *not* automatically advancing the dialog on drop (both because it's unexpected behavior and it prevents the user from adding more files or removing an accidentally dropped one)
* supporting drag and drop of URLs as well, if technically feasible, or alternatively including a text input field like the design below

![Screen Shot 2023-12-18 at 2 06 31 PM](https://github.com/OpenRefine/OpenRefine/assets/82178/bec30633-2494-4332-97a6-b88a11250217)

**Comment by cooperzoe** [comment] 2023-12-26 10:07
I like Tom's suggestions! I thought I'd propose another sketch idea for how it could work, to make it as easy to use/understand as possible:
<img width="652" alt="Screenshot 2023-12-26 at 11 06 37 AM" src="https://github.com/OpenRefine/OpenRefine/assets/52141007/0b08258a-be04-415c-a44d-4407aec2748c">

**Comment by wetneb** [comment] 2023-12-26 14:46
Nice! It would be good to see the suggestions in context (within OpenRefine's start page, with a consistent style).
Note that for now, importing from a URL is done in a separate screen, where multiple URLs can be entered. If we want to merge those screens together, it might be good to think about a way to add more URLs too.

**Comment by cooperzoe** [comment] 2024-01-01 19:24
Here's one idea.

Note to @wetneb : I know the button sizing is a bit off - I have a few questions about the design system and will ask when we speak soon.
![Screenshot 2024-01-01 at 8 23 15 PM](https://github.com/OpenRefine/OpenRefine/assets/52141007/4a804ef2-0667-4fed-8ab2-5226db7e2233)

**Comment by Abbe98** [comment] 2024-01-03 14:49
You should be able to drag and drop files on to the button in the current state as it's a native feature of file inputs.

The drop area (pictured below) is rather small, but it should be easy to address without introducing additional divs or JavaScript handling.

![Screenshot from 2024-01-03 15-47-01](https://github.com/OpenRefine/OpenRefine/assets/2631719/9ccf7eb7-1a13-4bf2-b428-58af2a631ec0)

**Comment by cooperzoe** [comment] 2024-01-04 12:37
@wetneb Yes, those two changes are the two I intended to propose!

**Comment by thadguidry** [comment] 2024-01-04 12:40
Tidbit:  Can we avoid the term "upload" there?  It makes it seem like the selected file is going up to a cloud service rather than copied locally to the OpenRefine server on the user's computer.

**Comment by tfmorris** [comment] 2024-01-04 23:23
That's cool that drag-n-drop is supported out of the box! I agree with @Abbe98 that making the drop zone bigger would be useful.

I'm not sure sure whether the introductory text is supposed to cover all the options in column 2 (since it mentions Google Data) or is specific to just the file upload case. If it's intended to be general, I think it should span the right two columns rather than just being in the file upload panel.

I'm a little concerned about the intro text getting unwieldy if it's made comprehensive. Some of the data sources which are supported but not mentioned include OpenDocument Spreadsheet, MARCXML, fixed format, RDF NT, JSON-LD, Wikitext, Zip & tar archives of any of the above, gzip & bzip2 compressed versions of any of the above, multiples of any of the above, a few SQL databases, and probably other stuff that I'm forgetting.

The additional guidance is nice, but there's also something to be said for the simplicity of "Try whatever you like and it'll probably work, but let us know if it doesn't."

**Comment by thadguidry** [comment] 2024-01-05 01:12
I'd get rid of the introductory text.  That sorta text could then appropriately move into a guide that appears every time **Create Project** is used, until it's dismissed by user.  We really want to move into dismiss-able guide texts throughout to increase both the page areas available for other components and extensions, and the translations.

**Comment by wetneb** [comment] 2024-03-10 12:31
I have checked that drag and drop is indeed already supported when we aim for the "Browse" button already.
Marking this as a good first issue, where the task should be to just make the area which accepts dropping files larger.
If this can be done without additional JS as suggested by @Abbe98 then that's great, but it's not clear to me how. Perhaps making the larger drop area into a `<label>` for the input might work?

**Comment by Abbe98** [comment] 2024-03-10 17:20
Complete nonsense demo of what can be done without changing the HTML:

`<input type="file" multiple="" bind="fileInput" name="upload" style="width: 400px;height: 200px;background: var(--fill-primary);border: 1px solid var(--dialog-border);line-height: 15;padding: 5px;border-radius: 5px;">`

Result:

![Screenshot 2024-03-10 at 18-19-41 OpenRefine](https://github.com/OpenRefine/OpenRefine/assets/2631719/900510f9-5d8c-4196-a577-f8ed7f6993ca)

**Comment by Ahmed-Elgamel** [comment] 2024-03-11 12:16
Hi @wetneb ,can you assign this to me? If I am understanding correctly I need to add new text beneath the browse button saying "or drag and drop files anywhere on this page". So I am required to make the whole page accept dragging and dropping of files not just adding a rectangular box beside the new text.

**Comment by Ahmed-Elgamel** [comment] 2024-03-11 14:51
I made another fileInput same as the old one but styled it to be a big box, but I can not find a way to remove the button displayed inside the box.The drawing and dropping works because by default the adding of files support it as mentioned earlier.How can I remove this button ?

<img width="997" alt="Screenshot 2024-03-11 at 4 45 36 PM" src="https://github.com/OpenRefine/OpenRefine/assets/116679740/3a96ffc4-e1ea-4fbb-90a0-6e0078c44344">

**Closed** 2024-03-29 09:54 UTC
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue
