### ISSUE TITLE
possible bug in the levenstein clustering algorithm?

### ISSUE THREAD

**Issue by plopenrefine** [OpenRefine/OpenRefine#3397] opened 2020-12-09 12:42 UTC
I am using the nearest neighbor method, levenstein, with radius 3.0 and block chars 6.

What i do not understand is why for example Unipress and Seepresse are in the same group, since they seem to differ in four edits

remove Uni, replace with See, and add an e in the and of the string.

What am I missing?

Unipress
Seepresse
UNIPRESS.
Edipresse
Légipresse
Mediapresse
Mediapresse.
Socpresse
UNIPRESS
UNIPRESS,
UniPress
I managed to reproduce this, using the latest stable version

**Comment by thadguidry** [comment] 2020-12-09 13:48
Hi @plopenrefine You can reduce your block chars to increase the granularity of substring search.

You probably didn't realize this, but we already have some very useful information for you regarding Clustering already.
See https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth#nearest-neighbor-methods

Yes, you will always be able to reproduce, because it's an algorithm that doesn't change in code and where you have 2 parameters that you can control in order to help speed up or slow down the substring searching in the Nearest Neighbor methods we provide, but you might miss some potential pairs either way, so it's best to experiment with the blocking size even down to just 1 if you want to get extremely granular in your pairing.

I'll close this for now, and after reading that wiki page, let us know if there is anything unclear still in the documentation there and we can improve it.  Feel free to just add more comments to this closed issue if that is the case.

**Closed by thadguidry** 2020-12-09 13:48 UTC
Labels: bug, to be reviewed

**Comment by tfmorris** [comment] 2020-12-09 18:46
Sorry I led you astray. This is working as designed. As @ostephens mentioned on the mailing list, the edit distance is measured from a single candidate, "Edipresse" in this case, and all other candidates are within an edit distance of 3 from it. This means that it's possible, as in this case, that any pair of candidates could have an edit distance greater than the limit.
