### ISSUE TITLE
beta: deleting single cell contents and pressing enter repopulates textbox

### ISSUE THREAD

**Issue by pmusser** [OpenRefine/OpenRefine#6406] opened 2024-02-29 21:56 UTC
The input box repopulates with cell's previous data after using the "edit" button to delete contents and then press enter to commit.

### To Reproduce
1. First, open a project and click "edit" on a cell that has text contents.
2. Then, delete the contents of the cell.
3. Finally, press enter to commit the changes to the cell

### Current Results
The cell contents are deleted, but the "edit" box immediately reappears with the cell's previous contents populating it. Pressing "escape" or clicking "cancel" will close the "edit" input box without re-entering the cell's content.

### Expected Behavior
Optimal: The cell's contents are deleted and the edit box closes.
Also acceptable: The cell's contents are deleted and the edit box remains open.

### Versions
 - Operating System: Windows 11 Pro 23H2, build 22631.3155
 - Browser Version: Version 122.0.6261.71 (Official Build) (64-bit)
 - JRE or JDK Version: 
 - OpenRefine: Version 3.8-beta1 [7fd4077]

### Datasets
 Contact me for a small sample set, but otherwise I have tried it with multiple projects and the issue is present for each

**Comment by wetneb** [comment] 2024-03-10 11:55
I can reproduce this (with Firefox on Linux). Note that the bug only happens when I press "Enter" (as mentioned above), not when I click the "Apply" button. Marking as a good first issue because it should be easy to reproduce and debug.

**Comment by WR-Smiley** [comment] 2024-03-12 14:43
Wanted to play around with this a little before volunteering to handle it to make sure it was something I could potentially figure out. I got absorbed and (I think) I found the underlying issue. When clicking on editLink, _focusBeforeEdit is set to the editLink button. It appears that when "Enter" is used to submit an edit, it both submits the edit _and_ triggers another instance of editLink with the old value simultaneously, due to the button's default submit behavior. 

Being quite new I am not very familiar with the code base, but the only fix I've found to work is to remove ```self._focusBeforeEdit.focus()``` from the commit function. This allows the editor to close when pressing "Enter". I tried myriad other solutions, such as incorporating a ```dismissAll()``` into the "apply" triggers and disabling editLink's default behavior, but none of them achieved the expected behavior. 

From what I can tell the only effect of editing commit is that it does not put the focus back onto editLink after applying the changes and instead defaults to having no focus on any specific page element. No functionality seems to be impacted.

Please let me know if this solution would pose any problems for something that I'm not realizing or if you think there is a better solution. If you think it is an acceptable fix please let me know and I'll send in a PR.

**Comment by wetneb** [comment] 2024-03-12 14:53
Thanks a lot for this very thorough investigation!

> From what I can tell the only effect of editing commit is that it does not put the focus back onto editLink after applying the changes and instead defaults to having no focus on any specific page element. No functionality seems to be impacted.

@Abbe98 might have more thoughts about the desired behavior of the focus, but that seems like a very reasonable effect to fix such a bug. I'd be keen to merge that.

**Comment by WR-Smiley** [comment] 2024-03-12 15:06
Great, thanks for the quick reply!

> @Abbe98 might have more thoughts about the desired behavior of the focus, but that seems like a very reasonable effect to fix such a bug. I'd be keen to merge that.

I'll wait to see if any other feedback comes in on focus behavior; if not, I'll send in the PR later this evening.

**Comment by wetneb** [comment] 2024-03-12 16:10
> There conflict when enter is pressed which should be fixed with a conditional check.

Could you expand a little? Where and what sort of conditional check?

**Comment by WR-Smiley** [comment] 2024-03-12 18:36
Seconded request for more info. I've tried a _lot_ of conditionals with a lot of different parameters and none have worked, so advice on what exactly to base it on would be very helpful. Generally, I'm finding that any conditional hooked to the editLink or literally any of the objects/methods related to it only resolves the first prompt and never affects the second prompt; altering the focus in some way is the only thing that's worked so far.

**Comment by thadguidry** [comment] 2024-03-12 22:49
The ideal solution should move focus back to the original cell, not the edit link of the cell. This allows keyboard navigation to the next cell to be edited more easily.

**Comment by WR-Smiley** [comment] 2024-03-12 23:00
I think I have found a solution following @Abbe98's suggestion of using a conditional check. I've added a new variable "enterPressed" to cell-ui.js. Upon using "Enter" to commit when the textarea is open, enterPressed = true. In the editLink 'click' eventListener, I have added a conditional check for enterPressed. If false, it runs as usual. If true, it sets enterPressed to false and dismisses all windows. This retains the existing focus mechanics and doesn't screw up the functionality.

Does this seem like a reasonable solution?

**Comment by wetneb** [comment] 2024-03-13 06:56
I am generally reluctant to introduce a bit of state to solve this sort of issues, but if that's the only option, we should definitely go for it! That being said I agree with @thadguidry on the desired focus behaviour. It's unlikely someone would want to edit the same cell twice in a row.

**Comment by Abbe98** [comment] 2024-03-13 07:39
Turn's out we solved this on our end a while back by moving the focus/dismiss logic into the a callback passed to the `commit` function. Maybe on OpenRefine's end it's enough to to move the two lines into the `ondone` section?

> The ideal solution should move focus back to the original cell, not the edit link of the cell. This more easily allows keyboard navigation to the next cell to be edited.

Cells them self's aren't focus-able so it would be rather weird for most users to have an in-between state like that. That said interactive cells would be nice but it's probably a much bigger task.

**Comment by Abbe98** [comment] 2024-03-13 07:41
Yeah moving the following into the `onDone` seems to do the trick on `master`:

```
self._focusBeforeEdit.focus();
MenuSystem.dismissAll();
```

**Comment by WR-Smiley** [comment] 2024-03-13 13:22
Oh awesome, thank you for letting us know! I agree that having focus go to the cells doesn't make sense as it stands but directly interactive cells would be a nice feature in the future.

@wetneb do we want to keep the focus behavior as is for now and implement @Abbe98's specified solution?

**Comment by wetneb** [comment] 2024-03-13 13:30
Sounds good to me!

**Closed** 2024-03-14 13:40 UTC
Labels: Type: Bug, Theme: UX/Usability, Good First Issue
