### ISSUE TITLE
Project creation using JSON fails

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2542] opened 2020-04-13 04:55 UTC
**Describe the bug**

Project creation using JSON always gives `Please specify record path first`

**To Reproduce**
1. Go to 'Create Project and Click on clipboard'
2. Paste this data 
```json
[
    {
        key1: value1,
        key2: value2
    }
]
```
3. Select `Parse Data as JSON Files`
4. Click on Create Project & see error

**Expected behavior**

Create Project should work smoothely.

**Screenshots**

<img width="1205" alt="Screenshot 2020-04-13 at 10 22 31 AM" src="https://user-images.githubusercontent.com/44091822/79093089-c26db400-7d70-11ea-9481-13429df18352.png">

**Additional context**

When I click on `Update Preview` and then click on `Create Project` it works smoothly. But it alwasy gives this error when I try to create JSON Project. 
Also there is dummy button with label `Please specify a record path first` and clicking on it makes no change.

<img width="568" alt="Screenshot 2020-04-13 at 10 24 45 AM" src="https://user-images.githubusercontent.com/44091822/79093168-09f44000-7d71-11ea-9395-9693191bc1b8.png">

**Comment by wetneb** [comment] 2020-04-13 07:17
As GitHub's syntax highlighting suggests, your JSON payload is invalid.

**Comment by kushthedude** [comment] 2020-04-13 07:23
@wetneb  The same error occurs on this dataset too!
```json
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
```

**Comment by wetneb** [comment] 2020-04-13 07:25
Not for me, I can import this without a problem.

**Comment by kushthedude** [comment] 2020-04-13 08:23
@wetneb Please see this Screen Recording for the bug 
https://drive.google.com/file/d/1NzWsR5Oz9Qg9GclK0nPWCMVm3FzR8dst/view?usp=sharing

**Comment by thadguidry** [comment] 2020-04-13 13:27
@kushthedude You have to use your mouse to hover around over "some" part of the JSON that you wish OpenRefine to try to treat as a Record.  In your screen recording, something like the `GlossEntry` would probably be useful, especially if you had many `GlossEntry` nodes inside the `GlossList`.

So that part is not a bug.

However, we COULD create a new issue to validate the JSON during preview and warn the user when it is invalid. (although huge JSON files might be a slight problem to check for complete validity, but still)

**Comment by tfmorris** [comment] 2020-06-20 16:43
Closing because this is based on a misunderstanding of how the JSON importer works.

**Closed by tfmorris** 2020-06-20 16:43 UTC
Labels: JSON, bug, import, invalid
