### ISSUE TITLE
Unable to create a SQL export for a project creating numeric data if I mark the column as numeric

### ISSUE THREAD

**Issue by nickcotter** [OpenRefine/OpenRefine#1684] opened 2018-07-18 14:26 UTC
**Describe the bug**
I am unable to create a SQL export for a project creating numeric data if I mark the column as numeric.

**To Reproduce**
1. Set up a project containing at least one numeric column
2. Choose Export->SQL Exporter...
3. Change the type to NUMERIC
4. Click preview (or Download)

**Current Results**
I am shown an error page with status 400 and a message of the form:

````
    12.865 is not compatible with column type :NUMERIC
````

**Expected behavior**
I expect the SQL statment to be constructed for numeric values, eg unquoted.

If I do not mark the column as NUMERIC then the export proceeds, but the values are quoted ("12.865"). I have tried converting the columns via value.toNumber() and Common Transformations, and they are coloured green.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 67.0.3396.99

**OpenRefine (please complete the following information):**
 - OpenRefine 3.0 Beta

**Datasets**
[Charges.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/2206130/Charges.openrefine.tar.gz)

**Additional context**
In my project a number of rows have been "filled down" after splitting on certain columns.

There is a stack trace as well:

````
15:21:42.574 [        ExportRowsCommand] error:12.865 is not compatible with column type :NUMERIC (0ms)
15:21:42.574 [          org.mortbay.log] /command/core/export-rows/Charges.sql (0ms) com.google.refine.exporters.sql.SqlExporterException: 12.865 is not compatible with column type :NUMERIC
        at com.google.refine.exporters.sql.SqlInsertBuilder.getInsertSQL(SqlInsertBuilder.java:138)
        at com.google.refine.exporters.sql.SqlExporter$1.endFile(SqlExporter.java:122)
        at com.google.refine.exporters.CustomizableTabularExporterUtilities$1.end(CustomizableTabularExporterUilities.java:166)
        at com.google.refine.browsing.util.ConjunctiveFilteredRows.accept(ConjunctiveFilteredRows.java:71)
        at com.google.refine.exporters.CustomizableTabularExporterUtilities.exportRows(CustomizableTabularExporterUtilities.java:171)
        at com.google.refine.exporters.sql.SqlExporter.export(SqlExporter.java:166)
        at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:109)
````

**Comment by jackyq2015** [comment] 2018-11-26 01:15
I cannot reproduce it. can you please retry it?

**Comment by jackyq2015** [comment] 2018-12-04 03:01
close it for now. Please reopen if still an issue

**Closed by jackyq2015** 2018-12-04 03:01 UTC
