### ISSUE TITLE
Wikimedia Commons Wikibase not detecting non-Latin script characters

### ISSUE THREAD

**Issue by psubhashish** [OpenRefine/OpenRefine#5656] opened 2023-03-01 01:33 UTC
I've been trying to upload a batch of files that have names containing both Latin and [Odia](https://en.wikipedia.org/wiki/Odia_script) characters. For instance, Wikimedia Commons allows filenames with Odia characters (for instance, this file](https://commons.wikimedia.org/wiki/Category:Audio_files_created_using_Kathabhidhana), but OpenRefine does not. See the screenshot of the error I see below. cc @wetneb

### To Reproduce
1. Create a file with a file name such as "ଫାଇଲ.wav" (that's a WAVE file with a filename with in the Odia script)
2. Try to upload to Wikimedia Commons using OpenRefine. It fails at the Wikibase (Upload edits to Wikibase)

### Current Results

It fails (see below)

<img width="752" alt="OpenRefine-issue-with-Odia" src="https://user-images.githubusercontent.com/1258090/222007841-b59c7218-db7a-44aa-b5cf-45b88375e354.png">

### Expected Behavior

The upload should normally happen, just like any other file.

### Versions
 - Operating System: MacOS
 - Browser Version: Brave 1.46.171
 - JRE or JDK Version: 
 - OpenRefine: 3.7

### Datasets

1. [Sample dataset containing the same files I was trying to upload](https://drive.google.com/drive/u/0/folders/1lyg_63oZCd7fIwWFvqU4v0AwKOIHK8FQ)

**Comment by thadguidry** [comment] 2023-03-01 03:54
@psubhashish Thanks for this report.  Indeed, it seems your filename technically would be allowed to be uploaded to Wikimedia Commons based on the file naming conventions detailed in the below wiki page.

@wetneb I think the regex compile pattern is too narrow in [FileNameScrutinizer.java](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java) ?
Firstly, it should not care about these things, since they are allowed and recommended:
* [graphemic](https://en.wiktionary.org/wiki/graphemic) characters, numbers, underscore (space), ASCII hyphen/minus/dash, plus, and period (dot).

And definitely, it should allow any language in any script, since that is allowed in Commons:Language policy.
https://commons.wikimedia.org/wiki/Commons:File_naming

I think just a simple "disallow" pattern is what we need there instead of an "allow" pattern? dunno.

Disallow:
* control chars
* filename lengths of greater than 240 bytes long (note: bytes not chars, so some scripts using 4 bytes per char will hit the length maximum sooner) (This is because hash based storage [isn't implemented yet](https://phabricator.wikimedia.org/T32202))
*

**Comment by trnstlntk** [comment] 2023-03-01 12:29
I've also heard other Wikimedia Commons uploaders who had trouble with files containing characters like é, à - these are allowed on Commons but OpenRefine is a bit too strict about them. I'd say we could generalize this issue to make it about supporting all Commons-allowed characters in file names.

**Comment by psubhashish** [comment] 2023-03-01 15:48
I think we're moving somewhere. Note that, some of the minoritized languages using their own writing systems are not supported on Commons, as the ranges were not defined or none reported the bugs (we did one in [2021](https://phabricator.wikimedia.org/T297351) which is yet to be resolved. Ideally Unicode ranges for such writing systems should be allowed on OpenRefine. So, when the bugs are fixed on Wiki Commons, one doesn't need to update on OpenRefine, considering the block on Commons is not a legitimate one and there is no resource for many languages to practically request for many platforms.

**Comment by satyamksharma** [comment] 2023-03-19 11:16
Hi there i would like to resolve this issue.

**Comment by santi4o** [comment] 2023-04-23 00:07
hello c:
I would like to work on this issue, could you assign it to me?

**Closed** 2023-12-09 09:05 UTC
Labels: Type: Bug, wikibase, wikicommons

**Comment by trnstlntk** [comment] 2024-04-09 19:09
I still hear from users that this issue is not resolved for them. I have put @sebastian-berlin-wmse and @lokal-profil in contact with one particular user who uploads a lot with "exotic" characters so that they can troubleshoot.

**Comment by lokal-profil** [comment] 2024-04-11 11:24
> I still hear from users that this issue is not resolved for them. I have put @sebastian-berlin-wmse and @lokal-profil in contact with one particular user who uploads a lot with "exotic" characters (Polish language) so that they can troubleshoot.

User confirmed that initial testing suggests that 3.8-beta1 fixes their issue.
