### ISSUE TITLE
Transpose > Columnize by Key/Value doesn't work in 2.6-rc.2 

### ISSUE THREAD

**Issue by libjohn** [OpenRefine/OpenRefine#1138] opened 2016-06-16 20:07 UTC
Newbie report here.  I hope it's helpful.

I _think_ I found a bug in doing a column transpose in version 2.6-rc.2.  I can accomplish the transaction in either 2.6-beta.1 or 2.5

Operating Systems and version:  does not work in 2.6-rc.2 on Windows 7 and Windows 10.  

Browser:  on Win10:  Chrome version is 51.0.2704.84
  on Win7:  Chrome version is 51.0.2704.84
                  Firefox version 29.0.1

Steps followed to create the issues
Transpose > Columnize by Key/Value Columns
    Key Column = Location
    Value Column = Category
        > OK

Current Results:  in 2.6-rc.2 I get the following error:
chrome: Index: 6, Size: 0
firefox:  Index: 6, Size: 0

Expected Results:  two columns transposed in 2.6-rc.2  as it does work in earlier versions  

If this message should go somewhere else, please advise.  

[data-and-operationHistory.zip](https://github.com/OpenRefine/OpenRefine/files/319212/data-and-operationHistory.zip)

**Comment by lmsurpre** [comment] 2016-06-20 18:38
Looks like a duplicate of #1098 which is already marked for 2.6

**Closed** 2016-11-06 18:17 UTC
Labels: PR-created
