### ISSUE TITLE
OpenRefine: cannot launch application

### ISSUE THREAD

**Issue by tentonsofhours** [OpenRefine/OpenRefine#1236] opened 2017-08-16 04:49 UTC
Hello,
I cannot launch OpenRefine, it reports the bug
![openrefine_screenshot](https://user-images.githubusercontent.com/20109912/29347689-1c046814-8257-11e7-8e3c-ed51a9aff10c.png).
My JRE is up to date, it is something with Jython, but I cannot figure out what exactly.
My OS is win8.1.
Thanks!

**Comment by wetneb** [comment] 2017-08-16 07:19
Hi @tentonsofhours!
Thanks for the report. The first lines of the stack trace are not visible in your screenshot, do you think it would be possible to have the full error?
Thanks!

**Comment by tentonsofhours** [comment] 2017-08-18 13:53
![openrefinegit](https://user-images.githubusercontent.com/20109912/29461769-9b3d58ea-8435-11e7-9cb1-a54294a3d6f7.png)
 Here the full screen shot, sorry for the wrong one previously.

**Comment by thadguidry** [comment] 2017-08-18 15:18
@tentonsofhours Your username on Windows is Ukrainian or Russian or a close cousin :) that has UTF-8 characters...so that's the reason.  We have seen this happen before with other users.  Your only choice is to create a different username in Windows using basic ASCII letters and then run OpenRefine under that user.  Sorry, but this is not a OpenRefine issue but more of a system / Jython issue that will be fixed by the Jython team in the near future.  Let us know how things go, so that we can close this issue once you have it fixed.

**Comment by wetneb** [comment] 2017-08-18 15:58
@thadguidry great that you could find the cause just by looking at the logs! Can we track the status of this issue anywhere in Jython? We should not forget to update the .jar we ship with OpenRefine once they have released a version that fixes this bug.

**Comment by thadguidry** [comment] 2017-08-21 13:57
@wetneb I had been tracking it.  The original bug is here http://bugs.jython.org/issue2331 and was fixed here https://github.com/jythontools/jython/commit/c61eaefb774cdb174472265d3c27fc5b87febd34

Jython 2.7.1 has just been released last month (also the reason why I asked if we could release a OpenRefine 2.7.1 - but we are not tied directly to Jython version, its just a coincidence) http://fwierzbicki.blogspot.com/2017/07/jython-271-final-released.html

I had asked Jacky to just build Jython 2.7.1 SNAPSHOT and then include it...but didn't happen.
If you want you can pull into our master branch that standalone jar now and update our dependencies, etc.   We can then cut a OpenRefine 2.7.1 release which I would like you to handle to get experience with it.

**Comment by wetneb** [comment] 2017-08-26 09:33
Hi @tentonsofhours, the bug should be fixed in the development version of OpenRefine.
It would be great if you could try to install this new version (see https://github.com/OpenRefine/OpenRefine/wiki/Get-Development-Version ) and confirm that it solves your issue.

**Comment by jackyq2015** [comment] 2017-11-10 18:07
will be release at 2.7.2 soon

**Closed by jackyq2015** 2017-11-10 18:07 UTC
Labels: bug, priority-Low
