### ISSUE TITLE
Warning for missing unit when making schema to Wikidata

### ISSUE THREAD

**Issue by Ainali** [OpenRefine/OpenRefine#5452] opened 2022-11-18 17:26 UTC
### To Reproduce
1. Have a dataset ready to upload to Wikidata
2. Make a schema for a quantity property, but where Wikidata does not expect units, for example students count (P2196)

This video shows this error (link is time stamped to when I discover it): https://youtu.be/oSXxraHgbLs?t=1594

### Current Results

Under issues a warning like this is issued:
> **Units missing for students count (P2196)**
> Values such as `whatever number you had` on [Wikidata item] are expected to have units.

### Expected Behavior

No warning should be given.

### Screenshots

![Skärmbild från 2022-11-18 18-20-40](https://user-images.githubusercontent.com/5566159/202764259-f705c91f-5422-4184-9e96-c172601c2838.png)

### Versions
This was in Chrome Version 107.0.5304.87 on Ubuntu 22.04 using OpenRefine in Wikimedia PAWS, 28 October, 2022.

### Datasets

[Studenter-universitet.csv](https://github.com/OpenRefine/OpenRefine/files/10043481/Studenter-universitet.csv)

**Comment by pushpanjali-10** [comment] 2023-03-19 06:43
Can you assign to me ?

**Comment by pushpanjali-10** [comment] 2023-03-19 10:49
Hey, I am new to this and I have a doubt what we should add in "unit" ?

**Comment by wetneb** [comment] 2023-03-19 11:18
A reconciled column containing the units, or typing a unit yourself and selecting a value from Wikidata.

**Comment by pushpanjali-10** [comment] 2023-03-20 15:23
I am facing a little difficulty. Could you guide me on how I can remove the warning?

**Comment by S1Y333** [comment] 2023-03-22 18:26
Hi @wetneb, can I try this one too? Can you please assign this to me? Thank you!

**Comment by wetneb** [comment] 2023-03-22 20:24
@pushpanjali-10 I can help you if you could ask more precise questions. Can you tell us at which of [those steps](https://openrefine.org/docs/technical-reference/contributing#your-first-code-pull-request) you are stuck? What have you tried so far?

@S1Y333 since @pushpanjali-10 is working on this, maybe not?

**Comment by S1Y333** [comment] 2023-03-22 20:34
> @pushpanjali-10 I can help you if you could ask more precise questions. Can you tell us at which of [those steps](https://openrefine.org/docs/technical-reference/contributing#your-first-code-pull-request) you are stuck? What have you tried so far?
> 
> @S1Y333 since @pushpanjali-10 is working on this, maybe not?

ok, no problem.

**Comment by pushpanjali-10** [comment] 2023-03-23 06:47
I am trying to solve the issue but I am new to this, so I am enable to understand the part unit. As I am putting any unit, it shows me error that it is invalid unit(for null too). Can  you guide me steps to move forward or learn from?
![image](https://user-images.githubusercontent.com/78951127/227124806-bc19b2ad-ca62-4a5a-8c1f-8d6e292e7dc0.png)

**Comment by pushpanjali-10** [comment] 2023-03-23 06:50
Adding to the above information, I am using : `value.replace(/[^0-9]/,'')` in cell.

**Comment by wetneb** [comment] 2023-03-23 07:13
I would suggest that you first ignore the issues tab and try uploading statements with and without units.

Have you tried entering a unit in the box, such as "meter", and selecting a suggested item in the drop-down list below? I think that should let you generate a test edit (that you could also try uploading to Wikidata, by editing the Wikidata Sandbox item for instance).
Then, you could also try uploading a statement without any unit (just leaving the "unit" field empty, without even putting your cursor in it).

You could then check how the results look on Wikidata. The statement with a unit should generate a warning (because "student count" should not actually have a unit) and the statement without one should not generate that warning.
The goal is that OpenRefine behaves in the same way: it should show a warning in the "issues" tab if the statement has a unit, and no warning if the statement does not have any unit. This will likely require you to make some code changes to OpenRefine. To do this, please follow this guide:
https://openrefine.org/docs/technical-reference/contributing#your-first-code-pull-request

**Comment by wetneb** [comment] 2023-03-23 08:20
@pushpanjali-10 please do not make test edits on normal Wikidata items, such as your edits here:
https://editgroups.toolforge.org/b/OR/f0058617460/

I also noticed that those were your first Wikidata edits so far. I have to say it is probably very difficult to make a contribution on this issue without being first familiar with Wikidata, since this issue is about Wikidata integration in OpenRefine.
With this in mind, I think it might be better for you not to work on this issue, since it requires too much background knowledge.

**Comment by wetneb** [comment] 2023-03-23 12:21
@S1Y333 are you still interested in working on this?

**Comment by S1Y333** [comment] 2023-03-23 13:53
> @S1Y333 are you still interested in working on this?

Yes, if possible

**Comment by S1Y333** [comment] 2023-04-11 02:20
Hi @wetneb, is this problem solved? When I am reproducing the error, it didn't show this error:
<img width="841" alt="Screen Shot 2023-04-10 at 10 17 11 PM" src="https://user-images.githubusercontent.com/105386341/231038648-8785ca12-b146-45df-a972-766c3df5a4a1.png">

**Comment by payalsaraljain** [comment] 2024-01-30 18:40
Hi I am interested in checking out this issue, is it still open?

**Comment by wetneb** [comment] 2024-01-30 19:26
Yes it is, go ahead!

**Comment by payalsaraljain** [comment] 2024-01-31 16:46
Thanks, will start looking into it

**Comment by payalsaraljain** [comment] 2024-02-03 10:04
Quick Question, the different types of statement options provided in the drop down something which open refine is getting from wikibase?

**Comment by wetneb** [comment] 2024-02-04 12:17
The statement options are something that's defined on OpenRefine's side. It configures how OpenRefine compares the data to be uploaded to the data that is currently on Wikidata, so as not to introduce redundant statements. It is documented here: https://openrefine.org/docs/manual/wikibase/schema-alignment#editing-mode

Let me know if you have any other question feel free to ask me directly (for instance on our Gitter channel: https://app.gitter.im/#/room/#OpenRefine_OpenRefine:gitter.im)

**Comment by payalsaraljain** [comment] 2024-02-05 18:05
Sure thanks, I understood

**Comment by payalsaraljain** [comment] 2024-02-11 14:45
Hi, can u please tell to run OpenRefine 3.8-SNAPSHOT which version of Java it is compatible with since when I am trying to run it is loading Open refine only with its logo and nothing else
I am currently running it with Java 14

**Comment by wetneb** [comment] 2024-02-11 18:11
@payalsaraljain let's move support questions like this one to either the [Forum](https://forum.openrefine.org) or [Gitter (Matrix)](https://gitter.im/OpenRefine/OpenRefine) so that we can keep the discussion here focused on the issue itself :) We can try debugging your problem there. Thank you!

**Comment by payalsaraljain** [comment] 2024-02-11 18:33
Sure

**Closed** 2024-02-14 20:59 UTC
Labels: Type: Bug, Good First Issue, wikibase
