### ISSUE TITLE
QuickStatements button not working when schema has not been opened yet

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1700] opened 2018-08-07 14:08 UTC
**Describe the bug**
QuickStatements export fails when Wikidata extension has not been opened yet

**To Reproduce**
1. Open a project where the Wikidata extension has not been used
2. Click on Export > QuickStatemetns

**Current Results**
Nothing happens

**Expected behavior**
The schema panel should open.

**Comment by afkbrb** [comment] 2020-02-29 14:04
Hi @wetneb , not sure whether I've reproduced this behavior.

I created a new project and clicked on `Export to QuickStatements` directly, then the schema panel showed as expected. If I click on `Export to QuickStatements` again, the schema panel won't show again (because `wikidata schema panel` has been set up), instead, a new window with the content `No schema was provided. You need to align your project with Wikidata first.` will appear.

> Expected behavior
The schema panel should open.

Do you mean as long as the schema is empty, clicking on `Export to QuickStatements` should always open the schema panel?

**Comment by wetneb** [comment] 2020-02-29 14:27
Hi @afkbrb, thanks a lot for looking into this!

You are right, I cannot reproduce what I described above. Curious! Does the current behaviour look appropriate to you? Would you handle this situation in any other way?

If you think this is an appropriate behaviour, feel free to close this (I just invited you to the organization so you should be able to do that once you join)

**Comment by afkbrb** [comment] 2020-02-29 14:56
@wetneb Thanks a lot for the invitation!

Maybe the bug has somehow been fixed by some commits. The current behavior seems fine to me (Why would someone try to export QuickStatements, if he/she has already known that the schema is empty). So I'd like to just close it.

**Closed** 2020-02-29 14:57 UTC
Labels: bug, export, wikidata
