### ISSUE TITLE
Large reconciliation tasks time-out

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#106] opened 2012-10-15 02:29 UTC
_Original author: iainsproat (July 01, 2010 07:39:40)_

<b>What steps will reproduce the problem?</b>
1.Send a large number of cells to be reconciled
2.Part way through the reconciliation process it will stop, but no results shown
3.No explanation is provided as to the problem

As a suggestion for a fix, is it possible for Gridworks to break down the recon task into chunks of no more than approx 5k cells, and queue the chunks up?

As errors will always occur I'd also like to see a dialog box being shown.  This would explain that there was an error, and give a suggestion on how the user might work around the issue (or suggest that they report it).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=106_
##

**Comment by wetneb** [comment] 2017-07-19 05:43
Has anybody experienced that recently? I haven't seen this "timing out" problem but we definitely need a better error-reporting (if the service returns an HTTP error code, or an invalid payload) but there is already #1128 for that, so I propose to close this one.

**Comment by thadguidry** [comment] 2017-07-20 03:37
@wetneb close and more as duplicate.... its sorta a duplicate...well close enough :) so mark it as a duplicate :) :)

**Comment by wetneb** [comment] 2017-07-20 06:47
Got it! Closing as a duplicate of #1128 then :)

**Closed by wetneb** 2017-07-20 06:47 UTC
Labels: component-Logic, component-UI, enhancement, imported, priority-Medium, usability
