### ISSUE TITLE
Don't return to the beginning of the rows after reviewing non-matches in a reconciled column 

### ISSUE THREAD

**Issue by jenyoung** [OpenRefine/OpenRefine#1915] opened 2018-12-21 17:18 UTC
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
It's frustrating to have a project with thousands of rows that I need to reconcile and not being able to navigate it easily.
 
**Describe the solution you'd like**
When going through a reconciled column to look at suggestions for non-matches, if I select `Match this item to this and all identical cells` I get returned to the start of the rows. Then I have to page through to get back where I was. Selecting `Match this item to this cell` leaves me where I am. I'd like this functionality for the other option as well.

**Describe alternatives you've considered**
I'm also submitting an issue to have the ability to better navigate thousands of rows/records.

**Additional context**
My current project. If I choose to match all 5 at once, I get returned to row 1. 

<img width="955" alt="2018-12-21_102903" src="https://user-images.githubusercontent.com/2250501/50353653-888af580-050e-11e9-945e-73f19b5a8ed0.png">

**Comment by wetneb** [comment] 2018-12-22 10:52
Hi! Thanks for the report. I agree this behaviour is annoying. See #33 for possible workarounds.

**Comment by thadguidry** [comment] 2019-03-30 12:51
Closing as duplicate of #33.  We'll add notes on possible new "Reconcile Mode" to #33

**Closed by thadguidry** 2019-03-30 12:51 UTC
Labels: duplicate, reconciliation
