### ISSUE TITLE
Export fails when previous export file exists - Google Chrome

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#585] opened 2012-10-15 03:42 UTC
_Original author: sitap...@worldsankirtan.net (June 21, 2012 03:32:28)_

<b>What steps will reproduce the problem?</b>
1. Export a project using templating
2. Attempt to the project export again
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

I'd expect the browser to save the file as &quot;projectname (1).txt&quot;; or else prompt for a filename (+1 to the Save As... RFE from me)

<b>What version of Google Refine are you using?</b>
Google Refine 2.5 [r2407]

<b>What operating system and browser are you using?</b>
Fedora 16 32-bit; Google Chrome Version 20.0.1132.34 beta

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>

It happens in Chrome. I tried with Firefox 13.0, and there I was prompted with a &quot;Save As&quot; dialog.

<b>Please provide any additional information below.</b>

Here's the server error message:

HTTP ERROR 500

Problem accessing /command/core/export-rows/EAP-6-Concepts.txt. Reason:

```
INTERNAL_SERVER_ERROR
```

Caused by:

java.lang.UnsupportedOperationException
    at com.google.refine.commands.Command.doGet(Command.java:86)
    at com.google.refine.RefineServlet.service(RefineServlet.java:170)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=585_

**Comment by eliohb** [comment] 2019-02-17 18:09
hello i have downloaded the openrefine 2.5 version and the rdf extension 0.9 version when i am trying to use the rdf extension by uploading a owl file (ontology) by using the advanced option i receive the following error:
 org.mortbay.log] /command/rdf-extension/upload-file-add-prefix (1ms)
java.lang.UnsupportedOperationException
        at com.google.refine.commands.Command.doGet(Command.java:86)
        at com.google.refine.RefineServlet.service(RefineServlet.java:170)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Any advice

**Comment by wetneb** [comment] 2019-02-17 18:21
@eliohb  This ticket is unrelated to your problem. Please use the latest version of OpenRefine (3.1) and the latest version of the RDF extension (1.1.0) from https://github.com/stkenny/grefine-rdf-extension/releases.

**Comment by eliohb** [comment] 2019-02-17 18:39
Dear,

I have install red extension 1.1.0 and i put all the file in
..\openrefine-3.1\webapp\extensions
and when i run the program the following error appear:
HTTP ERROR 500

Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension
[edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped
org.apache.lucene.index.IndexFormatTooOldException: Format version is
not supported (resource
BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))):
0 (needs to be between 4 and 6). This version of Lucene only supports
indexes created with release 5.0 and later.
(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format
version is not supported (resource
BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))):
0 (needs to be between 4 and 6). This version of Lucene only supports
indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more

any advice

**Comment by wetneb** [comment] 2019-02-17 18:49
@eliohb again, this is not the right place to report issues about the RDF extension. Please use https://groups.google.com/forum/#!forum/openrefine or https://github.com/stkenny/grefine-rdf-extension/issues.

Any further message that you post in this thread will be deleted.

**Comment by eliohb** [comment] 2019-02-17 19:28
I have install red extension 1.1.0 and i put all the file in  ..\openrefine-3.1\webapp\extensions
and when i run the program the following error appear:
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
any advice

**Comment by wetneb** [comment] 2019-12-20 15:01
We should check if this can be reproduced with a recent version of Chrome.

**Comment by wetneb** [comment] 2019-12-20 15:02
Similar to #212, #181.

**Comment by wetneb** [comment] 2019-12-21 18:27
Just tried again with Chrome (Version 78) and it works as expected, closing.

**Closed by wetneb** 2019-12-21 18:27 UTC
Labels: bug, export, imported from old code repo, priority: Medium, to be reviewed
