### ISSUE TITLE
Can't logout of a wikibase

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#6247] opened 2023-12-18 08:26 UTC
I'm trying to logout, but since my token is old and bad, OR keeps the connection opened with my credentials even if the log shows the bad token. OR should always honor a deconnection when it's gets a bad token on logout.

### To Reproduce
1. Be logged in with an old token
2. Do the loggout command
3. See that you are not logged out.

### Current Results
Stay logged in even if the API call to the wikibase failed because of a bad token

### Expected Behavior
Do the logout anyway.

### Screenshots
![image](https://github.com/OpenRefine/OpenRefine/assets/12217525/db6504ca-717c-43a0-8fce-e2214de655dc)

### Versions
 - Operating System: MacOS X.11.x
 - Browser Version: Chrome v120
 - JRE or JDK Version: openjdk_17.0.8.1
 - OpenRefine: v3.7.7

### Workaround
If, in the workspace.json file, you add this in the preference section:
![image](https://github.com/OpenRefine/OpenRefine/assets/12217525/653e446e-0c1d-4251-abb4-b488132e4790)

```
  "preferences": {
    "entries": {
      "wikidata_credentials": "",
```

It will force to logout. Actually, this is a bug because if there is no entry, the extension thinks you are logged in.

**Comment by Abbe98** [comment] 2023-12-18 12:40
Duplicate of #4905?

**Comment by wetneb** [comment] 2024-01-27 21:44
Let's keep only #4905 open then!

**Closed by wetneb** 2024-01-27 21:44 UTC
Labels: Type: Bug, Status: Duplicate, wikibase
