### ISSUE TITLE
Allow column resize and auto-resize on browser resize

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1312] opened 2017-11-08 14:14 UTC
A community request was mentioned on our mailing list https://groups.google.com/d/topic/openrefine/H3FAf5DSHPk/discussion

This example demonstrates the basic need of having resize-able columns and also auto-resizing the columns if the user changes the size of their browser window.
http://6pac.github.io/SlickGrid/examples/example15-auto-resize.html

**Comment by jackyq2015** [comment] 2017-11-08 17:50
there is one for AugularJS. just for the records:
https://tympanix.github.io/angular-table-resize/

**Comment by kushthedude** [comment] 2020-03-12 12:42
@thadguidry I would like to work on the following

**Comment by thadguidry** [comment] 2020-03-12 14:05
@kushthedude This is a baby step issue, to the larger goal of having a better grid technology that supports many features we would like such as draggable re-orderable columns, resizable columns, etc.  But sure, if you want to isolate on only the "resize columns" feature that's fine.  But how you do it and which technology choosen will impact the larger goal later (or you'll have to refactor/redo).

**Comment by kushthedude** [comment] 2020-03-12 22:59
> @kushthedude This is a baby step issue, to the larger goal of having a better grid technology that supports many features we would like such as draggable re-orderable columns, resizable columns, etc. But sure, if you want to isolate on only the "resize columns" feature that's fine. But how you do it and which technology choosen will impact the larger goal later (or you'll have to refactor/redo).

@thadguidry Hmm, I was first thinking to introduce `table-layout` property to our container and then go for column resize property for each column. But I just looked into code and saw the table is bound differently, All the column headers are coming from the `DataTableHeader Container` and the table data is coming from `TableDataContainer` which renders the data on row basis by labelling them with `odd/even` id.

**Comment by wetneb** [comment] 2020-03-12 23:01
Yes, it's a big mess! Resizing is done in JavaScript explicitly, which is massively inefficient since it triggers many DOM reflows. Also the size of the headers often get out of sync with the size of the grid.

**Comment by kushthedude** [comment] 2020-03-12 23:03
I was thinking to reimplement the tables and bind the content to a single table container if this can be done efficiently. Then the goal of having a better grid technology will be much more easier as we can directly apply our styling to the container rather worrying about how it would affect other columns and their headers.

**Comment by thadguidry** [comment] 2020-03-13 01:56
Myself and @wetneb are not exactly front-end wizards.  So we are depending on folks like you, maybe your peers or others in your circle that do have that experience to set the right course forward.  I think this is going to take a bit of experimentation to see what works best.  Have you looked at how agGrid with Vue works? https://www.ag-grid.com/vuejs-grid/  or others?  This might serve useful to your experiments.

**Comment by kushthedude** [comment] 2020-03-13 02:32
@thadguidry I will do the experiment to try bind the table to a single container for a staft and see how it goes. Coming to the Vue.js point, since the data-table is one of the biggest component of OpenRefine introducing vue.js directly into it may do more harm than good. I am looking to migrate the dialogues to vue.js for a start and if it looks good, we can look for migration of other components to Vue.js in summer, also once the data-table is converted into any progressive framework, introducing infinityLoader will be much more easier in them.

**Comment by kushthedude** [comment] 2020-03-16 13:47
@thadguidry Rather than going for a complete rewrite for the tables part, I
tweaked the UI a bit and got the complete data-table under a single table
container.
Since a complete rewrite in vue
Js will need opinion from more users.
Now I am trying to add resizable feature to the current container and will
keep you posted with the progress.

**Comment by thadguidry** [comment] 2020-03-16 14:33
@kushthedude great! looking forward to seeing your progress!

**Comment by kushthedude** [comment] 2020-05-24 13:51
Since the following was to be solved with the migration to a new data-grid while looking at chances of Vue.js. I think the GSoC candidates may resolve it during the work at infinityScroll.

**Comment by lisa761** [comment] 2020-06-04 14:56
I can take this up once infinite scrolling is implemented. However, for the gsoc project, there hasn't been any plans to migrate the table to a new data-grid library, as of now.

**Comment by ignaciomartin** [comment] 2021-08-31 22:13
Can anyone report any progress on this much needed request?

**Comment by magdmartin** [comment] 2024-10-24 15:45
@wetneb is it a duplicate of #4806 ?

**Comment by wetneb** [comment] 2024-10-24 16:59
Resizing we have, auto-resize not really, but I don't know if the auto-resize part of that issue is described clearly enough for it to be actionable, so maybe it's fine to close it as such indeed?

**Comment by tfmorris** [comment] 2024-10-24 17:12
The original request doesn't mention browser resize. That was added. Here's what was asked on the mailing list:

> Is there any way to adjust the width of columns in OpenRefine?  Sometimes, depending on the length of the content of a column, the width can be so long that it pushes columns off to the right that I would like to be able to see.  

> I know I can hide columns, but what I am hoping for is to keep a column visible while limiting its width somehow, perhaps by specifying a max-width property on a per-column basis (if not be able to resize columns more dynamically, as one might expect to in a spreadsheet application).  

Given that, I think #4806 was a duplicate of this.

**Closed by tfmorris** 2024-10-24 17:12 UTC
Labels: Status: Duplicate, Type: Feature Request, Theme: UX/Usability, Module: Frontend, Priority: High, columns
