### ISSUE TITLE
Allow reconciliation dialog to have option to store errors in cells

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3194] opened 2020-09-17 18:11 UTC
Sometimes intermittent internet problems can occur during (long or short) reconciliation batches due to various reasons. (dogs, cats, chairs, etc.)
Sometimes these might be HTTP errors where connectivity is still established.
Other times these errors might be due to SocketExceptions or networking abnormalities that prevent TCP packets (and hence HTTP) from being sent or received.

### Proposed solution
It would be nice for Reconciliation dialog similar to Fetch URLs to allow storing errors in the cells.  Maybe default is enabled?
That way they could be retrieved with `cell.errorMessage` and filtered out for retry from those that did have successful batch queries returned.

### Alternatives considered
Maybe it needs to be a deeper field added to `cell.recon` ?  or possibly just at `cell.value` level?  But it would be nice to have 1 place for cell errors, so I think `cell.errorMessage` might be better for now.  Up to the devs on this.  As long as it's documented at Cell or Recon: https://github.com/OpenRefine/OpenRefine/wiki/Variables#cell

### Additional context
Related to #2229 but this issue specifically asks to store errors as part of other improvements mentioned in #2229 for unreliable connections.

OpenRefine log example at 80% completed recon during a connectivity issue that occurred (my chair backed up too much and accidentally pulled the network plug):
```log
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Unknown Source)
12:47:53.233 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (77ms)
12:47:53.233 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.249 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (16ms)
12:47:53.249 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.264 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (15ms)
12:47:53.264 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.279 [    refine-standard-recon] Failed to batch recon with load:
{"q0":{"query":"Edward Jones","type":"Q4830453","type_strict":"should"},"q1":{"query":"Dropbox","type":"Q4830453","type_strict":"should"},"q2":{"query":"Novo Nordisk","type":"Q4830453","type_strict":"should"},"q3":{"query":"Nvidia","type":"Q4830453","type_strict":"should"},"q4":{"query":"Farmers Insurance","type":"Q4830453","type_strict":"should"},"q5":{"query":"CHG Healthcare","type":"Q4830453","type_strict":"should"},"q6":{"query":"USAA","type":"Q4830453","type_strict":"should"},"q7":{"query":"Burns & McDonnell","type":"Q4830453","type_strict":"should"},"q8":{"query":"Cisco","type":"Q4830453","type_strict":"should"},"q9":{"query":"Kettering Health Network","type":"Q4830453","type_strict":"should"}} (15ms)
java.net.SocketException: Network is unreachable: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Unknown Source)
12:47:53.357 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (78ms)
12:47:53.357 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.372 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (15ms)
12:47:53.373 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (1ms)
12:47:53.388 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (15ms)
12:47:53.388 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.403 [    refine-standard-recon] Failed to batch recon with load:
{"q0":{"query":"Publix Super Markets","type":"Q4830453","type_strict":"should"},"q1":{"query":"Cadence","type":"Q4830453","type_strict":"should"},"q2":{"query":"Workday","type":"Q4830453","type_strict":"should"},"q3":{"query":"Progressive Insurance","type":"Q4830453","type_strict":"should"},"q4":{"query":"Adobe","type":"Q4830453","type_strict":"should"},"q5":{"query":"Allianz Life Insurance Co. of North America","type":"Q4830453","type_strict":"should"},"q6":{"query":"Atlantic Health System","type":"Q4830453","type_strict":"should"},"q7":{"query":"Bain & Co.","type":"Q4830453","type_strict":"should"},"q8":{"query":"Sheetz","type":"Q4830453","type_strict":"should"},"q9":{"query":"Hilton","type":"Q4830453","type_strict":"should"}} (15ms)
java.net.SocketException: Network is unreachable: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Unknown Source)
12:47:53.480 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (77ms)
12:47:53.480 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.495 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (15ms)
12:47:53.496 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (1ms)
12:47:53.511 [..mpl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://wdreconcile.toolforge.org:443: Network is unreachable: connect (15ms)
12:47:53.511 [..mpl.execchain.RetryExec] Retrying request to {s}->https://wdreconcile.toolforge.org:443 (0ms)
12:47:53.526 [    refine-standard-recon] Failed to batch recon with load:
{"q0":{"query":"World Wide Technology","type":"Q4830453","type_strict":"should"},"q1":{"query":"KPMG","type":"Q4830453","type_strict":"should"},"q2":{"query":"Custom Ink","type":"Q4830453","type_strict":"should"},"q3":{"query":"The Cheesecake Factory","type":"Q4830453","type_strict":"should"},"q4":{"query":"Delta Air Lines","type":"Q4830453","type_strict":"should"},"q5":{"query":"W. L. Gore & Associates","type":"Q4830453","type_strict":"should"},"q6":{"query":"Baptist Health South Florida","type":"Q4830453","type_strict":"should"},"q7":{"query":"Nationwide","type":"Q4830453","type_strict":"should"},"q8":{"query":"Four Seasons Hotels & Resorts","type":"Q4830453","type_strict":"should"},"q9":{"query":"Camden Property Trust","type":"Q4830453","type_strict":"should"}} (15ms)
java.net.SocketException: Network is unreachable: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by tfmorris** [comment] 2020-09-17 20:03
Fixing the retry code (https://github.com/OpenRefine/OpenRefine/issues/2229#issuecomment-680952388) and making the operation restartable (#87/#580) would probably provide more user benefit.

**Comment by thadguidry** [comment] 2020-09-17 20:19
@tfmorris oh yeah, if we can make it even smarter, and it already knows that "hey this batch had some errors, we'll toss them aside, flag them for the user in a nice way, and let the user restart them later".  but I think part of that flagging and attaching the specific errors would still be useful for troubleshooting systems and services in general.  Maybe it doesn't even have to be cell by cell, but at batch level, dunno. Up to you guys.

**Comment by wetneb** [comment] 2023-05-29 10:11
I would really like to make some progress on this but I realize that there is an unsolved design issue here.

When reconciling a column, we preserve the original cell value (in `cell.value`) and only store new data in the reconciliation field (`cell.recon`). 
Operations which store errors in cells always do it by storing an `EvalError` object in `cell.value`.
Therefore, to implement this I would normally expect that the reconciliation operation does the same: when reconciliation fails, set `cell.value` to an `EvalError` object which contains an error message. From a user perspective, this would show a red error in the cell.

The problem with this is that we are overriding the original value. Imagine the reconciliation service was unavailable for a few seconds and the user wants to reconcile again all the cells which got errors in their first reconciliation pass. They could select all those cells with a facet, and run reconciliation again on them. The problem is that the value to reconcile is not there anymore, since it has been replaced by an error. Reconciling an error does not do anything.

I can think of a few solutions here:
* Let the `EvalError` store the original value internally, and modify the reconciliation operation so that when it is asked to reconcile such values, it reconciles the original value instead of the error message.
* Store the reconciliation error in the `cell.recon` field. This could be done by adding an error field to the `Recon` class, that users could access with something like `cell.recon.error`. We would adapt cell rendering accordingly (so that we can render the original value and the fact that reconciling it failed).
* other approaches?

Excitedly pinging @OpenRefine/designers for the first time on this occasion!

**Comment by thadguidry** [comment] 2023-05-29 11:38
I feel strongly about storing the original value internally.  That is something that is always there even from the first project creation.  We allow users to undo changes and see the original cell values.  I don't want to fundamentally change how that works.

We just need to modify reconciliation dialog so that the user is given a choice.
1. in other operations, we allow the user to "store the error in the cell", but we don't have that dialog option on recon dialog.
2. when a user choses to "store errors if they occur" that it perhaps similarly to other operations.  And if the user wants to restore the original values, it should be not only possible with an UNDO, but also through an additional menu.  The reasoning is that I might do further operations to the column cell values, and overwrite the values... but at some much later point, want to finally restore the original values.
3. wouldn't it be neat if you could select a column and then restore the original values for only that column from the operation history?  NEW ISSUE

**Comment by ostephens** [comment] 2023-05-30 08:43
>Operations which store errors in cells always do it by storing an EvalError object in cell.value

This seems like a slightly odd choice in any situation. Would it make more sense to have a specific cell property to store errors, and then decide whether they are displayed (in place of the cell.value) in some other way (rather like we do for cell.recon.match?)

**Comment by wetneb** [comment] 2023-08-03 06:51
@ostephens we could reconsider the practice of storing errors as EvalError objects in `cell.value`, but that's a pretty big change with likely many side effects in other operations or use cases (I would imagine). I am not opposed to those bold design re-thinks but I think we can and should solve this issue without that.

I am tempted to go for the approach of storing the error in `cell.recon.error`, it feels like the simplest approach which preserves the original value simply.

**Comment by thadguidry** [comment] 2023-08-03 10:01
I agree with @wetneb and it's more logical that the process that threw an error is _recon_ and not _value_.  I am looking forward to a design change that can show columns as being multipart frames, that is  when we can then show errors next to cell values and later even meta data.  The current design of a single cell to display many things is now antiquated.  I liked someone's design idea before that showed a small **info** icon in top left of cell to indicate that.  We could then add a small icon besides only the drop-down arrow on columns to hide/show the additional error detail or later metadata.    This is a long standing issue we left on the drawing board back in the day.

**Comment by tfmorris** [comment] 2023-08-03 15:42
> > Operations which store errors in cells always do it by storing an EvalError object in cell.value
> 
> This seems like a slightly odd choice in any situation. Would it make more sense to have a specific cell property to store errors, and then decide whether they are displayed (in place of the cell.value) in some other way (rather like we do for cell.recon.match?)

It's not just used for display. One advantage to the current setup is that the `value` is passed through the evaluation chain and short circuits any new evaluations so that the first error is available to the user (anything else makes debugging much harder). This could still be done with a new design, but it would require changes to pass both the `value` and the new error storage.

> I am tempted to go for the approach of storing the error in `cell.recon.error`, it feels like the simplest approach which preserves the original value and should be relatively safe to implement.

That seems fine to me, but there should be a related specification of what happens to various error related things like Facet by Error, `isError()`, etc with this new error storage.

I still think fixing #2229 would provide a bigger user benefit. The other issue mentioned above, #87, is marked as closed by an unmerged (and unreviewed) commit, which is odd. A mistake, perhaps?

**Comment by ayushrai206** [comment] 2023-08-05 20:09
Hey everyone,
what do we do after storing the error in cell.recon.error?do we display it in the cell instead of leaving the cell unreconciled?

**Comment by wetneb** [comment] 2023-08-06 10:25
> I still think fixing https://github.com/OpenRefine/OpenRefine/issues/2229 would provide a bigger user benefit.

@tfmorris Both are worth doing: retrying queries will not remove the need for proper error reporting, since some errors can persist no matter how often they are retried.

> The other issue mentioned above, https://github.com/OpenRefine/OpenRefine/issues/87, is marked as closed by an unmerged (and unreviewed) commit, which is odd. A mistake, perhaps?

No, that's intentional - we can discuss this more in [the forum thread about releasing 4.0-alpha2][https://forum.openrefine.org/t/releasing-4-0-alpha2/833).

>  what do we do after storing the error in cell.recon.error?do we display it in the cell instead of leaving the cell unreconciled?

I would render it similarly to an unmatched cell: we display the cell value, and underneath the reconciliation error (in place of the reconciliation candidates). It's probably useful to still leave the option to match the cell manually - we can tweak the rendering after testing, I would say.

**Comment by ayushrai206** [comment] 2023-08-25 02:25
Hey everyone, a lot of progress has been made on this issue and we would love to hear everyone's feedback on the work so far, though a lot of small bits are still pending like (as seen in the screenshot attached) we do need to simplify the very big error messages in some cells, we are still pondering upon if we should have the 'search for match' option in the cells that have an error as the user might like to retry reconciling them, and we are also working upon some of those cells that have some errors but are not displaying them(updating the unit tests accordingly).
![Screen Shot 2023-08-25 at 7 42 48 AM](https://github.com/OpenRefine/OpenRefine/assets/72227873/338e84e2-790a-4d9c-9cb7-40237f53f74b)

**Comment by thadguidry** [comment] 2023-08-25 03:44
`failed to batch recon with load:`
is just an error prefix and not useful. It's like saying just ERROR.
The query payload is also not useful I think and should be displayed only if a debug option is enabled.

What is more useful is the deeper exception.

As far as your work displaying errors, I think this is sufficient for now to at least surface errors and present them to the user.  We can address more useful errors in a case by case basis in a new issue.

**Closed** 2023-10-23 09:20 UTC
Labels: Type: Feature Request, reconciliation, error handling
