### ISSUE TITLE
Custom tabular exporter exports 1 row when none selected

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#800] opened 2013-09-01 19:25 UTC
If the current facets exclude all rows, the custom tabular exporter still exports one row.

**Comment by thadguidry** [comment] 2021-09-27 14:32
Not a bug.  I verified in 3.5.1 Beta (but options have been available to control this for last 10 years.)

We have 3 checkbox options at the bottom of the "Content" tab to control the following
- Output column headers
- Output empty rows (ie all cells null)
- Ignore facets and filters and export all rows

![image](https://user-images.githubusercontent.com/986438/134928845-7814b0a8-54b6-4497-99f6-a303c3599844.png)

If the option **Output column headers** is unchecked then OpenRefine will not export the 1 row column header.
It does however open a browser download window to save the empty file :-) which I think we can ignore.

Closing.

**Closed by thadguidry** 2021-09-27 14:32 UTC
Labels: bug, export
