### ISSUE TITLE
"Collapse consecutive whitespace": BUG?

### ISSUE THREAD

**Issue by fabiolinus** [OpenRefine/OpenRefine#5845] opened 2023-05-12 21:41 UTC
Hi. I used feature called 'Collapse consecutive whitespace' available under 'Edit cells / Common transforms'. I see that the GREL code under this operation is (Undo/Redo Extract):

value.replace(/[\\p{Zs}\\s]+/,' ')

In particular I performed this code:

"asssa".replace(/[\\p{Zs}\\s]+/,' ')

and I obtained this result:

"a a"

It sounds very strange, isn't it?

OpenRefine 3.5.2 used a different GREL expression:

value.replace(/\s+/,' ')

which works well for me

**Comment by thadguidry** [comment] 2023-05-13 02:03
Hi @fabiolinus ! You likely accidentally swapped the `\` before the `p` to after the `p` ?

My tests show the following:
 `"asssa".replace(/[p\{Zs}\s]+/, ' ')`
 --> `a a`
 
  `"asssa".replace(/[\p{Zs}\s]+/, ' ')`
  --> `asssa`
  
  It's a simple typo mistake on your part, no worries.
  Our code is correct however, and we have extensive tests for this now:
  https://github.com/OpenRefine/OpenRefine/blob/5e6581837d146b68f499baac6d7cec8f88b02ade/main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js#L409
  
Closing as not a bug.

**Closed by thadguidry** 2023-05-13 02:03 UTC
Labels: invalid

**Comment by thadguidry** [comment] 2023-05-13 02:06
stupid gh weirdness... NOW it updates! lol.

**Comment by fabiolinus** [comment] 2023-05-13 08:54
Thanks to all and sorry for my own mistake
