### ISSUE TITLE
Technical Docs for our Server tests setup with TestNG are outdated

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4675] opened 2022-04-01 01:19 UTC
The download link in our docs for TestNG update URL is now out of date and some of the info in this section:  https://docs.openrefine.org/technical-reference/build-test-run#testing-in-eclipse

There's good info to get and reuse some of it from their README.md file in their repo here:
https://github.com/cbeust/testng-eclipse

**Comment by elroykanye** [comment] 2022-04-01 07:01
Hello @thadguidry , can I get to work on this?

**Comment by wetneb** [comment] 2022-04-01 09:36
@elroykanye feel free to assign issues to yourself directly, you should have the required permissions to do so. Of course it is nice if you don't have to many issues assigned to yourself at once, to leave some for others. Thanks a million for all your contributions so far!

**Comment by elroykanye** [comment] 2022-04-01 10:25
Oh! It's my pleasure. I think I will help others towards solving these issues while checking for others which should be closed or have persisted for too long.

**Comment by amyy2022** [comment] 2022-04-01 21:54
One finding on windows is about the special characters. For the space character or possibly other characters, the TestNG will generate files in another location rather than the intended location.

To avoid this make sure the Eclipse workspace has no special characters including the space character.

**Comment by amyy2022** [comment] 2022-04-01 22:02
Error: Unable to initialize main class org.testng.remote.RemoteTestNG
Caused by: java.lang.NoClassDefFoundError: org/testng/TestNGException

I encounters this error which seems to be related to the classpath settings for TestNG, according to the official doc https://www.testingdocs.com/questions/how-to-fix-the-error-unable-to-initialize-main-class-org-testng-remote-remotetestng/

However, I cannot add the classpath according to the instructions. The "Add Libray..." button is unselectable.
![image](https://user-images.githubusercontent.com/102639466/161346671-9de7b141-ecbe-401c-903f-135bbebe4454.png)

Which seems to be related with build path entry is missing: server/src/main/java
![image](https://user-images.githubusercontent.com/102639466/161346817-d6985513-78db-4425-bebf-516632291e62.png)

I don't have lots of experience with maven setup / plugins in Eclispe. Would appreciate any help from here. Thanks.

**Comment by amyy2022** [comment] 2022-04-01 22:08
possible TODOs over the next few days:
* check out the detailed steps here to see if I can get the TestNG work in Eclipse: https://testng.org/doc/eclipse.html
* get and reuse some of it from their README.md file in their repo from the link @thadguidry provided above

**Closed** 2022-04-07 18:04 UTC
Labels: historical docs, current docs
