### ISSUE TITLE
Non-ascii characters in project name are lost

### ISSUE THREAD

**Issue by isaomatsunami** [OpenRefine/OpenRefine#2710] opened 2020-06-12 17:17 UTC
**Describe the bug**

Non-ascii characters in project name are lost

**To Reproduce**

I tried with both OR3.4beta on current Mac OS 10.15 AND java-embedded OR3.4beta on Windows10.

1. When starting project with file name in Japanese, all Japanese characters are lost in suggested (initial) project name, usually leaving only extention such as csv. (In the test file case, "2020 xls" is left )

2. So, I input manually a new project name in Japanese, like "選挙2020" (= election2020). The project is safely saved. The project list shows the Japanese project name perfectly. Reloading the project works fine.

3. When exporting csv/xls/html/odf, Japanse characters in exported file name are lost. BUT exporting project ( 選挙2020.openrefine.tar ) works fine, with Japanese characters intact.

**Desktop:**

 - OS:  Mac10.15/Windows10
 - Browser Version: 
 - JRE or JDK Version: 
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

**OpenRefine :**
 - Version  3.4beta

**Datasets**

P.S. I added a test file with Japanese file name/ Japanese cell value for dev team.
[選挙2020.xls.zip](https://github.com/OpenRefine/OpenRefine/files/4772265/2020.xls.zip)

Presumably this has been happening for a long time (<- sorry for my poor language)
I usually use ascii project name (is it bad habit?). But when I was teaching OR, they wanted to use original names.

**Comment by tfmorris** [comment] 2020-06-12 18:15
Thanks for the report and the test data. I believe this is the same as #1352, so I'm going to close this as a duplicate, but please follow that issue. I have a fix in testing which will be included in OpenRefine 3.4.

**Comment by isaomatsunami** [comment] 2020-08-24 21:27
As of the current nightly-built OR, the import side of this problem is solved. The export side is not still there.
When the project name has non-ascii chars, for example "result選挙2020",
exported csv/xls... file drops non-ascii characters.

**Comment by tfmorris** [comment] 2024-02-02 23:29
I've retested with the current code and can't reproduce the export issue on Mac OS Sonoma 14.2.1 using the string result選挙2020 as the project name. Excel/TSV/CSV all get exported with the correct names.

@isaomatsunami You mentioned both Windows & Mac in your initial bug report. Does the export failure happen with both? Can you still reproduce it with the current versions?

p.s. for the record #2713 ended up getting split into multiple PRs, so the actual PR that addressed this was #2720

**Comment by tfmorris** [comment] 2024-03-04 16:58
Closing as fixed. Please reopen if you see the problem again.

**Closed by tfmorris** 2024-03-04 16:58 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs More Information
