### ISSUE TITLE
Check File Format Error

### ISSUE THREAD

**Issue by bluntmagic** [OpenRefine/OpenRefine#1248] opened 2017-09-14 07:32 UTC
Im trying to upload an excel file (xlsx) with 14.2mb file size with 56,900 rows in 1 worksheet. But it always says "please check file format".

**Comment by wetneb** [comment] 2017-09-14 08:02
@bluntmagic have you tried increasing the memory limit for OpenRefine?
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory

if that does not work, could you share your dataset (or a part of it) so that we can investigate what is happening?

**Comment by thadguidry** [comment] 2017-09-14 13:33
@wetneb This is probably a Apache POI bug again which we use for loading XLSX files

My suggestion @bluntmagic would be to Save as CSV in Excel or LibreOffice Calc and then open the CSV file in OpenRefine.  If privacy is not a concern you could upload somewhere for us to grab the file and try to provide a fix or at least let the Apache POI team know about where the issue is at with your file and hopefully improve OpenRefine in the future.

**Comment by wetneb** [comment] 2017-10-10 16:09
Closing as non reproducible.

**Closed by wetneb** 2017-10-10 16:09 UTC
Labels: bug, import/xls, not-reproducible
