### ISSUE TITLE
Support checkpointing of long running operations like Add column by fetching URL

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#580] opened 2012-10-15 03:42 UTC
_Original author: demonsteam (May 30, 2012 16:30:39)_

I'm trying to add new column based on value of other via web service using the feature &quot;Add column by fetching URLs&quot;. I have about 200.000 rows and I have tried multiple times with different memory options but become every time after couple of hours (or days) OutOfMemoryError exception. In my case I have a list of freebase movie ids (e.g. /m/072x72) and I'm trying to fetch the movie descriptions via freebase web service (e.g. http://api.freebase.com/api/experimental/topic/standard?id=/m/072x72)

<b>What steps will reproduce the problem?</b>
1. Load a file with about 200.000 rows
2. Choose a webservice and add new column using &quot;Add column by fetching URLs&quot; 

<b>What is the expected output? What do you see instead?</b>
Job done or in case of exception at least resume option (this will be very useful for long running tasks).

Exception in thread &quot;Thread-8&quot; java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.insert(Unknown Source)
        at java.lang.StringBuffer.insert(Unknown Source)
        at com.google.refine.util.ParsingUtilities.readerToString(ParsingUtilities.java:109)
        at com.google.refine.util.ParsingUtilities.inputStreamToString(ParsingUtilities.java:96)
        at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperation$ColumnAdditionByFetchingURLsProcess.fetch(ColumnAdditionByFetchingURLsOperation.java:283)
        at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperation$ColumnAdditionByFetchingURLsProcess.run(ColumnAdditionByFetchingURLsOperation.java:223)
        at java.lang.Thread.run(Unknown Source)

<b>What version of Google Refine are you using?</b>
google-refine-2.5-r2407

<b>What operating system and browser are you using?</b>
Windows 7 64 Bit, Firefox, Chrome, Java 64 Bit

Is this problem specific to the type of browser you're using or it happens in all the browsers you tried?
Not related to the browser

<b>Please provide any additional information below.</b>
Using 64 Bit Java (JDK)
Google Refine options:
-Xms512M
-Xmx4096M
-XX:PermSize=128m 
-XX:MaxPermSize=192m

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=580_

**Comment by wetneb** [comment] 2019-12-20 14:58
Duplicate of #87.

**Closed by wetneb** 2019-12-20 14:58 UTC
Labels: duplicate, enhancement, fetch urls, imported from old code repo, persistence, priority: Medium
