### ISSUE TITLE
Extract History, Select/Unselect broken

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#1690] opened 2018-08-01 02:02 UTC
**Describe the bug**
When extracting the JSON from a project, I should be able to select only part of the operation using the select option. This option does not work at least since OpenRefine 2.8

No error shown in the terminal  (in the log I create a project and apply two operations)

```
21:56:27.155 [                   refine] POST /command/core/importing-controller (21361ms)
21:56:28.170 [                   refine] POST /command/core/get-importing-job-status (1015ms)
21:56:28.176 [                   refine] POST /command/core/cancel-importing-job (6ms)
21:56:29.270 [                   refine] POST /command/core/load-language (1094ms)
21:56:29.304 [                   refine] GET /command/core/get-preference (34ms)
21:56:29.316 [                   refine] POST /command/core/load-language (12ms)
21:56:29.330 [                   refine] POST /command/core/load-language (14ms)
21:56:29.343 [                   refine] POST /command/core/load-language (13ms)
21:56:29.534 [                   refine] GET /command/core/get-project-metadata (191ms)
21:56:29.563 [                   refine] GET /command/core/get-models (29ms)
21:56:29.780 [                   refine] GET /command/core/get-history (217ms)
21:56:29.781 [                   refine] POST /command/core/get-rows (1ms)
21:56:30.029 [                   refine] GET /command/core/get-history (248ms)
21:56:33.728 [                   refine] POST /command/core/apply-operations (3699ms)
21:56:33.830 [                   refine] GET /command/core/get-history (102ms)
21:56:33.860 [                   refine] GET /command/core/get-project-metadata (30ms)
21:56:33.876 [                   refine] GET /command/core/get-models (16ms)
21:56:33.891 [                   refine] POST /command/core/get-rows (15ms)
21:56:34.032 [                   refine] POST /command/core/compute-facets (141ms)
21:56:35.311 [                   refine] GET /command/core/get-operations (1279ms)
21:58:19.139 [           ProjectManager] Saving some modified projects ... (103828ms)
21:58:19.147 [        project_utilities] Saved project '1898382528686' (8ms)

```

**To Reproduce**
1. Create a project
2. Perform a couple of transforms operation
3. Go to `Undo/Redo` and then select `Extract`
4. Click to select, unselect some steps
5. The Json on the right panel should update based on the steps (un)selected. It does not

**Screenshots**
![awesomescreenshot-2018-08-01t01-57-11-983z](https://user-images.githubusercontent.com/2589584/43496764-0e66dc36-950d-11e8-88a6-32d7382eaa28.gif)

**Desktop:**
 - OS: ubuntu 16.04
 - Browser Chromium

**OpenRefine :**
 - Version OpenRefine2.8 and 3.0RC1

**Comment by thadguidry** [comment] 2018-08-01 02:14
@magdmartin any errors in javascript ?  Can you check the Browser console ?

**Comment by wetneb** [comment] 2018-08-04 12:09
@magdmartin I can't reproduce this either (with chromium on linux)… maybe a sample project would help indeed?

**Comment by wetneb** [comment] 2018-09-05 17:03
Closing as not reproducible.

**Closed by wetneb** 2018-09-05 17:03 UTC
Labels: bug, not-reproducible
