### ISSUE TITLE
3.7.4 refine.exe does not start openrefine in Windows

### ISSUE THREAD

**Issue by Stonepeople** [OpenRefine/OpenRefine#5988] opened 2023-07-27 10:04 UTC
I've downloaded 3.7.4 for Windows (both the Java one and the plain one). After unzipping into my new 3.7.4 folder I click the refine.exe as usual and it opens - "https://openrefine.org/docs/manual/installing#java"

### To Reproduce
1. First, follow the link from 3.7.3 (https://github.com/OpenRefine/OpenRefine/releases/tag/3.7.4)
2. Download and unzip the file (https://github.com/OpenRefine/OpenRefine/releases/download/3.7.4/openrefine-win-with-java-3.7.4.zip)
3. Try opening Openrefine from the refine.exe icon. 

If you download 3.7.4 via the openrefine download page (ie **not** via the "get 3.7.4 now" at the top of the start page) there is no problem

**Comment by wetneb** [comment] 2023-07-27 10:15
It's curious that downloading via the OpenRefine website works for you and GitHub does not, because both point to the same file:
https://github.com/OpenRefine/OpenRefine/releases/download/3.7.4/openrefine-win-with-java-3.7.4.zip
Could it be that the way you download it is different? For instance, could it be that in one of those cases you are trying to run the `.exe` file without first decompressing the archive it is contained in?
Otherwise it would be interesting to compare the hashes (such as SHA or MD5 sum) of the zip files depending on the download process you use. They should be identical. If that is not the case, then perhaps some other piece of software (browser, extension, firewall, operating system…) is interfering with the downloads and corrupting them?

**Comment by Stonepeople** [comment] 2023-07-27 10:36
It's very curious - which is why I reported it. It should be the same file - but they definitely behave differently when downloaded from the two different sites. I have unzipped each before attempting to run OR. (I have a regular workflow whenever I upgrade OR, and always unzip the download into the same overall folder....I will look for the hashes and report back!

**Comment by wetneb** [comment] 2023-09-02 10:27
I'd close this as not reproducible, happy to reopen if we have more info about the problem.

**Closed by wetneb** 2023-09-02 10:27 UTC
Labels: bug, to be reviewed, windows
