### ISSUE TITLE
URL Fetching hangs indefinitly if cache activated when a http error occurs

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1281] opened 2017-10-23 15:46 UTC
Hi
If caching is activated when fetching data from an URL, and if a http error occurs, the fetching is stuck.
Ex : 
https://geo.api.gouv.fr/communes?nom= NICE
-> error caused by the unescaped space
-> process hangs at 0%
![image](https://user-images.githubusercontent.com/932804/31898714-fc6e3856-b819-11e7-9931-6f4ce99b9c41.png)

I encountered the same unwanted behavior with errors caused by wrong https certificate

**Comment by wetneb** [comment] 2017-10-23 15:54
This is a known issue (duplicate of #1219) that has already been fixed in the development version. You can either disable caching, or use the development version (https://github.com/OpenRefine/OpenRefine/wiki/Get-Development-Version ) or wait for the next release.

**Closed by wetneb** 2017-10-23 15:54 UTC
