### ISSUE TITLE
support sql operations

### ISSUE THREAD

**Issue by opensas** [OpenRefine/OpenRefine#751] opened 2013-06-29 20:40 UTC
I don't know if this is even feasible, but for those accustomed to work with sql, a sql command line would be pretty useful.

If openRefine is using some kind of sql in memory db (like h2) it would be dead simple to implement. If openrefine is using some custom in memory db, I think it could be quite difficult.

Perhaps it could be possible to temporaly migrate the whole dataset to an in-memory h2 db, perform the sql operation, and then take it back, but it might just kill the performance.
##

**Comment by wetneb** [comment] 2017-08-02 08:14
Closing as a duplicate of #12.

**Closed by wetneb** 2017-08-02 08:14 UTC
