### ISSUE TITLE
Byte order marks ending up in project

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#356] opened 2012-10-15 03:33 UTC
_Original author: PaulMake...@gmail.com (March 28, 2011 13:08:35)_

Despite some digging it hasn't been clear how this data's come about although it's highly likely it went through Excel originating as CSV (that itself is free of any BOMs).

The issue is manifesting on export as in two cases we've seen, one having two BOM's, the other three(!). It turns out that the BOM's have been imported somehow into the column name. The clearest evidence of this is in the HTTP stream on a rename,

POST /command/core/rename-column?oldColumnName=&#37;EF&#37;BB&#37;BF&#37;EF&#37;BB&#37;BFproductcode&amp;newColumnName=a&amp;project=1376987350482 HTTP/1.1

Interestingly, on the rename, if I copy (Ctrl-C) the column name when it's highlighted the paste buffer will end up with the byte order marks (verified in a hexdump'ed paste) and a second rename &amp; paste will retain the BOMs back into Refine(!)

What version of Google Refine are you using? 2.0 r1836

What operating system and browser are you using? Windows 7 &amp; Chrome

Is this problem specific to the type of browser you're using or it happens in all the browsers you tried? Logically, not related to the browser, at least once the data's 'infected'. Unfortunately can't yet help on earlier than this.

I originally reported this at http://groups.google.com/group/google-refine/browse_thread/thread/3fa96f6297b28e0

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=356_

**Comment by wetneb** [comment] 2019-12-20 14:05
Closing as not reproducible since I can't find any sample dataset in this issue. Our libs have been updated since and this might have been fixed upstream.

**Closed by wetneb** 2019-12-20 14:05 UTC
Labels: bug, encoding, imported from old code repo, not reproducible, priority: Medium

**Comment by tfmorris** [comment] 2024-04-11 02:37
I think this was rediscovered as #1241
