### ISSUE TITLE
Slow performance in Chrome on Mac

### ISSUE THREAD

**Issue by matthewgertner** [OpenRefine/OpenRefine#2032] opened 2019-04-26 15:14 UTC
I've just starting playing with OpenRefine and it looks like a great tool for our purposes. However, the performance on our dataset is so slow as to make it basically unusable. Since I'm new to the tool, I wanted to check if I'm doing something wrong or if this is a known limitation.

My computer is a one-year-old Macbook Pro with 16Gb so it's pretty fast. Loading our dataset (400,000 rows, 2 columns) is quite fast. Creating a text facet on the second row is pretty fast too. The facet has about 30,000 unique entries. The problems start when I click on "count" to sort the facet entries by count. That takes about 2-3 minutes. If I click on an item to view the individual entries in the righthand panel, that also takes 2-3 minutes during which time the browser is completely unresponsive.

I'm using Java v1.8.0_192. This doesn't seem to be a memory issue since I ran with `./refine -m 4096m` and it doesn't seem to be close to the 4Gb limit (it never goes over 2Gb from what I've seen). When I launch a slow operation, it looks like the bottleneck is actually Chrome which is pegged at 100% CPU.

Does this seem normal to people when working with a dataset of this size or am I doing something wrong?

**Comment by ostephens** [comment] 2019-04-26 15:30
Hi @matthewgertner. The Facet 'sort by count' happens using javascript in the browser - which is why you are finding it slow even though you've assigned 4Gb to Java - that sort isn't using Java, so changing the Java memory allocation won't affect it. As you noted - the bottleneck is in the browser.

Working with a data set of this size is normal, but having such a large number of values in a facet is not.

Can you describe i more detail what you are trying to achieve and I may be able to suggest an approach that avoids having this large facet (possibly!)

**Comment by matthewgertner** [comment] 2019-04-26 15:38
Hey @ostephens, thanks for the quick response. We are matching product names so each item in our dataset is a product. There is a large number of unique products which is why the facet is so large. Right now I am just browsing through the data and the facet view is quite useful, but to be honest I'm not entirely sure what I'll end up doing with OpenRefine so perhaps this limitation will turn out not to be an issue.

**Comment by ostephens** [comment] 2019-04-26 15:48
You could try using the Text filter instead of the Facet to find specific values?

**Comment by matthewgertner** [comment] 2019-04-26 15:57
OK thanks, I'll try that. I'm kind of surprised because I would have expected sorting 30,000 items in a modern browser to be lightning fast.

**Comment by ostephens** [comment] 2019-04-26 16:01
@matthewgertner I'm not sure that the implementation of that sort is particularly clever - I'm trying to get my head around how it works but it doesn't look right to me at a first glance

**Comment by ostephens** [comment] 2019-04-26 16:23
OK - the thing that was throwing me was that for the Count sort, if two items have the same number then it falls back on sorting alphabetically - which means it's doing two calculations for each item with the same number.

This will slow it slightly - but I'm not sure it will be significant.

For a facet of 8000 unique values, each with a count of 1, it takes approx 6 seconds to sort numerically

**Comment by ostephens** [comment] 2019-04-26 16:43
OK - more investigation and I've realised that the `sort` aspect is a red herring. The speed issue isn't caused by the sort - which is fast - but by redrawing the facet each time. There's even a note in the code to the effect that there is a performance issue here!

Actually reported back in 2013 as #672 but never sorted I'm afraid. This feels like it is definitely fixable 5 years on, but I'm not sure what the solution is right now.

@matthewgertner I'm going to close this issue in favour of #672, but if you want some help in thinking about whether OpenRefine can help you get the outcome you want without encountering this facet performance issue please post about what sort of outcome you are looking for in the discussion forum at https://groups.google.com/forum/#!forum/openrefine

Hopefully I'll get some time to look at resolving #672 soon

**Closed by ostephens** 2019-04-26 16:43 UTC

**Comment by matthewgertner** [comment] 2019-05-02 15:31
OK thanks again @ostephens!

**Comment by tfmorris** [comment] 2024-04-24 15:52
Marking as duplicate for the historical record.
