### ISSUE TITLE
Custom tabular exporter not working 

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#2912] opened 2020-07-09 11:54 UTC
**Describe the bug**

Instead of downloading a file a new tab with the current project is opened 
**To Reproduce**
1. Export in top right corner 
2. "custom tabular exporter..." 
3. Change settings / don't change default settinga
4. Download as csv/excel/excel table

**Current Results**
A new tab is opened with the current project 

HTML export *is* working 
**Expected behavior**
A file is downloaded with the current project's data

**Screenshots**

**Desktop:**
 - OS: Windows 
 - Browser Version: Chrome 

**OpenRefine :**
 - Version: OpenRefine 3.4 Beta 2

**Comment by wetneb** [comment] 2020-07-10 09:32
I cannot reproduce this on Linux with Chromium or Firefox.

**Comment by VDK** [comment] 2020-07-10 12:06
Nothing is landing in my download folder.
If I try to the SQL exporter I get the message:
"This site can't be reached" ERR_INVALID_RESPONSE

when I do an SQL export and hit "preview" instead of download I get:

<code>
HTTP ERROR 500
Problem accessing /command/core/export-rows/chicago_tribute-covid-csv.sql. Reason:

    INTERNAL_SERVER_ERROR
Caused by:
java.lang.NullPointerException
	at com.google.refine.util.JSONUtilities.getString(JSONUtilities.java:57)
	at com.google.refine.exporters.sql.SqlInsertBuilder.getInsertSQL(SqlInsertBuilder.java:105)
	at com.google.refine.exporters.sql.SqlExporter$1.endFile(SqlExporter.java:122)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities$1.end(CustomizableTabularExporterUtilities.java:179)
	at com.google.refine.browsing.util.ConjunctiveFilteredRows.accept(ConjunctiveFilteredRows.java:71)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities.exportRows(CustomizableTabularExporterUtilities.java:184)
	at com.google.refine.exporters.sql.SqlExporter.export(SqlExporter.java:166)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:119)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</code>

first hitting preview and then download seems to make the table export work again though. This might also be why HTML export did work earlier.

**Comment by tfmorris** [comment] 2020-07-10 15:05
Perhaps there is something data specific going on. Is it possible to share the project (use Export Project Archive to File)? If you'd prefer to share it privately, you can email it to me on gmail (same username).

**Comment by tfmorris** [comment] 2020-07-10 20:14
I just tried Windows 7 with Chrome Version 81.0.4044.138 (Official Build) (64-bit) and was unable to reproduce it there either.

I had previously been unable to reproduce it on macOS Mojave 10.14 with Chrome 83.

**Comment by VDK** [comment] 2020-07-11 13:01
[OpenRefine project](http://veradekok.nl/wp-content/uploads/2020/07/chicago_tribute-covid-csv.openrefine.tar.gz)
It's not as consistently failing to export as it was yesterday.

**Comment by wetneb** [comment] 2020-07-15 07:22
From @allanaaa on the mailing list:

> Yes, I reproduced this on Windows with Chrome. You press "download," a new tab opens, and it loads the same project again. It only does it once - if you try to download again after that (from either the new tab or the original one) the file download dialog comes up properly.
> 
> I couldn't reproduce it on Windows with Firefox. A new tab opens, it loads for a few seconds, and then the file download dialog comes up. The new tab remains blank.

**Comment by muturinjokah** [comment] 2020-09-30 13:02
I am yet to get past the export puzzle!!!

**Comment by thadguidry** [comment] 2020-09-30 14:26
I have just finished thoroughly testing this on Windows 10 with the following browsers:

Browser | Opens Tab | Test Result
---------|------------|-----------
Firefox | YES, empty tab stays | Downloads OK with Custom tabular, SQL, Excel
Edge | YES, however quickly closes tab | Downloads OK with Custom tabular, SQL, Excel
Chrome | NO, nicer experience | Downloads OK with Custom tabular, SQL, Excel

One thing that I did notice is that my XLS file opens automatically in LibreCalc, but this was because of a saved setting for that Application type in Firefox Options - General - Files and Applications

It's possible some setting in the user's browser might be adversely affecting how downloads are being handled, and so users should check in their browser options for the particular MIME type (Content Type) and the setting for it.

![image](https://user-images.githubusercontent.com/986438/94698059-8a4a3580-02fe-11eb-9118-2d63ae629690.png)

**Comment by thadguidry** [comment] 2022-03-01 14:12
Tested again with the latest OpenRefine 3.6 Snapshot and latest 3 browsers (including 4th Brave and 5th Opera browser) and all of them work as expected with each of their specific download handling ways.  For those browsers that we kept the **new tab** handling, they automatically open a **save as** dialog as expected.

Closing as not reproducible.

**Closed by thadguidry** 2022-03-01 14:12 UTC
Labels: bug, UI, export
