### ISSUE TITLE
when importing a null, that row is not marked the rowId

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1546] opened 2018-03-18 03:15 UTC
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
2.8

#### Operating Systems and version:
Ubuntu 17.10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome

#### Steps followed to create the issue:
Create the project from following data:
c1,c2,c3,
111,222,333
,444,555
5555,666,
aaaa,bbbb,ccc

#### Current Results:
It should generate a project with a header and 4 rows.

#### Expected Results:
The 2nd row's rowId is not get marked and the total number of rows shows 3 instead of 4. Even there is 4 rows in the grid.

**Comment by ettorerizza** [comment] 2018-03-18 09:10
I cannot reproduce the problem with 2.8 - Windows 10 - Chrome.
![screenshot-127 0 0 1-3333-2018 03 18-10-08-37](https://user-images.githubusercontent.com/6286410/37564342-857f80b8-2a94-11e8-8fc9-2c3e7b38ebcc.png)

**Comment by jackyq2015** [comment] 2018-03-18 15:34
@ettorerizza You are right. it is in the records mode. but somehow it was automatically switched to record mode after importing. Not sure it is an bug or expected behaviour though

**Comment by wetneb** [comment] 2018-03-18 15:38
@jackyq2015 it has always been like this as far as I know

**Comment by thadguidry** [comment] 2018-03-18 17:53
@jackyq2015 automatically switching to records mode when record-like rows were detected...has always been a feature.

**Comment by jackyq2015** [comment] 2018-03-18 20:46
But for the given example, that's not the the right choice to apply the record mode.

**Comment by ostephens** [comment] 2018-03-18 21:06
@jackyq2015 why is it not the right behaviour? 

The only way I can see to avoid this would be to treat the missing value at the start of row 2 as an empty string. Is that what you think should happen?

**Comment by jackyq2015** [comment] 2018-03-18 21:36
@ostephens I think it is correct to leave the null as null instead of try to treat it at importing stage. But the record mode should NOT be triggered for the row-based importing. The idea is that "I told you it is row based csv importing, why do you present it as  the record mode to me by default"

**Comment by wetneb** [comment] 2018-03-23 13:26
what is "row-based importing" exactly? The distinction between the rows and records mode only arises after project creation in my opinion. I think it makes sense that projects created from CSV file can be treated in records mode. It is possible for a tabular file to have a records structure before import in OpenRefine (this would typically happen in Wikitables, or some Excel files).

The default mode does not matter that much AFAICT, given that it just takes one click to change. I think we can close this.

**Comment by thadguidry** [comment] 2018-03-23 14:38
@jackyq2015 @wetneb I would have to agree I guess with Jacky, that if a user chooses the "Line-based Importer"... then it should stay in Rows mode.  For other importers, I think its fine for us to continue to detect records and move into Records mode.  Once we get a new UI, we can have a Guide dialog that says "We've put you in Records mode, since we detected records based formatting of your data file".

I think we can close this issue if there is not objection ?

**Comment by ettorerizza** [comment] 2018-03-23 14:54
`if a user chooses the "Line-based Importer"... then it should stay in Rows mode.`

 Looks like there is no difference between rows mode and records mode with a Line-based file ( you can't create a record with a single column)

![screenshot-127 0 0 1-3333-2018 03 23-15-48-50](https://user-images.githubusercontent.com/6286410/37836246-50ec3a04-2eb2-11e8-92b8-285b1118f2ed.png)

**Closed** 2018-03-24 02:26 UTC
