### ISSUE TITLE
Wikidata error on "Add columns from reconciled column"

### ISSUE THREAD

**Issue by glenviewjeff** [OpenRefine/OpenRefine#2034] opened 2019-04-29 16:29 UTC
The Wikidata-based data extension API produces an error corrently. Here is the procedure to follow:

Lets suppose you want to match "Richard Cheney" and "William Clinton" with a dataset where both names are in short form (Dick Cheney and Bill Clinton).

1 Split the names into several columns, one of which containing the first names (for you to see what is the best way to split the names according to your data).

2 match the first names column with Wikidata and the category "Given name".

3 Extract the nicknames using "Edit column / add column from reconciled values".

4 As soon as you add the nickname property, you'll get an error as below. Some Given Name fields work properly, others like nickname produce an error. 

![image](https://user-images.githubusercontent.com/334914/56911170-e8bc1600-6a71-11e9-82f6-b451179c55d1.png)

**Comment by ostephens** [comment] 2019-04-29 17:30
I think the issue is caused because the "nickname" has a datatype of "Monolingual Text" meaning there is a language label on each value for this property.

The same error can also be seen by choosing "native label" which is also Monolingual Text.

When choosing to add data from properties which are not monolingual texts the error does not occur

**Comment by ostephens** [comment] 2019-04-29 19:24
Closing as this is the same issue as #1809

**Closed by ostephens** 2019-04-29 19:24 UTC
