### ISSUE TITLE
Support of conversion of millisecond Unix time to Refine datetime

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#608] opened 2012-10-15 03:43 UTC
_Original author: to...@benmoshe.com (September 15, 2012 11:52:15)_

It would be nice to have a function such as FORMAT_UTC_USEC to convert Unix time ( which is a number) to a Datatime format, and to extract only year/month/day

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=609_

**Comment by thadguidry** [comment] 2018-11-09 11:22
For whomever works on this... Here's a good primer, since OpenRefine now uses java.time.offsetdatetime https://stackoverflow.com/questions/21242110/convert-java-util-date-to-java-time-localdate

Our code for the GREL toDate() function is here: https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/ToDate.java

**Comment by ostephens** [comment] 2018-11-12 22:42
So I'm currently looking at toDate as per #1759 and @thadguidry reminded me of this (thanks Thad!).

At the moment I can think of two options for handling this:

Extend toDate to have a GREL specific 'format' option which is (something like) 'epochms' (epoch milliseconds) which tells toDate to use a long number (or a string which can be converted to a long number) as millisecond Unix time and use that to generate a date/time

The alternative I can see is to have a special new function such as 'epochToDate' which does this specifically.

The second approach avoids making the toDate function even more complex than it already is, but has the downside of introducing a new function rather than a single 'toDate' function handling all conversions to a date.

@thadguidry do you have thoughts on this?

**Comment by thadguidry** [comment] 2018-11-13 02:27
Summary:
I think I would choose the format option to make it painless for our users (we do the hard things, to make it easier for them). 

Errata:
While it is painful and complex within our toDate() function, this is necessary to keep GREL syntax nice and tidy. This is also how other programming languages handle this convention, like Javascript (Moment.js), Python, Pandas, Ruby.  Our toDate() already has an optional format argument.  Where I could see this leading to is possibly extending to handle a 3rd argument for timezone or utc.

Moment.js does things so beautifully and should be our model https://momentjs.com/docs/#/parsing/unix-timestamp-milliseconds/
Ruby uses time.at  http://ruby-doc.org/core-1.9.3/Time.html#method-c-at
Pandas uses Pandas.Timestamp  https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Timestamp.html#

We're not looking to completely incorporate all methods in Ruby and Pandas.Timestamp into our toDate().  Those can be handled by Python/Jython instead of GREL.  But for GREL, it makes sense to at least have a common Unix timestamp convertor built into our toDate() for our users.

**Comment by ostephens** [comment] 2018-11-13 06:06
Thanks @thadguiry. I can see a new format option working 

>Our toDate() already has an optional format argument. Where I could see this leading to is possibly extending to handle a 3rd argument for timezone or utc.

One of the complexities of the toDate function in code is that it has a set of optional arguments- including one boolean type (month first) and two string types (locale and repeatable format). 

Adding another optional argument (presumably of type string) for timezone will make it even more challenging to make sure the arguments are being interpreted correctly

**Comment by thadguidry** [comment] 2018-11-13 12:44
@ostephens Then don't worry about timezone at this time.  Just use something like:
```
Date date = Date.from( Instant.ofEpochSecond( timeStamp ) );
```
and we should be good.  That will give us the UTC/Greenwich time.
- [ ] Also ensure that we document on the Wiki this very important footnote:

> OpenRefine internally uses java.time which converts a Unix Timestamp using The Java Time-Scale.
The Java Time-Scale divides each calendar day into exactly 86400 subdivisions, known as seconds. These seconds may differ from the SI second. It closely matches the de facto international civil time scale, the definition of which changes from time to time.  More information here: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#Time-scale

**Comment by impune-pl** [comment] 2019-06-10 09:42
Hi @thadguidry, as you suggested I've taken a look at this issue. If I understand correctly the goal here is to allow user to use something like toDate(123456, "epoch") for parsing dates from epoch format.

**Comment by thadguidry** [comment] 2019-06-10 15:22
Correct @impune-pl , although we probably want to use the label "unix" instead of "epoch", since "epoch" is generally used to represent a "period of time".  In our case, its a very specific "period of time" that we want to handle more gracefully.  The "the number of seconds that have elapsed since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds."  Which is commonly referred to as Unix time.  Moment.js uses the syntax "moment.unix()" https://momentjs.com/docs/#/parsing/unix-timestamp/ and I think for OpenRefine GREL doing `toDate(123456, "unix")` would be aligned well with that.  At this time, I wouldn't worry about completely changing to Functional Composition as Ruby and Moment do, but continue to handle as a parameter passed to `toDate`.

**Comment by thadguidry** [comment] 2020-06-03 17:52
Hi @impune-pl If you don't mind, please take a look at @tfmorris comment on your PR https://github.com/OpenRefine/OpenRefine/pull/2072#issuecomment-638346540

**Comment by tfmorris** [comment] 2020-09-06 21:21
The original request was for microseconds, but we probably want seconds (Unix), milliseconds (ECMAscript), and nanoseconds (Java 8 Instants) as well.

I'm of two minds regarding overloading `toDate()` with more cruft in the form of made-up format specifiers, but perhaps that's easiest for the user. We may, however want to defer this until we have a design for adding a Date-only data type and fixing the current date handling.

**Comment by ostephens** [comment] 2020-09-08 12:37
Agree with the suggestions of the different units as listed by @tfmorris here.

I suggested the format string "epochms" originally which would given us the option of "epochs" and "epochns" for seconds/nanoseconds.

I also agree with his concerns about the 'toDate' parameters. `toDate` is already a bit of a monster in terms of the parameters you can pass, and I did suggest we could separate the epoch time -> date conversation into to a different function - which I think might be appropriate in this case - it would almost certainly be simpler and less prone to breaking things than changing the toDate function.

A possibility I still like is to add a GREL function like `epochToDate` (I'm sure we can come up with a better name!) which accepts a number as input, outputs a date, and has parameter which allows you to specify the units (seconds, milliseconds, nanoseconds)

This would give an option that could be easily added while we wait for any more substantial changes to the date handling

**Comment by MariaAngella** [comment] 2022-03-29 16:26
I'm Maria Angella, an Outreachy participant willing to work on this issue.
Kindly assign me the task for this period.
Thank you

**Comment by wetneb** [comment] 2022-03-29 19:53
Hi @MariaAngella, I assigned you one already, if you don't mind I would wait a bit more to assign you a second one as there is a chance we run out of good first issues in this initial Outreachy period.

**Comment by MariaAngella** [comment] 2022-03-30 06:56
This is fine @wetneb. I'll work on the one assigned already... Thanks

**Comment by keerthybreddy** [comment] 2022-04-03 00:57
Hello! My name is Keerthy Reddy and I am a Outreachy applicant for Summer 2022. If it is still available, can I be assigned this issue to work on? Thank you so much!

**Comment by antoine2711** [comment] 2022-04-03 01:03
> Hello! My name is Keerthy Reddy and I am a Outreachy applicant for Summer 2022. If it is still available, can I be assigned this issue to work on? Thank you so much!

@keerthybreddy sure. I'm assigning it to you.

Regards, Antoine

**Comment by keerthybreddy** [comment] 2022-04-17 22:49
Hi! I am currently working on testing the epochToDate() method that I have written to solve this issue, but am having trouble with it. Can someone explain how I can reproduce and test the issue? Thank you so much!

**Comment by keerthybreddy** [comment] 2022-04-20 02:52
Hi! 
   I edited the GREL epochToDate() function written by SustechcsKing with ZoneId.systemDefault() in order to make sure that the function is using the time zone that the system is currently in rather than the "America/Chicago" time zone that was previously hardcoded into the function. 
   However, this change is causing the epoch timestamp to convert to the date-time of the current time zone when being edited and then change to the UTC date-time when published. 
   Is this the expected result or does the published result also need to have the current time zone date-time?

**Comment by thadguidry** [comment] 2022-04-20 04:00
@keerthybreddy what do you mean by "published"?  You mean exported to a CSV/TSV/Excel or something? or do you mean once the **Apply** button in the Edit Cell dialog has been clicked?

**Comment by keerthybreddy** [comment] 2022-04-20 04:25
> @keerthybreddy what do you mean by "published"? You mean exported to a CSV/TSV/Excel or something? or do you mean once the **Apply** button in the Edit Cell dialog has been clicked after a **Data type** change is made then the value in the column cell is UTC date-time?

Sorry! I meant the latter. Once  I click the Edit Cells --> Transform option on the column with the timestamps, input value.epochToDate(), the preview shows the current time zone date-time, and changes to UTC date-time when I click the Ok button.

**Comment by keerthybreddy** [comment] 2022-04-20 08:03
Sorry! I meant the latter. Once I click the Edit Cells --> Transform option
on the column with the timestamps, input value.epochToDate(), the preview
shows the current time zone date-time, and it changes to UTC date-time when
I click the Ok button.

I have attached screenshots of my screen before and after hitting the Ok
button while using my current timestamp that should return April 20, 2022
12:58 am.

**Comment by keerthybreddy** [comment] 2022-04-21 01:04
Hi! I just submitted a pull request for this issue [here](https://github.com/OpenRefine/OpenRefine/pull/4784), please review it when possible!

**Comment by ostephens** [comment] 2022-04-22 14:58
Originally I said:
> A possibility I still like is to add a GREL function like epochToDate (I'm sure we can come up with a better name!) which accepts a number as input, outputs a date, and has parameter which allows you to specify the units (seconds, milliseconds, nanoseconds)

Which @keerthybreddy has been working on. During the work the question has arisen as to whether `epochToDate` is an appropriate name. Suggested alternatives we have so far are:

* epochToDate()
* unixToDate()
* posixToDate()

I don't love any of these, but I'm torn between a more appropriate name and keeping the name short and simple ('timeSinceUnixEpochToDate' seems a bit OTT!)

Anyone else have suggestions?
@antoine2711 @wetneb @thadguidry

**Comment by thadguidry** [comment] 2022-04-22 15:36
My opinion would be to keep it as `epochToDate()` because "epoch" is fairly common short terminology within Unix/Linux documentation and would be typically known coming from many places (including man pages in some cases) and https://en.wikipedia.org/wiki/Unix_time to be "time since Unix epoch".  It's understood that the "epoch" is really an interval and that's represented in an encoding sequence.  I would avoid the host and standards terms "unix" and "posix".

For the documentation, I definitely would point to that Wikipedia link which clears up lots of confusion for most folks.

**Comment by wetneb** [comment] 2022-04-22 15:42
On my side (as stated on the pull request) I would prefer "unix" or "posix" terms since I consider that "epoch" does not refer to an interval but a specific origin date.

**Comment by thadguidry** [comment] 2022-04-22 15:49
I'm just saying that the representation of the scalar value in Unix systems is commonly called just "Unix time".  But universally, we would say "epoch time" or just "epoch".

I guess most users would be more familiar with "Unix time" (even though "epoch" is indeed a short term often seen as I stated).
So maybe `unixToDate` is fine... which is a short short version of saying `unixTimeToDate` which is not that bad an alternative to type out with GREL.  Pick one @ostephens ;-)

**Comment by antoine2711** [comment] 2022-04-23 08:03
> (...) Although strictly Unix time is always in seconds since the Unix epoch.
> 
> Unix and Posix also aren't date formats so I'm not so keen on posixToDate or unixToDate for the same reason as @wetneb doesn't like epochToDate.

How about the middle ground, `unixEpochToDate()`?

Regards, Antoine

**Comment by wetneb** [comment] 2022-04-23 13:05
"UNIX epoch" refers even more unambigously to 1970-01-01 I would say, so rather not for me :)

**Comment by antoine2711** [comment] 2022-04-25 06:41
1. `unixTimeSecondsSinceEpochToDate()` might cover it, but it seam a bit long to me.
2. `unixTimeSinceEpochToDate()` could be an alternative, though still a bit long. 
3. Even `unixTimeEpochToDate()` could make it… Your take, @wetneb?

Regards, Antoine

**Comment by ostephens** [comment] 2022-04-26 10:18
If we're going to go for accuracy over brevity I think we may as well be precise, so out of those my vote goes to `timeSinceUnixEpochToDate()` 

Note that the function takes an argument to specify seconds, milliseconds or microseconds - so it isn't strictly the unix time or seconds - it's time (in seconds, milliseconds or microseconds) since the Unix epoch converted to a Java date/time. So I think "unixTimeSeconds" is definitely wrong, and as Unix Time is expressed in seconds, technically unixTime is also wrong

**Comment by keerthybreddy** [comment] 2022-05-01 18:27
After reading through the [article](https://en.wikipedia.org/wiki/Unix_time) that @thadguidry linked, I think I agree with @ostephen 's suggestion of timeSinceUnixEpochToDate() for the name. If no one else has any objections, I can change the name of the function to this.

**Closed** 2022-05-16 11:23 UTC
Labels: enhancement, imported from old code repo, priority: Medium, good first issue, grel
