### ISSUE TITLE
Improve browser launch in Linux distribution

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2640] opened 2020-05-25 11:31 UTC
**Describe the bug**

It would be worth making sure we are using the most appropriate API call to launch the browser on Linux. In some circumstances, this can happen:
```
You have 15876M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Starting OpenRefine at 'http://127.0.0.1:3333/'

15:02:40.754 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
15:02:40.755 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
15:02:40.763 [            refine_server] Initializing context: '/' from '/home/projadmin/dj/openrefine-3.3/webapp' (8ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/projadmin/dj/openrefine-3.3/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/projadmin/dj/openrefine-3.3/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15:02:41.204 [                   refine] Starting OpenRefine 3.3 [58b839b]... (441ms)
15:02:41.204 [                   refine] initializing FileProjectManager with dir (0ms)
15:02:41.204 [                   refine] /home/projadmin/.local/share/openrefine (0ms)
15:02:44.359 [                   refine] Sorry, some error prevented us from launching the browser for you.
```

It would be worth checking that we are using the best approach to open `http://localhost:3333/` - the API to do this might have evolved. We could try different APIs in turn, too (making sure that we do not launch it twice).

**Desktop (please complete the following information):**
 - OS: Linux

**OpenRefine (please complete the following information):**
 - Version 3.3

**Additional information**

Mailing list thread: https://groups.google.com/forum/#!topic/openrefine/oo4W-zlSqc8

**Comment by tfmorris** [comment] 2020-05-28 21:31
We could probably start by logging the exception so which know exactly which "some error" caused the problem.

One thing to try would be using the command `open  http://127.0.0.1:3333/` at the shell and see if that opens the browser. If it doesn't it might given an error which indicates what the problem is.

**Comment by elroykanye** [comment] 2022-04-05 15:11
Turns out that this is a popular issue in linux as I saw here: https://github.com/openmole/openmole/issues/140

The dependence we have in this case is the java.awt.Desktop. I would suggest using some other suitable call in case, like Runtime from java.lang...

**Comment by elroykanye** [comment] 2022-04-05 16:42
Yes! `Runtime.exec()`

> https://stackoverflow.com/a/54869038/1100717

This is actually what I had in mind. The client initially tries to launch using desktop, so adding another option to handle the not supported os could fix it. I currently use Linux only so I have been able to try this method on another application and it works well. Will need to try out with windows.

**Comment by Binita-tech** [comment] 2022-04-05 16:57
I can try out this on windows as I am window user. I would like to work on this issue. Kindly assign to me.

**Comment by elroykanye** [comment] 2022-04-05 17:04
Hey @Binita-tech , thanks for opting 😄 
I think I definitely needed help in the windows area. Please help out with this issue. I have not done my tests on the project itself, but I can show you how I tried it out and maybe that will land a solution. I will be assigning it to you.

**Closed** 2022-04-15 20:01 UTC
Labels: bug
