### ISSUE TITLE
Faceting with a Jsoup selector causes infinite recursion in Jackson JsonMapping

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4121] opened 2021-08-23 19:21 UTC
Serialization error while trying to use Jsoup selector with a Custom Text Facet

### To Reproduce
1. Import the provided OpenRefine exported project [Recursion-Error-Jackson-csv.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/7034348/Recursion-Error-Jackson-csv.openrefine.tar.gz) that demonstrates the problem
2. Perform a Custom Text Facet on column FETCH using the following GREL
```
value.parseHtml().select(
  "meta[property=og:title]"
)[0]
```
3. Notice the preview is OK and the `<meta property ` is showing the extracted string:
![image](https://user-images.githubusercontent.com/986438/130502951-8810308c-c077-4d32-bb2f-5eaf4e519322.png)
4. Click OK and then watch Facet being created quickly and then stacktrace with error is thrown in console.

### Current Results
```
13:42:47.736 [                   refine] POST /command/core/get-rows (6ms)
13:42:47.891 [                   refine] POST /command/core/compute-facets (155ms)
13:42:47.938 [                  command] Exception caught (47ms)
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.node

< -- SNIP --  10's of same output>

ments"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"]->org.jsoup.select.Elements[0]->org.jsoup.nodes.Element["allElements"])
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:785)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
```
### Expected Behavior
I expected the full extracted strings such as 
```
<meta property="og:title" content="INTERNATIONAL TYPEWRITER EXCHANGE INC">
```
to be shown in the Custom Text Facet

### Screenshots
![image](https://user-images.githubusercontent.com/986438/130501092-13e7a1cd-0855-438e-a704-3aa9d8ff700f.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK 15
 - OpenRefine: 3.5 Beta1

### Datasets
[Recursion-Error-Jackson-csv.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/7034348/Recursion-Error-Jackson-csv.openrefine.tar.gz)

### Additional context
Even though this is a corner case, I do sometimes lightly use Jsoup to quickly give me facets on substructure from fetched webpages that I later use for reconciling various things against Wikidata.  So I would like the ability to see in a Custom Facet the entire extracted string

#### GREL  (blows up with recursion error):
```
value.parseHtml().select(
  "meta[property=og:title]"
)[0]
```
results in the following nice string output in the GREL Preview that I'd like to see in a Facet, however I can't because it causes the aforementioned serialization bug and a recursion error
```
<meta property="og:title" content="INTERNATIONAL TYPEWRITER EXCHANGE INC">
```

instead I have to work around the serialization bug and be very specific and asking which HTML attributes I want, which does work in the Custom Text Facet  (but my use case it actually faceting on the attribute pairing etc. to quickly compare website metadata for some lightweight statistical analysis and then later extracting substructure content I am interested in to compare against a Wikidata Recon in the future.

#### GREL (that works with Custom Text Facet):
```
value.parseHtml().select(
  "meta[property=og:title]"
)[0].htmlAttr("content")
```

**Comment by wetneb** [comment] 2021-08-30 09:21
Thanks for this amazing bug report @thadguidry! I am tentatively adding the "good first issue" tag because it should be a nice thing to debug and well reproducible.

**Comment by mattzeeee** [comment] 2021-11-07 09:05
Hi, I plan to look into it as my first issue since the bug report indeed looks very clear and detailed.

**Comment by wetneb** [comment] 2022-01-25 10:29
Hi @mattzeeee, are you still working on this?

**Comment by haanhvu** [comment] 2022-03-07 10:55
Hi, I'm working on this issue. For now I'm studying the codebase and the documents. Will ping you later if I have questions.

**Comment by haanhvu** [comment] 2022-03-15 14:26
@wetneb from what I see, the fix will be in SerializationFilters.java?

Maybe some files in main/src/com/google/refine/expr/functions/xml need fixes too? I'm not really sure because I don't fully understand what each file in main/src/com/google/refine/expr/functions/xml do what.

Please help elaborate more on how to fix this.

**Comment by wetneb** [comment] 2022-03-15 15:52
Given the task here I do not know for sure which files will need editing. Before you get to that stage you need to understand why we have this behaviour.

I would write some unit tests which evaluate the expressions given in the ticket, make sure they indeed fail like the issue mentions, and then use my debugger to step through the evaluation steps to understand what is going on.

There are some existing GREL tests that you should be able to imitate to set up your own unit tests.

**Comment by ostephens** [comment] 2022-03-15 16:05
Looking at the issue and testing a little it's probably important to note:

* this seems to be specific to the creation a facet
* the output of the parseHtml().select() GREL statement is a org.jsoup.nodes.Element

**Closed** 2022-03-15 16:27 UTC
Labels: bug, good first issue, grel

**Comment by wetneb** [comment] 2022-03-15 16:54
Up to you! But I would say if we throw infinite recursions at the user in some cases, it is still worth fixing that (and not assuming that is up to the user to find a workaround on their side).

**Comment by thadguidry** [comment] 2022-03-15 17:05
@wetneb I'll keep it closed...As a user, I didn't give `compute-facets` what it really needed.  But could have if I had more information in UI via #443.  The alternative is to put in limits of the Java types acceptable (String, Number), but I eventually see fancier Facets being made with extensions that will unbound those limits (JSON Records).  So let's not hard code limitations for Facet extension developers down the road.
