### ISSUE TITLE
Facet selections remain applied after closing Facet when rows have been deleted

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1866] opened 2018-11-27 09:33 UTC
**Describe the bug**
Under some circumstances closing a Facet does not refresh the list of rows displayed in the data table

**To Reproduce**
1. Create a text facet and select a value to get a subset of rows
2. Remove the rows from the project ("All->Edit Rows->Remove all matching rows")
3. See no rows now appear (expected)
4. Close the facet by clicking the 'cross' at the top left of the facet panel
5. Note that still no rows appear even though you've removed the facet and there are still rows in the project

**Current Results**
The data  table was not refreshed to show the remaining rows in the project after the facet was removed

**Expected behavior**
The data table should refresh to show all the rows remaining the project

**Screenshots**
![screen shot 2018-11-27 at 09 31 03](https://user-images.githubusercontent.com/576174/49072080-56e08080-f227-11e8-994a-aac9c5267a70.png)

remove the filtered rows - note you can see in the facet there is still one row remaining

![screen shot 2018-11-27 at 09 31 14](https://user-images.githubusercontent.com/576174/49072092-5fd15200-f227-11e8-9bba-f03ff365bf8d.png)

Close the facet with the cross at the top left - still no rows display

![screen shot 2018-11-27 at 09 31 21](https://user-images.githubusercontent.com/576174/49072108-6cee4100-f227-11e8-83b4-9ee8e4217acf.png)

**OpenRefine (please complete the following information):**
 - 3.1 Beta

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment] 2018-11-27 10:52
@ostephens I can't reproduce this at the moment - do you have any errors in the JS console maybe? Could that be browser-dependent?

**Comment by ostephens** [comment] 2018-11-27 14:56
No JS Console errors. Happens on both Safari and Chrome. Not tested on Ff yet - can do later.

**Comment by ostephens** [comment] 2018-11-27 22:20
Also occurs using FF

**Comment by thadguidry** [comment] 2018-11-28 00:32
@ostephens This is resolved somehow in 3.1 trunk... I just followed your exact steps and things are fine in FF with Trunk... however you are correct that in 3.1 Beta release, the problem you observed can be reproduced by me as well.  Good news is that this is fixed in 3.1 trunk... but leaving it to you guys to figure out why and how. :-)

**Comment by wetneb** [comment] 2018-11-28 02:15
Ah indeed! Sorry I was trying from master, not from 3.1-beta. I suspect this was solved by the other fix about facets (empty facet choices disappearing). Let's close this then?

**Closed by wetneb** 2018-11-28 02:15 UTC
Labels: bug

**Comment by ostephens** [comment] 2018-11-28 16:37
Ah - sorry - should have tested from master
