### ISSUE TITLE
Text filter across all columns

### ISSUE THREAD

**Issue by felixlohmeier** [OpenRefine/OpenRefine#1737] opened 2018-09-16 22:42 UTC
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

Today I have worked with a big dataset that has several columns with similar values. I was looking for a certain value in the dataset. Finding it with text filters on each column one after the other was exhausting. 

**Describe the solution you'd like**

Text filter across all columns, i.e. select row if at least one column contains the key

**Describe alternatives you've considered**

* Custom text facet `filter(row.columnNames,cn,cells[cn].value.contains("key")).length()>0`

**Additional context**

Maybe this could lead to a search bar?

![GitHub search bar](https://help.github.com/assets/images/help/repository/searching_csvs.gif)

https://help.github.com/articles/rendering-csv-and-tsv-data/#searching-data

**Comment by thadguidry** [comment] 2018-09-19 23:12
Duplicate of #213

**Comment by thadguidry** [comment] 2020-06-16 18:26
Sorry, was not really a duplicate of #213 
Also, we now have **Edit cells -> Replace** on a single column that can search and replace only in a column.
But we still do not offer users a way to do a global search across **All columns** as shown above by @felixlohmeier in his example.  Which I really like the search bar appearing as very intuitive.  Perhaps it initially could be hidden in the `data-container` or outside of it, as just a magnifying glass icon, that once clicked, would open a horizontal input box as demonstrated.

**Comment by tfmorris** [comment] 2020-06-16 19:19
@thadguidry I disagree. This is an **exact** duplicate of #213 (which I've just reopened because it was mistakenly closed), down to suggestion that it be implemented as a search bar up top.

**Comment by thadguidry** [comment] 2020-06-16 19:50
I think what is causing much of the confusion.  (and I and Martin have even witnessed this during training folks) is that...
`filter`
`search`
`find`
are all different in OpenRefine.
But we and users sometimes mix up the terms sometimes (and sometimes the issues are talking about 1 of them, but intending to mean 1 of the others).  I know this, because I've witnessed it.

Maybe we need to make some really good GitHub labels and properly describe those labels so we know the functionality we all are talking about in our code?  Up to you.  Anyways...

I trust that you will sort out the wishes of our users (no matter the labels or terms chosen). Thanks Tom and Antonin!

**Comment by tfmorris** [comment] 2020-06-18 19:16
Please follow #213 to track progress on this

**Closed by tfmorris** 2020-06-18 19:16 UTC
Labels: duplicate, enhancement
