### ISSUE TITLE
Java exceptions when faceting or merging clusters

### ISSUE THREAD

**Issue by smurphy13IIT** [OpenRefine/OpenRefine#6990] opened 2024-11-15 19:55 UTC
After creating a project from a simple csv file of names, some operations are not working properly. Selecting "text facet" throws a Java exception as shown in the attached screenshot; the specific exception reads "java.lang.NullPointerException". Attempting to cluster and merge from the "cluster and edit" dialog box doesn't work properly, either; clustering occurs as expected, but after clicking "merge and re-cluster", no cells are apparently merged even if they were previously selected to merge. The datafile is attached, though we tried both an xlsx and a csv version of the same data with the same result.
[names_advisor.xlsx](https://github.com/user-attachments/files/17780656/names_advisor.xlsx)

![image (2)](https://github.com/user-attachments/assets/9d387550-4a9f-4451-ba54-fb16920d262d)

We're unable to replicate the issue on a different computer. The issue occurs using both Chrome and Firefox, after clearing the cache; Java was brought up to date as well. It occurs, also, in both the .exe version and the .zip version of 3.8.5, as well as 3.6.2. The computer is Windows 10, and it's up-to-date as of 11/15/2024. We're kind of baffled about what local environment variable might be causing this issue.

Has anyone else experienced a similar issue? Does anyone have an idea of what local configurations on this computer might be preventing OpenRefine from working properly?

**Comment by wetneb** [comment] 2024-11-15 20:43
One thing that would be quite useful to diagnose the problem would be the server logs (on windows, the things that get written in the white-over-black console) after reproducing the problem. Given that you have some extensions installed, it could also be worth removing them and see if the problem still occurs.

**Comment by smurphy13IIT** [comment] 2024-11-15 22:31
> One thing that would be quite useful to diagnose the problem would be the server logs (on windows, the things that get written in the white-over-black console) after reproducing the problem. Given that you have some extensions installed, it could also be worth removing them and see if the problem still occurs.

Oh yes, I can provide that, thanks for the reply! I'm attaching two screenshots of the console printout.
![image (4)](https://github.com/user-attachments/assets/29f238c5-7676-4a65-8358-fa932a7cba36)
![image (3)](https://github.com/user-attachments/assets/eb90343e-148d-4da4-8788-2db3207f68e7)

**Comment by wetneb** [comment] 2024-11-16 05:33
Thanks! It does look like this problem is caused by the RDF Transform extension. It would be worth reporting at https://github.com/AtesComp/rdf-transform.

**Comment by smurphy13IIT** [comment] 2024-11-20 00:59
Thank you! I will do so.

**Comment by AtesComp** [comment] 2024-11-20 04:11
RDF Transform should not be called by the thread pool / worker under these conditions.  Some kind of function call / lookup is confusing the Java system and may not be isolated to RDF Transform.  I'll review the RDF Transform extension registration code as it  uses minimal server side JS to hook up the extension in Java code.

**Comment by AtesComp** [comment] 2024-11-20 04:22
There are a couple of GREL functions that are added by RDF Transform.  I wonder if there is a naming conflict with the mass editor.

**Comment by tfmorris** [comment] 2024-11-20 04:55
@smurphy13IIT Screenshots of text are very difficult to work with. Please post the textual stack trace if you have it.

@AtesComp the exception is happening in binding initialization which is called every time any expression is evaluated, if the extension registered a binding initializer (because the extension may want to inject bindings to be used when evaluating other expressions).

**Comment by AtesComp** [comment] 2024-11-20 06:09
Ok, I see that.  It's been awhile.  Then...
```ExpressionNominalValueGrouper.visit()``` calls ```ExpressionUtils.createBindings()``` calls ```RDFTransformBinder.initializeBindings()```

RDF Transform does use the Expression Binder:
```
/*
 * Class RDFBinder
 *
 *   This class is registered by the "controller.js" in this extension.
 *   The purpose of registering this "binder" is to push an instance of this class onto the
 *   HashSet managed by the ExpressionUtils class.
 *
 *   This "binder" is used by the ExpressionUtils createBindings() method to create and add
 *   generic "bindings" properties.  It calls this "binder"'s initializeBindings() method to
 *   add a "baseIRI" binding to the "bindings" properties.
 *
 *   The ExpressionUtils bind() method is used to bind a specific row (Row), row index (int),
 *   column name (String), and cell (Cell) to the "bindings".  It calls this "binder"'s bind()
 *   method to perform any additional work concerning the added "baseIRI" binding.
 */
public class RDFTransformBinder implements Binder {
```
This is called during the extensions initialization process at startup.  See: https://github.com/AtesComp/rdf-transform/blob/main/src/main/java/org/openrefine/rdf/command/InitializationCommand.java

If this is called "every time any expression is evaluated", then a new RDFTransform object is created as needed (shouldn't it already be created at startup / extension load?). In:
https://github.com/AtesComp/rdf-transform/blob/main/src/main/java/org/openrefine/rdf/RDFTransform.java
at line 367.  Something in there has the null pointer...hard to tell from the output.  It's not doing much.  With debugging turned on, we might see what.  It's log should have the info.

Ideally, all the initialization should be good at this point.

**Comment by smurphy13IIT** [comment] 2024-11-20 18:07
> @smurphy13IIT Screenshots of text are very difficult to work with. Please post the textual stack trace if you have it.
> 
> @AtesComp the exception is happening in binding initialization which is called every time any expression is evaluated, if the extension registered a binding initializer (because the extension may want to inject bindings to be used when evaluating other expressions).

Great point, sorry about that. I asked my colleague to send me the console printout:

[OpenRefine Output.txt](https://github.com/user-attachments/files/17835004/OpenRefine.Output.txt)

**Comment by AtesComp** [comment] 2024-11-25 18:55
After getting into the code, this is beginning to look like an incompatibility between the newer OpenRefine (and libs) and the older RDF Transform (and its libs).  I'm updating RDF Transform with the newer libs and adjusting a few code parts for better error handling.

Never give up, never surrender!  ..and never go back!

**Comment by AtesComp** [comment] 2024-11-27 00:17
I'm closing this issue with a redirect to the [related RDF Transform issue](https://github.com/AtesComp/rdf-transform/issues/20).

I'll be updating RDF Transform with version 2.2.3 shortly to add better reporting (verbose and debug) controls around this and similar issues.  I'm attempting to capture any thrown exceptions and errors in the extension to keep OpenRefine from aborting its other functionality (play well with others, stop running with scissors).

**Closed by AtesComp** 2024-11-27 00:17 UTC
Labels: Type: Bug, RDF
