### ISSUE TITLE
XMLHttpRequest warning in Firefox console

### ISSUE THREAD

**Issue by simonaubertbd** [OpenRefine/OpenRefine#6317] opened 2024-01-17 20:25 UTC
### To Reproduce
Use OpenRefine 3.7.7 with Firefox. Open Inspector tool

### Expected Behavior
No warning

### Screenshots
![image](https://github.com/OpenRefine/OpenRefine/assets/46959192/ccd4e383-897e-4359-bbb6-7a9be54f9650)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox 121.0.1 (64 bits)
 - JRE or JDK Version: default
 - OpenRefine: 3.7.7

### Datasets
N/A

### Additional context
N/A

**Comment by tfmorris** [comment] 2024-01-18 00:40
This is a duplicate of #1039 which we closed as "Won't Fix" due to an [blocking dependency](https://github.com/jquery/jquery/issues/1895). At the time, we thought it would be fixed in jQuery 3.0, but the jQuery team has continued to kick the can down the road to 4.0 and now 5.0 because it's a breaking change.

Is this causing you problems or is it just a cosmetic issue?

The English translation of the warning is "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

p.s. as an aside, since images aren't searchable, please try to include the text of error messages or anything else important in your bug reports to make them easier to find rather than relying solely on screen captures.

**Comment by simonaubertbd** [comment] 2024-01-18 05:25
Hello @tfmorris  First of all thanks for your answer. To me, it's only cosmetic, I find it disturbing to have warning in the console. So no urge
PS : you're right and I'm the first to ask my users to do so. Sorry.

**Comment by wetneb** [comment] 2024-01-30 06:01
So if it's a duplicate of a closed issue, we should probably close this one, no? Feel free to reopen if you disagree :)

**Closed by wetneb** 2024-01-30 06:01 UTC
Labels: Type: Bug, Status: Duplicate
