### ISSUE TITLE
Inconsistency with handling null and empty string - (blank)

### ISSUE THREAD

**Issue by eximius313** [OpenRefine/OpenRefine#820] opened 2013-09-30 16:40 UTC
Google Refine has severe problems with handling nulls (https://github.com/OpenRefine/OpenRefine/issues/332, https://github.com/OpenRefine/OpenRefine/issues/252)

My problem was, that I cannot concatenate column values when one cell was null.
The solution is to "blank" cells not with null but with empty string. But there is no such option!

1)When you use option Edit cells -> Common transformations -> Blank out cells - Google Refine sets all cells to null.
2)When you do Edit cells -> Transform and you put "" - Google Refine sets all cells to null either!
3)Edit cells -> Transform and " ".trim() doesn't do anything
4)Luckily Edit cells -> Transform and " " and then Edit cells -> Common transformations -> Trim leading and trailing whitespace does the job right.

Conclusion
1)Bullets no. 2 and 3 above should perform exactly the same as no. 4
2)There should be two options: "Blank out cells" and "Null out cells"
3)Google refine should allow to concatenate nulls treating them as empty strings
4)"Text facet" should not treat nulls exactly the same as empty stings - currently both are displayed as (blank) and you cannot distinguish one from another

Kind regards

**Comment by wetneb** [comment] 2017-08-07 17:41
I agree with conclusions 1, 2 and 4 but it is not clear that 3 should be the desired behavior.

**Comment by eximius313** [comment] 2017-08-07 17:47
If there will be "coalesce" method, then I'm fine without 3

**Comment by magdmartin** [comment] 2017-08-07 18:01
@wetneb I documented the point 3 here: http://kb.refinepro.com/2011/07/merge-2-columns-that-have-both-blank.html

I think the idea is if a `column 1` has `blank` or `null` value and one does `cells["column 1"].value + " " + cells["column 2"].value`  then OpenRefine should only display `cells["column 2"].value` in the result.

**Comment by wetneb** [comment] 2017-08-07 18:06
@magdmartin yes I understand that this would be the desired result in some cases. But I think there should indeed be a "coalesce" method (that wolud translate all nulls to blanks) so that this is done explicitly.

For instance, consider a table where you would have email addresses split in two columns: one for the username (what is on the LHS of the at sign), one for the domain (RHS). If you want to recover email addresses from that with `cells["username"].value + "@" + cells["host"].value`, surely you don't want to have just `"@"` as value when both cells are null: you want that new cell to be null too, I think.

**Comment by thadguidry** [comment] 2017-08-07 18:51
All - we simply overkilled on the null safety at the wrong level.  Its a simple fix for someone. This is known in programming as null safety.  We missed the opportunity on the toString() + toString() case, that's all.  

For conversion methods using our + operator (concat) , we check if both sides are NOT NULL

```
        if (args.length == 2) {
            if (args[0] != null && args[1] != null) {   <-- The OP's problem
```
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/grel/ast/OperatorCallExpr.java#L65

and if both sides are not a number or integral then we convert both arguments to String and append them together.
```
                if ("+".equals(_op)) {
                    return args[0].toString() + args[1].toString();
                }
```
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/grel/ast/OperatorCallExpr.java#L122

to give the OP some relief, someone could fix the double null checking at each individual case.
1. Concat of 2 numbers
2. Concat of 2 integrals
3. Concat of 2 strings
4. Concat of 2 nulls

Additional test cases with both null arguments and both whitespace arguments, 1 null side, 1 whitespace side, etc could be added.  Codacy should show 100% test coverage for the OperatorCallExpr.java  which we don't currently.

**Comment by thadguidry** [comment] 2017-08-07 19:21
Sidenotes:

isNonBlank(" ")  <-- true
isNonBlank(null) <-- false
isNonBlank("")  <-- false

isNotNull(" ")  <-- true
isNotNull(null)  <-- false
isNotNull("")  <-- true

**Comment by wetneb** [comment] 2017-08-07 19:49
@thadguidry yeah that is fine! but do we have a coalesce function?

**Comment by thadguidry** [comment] 2017-08-07 19:53
coalesce("thad" + null) == "thad"  <-- true  ??

**Comment by wetneb** [comment] 2017-08-07 19:55
@thadguidry no, that syntax is clearly not possible as it would break compositionality. I think the op was thinking more of something like this: `"thad" + coalesce(null) == "thad"`. In other words, a function that converts null to `""` and leaves any string untouched.

**Comment by thadguidry** [comment] 2017-08-07 19:58
nope, we explicitly did not add any null conversion functions. Yes, I know those are quite common, and I use them in my daily database work all the time :)

We can certainly add that kind of function to https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/grel/ControlFunctionRegistry.java

**Comment by thadguidry** [comment] 2017-08-07 20:11
funny how a 2000 year old issue still becomes an issue for folks https://en.wikipedia.org/wiki/Null_morpheme

**Comment by eximius313** [comment] 2017-08-08 08:28
First of all - coalesce shoud look something like this:
```
nullableField = null;
coaleste(nullableField, "foo") == "foo"
```
or
```
nullableField = "bar";
coaleste(nullableField, "foo") == "bar"
```

second, coalesce solves only the 3rd point below

> Conclusion
> ~~1)Bullets no. 2 and 3 above should perform exactly the same as no. 4~~
> 2)There should be two options: "Blank out cells" and "Null out cells"
> ~~3)Google refine should allow to concatenate nulls treating them as empty strings~~
> 4)"Text facet" should not treat nulls exactly the same as empty stings - currently both are displayed as (blank) and you cannot distinguish one from another
>

**Comment by thadguidry** [comment] 2017-08-27 20:17
Brainstormed a bit today and thinking about making it super easy with our existing GREL dot notation syntax for users like what Groovy and Koitlin do... For the coalesce operation, what if we introduced this need as a new safe navigation operator "?." like what C# and Groovy and other languages do ?  http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html
This could be put as a new token in Parser.java

"Languages such as Groovy have a safe navigation operator represented by "?." to safely navigate through potential null references. (Note that it is soon to be included in C#, too, and it was proposed for Java SE 7 but didn't make it into that release.) It works as follows:

String version = computer?.getSoundcard()?.getUSB()?.getVersion();

In this case, the variable version will be assigned to null if computer is null, or getSoundcard() returns null, or getUSB() returns null. You don't need to write complex nested conditions to check for null.

In addition, Groovy also includes the Elvis operator "?:" (if you look at it sideways, you'll recognize Elvis' famous hair), which can be used for simple cases when a default value is needed. In the following, if the expression that uses the safe navigation operator returns null, the default value "UNKNOWN" is returned; otherwise, the available version tag is returned.

String version = 
    computer?.getSoundcard()?.getUSB()?.getVersion() ?: "UNKNOWN";"

**Comment by eximius313** [comment] 2017-08-29 18:37
Sounds great! But will this solve:
1)In [Edit cells -> Common transform] there should be two options: "Blank out cells" and "Null out cells"
2)"Text facet" should not treat nulls exactly the same as empty stings - currently both are displayed as (blank) and you cannot distinguish one from another

?

**Comment by thadguidry** [comment] 2017-08-29 19:11
@eximius313 I was only talking about GREL convention.
* For 1, we would still need to add Common Transforms  (BTW, Blank means both null and empty...and we will not ever change that behavior since its useful to have a single operation that treats them equally)  But we also need "Null all cells" and "Empty all cells").
* For 2, we would need to add 2 more Customized Facets... "Facet by null" and "Facet by empty"

**Comment by eximius313** [comment] 2017-08-31 10:20
That would be awesome!

**Comment by ostephens** [comment] 2018-02-14 16:50
I'm trying to create individual issues for each of the enhancements identified under this issue. I've done all except one I believe. I wanted to have a further discussion before I went ahead and created the last enhancement to be clear on what we wanted.

@thadguidry has suggested the implementation of the 'safe navigation' and 'elvis' operators. This is in place (I believe) of the 'coalesce' operation suggested by @eximius313 and @wetneb 

I'm unclear as to what the expectation of the 'safe navigation' operation does for us here. As I understand it, the usual purpose of a safe navigation operator is to avoid trying to call an operation on a null value - and instead returns null at that point.

In OpenRefine this is less of an issue because whether there is null or an error here, the user can decide through the transform process whether they keep the error or set to blank (actually null) in the transform window.

The Elvis operator makes more sense to me in place of coalesce, as it seems to provide the required functionality.

Can someone explain a bit more about how we'd expect the safe navigation operator to work in OpenRefine - I think I'm missing something. Also would appreciate views on whether this is two separate enhancements, or a single one covering both safe nav and Elvis.

**Comment by thadguidry** [comment] 2018-02-14 18:25
@ostephens
The safe navigation operator ?. is simply an inline sugary syntax to do "if null, please proceed", but does not replace null with anything, its just a check.

`assert value != null`

The Elvis operator ?: is simply a sugary syntax to perform a ternary operator, which is a shortcut for if/else branch assigning some value to a variable.  The downside is that the user has to tell the value they want to assign, rather than just coalescing null into "".  But we could do that as a default for our Elvis operator syntax.

(SIDENOTE: There is also the idea in other languages of collecting only non-null values and that can use the safe navigation operator ?.
```
assert listOfMaps*.a == listOfMaps.collect { it?.a } //equivalent notation
// But this will only collect non-null values
```
)

David implemented a Null Object Pattern for GREL (forgot where in code) that represents a recognized keyword of **null**, similar to 
http://docs.groovy-lang.org/latest/html/documentation/index.html#_null_object_pattern

BUT, if we go with coalesce() , it would need to be a well defined function for our GREL usage.  Because... it performs differently in different languages.  And I am so used to COALESCE in the Database world where the **first** non-null expression is returned.  For example, https://docs.microsoft.com/en-us/sql/t-sql/language-elements/coalesce-transact-sql where coalesce

Think through the need carefully.  WHAT problem do we actually have, and then HOW best to solve it.
The easiest way to solve the OP's immediate problem ?
Support this:
`replace(null,null,"")`

**Comment by eximius313** [comment] 2018-02-14 23:34
@thadguidry 
1) Please also have in mind my conclusion 1) from my initial message
2) `isBlank(" ")` should be `true` ([ref](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-))
3) What would `replace(null,null,"")` do? I have no idea how is it related to concatenating two columns that can have null values

**Comment by thadguidry** [comment] 2018-02-15 01:23
@eximius313 
It would look like this

`cells["Column 3"].value + cells["Column 1"].value.replace(null,"")`
`cells["Column 3"].value + cells["Column 1"].value.replace(null,"ThisIsNull")`

allowing you to replace null values with whatever you want,
instead of throwing our current error of **Error: Cannot retrieve field from null** even when doing the proper syntax in the above 2 examples.

Would that work for you ?

**Comment by fpompermaier** [comment] 2018-02-15 08:27
I agree with @thadguidry...null should be replaced with whatever you want and should not throw any errors when concatenating to other strings. In the end, also when you export a dataset to CSV null and "" are equivalent

**Comment by ostephens** [comment] 2018-02-15 09:52
@eximius313 I've added a new issues #1491 to deal with your Conclusion (1) in the original report

**Comment by eximius313** [comment] 2018-02-15 16:39
Ok, and what's wrong with:
`coalesce(cells["Column 3"].value, "") + coalesce(cells["Column 1"].value, "ThisIsNull")` which seems more intuitive to me?

**Comment by thadguidry** [comment] 2018-02-15 19:32
@eximius313 Sure we can introduce a new coalesce() for you to use instead of replace().  And yes, its easier with coalesce() since null check is a builtin and it removes 1 layer that does not have to be specified by the user as it would be with replace().  

`coalesce(null,"")`
`replace(null,null,"")`

I was just pointing out a minor flaw in our current replace() that we ALSO need to fix up to support null replacement handling to be a nice citizen all around.

**Comment by eximius313** [comment] 2018-02-15 21:32
that sounds great!

**Comment by ostephens** [comment] 2018-02-16 23:04
I've added a new issue for the Coalesce function enhancement.

I'm not completely convinced by the need for `replace(null,null,"")` although I'm happy to write an issue for it if it is needed. At the moment the reason this fails is because the replace function accepts only a string as the first argument and a string or a regular expression as the second argument.

I can't see a problem extending it to work if both the first and second argument are nulls, but it feels it adds complexity to the replace statement which is not needed.

@thadguidry - are you keen we do this?

**Comment by thadguidry** [comment] 2018-02-16 23:16
@ostephens No, that's a null replacement function...different than coalesce().  That would be something like NVL() in Oracle. https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions105.htm

And no, I am indifferent about replace() supporting NVL() like functionality, but others might.  So let them speak up later about it, if they need to.  For the OP's issue, only coalesce() is the wanted position and #1496 should do it.  Thanks for that Owen !

**Comment by ostephens** [comment] 2018-02-22 23:14
I'm in the midst of implementing the new `coalesce` function but have hit an issue. I have a working function as defined in #1496 but I think there is a problem with this fulfilling the original need by @eximius313 (and others).

If we have:

rowId | Col1 | Col2 |
----- | ----- | ------
1        |`null` | string
2       | string | string

In Col1 we can run the function `value.coalesce("")` we get the outcomes:

-  Row 1: `null` ->""
- Row 2: string->string

as expected.

**However** if we try the function `cells["Col1"].value.coalesce("") + cells["Col2"].value` we get:

- Row 1: "Error: Object does not have any field, including value"
- Row 2: "stringstring"

This is because `cells["Col1"].value` is not null. Instead `cells["Col1"]` is null, making `cells["Col1"].value` an error.

This means that it does not solve the problem 

> "My problem was, that I cannot concatenate column values when one cell was null."

So - I'm looking for suggestions as to how we might deliver the desired functionality - I don't have any immediate ideas. @thadguidry @wetneb @ettorerizza ?

**Comment by ostephens** [comment] 2018-02-23 09:07
I slept on it, and have a proposal for a possible way forward - I'd be interested in feedback. 

**Proposal: Extend the `toString` function with two new arguments as follows:**

- Boolean: Treat null as empty string (Default false)
- Boolean: Treat error as empty string (Default false)

`toString(null)` -> "null" (current behaviour)
`toString(null,true)` -> "" (treats null as an empty string)
`toString(<error>)` -> "error" (current behaviour)
`toString(<error>,<true or false>,true)` -> ""

Using my example from above:
rowId | Col1 | Col2 |
----- | ----- | ------
1        |`null` | string
2       | string | string

In Col1 we can run the function `value.toString(true)` we get the outcomes:

-  Row 1: `null` ->""
- Row 2: string->string

If we try the function `cells["Col1"].value.toString(true,true) + cells["Col2"].value` we get:

- Row 1: "string"
- Row 2: "stringstring"

The only thing I don't like about this approach is that it still feels like it is making the user jump through some hoops and it feels a bit verbose still, but it is definitely better than the current situation where you have to use something like:
`if(isNonBlank(cells["Col1"]),cells["Col1"].value,"") + ...`

**Comment by thadguidry** [comment] 2018-02-23 15:19
@ostephens Perhaps you could add the coding pattern of NullText in your coalesce() function?  org.apache.commons.text.StrBuilder has getNullText() and setNullText()

There are tons of examples online and in Github https://github.com/search?p=1&q=getNullText&type=Code&utf8=%E2%9C%93

**Comment by ostephens** [comment] 2018-02-23 17:38
Thanks @thadguidry. 

I'm afraid I don't quite understand your suggestion of using get/setNullText - it feels tangential to the problem here.

The problem is that for a null cell, the expression `cells["Col1"].value` doesn't return null, it returns an error. This means that `cells["Col1"].value.toString().replace("null","")` would also fail in this case.

That's why I'm suggesting that toString would be extended to treat errors as empty strings - because the problem of is dealing with an error output, not dealing with a null output.

**Comment by thadguidry** [comment] 2018-02-23 17:56
@ostephens ??? I'm confused also... are you telling me that when you have a null cell value... that a simple
```value.toString()``` does not convert that to a String representation of "null" in the preview ?  It does for me. https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/util/StringUtils.java

**Comment by thadguidry** [comment] 2018-02-23 18:01
@ostephens oh boy, yeah, I see the issue now...we are not consistent with cells[ ] ... I wonder if something changed or broke ?  I'm using 2.8 here:

![capturenull](https://user-images.githubusercontent.com/986438/36609010-313d36b8-1891-11e8-8d8d-c5502db1602a.PNG)
![capturenull_string](https://user-images.githubusercontent.com/986438/36609019-363f69e2-1891-11e8-880a-f14210a9fe75.PNG)

**Comment by ostephens** [comment] 2018-02-23 18:37
That's it - but it's actually the bit `cells["Column 1"].value` that's the problem. If you strip out the 'toString' part of your expression you'll see that this gives an error `Error: Cannot retrieve field from null` - because the cell is null, rather than the value in the cell. 

I'm not completely sure how this works tbh - but I'm reluctant to change the innards of how we handle null cells - it feels like it could have unexpected side-effects. Hence looking for other approaches

**Comment by thadguidry** [comment] 2018-02-23 18:40
@ostephens its done here https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/model/Cell.java#L68  and do you have "value"... no you don't, so it breaks.  Probably just need to fix it there and put a null check there ?

**Comment by ostephens** [comment] 2018-02-23 18:46
I'll have a look - thanks @thadguidry

**Comment by thadguidry** [comment] 2018-02-23 18:57
@ostephens and @tfmorris is the one who added the toString() method for debugging the cells variable itself so you can do things like `cells["Column 1"].toString()`

Look at the history of things also in our Github and BLAME is very useful view to see timeline of who/where/why for any file in codebase.  I've found it super useful over the years to track regressions, but I don't see one on Cell.java I think.  The impact of cells variable is at the row and column level. And our model folder is where everything comes together.
![blame](https://user-images.githubusercontent.com/986438/36611409-ed9678fe-1898-11e8-8790-c668ab9836f2.PNG)

**Comment by eximius313** [comment] 2018-02-23 19:10
And by the way - this is the initial reason, that forced me to blank all null cells :D

**Comment by ostephens** [comment] 2018-05-17 08:46
With #1598 all the work spawned by this issue has been completed. Thanks to @eximius313 and @thadguidry for their patience and explanations and @joanneong for delivering some of the new functions.

Feeling really pleased with the work we've done here - hope @eximius313 and others find it helpful

**Closed by ostephens** 2018-05-17 08:46 UTC
Labels: component-Logic, enhancement, good first issue

**Comment by eximius313** [comment] 2018-05-17 17:10
Thank you very much `OpenRefine` team!

**Comment by eximius313** [comment] 2018-05-25 19:35
By the way - when do you plan to release 3.0?

**Comment by ostephens** [comment] 2018-05-26 09:13
We will be releasing a beta version of 3.0 very soon (in the next few days I hope but it is all down to someone having the time to build the release)

**Comment by tfmorris** [comment] 2020-10-02 03:37
Is there a summary someplace of all the changes that got made to the null handling?

**Comment by ostephens** [comment] 2020-10-02 08:15
>Is there a summary someplace of all the changes that got made to the null handling?
Short answer is No. The issues and PRs linked back to here are probably the best we have

Not all the changes were directly related to null handling, but the changes included:

* changing the outcome of  `null`.toString() https://github.com/OpenRefine/OpenRefine/pull/1650 
* Add a way of viewing null cells vs blank cells in the UI https://github.com/OpenRefine/OpenRefine/pull/1544
* Addition of the coalesce function https://github.com/OpenRefine/OpenRefine/pull/1536
* Behaviour of "Apply to identical cells" when editing empty or null cells https://github.com/OpenRefine/OpenRefine/pull/1642
* Behaviour on trying to get non-existent fields including trying to get fields from `null` https://github.com/OpenRefine/OpenRefine/pull/1598

**Comment by thadguidry** [comment] 2020-10-02 14:09
@ostephens And the Facet code caused you some grief as well I recall with the changes to strict null handling introduced. https://github.com/OpenRefine/OpenRefine/pull/1666
There are probably others.  Basically it's the PR's from Owen prior and directly after 3.0 , 3.1 , 3.2

**Comment by ostephens** [comment] 2020-10-02 14:37
Agreed there were changes in #1666 but that was later reverted so no longer applies

**Comment by tfmorris** [comment] 2020-10-02 18:56
Thanks for the summary. It doesn't look like there was too much modification of core null handling functionality, so I suspect there are probably a number of internal inconsistencies still. A related issue that I'll just mention in passing is whether functions return `null` or `EvalError` in the case of an error.

The original approach of treating all empty cells equivalently, whether they contain an empty string or nothing at all, is usually what users want, I think, but isn't really compatible the database import/export where NULLs are a thing and they need to be distinguished from empty strings.
