### ISSUE TITLE
Cross function doens't produce the desired results

### ISSUE THREAD

**Issue by mobaset** [OpenRefine/OpenRefine#954] opened 2015-03-02 10:52 UTC
I have two datasets that I need to merge. Basically, I need to retrieve two columns from dataset 2 into dataset 1 using cross function. Dataset1 has 271300 rows, dataset2 has 22000 rows. I'm using a column as a key in dataset1 to lookup the value if matched in dataset2. Not all keys in dataset1 are available in dataset2, but that is fine. The problem is, when using Cross function on the entire dataset1, the result is 0 rows. If I filtered down the rows to a smaller number, the function works. But after some comparison in Excel, I found that Open Refine didn't lookup all the values.

Is this a known bug?

I'm using Open Refine 2.5 (r2407), i have java 1.8 & java 1.6 installed. 

Thanks,
Mo

**Comment by magdmartin** [comment] 2015-03-06 00:31
I see two differents issue in your ticket. 

First, for cell.cross() returning 0 value, this has been addressed in OpenRefine2.6-beta see #432 for reference. 

Second you mention that on a smaller data set Refine doesn't return the value as expected
* Did you trim() your key column before? 
* In the dataset2 do you have duplicate value for your key?
* Can you share your data so we can reproduce it locally?

**Comment by tfmorris** [comment] 2015-03-08 23:02
Please upgrade to OpenRefine 2.6-beta1 and see if it helps.  If you're still seeing the problem, we'll need a test data set to help reproduce the problem.

You might also ask for help on the mailing list, because the cross() function is one of the most difficult to use and people often get it wrong.  For example, it's pretty much the only function that takes a cell instead of a value as an argument.

**Comment by srugano** [comment] 2015-03-26 04:04
I'm on OpenRefine 2.6 beta and the **cell.cross("results_export", "Values")** is returning me an empty array **[]** .

**Comment by magdmartin** [comment] 2015-03-26 11:41
@srugano you need to define which column from the "results_export" project
you want to import. For example *cell.cross("results_export",
"Values").cells["Column 1"].value[0]*

You can learn more on the cell.cross() function here:
http://googlerefine.blogspot.ca/2011/08/vlookup-in-google-refine.html

For support request please use our mailing list:
https://groups.google.com/forum/#!forum/openrefine

Thank you

**Comment by tfmorris** [comment] 2015-03-26 19:42
As Martin said, this discussion is better suited for the mailing list (and
don't hijack someone else's issue unless you're 110% convinced that it's
the same problem as you're seeing).

On Thu, Mar 26, 2015 at 12:05 AM, RUGANO <notifications@github.com> wrote:

> I'm on OpenRefine 2.6 beta and the *cell.cross("results_export",
> "Values")* is returning me an empty array *[]* .
>
If you're getting an empty array (ie null result), Martin's proposed
solution won't help.  Are you getting empty arrays for *all* rows?

The first thing I'd do is triple check your project names, column names,
key values, etc.  Make sure that you've trimmed all whitespace and gotten
rid of anything else which might be messing up the matching.  Cross is one
of the trickiest functions to use because it has some many parameters and
ways to go wrong.

If that doesn't fix things, please post more details on the mailing list,
including, if possible, some example projects that demonstrate the problem.

Tom

**Closed** 2017-06-07 11:14 UTC
