### ISSUE TITLE
Please check the file format

### ISSUE THREAD

**Issue by kswsu** [OpenRefine/OpenRefine#5318] opened 2022-10-06 19:42 UTC
Any Excel document I try to upload (which is the only type of document I upload into OpenRefine) gives me this error message, as of today: "Please check the file format." This is also true of Excel files I have uploaded in the past. When I try to upload the exact same files that have worked with no issue in Open Refine before, they now throw this error.

### To Reproduce
1. First, launch OpenRefine.
2. Then, click Create Project --> Choose Files
3. Then, select a .xlsx file from your computer.
4. Finally, click "Next." Error message will appear: "Please check the file format."

### Current Results
"Please check the file format."

### Expected Behavior
I expect to advance to the next screen with the content loaded.

### Versions
 - Operating System: Apple OS 11.3.1
 - Browser Version:  Safari 14.3.1
 - JRE or JDK Version: I don't know what this means.
 - OpenRefine: OpenRefine 3.4.1 [437dc4d]

### Additional context
I cannot even re-upload the same files I have uploaded in the past. Literally every single Excel file gives me this same error even though they worked fine before today.
<img width="1225" alt="Screen Shot 2022-10-06 at 3 38 42 PM" src="https://user-images.githubusercontent.com/115185909/194404327-4a42143f-f78a-4f50-94c0-02dd00f23874.png">

**Comment by thadguidry** [comment] 2022-10-06 23:15
If the exact same Excel files worked fine before today, perhaps it is a system change on your end somewhere?  Where or how you store the Excel files?

**Comment by thadguidry** [comment] 2022-10-07 05:45
Closing as I cannot reproduce, and this is likely a system environment issue.  Reopen if there are other details missing that might help us reproduce.

**Closed by thadguidry** 2022-10-07 05:45 UTC

**Comment by wetneb** [comment] 2022-10-07 07:32
> When I try to upload the exact same files that have worked with no issue in Open Refine before, they now throw this error.

Can you think of any change that happened in between? Any upgrade of your Java version for instance?

**Comment by kswsu** [comment] 2022-10-07 18:14
No update to Java that I know of, and because most updates have to be done through IT because they require an admin password, it's unlikely. The files I'm accessing are stored on my computer itself.

**Comment by wetneb** [comment] 2022-10-07 18:17
I do not see of how us releasing a new version would have any impact on already released versions (except by showing a notification on the main screen, which is very unlikely to have anything to do with your problem).

**Comment by kswsu** [comment] 2022-10-11 18:01
Hi all: IT installed the latest version of OpenRefine today it it solved the problem. Why the older version stopped reading .xlsx documents, at least in my instance of the program, I do not know.

**Comment by kswsu** [comment] 2022-10-11 22:29
So I'm on the new version now, 3.6.2, which can now read my Excel files. It did save my templating text. But, now nothing works. The file it exports using the code I used to use—which a developer wrote, not me—doesn't have the right title. And even if I fix the title, when I apply the transforms to it using Terminal, which is our usual process, I get a whole list of errors. So, this new version of OpenRefine broke everything.

Kate

**Comment by wetneb** [comment] 2022-10-12 05:52
Hi Kate,

I am sorry to hear that this new version of OpenRefine does not work for you. It looks like the problems you are facing now are no longer relevant to this issue (which was about Excel import). It would be great if you could start a new GitHub issue, or reach out on the mailing list, about those other problems. By reporting on them here, they are unlikely to be acted upon, because this is not a very discoverable location.

**Comment by Hungreeee** [comment] 2023-06-17 11:59
I am having the same issue with the current version. Not sure why this is happening.

**Comment by thadguidry** [comment] 2023-06-17 12:19
@Hungreeee Please open a [New Issue](https://github.com/OpenRefine/OpenRefine/issues/new/choose) with the details.   Thanks!
