### ISSUE TITLE
Text facets show incorrect text. 

### ISSUE THREAD

**Issue by kraidt** [OpenRefine/OpenRefine#2142] opened 2019-08-28 23:33 UTC
**Describe the bug**
Text facets show incorrect text when compared to the original google sheet that was imported. 

**To Reproduce**
1. import from google 
2. text facet a column
3. text facet the next column
4. select item from first facet
5. corresponding item from the second facet is not on the same line as the first facet in the google sheet that was uploaded. 

**Current Results**
shows data that cannot be found in the imported spreadsheet at all.

**Expected behavior**
expected line to match google sheet contents.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS Mojave 10.14.6
 - Browser Version:  Chrome 19
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version 3.2

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment] 2019-08-29 12:44
Hi @kraidt, thanks for this report! It would be helpful to have a bit more information about your issue.

What sort of unexpected data do you see in the text facet? Could you share your dataset, maybe? Or provide screenshots which demonstrate the issue?

**Comment by wetneb** [comment] 2019-12-21 18:22
Closing as not reproducible since not enough information was provided to debug this.

**Closed by wetneb** 2019-12-21 18:22 UTC
Labels: bug, facets, not reproducible
