### ISSUE TITLE
Edit > Apply to all identical cells behavior modification

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#569] opened 2012-10-15 03:41 UTC
_Original author: ericjarv...@gmail.com (May 05, 2012 16:42:29)_

Behavior modification request:

-When editing large numbers of records, and on high page numbers(e.g.- page 5000 of 10,000), when the user edits a records and applies the change to all of the same(e.g.- Edit &gt; Apply to all identical cells), the table refreshes back to the first page. Suffice it to say, it is a major drag having to manually click 'next... next... next...' 500 times to get back to record 5000.  

The ideal behavior when using 'Edit &gt; Apply to all identical cells' should be to refresh, but instead of kicking user back to the first record/page, it should refresh and maintain the same page(minus whatever records may have fallen off the Facet list).   

Thanks,

Eric Jarvies

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=569_

**Comment by wetneb** [comment] 2019-12-20 14:48
Closing as duplicate of #33.

**Closed by wetneb** 2019-12-20 14:48 UTC
Labels: bug, duplicate, imported from old code repo, priority: Medium
