### ISSUE TITLE
Reconcile candidate popup gets cutoff sometimes along top edge

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#505] opened 2012-10-15 03:39 UTC
_Original author: thadguidry (December 14, 2011 18:22:14)_

The Reconcile candidate popup sometimes gets cutoff along the top in both Firefox and Chrome browser when a Standard Reconcile service is setup and used, rather than Freebase Reconcile using the Suggest Widget popup.

We need to add something like margin-top: 10px or whatever works to keep the popup from never moving up past the browser screen view and no matter if they are displaying 10, 25, 50 rows, etc.

Popup should ideally be centered in view and a bit down from the top edge of browser window.

http://code.google.com/p/google-refine/source/detail?r=2414

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=505_

**Comment by thadguidry** [comment] 2018-04-17 22:09
@wetneb would you say this is resolved now ?

**Comment by wetneb** [comment] 2018-04-19 08:48
@thadguidry I can't think of a situation where I encountered something like this - I think we would need a screenshot to see exactly what the issue is. Closing as non reproducible in doubt.

**Closed by wetneb** 2018-04-19 08:48 UTC
Labels: bug, component-UI, imported from old code repo, priority-Medium, reconciliation
