### ISSUE TITLE
Column names issue when importing json file

### ISSUE THREAD

**Issue by juanmas07** [OpenRefine/OpenRefine#1147] opened 2016-08-25 14:23 UTC
In Version 2.6-rc.2 [TRUNK] I'm getting someting like this in all the column names:

_ - _ - year

although the json is well formed:

[{"id":"1021","line_name":"W07004","breeder":"Barrow","origin":"CBS","year":"2010","status":...

**Comment by Opennat** [comment] 2016-09-01 16:16
Same https://github.com/OpenRefine/OpenRefine/issues/1017

**Comment by wetneb** [comment] 2017-08-02 08:04
Closing as a duplicate of #1017.

**Closed by wetneb** 2017-08-02 08:04 UTC
Labels: bug, import
