### ISSUE TITLE
Call the filter() function from a method of an array

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#4923] opened 2022-06-03 16:03 UTC
The `filter()` function cannot be called from an Array. I would like to have it as it make the code more readable.

### Proposed solution
![image](https://user-images.githubusercontent.com/12217525/171902489-13d09bf4-f0f3-449c-83e6-e00e2e4e9ea1.png)

### Alternatives considered

![image](https://user-images.githubusercontent.com/12217525/171902587-67d063b9-f8b3-40ec-bdd2-0e4760d37c8a.png)

**Comment by antoine2711** [comment] 2022-06-03 18:14
> Even better would be to know during GREL parsing that the Object is an Array having the .filter() function applied and completely avoiding the variable passing of `vC`. Concisely: `cell.recon.candidates.filter(score > 70)` Making "applying a variable" an actual optional based on user needs in the expression.

That might make the coding of the parsing very hard. But, would could have an implicit variable, like `this` or `item`…
`cell.recon.candidates.filter(item.score > 70)`

But I wouln'd ask for that, I think the other syntax is already well accepted and easier to remember.

Regards, Antoine

**Comment by thadguidry** [comment] 2022-06-03 18:42
It's something we discussed during the early days of GREL design... just thought I would mention it. :-)

**Comment by antoine2711** [comment] 2022-06-03 18:50
> It's something we discussed during the early days of GREL design... just thought I would mention it. :-)

I undestand @thadguidry. I'm not against it. I just think it's hard to code, but I might be wrong. I think this issue is not receivable anyway, because filter() is actually a CONTROL function, and those can't be called from an object… 

Regards, Antoine

**Comment by thadguidry** [comment] 2022-06-03 18:54
Well for filter() that might have to change to be just a regular function, if my hunch is right after 4.0 :-)  We'll have to discuss this while toying with 4.0 in more depth later on.

**Comment by ostephens** [comment] 2022-06-06 10:39
As I understand it this is essentially a duplicate of #2618, although with a focus on a specific control rather than controls in general?

**Comment by thadguidry** [comment] 2022-10-15 04:16
Closing issue as won't fix since it's a fundamental change to our Control versus Function handling and only a syntactic convenience.

**Closed by thadguidry** 2022-10-15 04:16 UTC
Labels: enhancement, to be reviewed, grel
