### ISSUE TITLE
Styling issues in sidebar sub-hyperlinks

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3452] opened 2021-01-07 14:43 UTC
Subheading for side-bar has weird styling issues.

### To Reproduce
1. First, build a documentation website
2. Then, click on a sub-menu hyperlink with a dropdown
3. Finally, see the issue

### Expected Behavior

The style should be proper
### Screenshots

<img width="1253" alt="Screenshot 2021-01-07 at 8 10 38 PM" src="https://user-images.githubusercontent.com/44091822/103905544-c32b4f00-5124-11eb-9823-d5153e44dd00.png">

### Additional context

Browser: *Safari*

**Comment by wetneb** [comment] 2021-01-07 21:44
It's not exactly clear to me what the issue is, but if you want to propose an improvement I think it will make things clearer :)

**Comment by wetneb** [comment] 2021-02-02 17:02
@kushthedude I'll just close this as I really cannot see any issue with the style here (both with Chromium and Firefox). Safari should be the same as Chromium, I would expect. Feel free to reopen if I missed anything here.

**Closed by wetneb** 2021-02-02 17:02 UTC
Labels: UI, bug, documentation
