### ISSUE TITLE
Apply to all Identical Cells resets viewport to row 1

### ISSUE THREAD

**Issue by david-waterworth** [OpenRefine/OpenRefine#4293] opened 2021-11-13 00:10 UTC
If I select `Edit`, make a change and `Apply`, the viewport remains on the row I was editing. If however I select Edit then `Apply to all Identical Cells` after apply the viewport resets to row 1

### To Reproduce
1. View as rows
2. Show 1000 rows
3. Scroll to a row off the bottom of the page
4. Select a cell and edit it
5. Select `Apply to all Identical Cells`

### Current Results
View resets to row 1

### Expected Behavior
View should not reset to row 1, should be consistent with pressing `Apply` in step 5

### Versions
 - Operating System: Ubuntu 20.04
 - Browser Version: Chrome Version 95.0.4638.69
 - JRE or JDK Version: openjdk version "11.0.11" 2021-04-20
 - OpenRefine: OpenRefine 3.5

**Comment by david-waterworth** [comment] 2021-11-13 00:54
Also note `Edit Cell` / `Transform` does the same thing.

Related - the preview when you're attempting to create a GREL expression always seems to show the topk entries. This makes it really difficult if you're trying to develop a transform for specific rows. The preview is of little use since it doesn't show the rows you're trying to transform and once applied the rows you're trying to transform are also no longer visible.

**Comment by thadguidry** [comment] 2021-11-13 02:31
@david-waterworth Regarding your last comment for specific rows and transforming them and seeing a preview.  Many of us just Star or Flag those rows and then add a Facet for Star or Flagged rows to filter the grid and then do further transforms... the Expression preview dialog will then only show what the grid shows.

**Comment by david-waterworth** [comment] 2021-11-13 03:54
Thanks @thadguidry I didn't originally realise you could filter and then apply transforms to the filtered rows. That makes things a lot easier!

**Comment by thadguidry** [comment] 2021-11-13 04:19
No problem. If you still feel you need that feature for the Reset then let us know further.  I'd imagine there's a bit of nuance with how you can generally filter, transform, filter by using our various facets or your custom ones depending on your needs at various stages if your workflow. But we always listen for ways to help further if something could be made easier.

**Comment by wetneb** [comment] 2021-11-13 08:50
Although it is about scrolling and not page changes, I would say this is mostly a duplicate of #33, our longest standing issue.

**Comment by wetneb** [comment] 2023-02-27 12:50
Fixed by #5411.

**Closed by wetneb** 2023-02-27 12:50 UTC
Labels: duplicate, enhancement, UI
