### ISSUE TITLE
Fix mechanism to download Maven on the fly (MacOS)

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4865] opened 2022-05-18 15:33 UTC
I tried to run https://github.com/wetneb/OpenRefine/tree/4682-commons-upload to test [uploading to Wikimedia Commons](https://github.com/OpenRefine/OpenRefine/pull/4863), but OpenRefine refused to start. 

### Current Results
See log below

### Expected Behavior
Maven is downloaded and I can run OpenRefine

### Terminal log
```
Sandras-MacBook-Air:~ fokky$ /Users/fokky/Documents/GitHub/OpenRefine/upload-test/refine ; exit;
Using refine.ini for configuration
-------------------------------------------------------------------------------------------------
You have 173M of free memory.
Your current configuration is set to use 1024M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://docs.openrefine.org/manual/installing#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
ls: server/target/lib: No such file or directory
\nCould not find Maven locally, starting download for Maven ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
/Users/fokky/Documents/GitHub/OpenRefine/upload-test/refine: line 236: exit: Error while downloading https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz: numeric argument required
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

### Versions
 - Operating System: MacOS 10.13.6
 - Browser Version: Chrome 101.0.4951.64 (Official Build) (x86_64)
 - JRE or JDK Version: 
 - OpenRefine: testing https://github.com/wetneb/OpenRefine/tree/4682-commons-upload

**Comment by wetneb** [comment] 2023-02-07 09:58
Duplicate of #5484.

**Closed by wetneb** 2023-02-07 09:58 UTC
Labels: bug, mac, maven
