### ISSUE TITLE
Import JSON Streaming

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#963] opened 2015-03-26 22:04 UTC
There are two versions of this:
1. Line delimited JSON
2. Concatenated JSON

See http://en.wikipedia.org/wiki/JSON_Streaming

If our underlying parsers don't handle this directly, we could probably transform the sequence of JSON objects into an array.  ie

[{a},{b}] instead of {a}{b} or 
{a}
{b}

**Comment by wetneb** [comment] 2017-08-02 08:09
Closing as a duplicate of #1135.

**Closed by wetneb** 2017-08-02 08:09 UTC
Labels: enhancement, import
