### ISSUE TITLE
Browse this cluster does not show records with accents

### ISSUE THREAD

**Issue by viktordickmm** [OpenRefine/OpenRefine#1157] opened 2016-10-12 15:09 UTC
Records with Special Characters / Accents like é È etc. do not appear in "Browse this cluster" window. Most probably they are not correctly encoded in URL.

Window remains empty:
![openrefine_empty_browse_records](https://cloud.githubusercontent.com/assets/22795905/19315519/48e88d5c-909e-11e6-93ac-294d2281d0a3.PNG)

Tested on Windows 10 Firefox 49.0.1

**Comment by viktordickmm** [comment] 2017-03-30 09:05
Hello,

is there any workaround or plans to correct this?

Many thanks,
Viktor

**Comment by thadguidry** [comment] 2017-04-09 12:39
@viktordickmm I'm not sure what your facet represents... can you show me the data that forms the cluster ?  Did you choose UTF-8 for the character encoding when you originally imported into OpenRefine ?

**Comment by tfmorris** [comment] 2020-06-03 18:35
It looks like this may have gotten fixed as a side effect of some other change. When I create a two line project consisting of "Rene" and "René", cluster, then click "Browse cluster", I get the following, correctly escaped URL:

http://127.0.0.1:3333/project?project=1704077407562&ui=%7B%22facets%22%3A%5B%7B%22c%22%3A%7B%22type%22%3A%22list%22%2C%22name%22%3A%22Column%201%22%2C%22columnName%22%3A%22Column%201%22%2C%22expression%22%3A%22value%22%7D%2C%22o%22%3A%7B%22sort%22%3A%22name%22%7D%2C%22s%22%3A%5B%7B%22v%22%3A%7B%22v%22%3A%22Rene%22%2C%22l%22%3A%22Rene%22%7D%7D%2C%7B%22v%22%3A%7B%22v%22%3A%22Ren%C3%A9%22%2C%22l%22%3A%22Ren%C3%A9%22%7D%7D%5D%7D%5D%7D

I'm going to close this, but feel free to reopen if you have an example to reproduce the original problem.

**Closed** 2020-06-05 08:29 UTC
Labels: UI, clustering, encoding, not reproducible
