### ISSUE TITLE
Use column name as default property name for including other column data in reconciliation

### ISSUE THREAD

**Issue by adamhadani** [OpenRefine/OpenRefine#1449] opened 2018-02-02 00:21 UTC
Hey,

currently it looks like when doing reconciliation, if I choose `Also use relevant details from other columns` I can check various boxes for columns I wish to inculde, but if I leave the textbox near them empty (for `As Property`) it doesn't look like they actually get sent.

I'd expect a more sensible default to be - whenever I check a box, that column name is used by default as the property name, and  it gets sent as part of request (Otherwise I'd expect some UI validation to stop me from just checking the box without filling the textbox!)

A quick fix could be just populating the textbox in the UI by default with the column name when I click the checkbox next to it.

This makes a huge difference UX-wise to editors who need to do this many times

**Comment by wetneb** [comment] 2018-02-02 03:44
@adamhadani I agree that the UI could be improved there.

The problem is that the most reconciliation services will only accept a limited, closed-list of strings as properties, which is why we recommend to provide auto-completion there. We cannot expect that the column names will be recognized by the reconciliation service as valid properties: the point of this dialog is to let the user perform the alignment, ideally with the help of suggestions provided by the service as they type.

There are also cases where my dataset contains a column matching a property of my foreign service exactly, but I do not want it to be used for reconciliation (for instance because it has unreliable values). So even if we could magically match columns to properties, it might not be something we want to do implicitly. We could definitely consider adding heuristics to do some automatic schema alignment here, but I think the user should ask for it explicitly (and that's a non-trivial task).

One change I would definitely like to see is some sort of visual clue that a property has been matched with the suggest service. Currently if you type the property name exactly as it is stored in the reconciliation service, there is no way to tell if I have correctly clicked on the suggestion to match it with an identifier.

**Comment by adamhadani** [comment] 2018-02-09 21:27
@wetneb I think what I'm saying is simpler. Something like this:

1. When I check a box to signify column should be included, It should be *required* to provide a non-empty value in the textbox next to it for it to be passed to API in the textbox (since otherwise it just silently doesn't get sent which is not great UX)
2. On top of this, I suggest further that a sensible **default value** for that textbox, when I click the checkbox, is simply the name of the column (which is what appears to the left of the checkbox). Of course different use cases might call for customizing this, but this is a great starting point/default value to use when I check a box to indicate I wish a specific column should be passed along to backend

**Comment by wetneb** [comment] 2018-02-10 09:33
@adamhadani Okay for 1. (so you would just refuse to start the reconciliation process without a property name there).

But I'm still not convinced by 2. By providing a default value there, you would indicate that there could be cases where the user would not have to edit this field and leave the default value as it is. The problem is that for all reconciliation services which provide a suggest service to translate property names to property ids, this is wrong: we always want the user to use the suggest service to translate the property name to an id. So even if you have a column "country" in your dataset, whose name matches exactly the English label of the P17 property in Wikidata, simply writing "country" in the reconciliation dialog will not work.

**Comment by wetneb** [comment] 2019-12-20 19:05
For 1. this is covered by #2230.
For 2. this would just not work in general, so closing this issue.

**Closed by wetneb** 2019-12-20 19:05 UTC
Labels: enhancement, reconciliation, to be reviewed
