### ISSUE TITLE
XLSX export error

### ISSUE THREAD

**Issue by richyvk** [OpenRefine/OpenRefine#1984] opened 2019-03-14 03:54 UTC
Getting the following error trying to export to XLSX in version 3.2:

HTTP ERROR 500
Problem accessing /command/core/export-rows/extract-judgments-QDC-csv.xlsx. Reason:

    DEFAULT
Caused by:
java.lang.NoSuchFieldError: DEFAULT
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:125)
	at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:75)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:115)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Powered by Jetty://

Using version 3.2 on MacOS Mojave.

CSV and XLS exports working OK.

**Comment by wetneb** [comment] 2019-03-14 08:48
I think that is the same root cause as #1981.

**Comment by wetneb** [comment] 2019-04-18 19:35
Closed by #2011.

**Closed by wetneb** 2019-04-18 19:35 UTC
Labels: bug, export, pull-request-pending
