### ISSUE TITLE
Problems with Property Page(s) (P304) in Wikidata Schema

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#3790] opened 2021-04-06 16:03 UTC
i want to add some bibliographic data to Wikidata, but unfortunately openRefine said, my "schema is incomplete"

### To Reproduce
1. create a new schema
2. add Property page(s) (P304)
3. drop any column values containing some page like values.

### Current Results
* In the preview tab i receive "Your schema is incomplete, fix it to see the preview."
* In the CLI i fetch the following 
```
Exception caught (5ms)
java.util.regex.PatternSyntaxException: Unknown inline modifier near index 3
^(?'r'(?'p'(?'d'\d+)(?'w'[A-Za-z]+)?|\g'w'(?:\g'd'\g'w'?)?)(?:[-–]\g'p')?)(?:[,;]\s?\g'r')*$
   ^
```

### Expected Behavior
* Show me my bibliographic wikidata-schema, containing the page(s)-Statement.

### Versions
 - Operating System: ubuntu 20.04
 - Browser Version: firefox 87
 - JRE or JDK Version: OpenJDK 11.0.10
 - OpenRefine: 3.4.1

**Comment by gitonthescene** [comment] 2021-04-07 04:03
Would you be able to add some screenshots?  I for one am not following your description of the problem.  Being as specific as possible always helps.

**Comment by gitonthescene** [comment] 2021-04-07 06:02
I think this goes back to the format constraint defined [here](https://www.wikidata.org/wiki/Property:P304).  That regex seems not to be parseable.  Perhaps it's best to address the people who made the change on the Talk page for that property.  It looks like it was changed in November of last year by Verdy p.  I can't parse this regular expression in python, but I could parse the previous expression.

**Comment by wetneb** [comment] 2021-04-07 07:35
Duplicate of #3274: the problem is solved in the development version of OpenRefine, that you can install from here:
https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases

**Closed by wetneb** 2021-04-07 07:35 UTC
Labels: bug, to be reviewed

**Comment by gitonthescene** [comment] 2021-04-07 07:37
FWIW, it looks like the syntax of the regular expression [can be specified](https://www.wikidata.org/wiki/Property:P4240)
