### ISSUE TITLE
Regex Filter hanging

### ISSUE THREAD

**Issue by mechawatts** [OpenRefine/OpenRefine#1199] opened 2017-06-08 16:49 UTC
When I use the Regex option of the text filter, the 'Working…' dialog appears, but never goes away. For simple filters (two or three characters) the correct results appear behind the dialog, but I can't interact with them; more complicated filters (lots of | and ?) never display. In both cases, I can re-enter another query, and the background gets progressively greyer each time.

OpenRefine 2.7-rc2
Chrome Version 58.0.3029.110 (64-bit)
Windows 7 sp1 (64-bit)

**Comment by thadguidry** [comment] 2017-06-08 17:04
You might not be running OpenRefine with enough memory...especially if you have a really long string that your trying to parse out.  https://github.com/OpenRefine/OpenRefine/wiki/FAQ%3A-Allocate-More-Memory

An alternative is to use Jython as your expression engine instead of GREL.

```
import re
m = re.search('(?<=abc)def', 'abcdef')
return m.group(0)
```

More info on our wiki here: https://github.com/OpenRefine/OpenRefine/wiki/Jython

I'll close this issue out as its a known handling case (probably the lookahead in the Java Regex Engine as always) that we can assist with on our mailing list.  It's not a bug.

**Closed by thadguidry** 2017-06-08 17:04 UTC
Labels: wontfix
