### ISSUE TITLE
Cannot edit project metadata if OR is not in English

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1350] opened 2017-11-20 12:33 UTC
Could it be simply because the word "About" needs to be translated? 

![screenshot-localhost-3333-2017-11-20-13-31-48-005](https://user-images.githubusercontent.com/6286410/33018579-41e93852-cdf7-11e7-8fec-17ef5d53e7f2.jpeg)

**Comment by jackyq2015** [comment] 2017-11-20 13:31
right, the "About" link is not shown because it is not translated. could you help to translate it in French from the weblate(you can find the link from readme page). The key is under "core-index-open" section.

**Comment by ettorerizza** [comment] 2017-11-20 13:34
I will try to translate "About" into all languages supported. But how does this system work? Does Weblate update the interface itself in the development version?

**Comment by jackyq2015** [comment] 2017-11-20 14:35
That will be merged automatically. It supposed to fallback to English. I will double check on this.

**Comment by thadguidry** [comment] 2017-11-20 15:29
@jackyq2015 Yes it falls back to English, @wetneb and I already confirmed this.

**Comment by ettorerizza** [comment] 2017-11-20 15:40
The word "About" has been translated on Weblate into all language.

**Comment by jackyq2015** [comment] 2017-11-20 16:00
Just tried to remove a translation "rename" from import page, the fallback dose NOT happen. something is broken on this part in general. Not sure started from when though.  will look into this.

**Comment by wetneb** [comment] 2017-11-20 16:56
We probably need to configure weblate so that by default the strings are copied from English into the localization files for other languages. Also, it could be useful to have a "feature freeze" period before a release so that translators have the time to catch up on new messages to translate.

**Comment by thadguidry** [comment] 2017-11-20 17:04
@wetneb ah!

**Comment by jackyq2015** [comment] 2017-11-20 18:08
I am sure we have the fallback. Just tried up to version 2.6, the feature is not working properly. have to dig further.

**Comment by jackyq2015** [comment] 2017-11-20 20:48
looks like we are wrong. there is "default language" in the code but never worked.
we can enable the fallback plugin jquery.i18n.fallbacks.js to have this:
https://github.com/wikimedia/jquery.i18n

@ostephens , could you take a look of this?

**Comment by thadguidry** [comment] 2017-11-20 21:00
@jackyq2015 and then how does the existing Pull Request affect this or that ? https://github.com/OpenRefine/OpenRefine/pull/1285

**Comment by jackyq2015** [comment] 2017-11-20 21:08
@thadguidry It is not merged yet

**Comment by thadguidry** [comment] 2017-11-21 05:42
@jackyq2015 lolol, I KNOW that.  What's the effect of the changes in that pull request ?  How do they relate to this issue is my wonder as well.

**Comment by ostephens** [comment] 2017-11-27 14:58
@jackyq2015 I've had a look, but I think until we switch to using the wikipedia i8n library (as per the PR @thadguidry asked about) we can't use the fallback option in isoloation.

So I'd suggest that any effort here should be put into getting #1285 to the point where we can merge?

**Closed** 2019-11-18 22:01 UTC
Labels: bug
