### ISSUE TITLE
string.find() fails with regular expression

### ISSUE THREAD

**Issue by frederik-elwert** [OpenRefine/OpenRefine#3170] opened 2020-09-07 11:24 UTC
### To Reproduce

1. Create a test project from clipboard with just "Test 123"
2. Choose "Add column based on this column"
3. Past the expression `value.find('[T]')`

### Current Results

With a regular expression like this, it returns an empty array. On the console, an exception is shown:

```
13:16:42.937 [          org.mortbay.log] Error for /command/core/preview-expression (2776ms)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:238)
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at com.google.refine.expr.functions.strings.Find.call(Find.java:52)
	at com.google.refine.grel.ast.FunctionCallExpr.evaluate(FunctionCallExpr.java:69)
	at com.google.refine.commands.expr.PreviewExpressionCommand.doPost(PreviewExpressionCommand.java:164)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The function works with a simple string search such as `value.find('T')`, returning `[ "T" ]` as expected.

### Expected Behavior

The function should return an array of matches, in this case `[ "T" ]`.

### Versions
 - Operating System: Ubuntu 20.04
 - Browser Version: Firefox 80.0
 - JRE or JDK Version: openjdk version "11.0.8" 2020-07-14
 - OpenRefine: 3.4

**Comment by wetneb** [comment] 2020-09-07 12:03
Thanks @frederik-elwert for getting in touch!

To search for matches of a regular expression, you need to use `/[T]/', not `'[T]'`, as the latter will search for `[T]` as a string. I do not think this has changed in 3.4 - you should have the same behaviour in earlier versions.

Your server logs seem to indicate that OpenRefine is running out of memory, so I suspect you are dealing with a large project. You should probably increase the amount of memory allocated to OpenRefine:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ-Allocate-More-Memory

Let me know if that helps!

**Comment by frederik-elwert** [comment] 2020-09-07 12:50
Thank you, @wetneb, for the hint! I think I missed the interface change, since the syntax I was using works with OpenRefine 3.1. (I was testing an old lesson I wrote with the new release and encountered the issue). I just checked, and indeed the behaviour is the same in 3.3, so it’s not a regression in 3.4 as I first assumed.

Still, looks like there’s a bug lurking somewhere. I re-started OpenRefine and really just used that tiny test project I described above, so memory should not be an issue here. I guess there’s a memory leak or something in the function that blows up memory usage while handling the string? But I don’t have much knowledge of Java, so I have no idea what actually might be going on.

**Comment by wetneb** [comment] 2020-09-07 13:04
To be honest I don't remember any change on this between 3.1 and 3.3 either.

Concerning the memory leak, do you think you could share your test project (as an OpenRefine project)?

**Comment by frederik-elwert** [comment] 2020-09-07 13:30
Sure! [clipboard.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/5183295/clipboard.openrefine.tar.gz)

I don’t know if it shows much. I also noticed that I don’t get the exception the first time I write the expression in the dialog, but only after trying out some expressions. But then it is reproducible. This might be a hint that the memory runs full only after a while.

**Comment by franparras** [comment] 2020-12-13 22:04
@frederik-elwert  I can't reproduce your issue, what is your mem configuration? to see if I can reproduce this issue. My mem configuration is 8GB.

**Comment by frederik-elwert** [comment] 2020-12-14 06:58
Weird, no, now I also cannot reproduce the issue anymore. I don’t think I changed anything. But maybe it was a glitch somewhere. Thanks for investigating!

**Comment by thadguidry** [comment] 2020-12-14 15:05
@frederik-elwert Great!  Then we'll close this issue, we can always reopen later if you eventually figure out how to reproduce.

**Closed by thadguidry** 2020-12-14 15:05 UTC
Labels: bug, to be reviewed
