### ISSUE TITLE
Writing Custom Expression via Transform

### ISSUE THREAD

**Issue by vineetharkut** [OpenRefine/OpenRefine#1811] opened 2018-11-06 16:07 UTC
**Describe the bug**
Writing Custom Expression via Transform using Python as an language showing me message "internal error"

**To Reproduce**
1. Go to Edit Cell from drop down list
2. Click on Transform
3. Select Python as language from the drop down list
4. Write this custom expression in expression section 
    return value if value !="" else "Fill Empty Cell"

**Current Results**
The API is returning "internal error" but the expression is correct. It was wrong last week but tried now is showing that message.

**Expected behavior**
The expression will run for each cell and check whether it is empty if empty then the given string will be saved otherwise existing value will be saved.

**Screenshots**
![menu to short csv openrefine](https://user-images.githubusercontent.com/34603714/48076804-053a6c80-e20c-11e8-851a-0d1ac0872ee2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta]

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by ostephens** [comment] 2018-11-09 14:19
@vineetharkut can you confirm which version of OpenRefine you are using? I've just tested this on OpenRefine 3.0 (the current version) and it seems to be working OK for me.

It would be good to know if this is just an issue in an earlier version of OpenRefine or if something else is happening

**Comment by vineetharkut** [comment] 2018-11-10 11:03
@ostephens thanks for reply
Yes you are right it was working for me also but suddenly it is showing me "internal error" from past week do not know what happen and I am using version 3 of open refine only. For more clarity i am sharing a [google drive link](https://drive.google.com/file/d/1GaHhmbaXKylBuPSnayE8ZBKBT_QAqSGo/view?usp=sharing) which contain video, what i am doing if i does any mistake then correct me. Basically in video i am showing the version which i am using then uploading one csv list from project list section and then previously i am made first cell of event column empty and then using transform to fill that empty cell by using custom expression.

**Comment by ostephens** [comment] 2018-11-11 21:10
Thanks for the video. From that, it looks like there is a more general error than in particular using ```return value if value !="" else "Fill Empty Cell"``` as I can see even just ```return value``` gives an internal error.

What operating system are you on?
Can you have a look at the command line window (on Windows or Linux - you won't see this on Mac) and see if there are any error messages in there?

Thanks

**Comment by thadguidry** [comment] 2018-11-17 21:10
@vineetharkut Please perform the following and then reply with the output...

While OpenRefine is running...
1. If you are running the JRE and not the JDK, then stop here, [install the JDK 8](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), and continue.
2. Start ANOTHER New Command Prompt terminal window, in Cortana search box type `cmd` & hit ENTER
3. First let's find the Pid number that OpenRefine is running on... so issue this command.
    `C:\Users\THAD>"C:\Program Files\Java\jdk1.8.0_191\bin\jcmd"`

    should result in something like:

    ```
    C:\Users\THAD>"C:\Program Files\Java\jdk1.8.0_191\bin\jcmd"
    16064 com.google.refine.Refine
    6512 sun.tools.jcmd.JCmd
    
    C:\Users\THAD>
    ```
4. Then with that Pid number issue the command again but the `VM.properties` added, for example:

    `C:\Users\THAD>"C:\Program Files\Java\jdk1.8.0_191\bin\jcmd" 16064 VM.system_properties`

5. Copy and paste the output into your reply

My hunch is that in the last week, something you updated or installed has caused the JVM or Python or Path to cause this issue.

**Comment by thadguidry** [comment] 2022-10-19 01:24
Cannot reproduce, closing.

**Closed by thadguidry** 2022-10-19 01:24 UTC
Labels: bug, waiting on submitter feedback, jython
