### ISSUE TITLE
Modal dialogue buttons should be right-aligned

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#4564] opened 2022-02-25 07:20 UTC
Many of the modal dialogue buttons are left-aligned, while it is standard that they should be right-aligned

The following dialogs have the buttons left-aligned:

Export->Custom tabular exporter
Export-> SQL Exporter
Undo/Redo-> Extract operation history
Undo/Redo->Apply Operation History
All->Edit all columns->Transform
All->Edit all columns->Trim leading and trailing whitespace
All->Edit all columns->Collapse consecutive whitespace
All->Edit all columns->Unescape HTML entities
All->Edit all columns->Replace smart quotes with ASCII
All->Edit all columns->To titlecase
All->Edit all columns->To uppercase
All->Edit all columns->To lowercase
All->Edit all columns->To number
All->Edit all columns->To date
All->Edit all columns->To text
All->Edit all columns->To null
All->Edit all columns->To empty string
Column->Facet->Custom text facet on column
Column->Facet->Custom numeric facet on column
Column->Edit cells->Split multi-valued cells
Column->Edit cells->Join multi-valued cells
Column->Edit cells->Replace
Column->Edit Column->Transform
Column->Edit Column->Add column by fetching URLs based on column X
Column->Edit Column->Add column based on column X
Column->Edit Column->Split column X into several columns
Column->Edit Column->Join columns
Column->Transpose->Transpose cells across columns into rows...
Column->Transpose->Transpose cells in rows into columns...
Column->Transpose->Columnize by key/value columns...
Column->Sort
Column->Reconcile->Actions->Match all filtered cells to...
Column->Reconcile->Copy recon judgments from column X
Column->Reconcile->Use values as identifiers
Column->Reconcile->Add column containing entity identifiers on Bird

### Proposed solution
Right-align the buttons in the listed dialogues

**Comment by wetneb** [comment] 2022-02-25 07:37
Duplicate of #4457 (but I definitely agree)

**Comment by wetneb** [comment] 2022-02-25 07:47
Let's keep this issue since it has a nice review of the current state of dialogs.

**Closed** 2022-03-01 09:26 UTC
Labels: bug, usability, UI, good first issue
