### ISSUE TITLE
Enable hyperlinks in in-tool Help field

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3579] opened 2021-02-04 20:02 UTC
The expressions editor window includes a Help tab that has some plain-text information about each variable and function.

![display3](https://user-images.githubusercontent.com/28012148/106948555-d6b4e000-66f9-11eb-8b06-bf4c5b181b0f.PNG)

I am editing this text right now to match the user manual. I'd like the fields to render with links (they currently just have full URLS that users can copy-paste). 

If you look into the code, you'll find that the function files themselves support the Help entries, for example for `cross()`:

>     @Override
>     public String getDescription() {
>         return "Looks up the given value in the target column of the target project, returns an array of matched rows. Two values match if and only if they have the same string representation. " +
>                 "The first argument will be interpreted as cell.value if set to cell. " +
>                 "The second argument will be interpreted as the current project name if omitted or set to \"\". " +
>                 "The third argument will be interpreted as the index (starts from 0) column if omitted or set to \"\"";
>     }
> 
>     @Override
>     public String getParams() {
>         return "cell or value, string projectName (optional), string columnName (optional)";
>     }
> 
>     @Override
>     public String getReturns() {
>         return "array";
>     }

### Proposed solution
Render these text entries with hyperlinks, somehow! Whether it's simple HTML or markdown or what-have-you, I can work with it.

**Comment by sarahelshabrawy** [comment] 2021-02-04 20:36
I would like to help with this issue

**Comment by wetneb** [comment] 2021-02-04 20:44
Thanks! Note that there will be a few design decisions to do on this issue, so perhaps it's worth discussing your approach here before opening a pull request, to make sure we agree on the direction.

**Comment by sarahelshabrawy** [comment] 2021-02-10 15:19
So my approach is to delete the String URL reference from all translation .json files and add an anchor tag in expression-preview-dialog class to stand for all languages, Another change is to replace .text() with .html() in order to render the html content of the String of the table cell
Below is a screenshot of the link rendered
![image](https://user-images.githubusercontent.com/58959185/107526072-2266fe00-6bc0-11eb-9a4f-4bb16a6f6296.png)
Is that okay ?
As for the other link I have a question about it.

**Comment by wetneb** [comment] 2021-02-10 16:53
I think allowing HTML in translations is a sensible way to go. Since we review the translation updates as pull requests we can consider these strings as trusted. Allowing HTML markup could be an opportunity to style code samples more nicely (such as `row.index` instead of 'row.index').

**Comment by sarahelshabrawy** [comment] 2021-02-10 17:19
I agree, I will go with that approach then and create a pull request.

**Comment by NikitaEmberi** [comment] 2021-02-15 21:10
Hey, I am new to open source contribution. I see even though @sarahelshabrawy  has issued a pull request, there were merge conflicts. This issue seems like something I could work on. I am not sure if @sarahelshabrawy is already working on it, can I also try for the same issue?

**Comment by tfmorris** [comment] 2021-02-16 01:23
@NikitaEmberi The issue is still assigned to them and the last activity was only a few days ago. Please choose an issue which isn't assigned to anyone.

**Comment by sarahelshabrawy** [comment] 2021-02-17 12:00
I solved the conflicts I had.
I opened a new PR and I'm waiting for a review.

**Closed** 2021-02-20 11:56 UTC
Labels: UI, enhancement, good first issue, grel
