### ISSUE TITLE
IllegalStateException: Committed when fetching favicon

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#416] opened 2012-10-15 03:35 UTC
_Original author: tfmorris (June 23, 2011 20:40:35)_

Got this weird error message on the console when starting up Refine today.  Don't have time to investigate right now...

16:00:16.846 [                butterfly] GET /images/logo-googlerefine40.png [ain](0ms)
16:00:16.877 [          org.mortbay.log] /favicon.ico (31ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWraper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:180)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:51x)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81
```
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servle
```

Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java: 88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.ja a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java: 82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java: 65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418
```
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:
```

52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:5 2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpC nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector java:228)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExe utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecuto .java:908)
        at java.lang.Thread.run(Thread.java:619)
16:00:16.987 [                butterfly] GET /images/favicon.png [main](110ms)
16:00:52.977 [                butterfly] GET / [main](35990ms)
16:00:53.195 [                butterfly] GET /wirings.js [main](218ms)
16:00:53.227 [                butterfly] GET /images/favicon.png [main](32ms)
16:00:53.227 [                butterfly] GET /images/logo-googlerefine-40.png [ain](0ms)
16:00:57.598 [                butterfly] GET / [main](4371ms)
16:00:57.661 [                butterfly] GET / [main](63ms)
16:00:58.644 [                butterfly] GET /images/favicon.png [main](983ms)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=416_

**Comment by felixlohmeier** [comment] 2020-07-10 11:30
While testing OpenRefine-3.4-beta2 I stumbled across this bug. As Thad wrote in 2011, this error message only appears with Firefox and not with Chrome. Tested under Linux (Fedora 32) with FIrefox 78.0.1.
```
13:25:21.443 [          org.mortbay.log] /images/favicon.png (32ms)
java.lang.IllegalStateException: Committed
	at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
	at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
	at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
	at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
	at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
	at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
	at com.google.refine.RefineServlet.service(RefineServlet.java:210)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tfmorris** [comment] 2020-07-10 15:16
@felixlohmeier Does this happen consistently for you or was it a one time thing (as it was with me back in 2011)?

**Comment by felixlohmeier** [comment] 2020-07-10 15:36
This error seems to occure only on first access in Firefox browser. Reloading the page does not trigger the error message. To reproduce the error, I sometimes need to close both refine **and** browser.

**Comment by wetneb** [comment] 2020-07-10 15:44
This has been happening for ages, so it is not a recent regression. It would be worth fixing it of course!

**Comment by wetneb** [comment] 2020-11-17 20:00
This is still happening: https://github.com/OpenRefine/OpenRefine/issues/3339.

**Comment by squeezer44** [comment] 2020-11-17 20:34
Is there a plan to fix it?
I don't want to annoying you, but am really interested to fix my error (mentioned in https://github.com/OpenRefine/OpenRefine/issues/3339).

**Comment by wetneb** [comment] 2020-11-18 07:19
Yes it would be great to fix this!

**Comment by tfmorris** [comment] 2020-11-18 16:31
@squeezer44 Does this happen consistently for you? What browser are you using?

A consistent way of reproducing this would be the first step in solving it. Adding some additional logging and/or exception handling to Butterfly (e.g. at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)) might also help.

**Comment by fgiroud** [comment] 2020-11-26 16:00
Hello, not sure if it's related or not, but I've got this error on Firefox
```
butterfly.module] Error processing file:/Volumes/data/projects/refinepro/openrefine/OpenRefine/main/webapp/modules/core/images/logo-openrefine-550.png (8880ms)
org.mortbay.jetty.EofException
	at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:787)
	at org.mortbay.jetty.AbstractGenerator$Output.flush(AbstractGenerator.java:568)
	at org.mortbay.jetty.HttpConnection$Output.flush(HttpConnection.java:1005)
	at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:648)
	at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:579)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1026)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.send(ButterflyModuleImpl.java:688)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.sendBinary(ButterflyModuleImpl.java:496)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:443)
	at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:516)
	at com.google.refine.RefineServlet.service(RefineServlet.java:210)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.mortbay.io.ByteArrayBuffer.writeTo(ByteArrayBuffer.java:368)
	at org.mortbay.io.bio.StreamEndPoint.flush(StreamEndPoint.java:122)
	at org.mortbay.io.bio.StreamEndPoint.flush(StreamEndPoint.java:154)
	at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:710)
	... 33 more
15:48:00.999 [          org.mortbay.log] /images/logo-openrefine-550.png (4ms)
java.lang.IllegalStateException: Committed
	at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
	at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
	at org.mortbay.servlet.GzipFilter$GZIPResponse

...

```

**Comment by thadguidry** [comment] 2020-12-13 22:03
@fgiroud That is not related.

However, I investigated a bit more on Firefox issues and found more detail now on this issue today with Firefox using it's Browser Console utility it provides:

```
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 191"  data: no] FaviconLoader.jsm:191:20
    load resource:///modules/FaviconLoader.jsm:191
    load resource:///modules/FaviconLoader.jsm:579
    loadIcons resource:///modules/FaviconLoader.jsm:655
    onPageShow resource:///modules/FaviconLoader.jsm:692
    onPageShow resource:///actors/LinkHandlerChild.jsm:72
    handleEvent resource:///actors/LinkHandlerChild.jsm:171
```
![image](https://user-images.githubusercontent.com/986438/102025232-35925480-3d5c-11eb-8989-2417c6981b4c.png)

**Comment by TorstenVeit** [comment] 2021-06-06 09:29
I got the same error:

11:21:46.114 [          org.mortbay.log] /images/favicon.png (10970ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

it launches the browser but only the favicon is visible. Reloading doesn't effect anything.
I'm running it on win10 and firefox 89

**Comment by elroykanye** [comment] 2022-04-19 07:41
Unable to reproduce this issue. 

OS: Kali Linux (with KDE Plasma desktop environment)
Browser: Firefox 91.7.0esr (64-bit)

This image shows no error message on the console (both terminal and browser console).

![Screenshot_20220419_082644](https://user-images.githubusercontent.com/68631069/163949100-ac862eff-d211-422a-8e13-8d1371862e5c.png)

**Comment by wetneb** [comment] 2022-04-19 14:24
It's true that I have not seen it for a while. Could it be that it solved itself after updating some libraries? @elroykanye have you been able to reproduce it with the earlier versions of OpenRefine stated in this issue?

**Comment by elroykanye** [comment] 2022-04-19 14:28
Probably solved itself.

I will check out the older versions today then.

**Comment by elroykanye** [comment] 2022-04-20 07:08
@wetneb , I have been able to reproduce this with v3.4 of OpenRefine. Tried investigating the issue but it only seems that it is in the libraries that OpenRefine uses, and had probably been resolved in some updates. 
However, it is still a mystery to me why FireFox is the only one triggering this.

**Comment by wetneb** [comment] 2022-04-20 07:14
Amazing! Well, I think that is enough to close this issue then!

**Closed by wetneb** 2022-04-20 07:14 UTC
Labels: bug, imported from old code repo, priority: Low

**Comment by elroykanye** [comment] 2022-04-20 07:23
Very well :)
