### ISSUE TITLE
Maximum number of columns for XLSX decreased between v2.7 & v3.1

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2122] opened 2019-08-12 10:01 UTC
_Originally posted by @mlhale7 in https://github.com/OpenRefine/OpenRefine/issues/1824#issuecomment-520244576_

I wanted to follow back up on this and share that when I updated to OpenRefine 3.1 on my own Mac computer it actually couldn't even save changes on my project. I would make changes and then close out as normal and then the next day all of my previous changes would be gone. I also was unable to export a full Excel spreadsheet with the data and changes to try and save my work in a roundabout way. Upon exporting, I found that many of my columns were removed and that the last column was filled with the text "ERROR: TOO MANY COLUMNS" (Image below). I have since reverted to 2.7 and it has been able to save the changes I've made and export the complete set of data as an Excel Spreadsheet. I understand that this project is atypical (tons of columns), but it seems odd that the newer versions of OpenRefine can't handle projects that the older versions can. I lost two days of work from upgrading. Please let me know if sharing additional information is helpful.
<img width="428" alt="TOOMANYCOLUMNS" src="https://user-images.githubusercontent.com/12545660/62837096-4b0fdf80-bc39-11e9-957d-dddec46ccaab.png">

**Comment by tfmorris** [comment] 2020-06-28 03:59
@wetneb Is this from you or are you quoting a user? Is an example file available?

**Comment by tfmorris** [comment] 2020-06-28 04:14
It seems like the change could be related to ab64303cbbbdc180b53e3f83dd063bdb49d9669c but the old limit was 256 and the screenshot shows 256 columns ("IV" = 9*26+22 = 256), plus that patch was intended to **remove** the ancient 256 column limit and up it to 16K columns.

**Comment by wetneb** [comment] 2020-06-28 06:58
@tfmorris as the issue says it was originally posted by @mlhale7 in https://github.com/OpenRefine/OpenRefine/issues/1824#issuecomment-520244576

**Comment by tfmorris** [comment] 2020-06-28 16:42
@mlhale7 Do you remember if you were exporting to XLS or XLSX? Older versions of Excel are limited to 256 columns which is why that restriction is there. The XLSX export has a much higher limit.

**Comment by mlhale7** [comment] 2020-06-28 22:15
I would've been exporting to XSLX. Let me know if you need more information or files.

**Comment by tfmorris** [comment] 2020-06-28 22:40
@mlhale7 If you have a small example of one of the wide files that you could attach, that would save me the trouble of recreating a test case.

**Comment by tfmorris** [comment] 2020-06-28 23:57
I may be missing something, but as far as I can tell, the XLS/XLSX chronology for Refine is:

pre-v2.1 - spreadsheets wider than 256 columns would error (500 server error) on export for XLS, but XLSX supported 16K columns
v2.1 (2011) - columns > 256 silently truncated for both XLS & XLSX
v2.6 (2015) - warning added to 256th column about data loss (both formats)
v3.4 (2020) - column limit conditionalized on output type with XLS = 256 and XLSX = 16K

If you still have old XLSX backups I'd be curious to see if they agree with that timeline.

The good news is that OpenRefine 3.4 raises the limits for XLSX files. Unfortunately, we still don't have a good way of reporting errors to the user though if they exceed these limits. That's something that'll take a little more work.

**Comment by mlhale7** [comment] 2020-06-29 11:59
@tfmorris - I've attached what I think is the tar.gz file I used in 2.7 that actually worked. Looking at this project in 2.7, it does give an error message of "Too many columns" in column IV when you export XSLX from OpenRefine. I actually have never used 3.4.
[volvoices_Jan.openrefine (6).tar.gz](https://github.com/OpenRefine/OpenRefine/files/4845291/volvoices_Jan.openrefine.6.tar.gz)

**Comment by tfmorris** [comment] 2020-06-29 17:07
Thanks very much for the test data. OpenRefine 3.4 isn't out yet but the bug fix is in [3.4-beta](https://github.com/OpenRefine/OpenRefine/releases/tag/3.4-beta). We'll be doing another beta before releasing in the next few weeks.

**Comment by tfmorris** [comment] 2022-11-21 20:29
@wetneb Is there a reason for this to remain open?

**Comment by wetneb** [comment] 2022-11-21 21:56
I guess it did not get closed by your PR because you did not include the "Fixes"/"Closes" keywords, but I am not clear on the situation: your PR demonstrates that this is not a problem anymore, I guess? If so it makes indeed sense to close it - you understand the problem better than I do!

**Comment by tfmorris** [comment] 2022-11-21 22:34
The PR that I believe fixed this was pfanning's #2602, closing #2600.

I **think** @mlhale7 confirmed that the bug exists in 2.7 (contrary to the original problem report), so I'm going to assume that a) my historical [timeline above](https://github.com/OpenRefine/OpenRefine/issues/2122#issuecomment-650840203) is accurate and b) the problem was fixed in OpenRefine 3.4.

@mlhale7 - Please feel free to reopen if you believe it's not fixed in 3.4 and later versions.

**Closed by tfmorris** 2022-11-21 22:34 UTC
Labels: bug, export, XLS(X)
