### ISSUE TITLE
Editing redirect Wikidata items throws error

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#5408] opened 2022-11-06 09:42 UTC
### To Reproduce
1. Match random item to Q114874168
2. Add statement P31=Q5
3. Upload to Wikidata

### Current Results
Exception in thread "Thread-23" java.lang.IllegalArgumentException: Statements describe different subject.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at org.wikidata.wdtk.datamodel.implementation.StatementDocumentUpdateImpl.<init>(StatementDocumentUpdateImpl.java:68)
	at org.wik

### Versions
 - OpenRefine: OpenRefine 3.6.2

### Additional context
see also https://github.com/OpenRefine/OpenRefine/issues/5162

**Comment by wetneb** [comment] 2022-11-06 10:17
Interesting, it looks like the fix for this was meant to be backported to 3.6 but I forgot to do it? Annoying…
Could you double-check that the problem is indeed fixed [in the snapshot releases](https://github.com/OpenRefine/OpenRefine#snapshot-releases)?

**Comment by mshd** [comment] 2022-11-16 05:03
Yes it works in the latest snapshot. Thanks and keep up the good work!

**Closed** 2022-11-17 04:27 UTC
Labels: bug, wikibase
