### ISSUE TITLE
Fix "OpenRefine" cannot be opened because the developer cannot be verified - on MacOS

### ISSUE THREAD

**Issue by coopr** [OpenRefine/OpenRefine#2524] opened 2020-04-07 01:42 UTC
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
OpenRefine will not open on MacOS - this error is presented:
![Blank_Skitch_Document](https://user-images.githubusercontent.com/94904/78620832-e2175080-7835-11ea-8c13-4e212fd1f872.jpg)

**Describe the solution you'd like**
Build OpenRefine with a verified developer so this error does not occur.

**Describe alternatives you've considered**
1. Open System Preferences
1. Open Security & Privacy
1. If you have recently been prevented from opening OpenRefine by the reported error, you can bypass this restriction in this System Preferences panel. 

**Additional context**
This issue could be addressed by improving the download instructions to include the work around, or by including a text file describing the workaround in the downloaded disk image.

**Comment by thadguidry** [comment] 2020-04-07 02:28
You didn't describe which download instructions URL you followed along with.
Was it ours here? https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#macos

**Comment by thadguidry** [comment] 2020-04-07 02:30
Duplicate of #2191

**Comment by thadguidry** [comment] 2020-04-07 02:31
I'll close this issue since it's a duplicate.  Please take a look at our explanation in #2191 
And thanks for using OpenRefine!  If you have other issues, please let us know!

**Closed by thadguidry** 2020-04-07 02:31 UTC
Labels: duplicate
