### ISSUE TITLE
Allow facet-undo/redo panel to be shown/hidden

### ISSUE THREAD

**Issue by simon1tan** [OpenRefine/OpenRefine#1038] opened 2015-07-21 23:46 UTC
It would be nice to be able to minimize the left panels(that show the facets). This give more space to maneuver without having to use the scroll up and down. I know we can resize the panels but doubleclicking the title area and having it toggle to regular size or minimize would be nice.

**Comment by tfmorris** [comment] 2015-07-22 16:26
Rather than double clicking, the typical UI affordance for this kind of thing is a small arrow/triangle icon on the vertical splitter.

**Comment by magdmartin** [comment] 2015-07-22 17:37
related to (duplicate of ?) #1012

**Comment by tfmorris** [comment] 2015-07-22 18:05
Not a duplicate, I think, but definitely related.  This is a relatively simple request, as compared to the other.

**Comment by wetneb** [comment] 2020-02-18 17:55
Marking this as a bit more involved than a first issue since the way the layout is currently set up does not make it very easy to resize panels (panel sizes are computed explicitly in Javascript). Still an issue that should be totally doable though!

**Comment by antoine2711** [comment] 2020-05-10 06:34
A duplicate Issue was opened in error. Now linked to the PR that implemented it.

Regards, A.

**Comment by wetneb** [comment] 2020-05-10 06:46
No this is not the same thing: this is about minimizing the entire facets panel (such that you don't even see the list of facets anymore).

**Comment by antoine2711** [comment] 2020-05-10 06:47
> No this is not the same thing: this is about minimizing the entire facets panel (such that you don't even see the list of facets anymore).

Oups. Sorry. My bad. Regards, A.

**Comment by antoine2711** [comment] 2020-05-11 00:22
> Marking this as a bit more involved than a first issue since the way the layout is currently set up does not make it very easy to resize panels (panel sizes are computed explicitly in Javascript). Still an issue that should be totally doable though!

@wetneb: can you explain to me in what this is different from what I implemented?

Is this issue about hidding the whole left panel like in this video?
![leftpanel-showhide2](https://user-images.githubusercontent.com/12217525/81514219-cf43e000-92fb-11ea-9b5b-243290803102.gif)

Regards, Antoine

**Comment by wetneb** [comment] 2020-05-11 17:16
Yes your video describes it pretty well!

**Comment by antoine2711** [comment] 2020-05-11 17:47
> Yes your video describes it pretty well!

Then, I believe you will find that this PR does what shown in the video.
« Add a Show/Hide left panel PR #2616 »

Regards, 
   Antoine

**Closed** 2020-05-30 11:01 UTC
Labels: UI, enhancement, good second issue
