### ISSUE TITLE
Problem with Columnize by key/value columns

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#1093] opened 2015-11-26 12:58 UTC
Using OpenRefine v2.6-rc2 Release Candidate 2 (linux) I'm getting a problem with columnize by key / value, eg in the below trying to columnize on the Indicator / Value columns I get the following pop-up:

![image](https://cloud.githubusercontent.com/assets/82988/11423541/2fa519b8-943d-11e5-98e8-882f6f3884b8.png)

**Comment by felixlohmeier** [comment] 2016-08-23 14:31
Same problem here with 2.6rc2

> 14:24:43.800 [ refine] POST /command/core/key-value-columnize (67718ms)
> 14:24:44.375 [ command] Exception caught (575ms)
> java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.remove(ArrayList.java:492)
> 	at com.google.refine.operations.cell.KeyValueColumnizeOperation.createHistoryEntry(KeyValueColumnizeOperation.java:262)
> 	at com.google.refine.model.AbstractOperation$1.createHistoryEntry(AbstractOperation.java:52)
> 	at com.google.refine.process.QuickHistoryEntryProcess.performImmediate(QuickHistoryEntryProcess.java:73)
> 	at com.google.refine.process.ProcessManager.queueProcess(ProcessManager.java:85)
> 	at com.google.refine.commands.Command.performProcessAndRespond(Command.java:248)
> 	at com.google.refine.commands.cell.KeyValueColumnizeCommand.doPost(KeyValueColumnizeCommand.java:66)
> 	at com.google.refine.RefineServlet.service(RefineServlet.java:177)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

**Comment by jackyq2015** [comment] 2016-08-24 18:08
duplicate of #1138 
PR already created

**Closed by jackyq2015** 2016-08-24 18:08 UTC
Labels: PR-created
