### ISSUE TITLE
Network error kills status updates

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#875] opened 2014-05-13 15:04 UTC
While running a long "Add column by fetching URLs" my laptop went to sleep and I got:

Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED http://127.0.0.1:3333/command/core/get-processes?project=1445522723935

when the laptop resumed, the server job continued, but the front-end was stuck, no longer getting status updates.  It should retry on a network error (and/or inform the user).

**Comment by Rookev** [comment] 2015-03-12 09:31
Same error here. Sometimes, after a bit of inactivity, the front end is stuck. I can see graphical changes like hover effects for buttons but the connection seems to be lost and won't come back. Error console shows:

Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED

**Comment by jackyq2015** [comment] 2015-03-15 02:42
@Rookev, According to this:
http://stackoverflow.com/questions/23725085/failed-to-load-resource-neterr-network-io-suspended
It might caused by the ajax call. 

If you can exactly put the steps to reproduce this error, I am happy to pin point it and root cause and fix it.

**Comment by tfmorris** [comment] 2020-06-06 22:20
It looks like adding error/retry code here: https://github.com/OpenRefine/OpenRefine/blob/1638d68e352a89c3481d661b0cc950e667447da2/main/webapp/modules/core/scripts/util/ajax.js#L45-L53
would be a likely fix. The timeout added in #2482 will keep the client from getting hung forever, but probably won't be a complete solution.

**Comment by wetneb** [comment] 2023-06-21 19:04
This is fixed in 4.0 by adding a global jQuery error handler which notifies the user if any query to the backend fails due to a connection error:
https://github.com/OpenRefine/OpenRefine/blob/c87d082fe27b1bcdbd2227c107d7e12b77d49cdb/main/webapp/modules/core/scripts/util/ajax.js#L37-L60

**Closed by wetneb** 2023-06-21 19:04 UTC
Labels: bug, fetch urls
