### ISSUE TITLE
SourceMap for http://127.0.0.1:3333/jquery.contextMenu.min.js.map not present

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2834] opened 2020-06-28 22:04 UTC
**Describe the bug**
When one loads the base OpenRefine URL, we get this error:
`DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:3333/jquery.contextMenu.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE` in the JS console.

**To Reproduce**
1. Load page « http://127.0.0.1:3333/ » (or just the first page launched by OR)
2. Click on the right button (contextual menu) 'Inspect'
3. Go to « Console »
4. See error : `DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:3333/jquery.contextMenu.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/85959328-c40b4900-b969-11ea-9297-5ff9d8b9fb06.png)

**Desktop:**
 - OS: MacOS X.14.6
 - Browser Version: Chrome lastest.
 - Language: FR (French)

**OpenRefine :**
 - Version v3.5 (master)

**Comment by tfmorris** [comment] 2020-06-28 22:35
Duplicate of  #2701.

**Closed by tfmorris** 2020-06-28 22:35 UTC
Labels: bug, javascript, to be reviewed
