### ISSUE TITLE
Inconsistent selection behavior with "Cluster & Edit"

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1060] opened 2015-09-04 20:41 UTC
In the "Cluster & Edit" window, if I select a checkbox (to indicate that I want to merge entries) and select merge, the merge works as expected. Or if instead I click on one of the entries (to change the value to be used for merging) and then select merge, the merge works as expected. But if I select a checkbox AND click on one of the entries, I get an error dialog, stating: "The page at localhost:3333 says: You must check some Edit? checkboxes for your edits to be applied." Only by carefully *un*checking the checkbox will the merge proceed as intended. Alternatively, re-clicking on one of the entries will allow the merge to proceed. Clicking on an entry should only re-affirm the checkbox's checked status; it should not un-select the checkbox or cause a hidden selection toggle.

(I'm using 2.6RC1 with current versions of Mac OS X and Google Chrome.)

**Comment by magdmartin** [comment] 2015-09-05 19:04
not sure if it is a duplicate or related to ##1056

**Comment by joewiz** [comment] 2015-09-06 00:51
Yes, this is the same issue, though I provided some more detail than #1056.  The most concerning aspect of this is that the behavior can result in merges even without the checkbox checked.  In other words, this can lead to merges even when the user has intentionally said "no" by unchecking a box.  Less concerning but equally a bug is when the user intends the merge, but the merge isn't made - even though the checkbox is checked..

**Comment by magdmartin** [comment] 2015-09-06 17:28
Going back few version this bug has been introduce between the 2.5 and 2.6-beta release.

I am also closing #1056 as this issue provide more details.

**Comment by jackyq2015** [comment] 2015-09-07 00:13
can't reproduce it under windows7 + chrome(Version 44.0.2403.130 m). Can anyone confirm this only happens on the Mac?

**Comment by magdmartin** [comment] 2015-09-07 03:52
I have the issue with Linux. You need to click on the merge button to get
the error message.

**Closed** 2015-09-20 13:18 UTC
Labels: bug, component-UI, PR-created

**Comment by joewiz** [comment] 2015-09-20 14:11
Many thanks again, @jackyq2015 and all!
