### ISSUE TITLE
Numeric facets not being refreshed after Undo/Redo

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#400] opened 2012-10-15 03:35 UTC
_Original author: PaulMake...@gmail.com (June 07, 2011 14:15:37)_

<b>What steps will reproduce the problem?</b>
1. Create a numeric facet on width column
2. Perform some op (e.g. Create new column new width based on column width by filling 5 rows with grel:value)
3. Undo it
4. Return to Facet/Filter 

<b>What is the expected output? What do you see instead?</b>

Expect to see the numeric facet up to date. Instead it shows no histogram.

<b>What version of Google Refine are you using?</b>

r2090 &amp; r1836

<b>What operating system and browser are you using?</b>

Windows &amp; Chrome 11

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>

Just this combo.

I've included a small TSV to play with if you don't have one handy.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=400_

**Comment by jackyq2015** [comment] 2015-07-25 01:48
Just verify it under chrome "Version 43.0.2357.132 m", can't reproduce it. Since Chrome 11 is pretty old also JQuery has been upgraded at Sep of 2014, I suggest we close it.

**Closed** 2015-08-13 01:55 UTC
Labels: bug, imported, priority-Medium
