### ISSUE TITLE
Cluster & edit - not possible to select value from the list and merge

### ISSUE THREAD

**Issue by StaniKub** [OpenRefine/OpenRefine#5200] opened 2022-08-19 13:55 UTC
In Cluster & edit, when I click on one of the values in cluster it automatically checks the Merge? checkbox. BUT - when at this point I want to Merge selected & re-cluster I get an alert message - You must check some Edit? checkboxes for your edits to be applied.

So now I have to uncheck and re-check the checkbox for the merge to work. Or, I firstly need to check the Merge? checkbox before I choose the correct value from the options.

This is a bug in my opinion and should work right after I select the value without having to manually check the Merge checkbox.

### To Reproduce
1. First, open Cluster & Edit window.
2. Then, select a value from the list, without first checking the Merge? checkbox manually.
3. Finally, try to merge & re-cluster.

### Current Results

Javascript alert message: You must check some Edit? checkboxes for your edits to be applied.

### Expected Behavior

The values merge and re-cluster.

### Screenshots

![image](https://user-images.githubusercontent.com/45338526/185633235-aedf9214-4477-4917-a5ce-cb1ef2305d59.png)

### Versions 
 - Operating System: macOS Monterey 12.2.1
 - Browser Version: Brave 1.42.95 Chromium 104
 - JRE or JDK Version: JRE 1.8.0_331-b09
 - OpenRefine: 3.6.0 [ff7de4d]

### Datasets

Happens to all of the sets I try.

**Comment by elebitzero** [comment] 2022-08-19 22:45
This is a duplicate of #5138 which was already fixed in next release, and will be included in next 3.6.0 patch release.

To my knowledge, the current snapshot release is stable, so you could download it and see if that fixes your problem. https://github.com/OpenRefine/OpenRefine#snapshot-releases

@wetneb, should we release a 3.6.0 patch with the current fixes?

**Comment by wetneb** [comment] 2022-08-20 09:19
Yes a release is due. I just opened #5201 that I would like to ship with it as it seems low risk.

**Comment by StaniKub** [comment] 2022-08-22 07:37
> This is a duplicate of #5138 which was already fixed in next release, and will be included in next 3.6.0 patch release.
> 
> To my knowledge, the current snapshot release is stable, so you could download it and see if that fixes your problem. https://github.com/OpenRefine/OpenRefine#snapshot-releases
> 
> @wetneb, should we release a 3.6.0 patch with the current fixes?

Thank you. I tried the new snapshot and it does fix the problem.

**Comment by thadguidry** [comment] 2022-10-10 14:38
Great @StaniKub we'll close this issue then as a duplicate of #5138 and glad the new patch fixes it for you!

**Closed by thadguidry** 2022-10-10 14:38 UTC
Labels: bug, to be reviewed, clustering
