### ISSUE TITLE
Error when editing CustomMetadata field 

### ISSUE THREAD

**Issue by anisdismail** [OpenRefine/OpenRefine#5772] opened 2023-04-05 08:50 UTC
When trying to edit the customMetadata field in the about section of a project to add new values, the OpenRefine server crashes and throws a ``` java.lang.IllegalArgumentException: Can not set java.util.Map field com.google.refine.ProjectMetadata._customMetadata to java.lang.String```. The issue is the same as well when interacting with the OpenRefine API through ```set-project-metadata``` endpoint as well.

### To Reproduce
1. First, open the Open Project section to the left of the screen
2. Then, choose any project (with empty customMetadata) and press on about.
3. Finally, next to the customMetada field, press the edit button and add any JSON-like format.

### Current Results
The newly added values in the customMetadata field is not saved when the page is reloaded and the server crashes (error shown below).  

### Expected Behavior
The newly added values in the customMetadata field should be saved when the page is reloaded.

### Screenshots
![image](https://user-images.githubusercontent.com/51036803/230028568-53b7d757-f3b2-4508-b50a-fd341626a0f0.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Chrome Version 111.0.5563.147
 - JRE or JDK Version: openjdk 1.8.0_345 
 - OpenRefine: 3.7

**Comment by swkasica** [comment] 2023-04-12 21:13
I was able to replicate this bug on my Macbook:
- Operating System: macOS Ventura 13.0.1
- Browser: Firefox 111.0.1
- JDK: Temurin 17
- OpenRefine 3.7

**Comment by tfmorris** [comment] 2023-04-13 00:00
From a quick glance at the code, it looks likely that this hasn't worked since at least 2018/2019 -- and perhaps never worked. Given that, it may be easier/better to just remove it rather than spend the effort fixing it.

> I'm not sure why this exception isn't being caught, 

The exception is being caught, logged, and dismissed. That's the reason nothing gets returned to the front end.
https://github.com/OpenRefine/OpenRefine/blob/4d2519f38db8b4f5d1ec42598a4fae24b193e830/main/src/com/google/refine/ProjectMetadata.java#L383-L385

> could the cause of this bug be due to ProjectMetadata.setAnyField trying set the _customMetadata property to serialized JSON data?

Yes, it's trying to set a field which is `Map` to a value which is a `String`.

**Comment by swkasica** [comment] 2023-04-13 15:18
@tfmorris thanks for explaining how that exception is being handled for me. With OpenRefine commands, in general, does the server always respond with a 200 response code? In this case, I was surprised it doesn't respond in the 500 range since the request was unsuccessful due to a server error.

I'm thinking of leveraging this `_customMetadata` property for an extension. So I'd be in favor of not letting users edit it directly in this Project Metadata modal window. Although in practice, I don't know if it'd actually be an issue. If that field was not editable, like Import option metadata, would that have an serious consequences?

**Comment by wetneb** [comment] 2023-04-13 18:59
yes it is pretty shameful to what extent we disregard HTTP status codes entirely in most commands. On my side this might soon reach the level of shamefulness that will push me to tackle it.

**Comment by anisdismail** [comment] 2023-04-13 19:28
I actually discovered the issue when doing some API post requests to set-metadata and adding data to the customMetadata field. The OpenRefine server was always returning 200 and I spent hours losing my mind why the metadata was not being written to the customMetadata field, until I eventually I found this issue. 
Not to mention I have seen this "graceful error handling and always returning 200" behavior over other API requests like apply-operations, not matter what the request is correct or not...

**Comment by tfmorris** [comment] 2023-04-14 18:00
> With OpenRefine commands, in general, does the server always respond with a 200 response code? 

No, the server will respond with a 5xx code if there's an unhandled exception. In this particular case, there's a poorly written exception handler swallowing the exception and not allowing it to propagate. I've put a minimal fix for this problem up in #5785.

> Not to mention I have seen this "graceful error handling and always returning 200" behavior over other API requests like apply-operations, not matter what the request is correct or not...

If you create issues for these, they can be addressed, but note that the operation history was designed as a very simple undo/redo capability. Using the operation history for other things, such as applying it to different project than it was created with or attempting to modify it, is very likely run into issues due to the fragility of the mechanism and the lack of error handling.

**Comment by tfmorris** [comment] 2023-04-14 18:03
> I'm thinking of leveraging this `_customMetadata` property for an extension. So I'd be in favor of not letting users edit it directly in this Project Metadata modal window. 

That would remove one potential source of conflict, but I don't think there's any documentation on how multiple extensions should cooperate to keep from stepping on each others' custom metadata.

**Comment by thadguidry** [comment] 2023-04-15 00:36
@tfmorris  I think @wetneb or @jackyq2015 had at one time suggested extensions could register a namespace or prefix.  I.e. two extensions could have `wikidata_keep.login` and `google_keep.login` respectively.

Do not know what Jacky's old code did for that which we reverted but I guess you could check or if he left code comments.

**Comment by tsukipedia** [comment] 2023-07-14 01:55
> From a quick glance at the code, it looks likely that this hasn't worked since at least 2018/2019 -- and perhaps never worked. Given that, it may be easier/better to just remove it rather than spend the effort fixing it.
> 
> > I'm not sure why this exception isn't being caught,
> 
> The exception is being caught, logged, and dismissed. That's the reason nothing gets returned to the front end.
> 
> https://github.com/OpenRefine/OpenRefine/blob/4d2519f38db8b4f5d1ec42598a4fae24b193e830/main/src/com/google/refine/ProjectMetadata.java#L383-L385
> 
> > could the cause of this bug be due to ProjectMetadata.setAnyField trying set the _customMetadata property to serialized JSON data?
> 
> Yes, it's trying to set a field which is `Map` to a value which is a `String`.

Maybe it is necessary to spend time/effort fixing this. When trying to edit the custom metadata, that illegal argument exception is caught and it seems like the edits get saved, but when refreshing the projects dashboard and checking the edits  made to the custom metadata field they're no longer there, this means that changes aren't saved properly in the server. You can check out my proposed solution here: https://github.com/OpenRefine/OpenRefine/pull/5973

**Closed** 2023-07-16 17:37 UTC
Labels: bug, priority: Low, metadata
