### ISSUE TITLE
500 error when creating custom export

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#605] opened 2012-10-15 03:43 UTC
_Original author: Martin.M...@gmail.com (August 27, 2012 01:34:18)_

<b>What steps will reproduce the problem?</b>
I'm working with a program that understand only dos encoded file (ASCII, win 1252 or CP 1252-ISO-8859-1)

I've been trying the custom export with dos format and got an HTTP ERROR 500.
See screenshot for more details

<b>What is the expected output? What do you see instead?</b>
chrome starts to download the file in the right format

<b>What version of Google Refine are you using?</b>
using 2.5 trunk

<b>What operating system and browser are you using?</b>
vista &amp; chrome

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=606_
##

**Comment by wetneb** [comment] 2017-08-02 08:40
Closing as a duplicate of #585 since no additional info was provided.

**Closed by wetneb** 2017-08-02 08:40 UTC
Labels: bug, duplicate, imported, priority-Medium
