### ISSUE TITLE
OpenRefine application fails to start - https://github.com/OpenRefine/OpenRefine/pull/6975

### ISSUE THREAD

**Issue by sunilnatraj** [OpenRefine/OpenRefine#7009] opened 2024-11-26 05:10 UTC
Changes introduced in https://github.com/OpenRefine/OpenRefine/pull/6975
@Abbe98 Application start fails as extensionsDir is null. 
xtensionsDir is being initialized for Unix OS only. On other OS it is set as null and that is resulting in failure.

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "extensionsDir" is null
at com.google.refine.RefineServer.getDataDir(Refine.java:446)
at com.google.refine.RefineServer.configure(Refine.java:337)

**Comment by wetneb** [comment] 2024-11-26 18:04
The Windows workflow only runs the unit tests on Windows, not the end to end tests.

**Comment by wetneb** [comment] 2024-11-27 11:40
@Abbe98 I've temporarily reverted the change so as to ease the pressure on your side to fix it in a timely manner, but looking forward to including it again once the problem is fixed. Happy to have a look at it myself too.

**Comment by wetneb** [comment] 2024-11-28 08:14
Closed by #7011.

**Closed by wetneb** 2024-11-28 08:14 UTC
Labels: Type: Bug
