### ISSUE TITLE
Request to upload WD schema of new objects at once 

### ISSUE THREAD

**Issue by dvalexieva97** [OpenRefine/OpenRefine#2305] opened 2020-02-04 21:26 UTC
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

I get frustrated when adding objects through OpenRefine to WD with a schema which includes multiple types of new objects.  If the schema includes objects which are still to be created which are connected through statements, then OpenRefine cannot import the changes to WD. 

**Potential solution**
A solution to this would be for OpenRefine to go through each object definition first (Object-Label-Description-Instance of/Subclass of), to reconcile this data and then continue further with the schema, where interlinked statements are presented.

**Alternative**
An alternative is:
  - creating the full scheme (since this way it is easier to make sure all statements are included)
  - exporting the whole schema
  - splitting the schema for the different new object types: importing the schema, deleting all but one object type to be created
  - updating to WD
  - reconciling the newly created objects
  - importing the schema again with the next objects, until all new objects are created and reconciled. Finally, quickest and least messy is to export the remaining part of the schema (e.g. statements with 2 new objects of different types to QuickStatements.

However, this alternative can get messy with complex semantic structures. 

**Additional context**

Link to the data used as example of this limitation in OpenRefine:
https://raw.githubusercontent.com/dvalexieva97/chalga-ili-rap/master/albums-songs_rap.csv

**Comment by wetneb** [comment] 2020-02-05 08:14
Thanks for this report! Could you share an example project with a schema where this issue can be observed (the CSV you added is great but it would be better to see the schema you are using on it).

Which version of OpenRefine are you using? OpenRefine is supposed to support creation of various types of new items in one go (even with interlinking statements). A bug was recently fixed about that https://github.com/OpenRefine/OpenRefine/issues/2206 so I would encourage you to try the latest version (3.3).

**Comment by VladimirAlexiev** [comment] 2020-02-05 10:08
Here are a couple shots from @dvalexieva97 to illustrate the issue:
- Reconciled Artist and Albums. Some are found, others will be created as new
- The schema for Artist:

![image](https://user-images.githubusercontent.com/536250/73832096-30957800-4810-11ea-97db-712a8355daf9.png)

- The schema for Album uses artist:

![image](https://user-images.githubusercontent.com/536250/73832118-3db26700-4810-11ea-8f4e-cc8968ccbe47.png)

- When the two schemas are used together, the problem occurs

**Comment by wetneb** [comment] 2020-02-05 10:36
Thanks for the screenshots!

To debug this further, I would like to know:
* which version of OpenRefine are you using?
* what do you mean by "the problem occurs"? Concretely, how do you see that OpenRefine cannot upload both schemas at the same time? Are there any edits produced at all, if so could you give links to the diffs? If no edits are produced at all, can you give a copy of the server logs (the black window with white text)?
* could you provide an export of a project with the problematic schema? (screenshots are useful, but they do not make debugging very easy)

**Comment by dvalexieva97** [comment] 2020-02-05 13:30
> Thanks for the screenshots!
> 
> To debug this further, I would like to know:
> 
> * which version of OpenRefine are you using?
> * what do you mean by "the problem occurs"? Concretely, how do you see that OpenRefine cannot upload both schemas at the same time? Are there any edits produced at all, if so could you give links to the diffs? If no edits are produced at all, can you give a copy of the server logs (the black window with white text)?
> * could you provide an export of a project with the problematic schema? (screenshots are useful, but they do not make debugging very easy). Please use the "Export project" button, such that your entire OpenRefine project (with its history and schema) is exported.
  -I am using OpenRefine 3.3
  -Here is a link to the project  export: https://github.com/dvalexieva97/chalga-ili-rap/blob/master/Common%20Schema_albums%2Bsongs_rap.openrefine.tar.gz - I have already fixed the project and all the objects are in WD by now.
  -By **the problem occur** I mean the following. I used the schema from the project at once. When uploading it to WD, OpenRefine would work until about 50% and then lag and not do anything. I tried exporting the schema to QuickStatements and got the following error message: "This edit batch cannot be performed with QuickStatements due to the structure of its new items." - I figured out it is because in the schema there are new items which are also linked to to other items (I checked my schema and all errors from OpenRefine). Once I split up the schema into parts, everything went smoothly and I managed to upload everything (you can see all edits in the project, since I reconciled them).

**Comment by wetneb** [comment] 2020-02-05 13:45
> OpenRefine would work until about 50% and then lag and not do anything.

This sounds more like a Wikidata lag issue: if you have encountered this issue over the past few days, it might be due to the fact that Wikidata's server is overloaded:
https://phabricator.wikimedia.org/T243701

If this happens again, can you check what is shown in the terminal? This should give a definitive explanation of the issue.

> "This edit batch cannot be performed with QuickStatements due to the structure of its new items."
 
Yes this is normal, as QuickStatements does not support this kind of batch.

**Comment by antoine2711** [comment] 2020-02-09 23:49
It's not directly related to this problem, but I, for one, would like the ability to « disable » a statement declaration, or one of it's reference or quantifier. Because, sometimes I go in batches, with or without these info.

With saving/deleting, it can provide some of what I need, but enabling/disabling lines would be better and faster.

**Comment by VladimirAlexiev** [comment] 2020-02-10 08:17
> Wikidata's server is overloaded

Indeed, I see updates of 1 **per minute**. See https://www.wikidata.org/wiki/Topic:Vfnr6v8lfqagpi7g

> disable » a statement declaration, or one of it's reference 

@antoine2711 you can do that by tweaking the schema. Save a full schema, then delete the elements you don't want in a particular batch.

**Comment by wetneb** [comment] 2020-02-10 09:22
> enabling/disabling lines would be better and faster.

You can do that with facets, see https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Advanced_schemas

**Comment by antoine2711** [comment] 2020-02-10 10:58
> > enabling/disabling lines would be better and faster.
> 
> You can do that with facets, see https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Advanced_schemas

What I mean is enabling/disabling SCHEMA lines. Like Lfr, Den, Ade, or a statement, qualifier or reference of a statement, or even a whole item with a single click. Not lines of data.

> > Wikidata's server is overloaded
> 
> Indeed, I see updates of 1 **per minute**. See https://www.wikidata.org/wiki/Topic:Vfnr6v8lfqagpi7g
> 
> > disable » a statement declaration, or one of it's reference
> 
> @antoine2711 you can do that by tweaking the schema. Save a full schema, then delete the elements you don't want in a particular batch.

Yes, I get that. I already do that. But, after I cut parts of my full schema, I sometimes come to modify my subset with many modifications. Then, I have to save a version, and manually merge it's differences with my full schema. It not complicated, but not for the average user…
I picture of my ideal would explain it better. But think of it of a temporary removing a part of the schema with a click close to the part.

Regards, Antoine

**Comment by wetneb** [comment] 2020-02-10 11:01
If you have a concrete system to propose, let's do this in another issue, as this one is unrelated. Closing this one since the problem is Wikidata's lag.

**Closed by wetneb** 2020-02-10 11:01 UTC
Labels: to be reviewed, wikidata
