### ISSUE TITLE
Data loss/ column mismatch when importing multiple sheets from xlsx

### ISSUE THREAD

**Issue by burgerga** [OpenRefine/OpenRefine#1792] opened 2018-10-31 09:12 UTC
**Describe the bug**
I want to import data from multiple sheets in one excel file, but somehow data from column 2 ends up in column 17 and is partly lost, because there is already data in column 17

**To Reproduce**
1. Open attached xlsx file
2. Uncheck "Parse next 1 line(s) as column headers"
3. Uncheck "Store blank rows"
4. (Optional) Check "Store file source (file names, URLs) in each row
5. Preview shows unexpected results
6. Uncheck "test.xlsx#Sheet1" from "Worksheets to Import"
7. Preview shows expected Sheet2 results

(If you click "Create Project" you'll end up with the situation as in the preview, so it's not a preview problem)

**Current Results**
- Data from Column 2 in Sheet2 ends up in Column 17, however first part of Column 2 is lost because there is already data in Column 17 in Sheet2.
- Also, (not sure if related), Sheet2 shows a ridiculous amount of rows to import

**Expected behavior**
Data from Column 2 in Sheet2 should stay in Column 2

**Screenshots**
What happens:
![screenshot from 2018-10-31 10-06-02](https://user-images.githubusercontent.com/907362/47777248-9d0ff600-dcf4-11e8-8c78-850f6861dbd5.png)

What Sheet2 should look like: 
![screenshot from 2018-10-31 10-09-28](https://user-images.githubusercontent.com/907362/47777469-19a2d480-dcf5-11e8-9c49-429f509f8bd5.png)

**Desktop:**
 - OS: Manjaro Linux
 - Browser Version: Chrome 70.0.3538.77 (Official Build) (64-bit)
 - JRE or JDK Version: openjdk version "1.8.0_192"

**OpenRefine:**
 - Version 3.0 [TRUNK]

**Datasets**
Sort of minimal working example: 
[test.xlsx](https://github.com/OpenRefine/OpenRefine/files/2533471/test.xlsx)
Derived from a larger, but private, data set.

**Comment by wetneb** [comment] 2019-12-22 09:55
I can reproduce this bug on master.

**Comment by zengchu2** [comment] 2020-03-12 16:22
Hi, I am now currently working on this issue. It seems that the problem occurs due to the false update for request `update-format-and-options` is sent and so the incorret row model is returned. 
Are there any hints or docs related to the server side job updating, that would speed up my process quickly ! 

Thanks in advanced!

**Comment by tfmorris** [comment] 2020-06-29 23:44
I think this was intended to be closed when #2404 was merged.

**Closed by tfmorris** 2020-06-29 23:44 UTC
Labels: XLS(X), bug, good second issue, import
