### ISSUE TITLE
[Documentation] Link broken

### ISSUE THREAD

**Issue by strarsis** [OpenRefine/OpenRefine#3674] opened 2021-02-27 21:04 UTC
### To Reproduce
1. Visit [GREL-supported regex](https://docs.openrefine.org/manual/expressions/#grel-supported-regex) section of the OpenRefine documentation.
2. Select any link from the list (`The GREL functions that support regex are:`).
Notice the HTTP 404 Page not found errors for all of these links.

### Current Results
HTTP 404 Page not found when following any of these links.

### Expected Behavior
Correct page or section in documentation when following any of these links.

**Comment by thadguidry** [comment] 2021-02-27 21:15
I just tried to reproduce this with Firefox and all those links seems to work just fine for me.
Such as the first one: 
* [contains](https://docs.openrefine.org/manual/grelfunctions#containss-sub-or-p)

**Comment by strarsis** [comment] 2021-02-27 21:28
@thadguidry: Strange. It surely doesn't work with Chrome (Windows 10). So this could be a browser-specific issue?

**Comment by joanneong** [comment] 2021-02-28 04:00
I can verify that the links are broken.

Example of a correct link: https://docs.openrefine.org/manual/grelfunctions/#containss-sub-or-p
Example of the link by clicking from the documentation: https://docs.openrefine.org/manual/expressions/grelfunctions#containss-sub-or-p

This is because the base url becomes `https://docs.openrefine.org/manual/expressions/` thanks to Docusaurus magic, so the links generated using markdown anchor tags are actually incorrect.

I can think of 2 possible workarounds for the [page](https://github.com/OpenRefine/OpenRefine/blob/eb7761e23034ea32bf523fe1e63dd5bb8b2bb300/docs/docs/manual/expressions.md):
1. just use the full raw link directly (e.g. `https://docs.openrefine.org/manual/grelfunctions/#containss-sub-or-p`)
2. modify the anchor link from `grelfunctions#containss-sub-or-p` to `../grelfunctions#containss-sub-or-p`

**Comment by wetneb** [comment] 2021-03-03 10:56
Thanks for the analysis! I would go for the second option.

**Comment by thadguidry** [comment] 2021-03-03 15:19
Where is there an extra `s` in `contains` ?  `#containss-sub-or-p`

**Comment by ostephens** [comment] 2021-03-03 15:37
>Where is there an extra s in contains ? #containss-sub-or-p

Because the anchors contain the expression and the parameters with spaces converted to hyphens and brackets ignored. So `contains(s, sub or p)` becomes #containss-sub-or-p

**Comment by strarsis** [comment] 2021-03-03 15:40
Is this is an issue with the documentation generator or with the documentation options?

**Comment by wetneb** [comment] 2021-03-03 15:42
This is an issue with the documentation itself: the markdown files from which the documentation is generated should be fixed as suggested by Joanne above.

**Comment by wetneb** [comment] 2021-05-09 06:35
It looks like this is mostly a duplicate of #3819, all the links mentioned in the issue now work for me. Should we close it?

**Closed** 2021-05-31 12:58 UTC
Labels: bug, documentation, good first issue
